### ISSUE TITLE
Regression Test does not work on Kubernetes

### ISSUE THREAD

**Issue by piyush1594** [fabric8io/kubernetes-client#1024]
All our regression test does not work when we run them on Kubernetes. All the test works fine with Openshift. For Kubernetes, they throw some error of Class Configuration.

The error is `Did not find any kubernetes configuration`

This may be because of some configuration I am missing locally but they all work fine with Openshift

minikube version: v0.23.0
kubernetes version: v1.7.0
arquillian.cube.version 1.11.0
arquillian.core.version 1.2.0.Final

**Comment by hrishin** [comment]
@piyush1594 could you please post error logs here?

**Comment by piyush1594** [comment]
These are the tests which are getting failed
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ConfigMapIT.io.fabric8.kubernetes.ConfigMapIT » KubernetesClient Failure execu...
[ERROR]   DeploymentIT.io.fabric8.kubernetes.DeploymentIT » KubernetesClient Failure exe...
[ERROR]   NetworkPolicyIT.io.fabric8.kubernetes.NetworkPolicyIT » KubernetesClient Failu...
[ERROR]   PodIT.io.fabric8.kubernetes.PodIT » KubernetesClient Failure executing: GET at...
[ERROR]   PodSecurityPolicyIT.io.fabric8.kubernetes.PodSecurityPolicyIT » KubernetesClient
[ERROR]   ReplicaSetIT.io.fabric8.kubernetes.ReplicaSetIT » KubernetesClient Failure exe...
[ERROR]   ReplicationControllerIT.io.fabric8.kubernetes.ReplicationControllerIT » KubernetesClient
[ERROR]   ResourceIT.io.fabric8.kubernetes.ResourceIT » KubernetesClient Failure executi...
[ERROR]   SecretIT.io.fabric8.kubernetes.SecretIT » KubernetesClient Failure executing: ...
[ERROR]   SecretIT.testLoadInPod:108 » KubernetesClient Failure executing: POST at: http...
[ERROR]   ServiceAccountIT.io.fabric8.kubernetes.ServiceAccountIT » KubernetesClient Fai...
[ERROR]   ServiceIT.io.fabric8.kubernetes.ServiceIT » KubernetesClient Failure executing...
[ERROR]   StatefulSetIT.io.fabric8.kubernetes.StatefulSetIT » KubernetesClient Failure e...
[ERROR]   StorageClassIT.io.fabric8.kubernetes.StorageClassIT » KubernetesClient Failure...
[ERROR]   WatchIT.io.fabric8.kubernetes.WatchIT » KubernetesClient Failure executing: GE...
[ERROR]   SecurityContexConstraintsIT.delete » Runtime Could not lookup value for field ...
[ERROR]   SecurityContexConstraintsIT.get » Runtime Could not lookup value for field io....
[ERROR]   SecurityContexConstraintsIT.io.fabric8.openshift.SecurityContexConstraintsIT » KubernetesClient
[ERROR]   SecurityContexConstraintsIT.list » Runtime Could not lookup value for field io...
[ERROR]   SecurityContexConstraintsIT.load » Runtime Could not lookup value for field io...
[ERROR]   SecurityContexConstraintsIT.update » Runtime Could not lookup value for field ...
[INFO]
```

**Comment by piyush1594** [comment]
Logs are 
```
Mar 06, 2018 12:10:21 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor createOpenShiftResource
INFO: Creating environment for io.fabric8.kubernetes.NetworkPolicyIT method public void io.fabric8.kubernetes.NetworkPolicyIT.delete()
Mar 06, 2018 12:10:27 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor deleteOpenShiftResource
INFO: Deleting environment for io.fabric8.kubernetes.NetworkPolicyIT method delete
Mar 06, 2018 12:10:27 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor createOpenShiftResource
INFO: Creating environment for io.fabric8.kubernetes.NetworkPolicyIT method public void io.fabric8.kubernetes.NetworkPolicyIT.update()
Mar 06, 2018 12:10:33 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor deleteOpenShiftResource
INFO: Deleting environment for io.fabric8.kubernetes.NetworkPolicyIT method update
Mar 06, 2018 12:10:33 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor createOpenShiftResource
INFO: Creating environment for io.fabric8.kubernetes.NetworkPolicyIT method public void io.fabric8.kubernetes.NetworkPolicyIT.get()
Mar 06, 2018 12:10:39 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor deleteOpenShiftResource
INFO: Deleting environment for io.fabric8.kubernetes.NetworkPolicyIT method get
Mar 06, 2018 12:10:40 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor createOpenShiftResource
INFO: Creating environment for io.fabric8.kubernetes.NetworkPolicyIT method public void io.fabric8.kubernetes.NetworkPolicyIT.list()
Mar 06, 2018 12:10:46 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor deleteOpenShiftResource
INFO: Deleting environment for io.fabric8.kubernetes.NetworkPolicyIT method list

Test ignored.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Initializing Session:a1605ed9
Using Kubernetes at: https://192.168.42.130:8443/
Mar 06, 2018 12:10:17 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading io/fabric8/kubernetes-client/3.1-SNAPSHOT/maven-metadata.xml from http://repo1.maven.org/maven2/. Reason: 
org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata io.fabric8:kubernetes-client:3.1-SNAPSHOT/maven-metadata.xml in central (http://repo1.maven.org/maven2)
Mar 06, 2018 12:10:18 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading io/fabric8/kubernetes-client/3.1-SNAPSHOT/maven-metadata.xml from https://oss.sonatype.org/content/repositories/snapshots/. Reason: 
org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata io.fabric8:kubernetes-client:3.1-SNAPSHOT/maven-metadata.xml in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
Mar 06, 2018 12:10:18 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading io/fabric8/openshift-client/3.1-SNAPSHOT/maven-metadata.xml from http://repo1.maven.org/maven2/. Reason: 
org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata io.fabric8:openshift-client:3.1-SNAPSHOT/maven-metadata.xml in central (http://repo1.maven.org/maven2)
Mar 06, 2018 12:10:19 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading io/fabric8/openshift-client/3.1-SNAPSHOT/maven-metadata.xml from https://oss.sonatype.org/content/repositories/snapshots/. Reason: 
org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata io.fabric8:openshift-client:3.1-SNAPSHOT/maven-metadata.xml in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
Did not find any kubernetes configuration.
Mar 06, 2018 12:10:20 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor createEnvironment
INFO: Creating environment for io.fabric8.kubernetes.NetworkPolicyIT
Mar 06, 2018 12:10:46 PM org.arquillian.cube.openshift.impl.CEEnvironmentProcessor deleteEnvironment
INFO: Deleting environment for io.fabric8.kubernetes.NetworkPolicyIT

io.fabric8.kubernetes.clnt.v3_1.KubernetesClientException: Failure executing: GET at: https://192.168.42.130:8443/oapi/v1/namespaces/myproject/builds?labelSelector=test-case%3Dnetworkpolicyit. Received status: Status(apiVersion=meta/v1, code=404, details=null, kind=Status, message=null, metadata=null, reason=null, status=null, additionalProperties={}).

	at io.fabric8.kubernetes.clnt.v3_1.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.clnt.v3_1.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.clnt.v3_1.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.clnt.v3_1.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.clnt.v3_1.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
	at io.fabric8.kubernetes.clnt.v3_1.dsl.base.BaseOperation.list(BaseOperation.java:605)
	at io.fabric8.kubernetes.clnt.v3_1.dsl.base.BaseOperation.list(BaseOperation.java:70)
	at org.arquillian.cube.openshift.impl.fabric8.F8OpenShiftAdapter.cleanBuilds(F8OpenShiftAdapter.java:687)
	at org.arquillian.cube.openshift.impl.fabric8.F8OpenShiftAdapter.cleanRemnants(F8OpenShiftAdapter.java:682)
	at org.arquillian.cube.openshift.impl.CEEnvironmentProcessor.additionalCleanup(CEEnvironmentProcessor.java:245)
	at org.arquillian.cube.openshift.impl.CEEnvironmentProcessor.deleteEnvironment(CEEnvironmentProcessor.java:178)
	at org.arquillian.cube.openshift.impl.CEEnvironmentProcessor.deleteEnvironment(CEEnvironmentProcessor.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.afterClass(EventTestRunnerAdaptor.java:86)
	at org.jboss.arquillian.junit.Arquillian$3$1.evaluate(Arquillian.java:191)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:376)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:185)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:140)
	at org.arquillian.cube.requirement.ArquillianConditionalRunner.run(ArquillianConditionalRunner.java:28)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Test ignored.

Test ignored.

Test ignored.

Test ignored.

Test ignored.
Destroying Session:a1605ed9

Process finished with exit code 255

```

**Comment by dipak-pawar** [comment]
@piyush1594 How are you starting the k8s cluster before running tests?

**Comment by piyush1594** [comment]
Hey @dipak-pawar 

I am hitting `minikube start --vm-driver=kvm --kubernetes-version=v1.7.0`

**Comment by piyush1594** [comment]
Closing this as #1027 will fix this.
