### ISSUE TITLE
ConfigBuilder.withCaCertData() results in error in 3.1.8+

### ISSUE THREAD

**Issue by ArtemZ** [fabric8io/kubernetes-client#1049]
Hello,

I'd prefer to supply CA certificate to kubernetes-client as string instead of a file, so I attempting to use
 ConfigBuilder.withCaCertData("plain text ca.crt content"), but it fails with:

> Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:168)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:55)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:61)
	at com.griddynamics.Main.main(Main.java:34)
Caused by: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:110)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:94)
	at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:72)
	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:114)
	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:93)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:63)
	... 3 more
Caused by: java.io.IOException: Empty input
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:106)
	... 9 more

Code example:
```
Config config = new ConfigBuilder()

                .withMasterUrl("master url")

                .withUsername("admin")

                .withPassword("password")

                .withCaCertData(new String (Files.readAllBytes(Paths.get("ca.crt")) ))

                //.withCaCertFile("ca.crt")

                .build();
        KubernetesClient client = new DefaultKubernetesClient(config);
```

But if I use withCaCertFile("ca.crt") then everything works. ``ConfigBuilder`` appears to be auto-generated so it is not clear to me how to fix this.

**Comment by wybrono** [comment]
I have solved this problem. By skipping the authentication method, you can create a client with only token.
