### ISSUE TITLE
access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/kubernetes-client#1068]
Use in versions >=2.0 cause the following exception in the elasticsearch-cloud-kubernetes plugin even though the proper permissions is listed in the security file.
```
[2018-04-29T19:59:03,544][WARN ][i.f.e.d.k.KubernetesUnicastHostsProvider] [logging-es-data-master-dtp8bmgy] Exception caught during discovery: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/openshift-logging/endpoints/logging-es-cluster. Cause: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
io.fabric8.kubernetes.client.KubernetesClientException: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/openshift-logging/endpoints/logging-es-cluster. Cause: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestException(OperationSupport.java:481) ~[kubernetes-client-3.1.10.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:391) ~[kubernetes-client-3.1.10.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[kubernetes-client-3.1.10.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313) ~[kubernetes-client-3.1.10.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296) ~[kubernetes-client-3.1.10.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:770) ~[kubernetes-client-3.1.10.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:195) ~[kubernetes-client-3.1.10.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:162) ~[kubernetes-client-3.1.10.jar:?]
	at io.fabric8.elasticsearch.cloud.kubernetes.KubernetesAPIServiceImpl.endpoints(KubernetesAPIServiceImpl.java:34) ~[elasticsearch-cloud-kubernetes-5.6.9.2-SNAPSHOT.jar:?]
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.readNodes(KubernetesUnicastHostsProvider.java:118) [elasticsearch-cloud-kubernetes-5.6.9.2-SNAPSHOT.jar:?]
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.access$000(KubernetesUnicastHostsProvider.java:40) [elasticsearch-cloud-kubernetes-5.6.9.2-SNAPSHOT.jar:?]
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider$1.run(KubernetesUnicastHostsProvider.java:83) [elasticsearch-cloud-kubernetes-5.6.9.2-SNAPSHOT.jar:?]
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider$1.run(KubernetesUnicastHostsProvider.java:80) [elasticsearch-cloud-kubernetes-5.6.9.2-SNAPSHOT.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_161]
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.buildDynamicNodes(KubernetesUnicastHostsProvider.java:80) [elasticsearch-cloud-kubernetes-5.6.9.2-SNAPSHOT.jar:?]
	at org.elasticsearch.discovery.zen.UnicastZenPing.ping(UnicastZenPing.java:309) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.discovery.zen.UnicastZenPing.ping(UnicastZenPing.java:286) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.discovery.zen.ZenDiscovery.pingAndWait(ZenDiscovery.java:1010) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:869) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:377) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.discovery.zen.ZenDiscovery.access$4100(ZenDiscovery.java:82) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1188) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:575) [elasticsearch-5.6.9.jar:5.6.9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_161]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_161]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_161]
	at java.lang.Class.checkMemberAccess(Class.java:2348) ~[?:1.8.0_161]
	at java.lang.Class.getEnclosingMethod(Class.java:1037) ~[?:1.8.0_161]
	at sun.reflect.generics.scope.ClassScope.computeEnclosingScope(ClassScope.java:50) ~[?:?]
	at sun.reflect.generics.scope.AbstractScope.getEnclosingScope(AbstractScope.java:78) ~[?:?]
	at sun.reflect.generics.scope.AbstractScope.lookup(AbstractScope.java:96) ~[?:?]
	at sun.reflect.generics.factory.CoreReflectionFactory.findTypeVariable(CoreReflectionFactory.java:110) ~[?:?]
	at sun.reflect.generics.visitor.Reifier.visitTypeVariableSignature(Reifier.java:165) ~[?:?]
	at sun.reflect.generics.tree.TypeVariableSignature.accept(TypeVariableSignature.java:43) ~[?:?]
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[?:?]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[?:?]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:?]
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90) ~[?:?]
	at java.lang.Class.getGenericSuperclass(Class.java:777) ~[?:1.8.0_161]
	at com.fasterxml.jackson.core.type.TypeReference.<init>(TypeReference.java:33) ~[jackson-core-2.8.6.jar:2.8.6]
	at io.fabric8.kubernetes.client.utils.Serialization$2.<init>(Serialization.java:190) ~[?:?]
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190) ~[?:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:383) ~[?:?]
	... 24 more

````

**Comment by damienjoldersma** [comment]
Any luck? I just ran in to this as well.

**Comment by jcantrill** [comment]
None, I ended up reverting to a previous client as it supported the functionality I needed.  I defer to @iocanel  who may be able to offer a solution.
