### ISSUE TITLE
Error parsing openshift json template with the latest version.

### ISSUE THREAD

**Issue by hemanik** [fabric8io/kubernetes-client#1070]
`RuntimeException` thrown when trying to parse the openshift json template.

Sample json document is as follows:

```json
{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "hello-openshift"
  },
  "labels": {
    "template": "hello-openshift"
  },
  "objects": [
    {
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "hello-openshift-service"
      },
      "spec": {
        "ports": [
          {
            "name": "hello-openshift-service",
            "port": 8080,
            "targetPort": 8080
          }
        ],
        "selector": {
          "name": "hello-openshift-service"
        }
      }
    },
    {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata": {
        "name": "hello-openshift",
        "creationTimestamp": null,
        "labels": {
          "name": "hello-openshift-service"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "hello-openshift",
            "image": "openshift/hello-openshift",
            "ports": [
              {
                "containerPort": 8080,
                "protocol": "TCP"
              }
            ],
            "resources": {

            },
            "volumeMounts": [
              {
                "name": "tmp",
                "mountPath": "/tmp"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "imagePullPolicy": "IfNotPresent",
            "capabilities": {

            },
            "securityContext": {
              "capabilities": {

              },
              "privileged": false
            }
          }
        ],
        "volumes": [
          {
            "name": "tmp",
            "emptyDir": {

            }
          }
        ],
        "restartPolicy": "Always",
        "dnsPolicy": "ClusterFirst",
        "serviceAccount": ""
      },
      "status": {

      }
    }
  ]
}
```  

Error Log is as follows:

```console
Caused by: com.fasterxml.jackson.databind.JsonMappingException: YAML decoding problem: while parsing a block mapping
 in 'reader', line 1, column 3:
      "kind": "Template",
      ^
expected <block end>, but found FlowEntry
 in 'reader', line 1, column 21:
      "kind": "Template",
                        ^

	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:351)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:655)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:219)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3779)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2158)
	at com.fasterxml.jackson.core.JsonParser.readValueAsTree(JsonParser.java:1564)
	at io.fabric8.kubernetes.clnt.v3_1.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:50)
	at io.fabric8.kubernetes.clnt.v3_1.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:31)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1578)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1166)
	at io.fabric8.kubernetes.clnt.v3_1.utils.Serialization.unmarshal(Serialization.java:129)
	... 51 more
```

**Comment by rohanKanojia** [comment]
Possible regression of 1399edf . Will take a look soon. Right now mugged up with lots of summit work :persevere:

**Comment by piyush1594** [comment]
@rohanKanojia It is assigned to you but saw a very small fix so sent a PR. If you have done some work on it I can close my PR.

**Comment by rohanKanojia** [comment]
No, I haven't done any work on it. Thanks for the heads up :+1:

**Comment by piyush1594** [comment]
Closing as #1072 is merged
