### ISSUE TITLE
Regression Tests Breaking

### ISSUE THREAD

**Issue by piyush1594** [fabric8io/kubernetes-client#1119]
Regression Tests are breaking more often because of these 3 tests and are kind of blocking for all the PR's. We should make it work more reliably.

```
Errors: 
[ERROR]   DeploymentIT.waitTest:130 » KubernetesClientTimeout Timed out waiting for [0] ...
[ERROR]   PodIT.exec:139 » KubernetesClientTimeout Timed out waiting for [0] millisecond...
[ERROR]   PodIT.log:132 » KubernetesClientTimeout Timed out waiting for [0] milliseconds...
```

The error is something like this 
```
[ERROR] Tests run: 7, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1,411.297 s <<< FAILURE! - in io.fabric8.kubernetes.PodIT
[ERROR] log(io.fabric8.kubernetes.PodIT)  Time elapsed: 630.268 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [0] milliseconds for [Pod] with name:[pod1-ztkffc] in namespace [itest-7f7810e0].
	at io.fabric8.kubernetes.PodIT.log(PodIT.java:132)

[ERROR] exec(io.fabric8.kubernetes.PodIT)  Time elapsed: 630.28 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [0] milliseconds for [Pod] with name:[pod1-w6pfcl] in namespace [itest-7f7810e0].
	at io.fabric8.kubernetes.PodIT.exec(PodIT.java:139)
```

```
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 828.331 s <<< FAILURE! - in io.fabric8.kubernetes.DeploymentIT
[ERROR] waitTest(io.fabric8.kubernetes.DeploymentIT)  Time elapsed: 637.4 s  <<< ERROR!
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [0] milliseconds for [Deployment] with name:[deployment1] in namespace [itest-7f7810e0].
	at io.fabric8.kubernetes.DeploymentIT.waitTest(DeploymentIT.java:130)
```

**Comment by piyush1594** [comment]
Closed in #1121
