### ISSUE TITLE
Executing a simple request (e.g. list) results in a 400 Bad Request when using basic authorization

### ISSUE THREAD

**Issue by valentinabojan** [fabric8io/kubernetes-client#1122]
### Description:
We created an OpenshitClient using basic authorization and tried to use it to execute a simple action like listing all deployments from a specific namespace. This operation resulted in a 400 Bad Request response.
Note: Trying the same deployment listing, but having a client configured with an OAuthToken works perfectly.

### Code to reproduce the bug
```
OpenShiftConfigBuilder configBuilder = new OpenShiftConfigBuilder()
    .withMasterUrl(MASTER_URL)
    .withUsername(USERNAME)
    .withPassword(PASSWORD)
    .withNamespace(NAMESPACE);

try (OpenShiftClient client = new DefaultOpenShiftClient(configBuilder.build())) {
    DeploymentList deployment = client.extensions().deployments().list();
}
```

### Result (with stacktrace):
```
io.fabric8.kubernetes.client.KubernetesClientException: Unexpected response (400 Bad Request), to the authorization request. Missing header:[Location]!

	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.authorize(OpenShiftOAuthInterceptor.java:120)
	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:780)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:196)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:163)
	at com.openshift.OpenShiftServiceImplWithFabric8ClientTest.test_fabric8(OpenShiftServiceImplWithFabric8ClientTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:16)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### Investigation
Looking at the sources, we noticed the following behavior that might by the bug that causes the 400 Bad Request response:
- we create a DefaultOpenShiftClient client
- DefaultOpenShiftClient extends BaseClient
- in the BaseClient constructor, an OkHttpClient instance will be created using the HttpClientUtils class. In the creation process, an interceptor is added (HttpClientUtils:98) 
- **IMPORTANT**: the above interceptor adds the Authorization header on the request
- in the DefaultOpenShiftClient constructor, an OpenShiftOAuthInterceptor is added on the previously created OkHttpClient
- **IMPORTANT**: the OpenShiftOAuthInterceptor checks if a token or credentials for basic authorization were used when creating the DefaultOpenShiftClient instance. Because we used a username and password, then a request to get the token will be created. When creating this request, the Authorization header is added on the request (OpenShiftOAuthInterceptor:121)

Following the interceptors chain, the request will end up having 2 Authorization headers, this resulting in a 400 Bad Request response. (looking on the request that reaches the ImpersonatorInterceptor, you will notice the 2 headers as well).

**Comment by piyush1594** [comment]
@valentinabojan 

Can you provide the details about the kubernetes-client version you are using. Thanks

**Comment by valentinabojan** [comment]
We are using io.fabric8:openshift-client:3.2.0

**Comment by piyush1594** [comment]
@dipak-pawar Would you like to take a look at this?

**Comment by dipak-pawar** [comment]
@valentinabojan Can you try on `io.fabric8:openshift-client:3.1.0`?

**Comment by valentinabojan** [comment]
@dipak-pawar Yes, same behavior with io.fabric8:openshift-client:3.1.0.

**Comment by dipak-pawar** [comment]
@valentinabojan Thank for confirmation. As you already know all the details about why it's failing. Would you like to provide a fix for it?

**Comment by valentinabojan** [comment]
@dipak-pawar The details that I put in the ticket is what I gathered making a debug to see why our request fails. Lookig at the code, the easiest fix that I could come with is to make the call that gets the token without passing the Authorization header (OpenShiftOAuthInterceptor:121):
```
Response response = clone.newCall(new Request.Builder().get().url(url).header(AUTHORIZATION, credential).build()).execute();
```
would go into
```
Response response = clone.newCall(new Request.Builder().get().url(url).build()).execute();
```

But we don't know the internals of this project at all (we barely started using it yesterday to execute some simple operations in our Openshift cluster) so I don't know the implications that the above change would bring with it.

**Comment by rmartseniuk** [comment]
@valentinabojan Our team was faced with the same problem. How did you solved this problem?

**Comment by valentinabojan** [comment]
@rmartseniuk Instead of using the username/password to authenticate ourselves, we configured the builder to use the OathToken instead. Because the token is volatile, we chose to re-create the OpenShiftClient every time, before executing a command in the cluster through the API.

```
OpenShiftConfigBuilder configBuilder = new OpenShiftConfigBuilder()
    .withMasterUrl(MASTER_URL)
    .withOauthToken(getToken())
    .withNamespace(NAMESPACE);
```

The getToken() method is a close copy of the OpenShiftOAuthInterceptor.authorize() method:
```
try {
            String credential = Credentials.basic(USERNAME, PASSWORD);
            URL url = new URL(URLUtils.join(MASTER_URL, AUTHORIZE_PATH));
            Response response = new OkHttpClient().newCall(new Request.Builder().get().url(url).header(AUTHORIZATION, credential).build()).execute();

            response.body().close();
            response = response.priorResponse() != null ? response.priorResponse() : response;
            response = response.networkResponse() != null ? response.networkResponse() : response;
            String token = response.header(LOCATION);
            if (token == null || token.isEmpty()) {
                throw new KubernetesClientException("Unexpected response (" + response.code() + " " + response.message() + "), to the authorization request. Missing header:[" + LOCATION + "]!");
            }
            token = token.substring(token.indexOf(BEFORE_TOKEN) + BEFORE_TOKEN.length());
            token = token.substring(0, token.indexOf(AFTER_TOKEN));

            return token;
        } catch (Exception e) {
            LOGGER.error("Error when getting OAuth token for OpenShift client: " + e.getMessage(), e);
        }
```

This is clearly not the best approach, but for us was the quickest fix.
