### ISSUE TITLE
Watcher is not notified on unsuccessful response

### ISSUE THREAD

**Issue by rvansa** [fabric8io/kubernetes-client#1163]
Running against Openshift, I am trying to delete existing project and wait for the completion. Therefore I've setup a `Watcher` on the project, expecting a DELETE action.
My user does not have cluster-admin role so I can't access projects that are not mine - the REST call fails with error. All I get is an exception in the log:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://myip:8443/apis/project.openshift.io/v1/projects/myproject?resourceVersion=78601&watch=true. Message: Forbidden.
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure (OperationSupport.java:472)
    at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager$2.onResponse (WatchHTTPManager.java:168)
    at okhttp3.RealCall$AsyncCall.execute (RealCall.java:153)
    at okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
```
but neither `eventReceived` (with ERROR or DELETE action) is called, nor is the watcher forcibly closed.

How should I monitor completion of resource termination?

**Comment by rvansa** [comment]
I've tried to set up watcher on all projects, but this failed with
```
16:25:17.172 [WARN ] i.f.k.c.d.i.WatchConnectionManager - Exec Failure
java.lang.NullPointerException: null
	at java.lang.String.compareTo(String.java:1155) ~[na:1.8.0_172]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:233) ~[kubernetes-client-4.0.3.jar:na]
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204) ~[okhttp-3.9.1.jar:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) [okhttp-3.9.1.jar:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.9.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]
```
(that's a separate bug, though).
