### ISSUE TITLE
NullPointerException in TemplateOperationsImpl if a parameter value is null

### ISSUE THREAD

**Issue by gastaldi** [fabric8io/kubernetes-client#1165]
In TemplateOperationsImpl#processLocally. if the map contains a null parameter value a NPE is thrown. 

```
2018-08-01 17:14:51 WARN  ResourceChecker:53 - Exception in checker task
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:205)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:157)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:59)
	at io.enmasse.controller.common.KubernetesHelper.processTemplate(KubernetesHelper.java:123)
	at io.enmasse.controller.TemplateInfraResourceFactory.createResourceList(TemplateInfraResourceFactory.java:85)
	at io.enmasse.controller.CreateController.handle(CreateController.java:104)
	at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:120)
	at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
	at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
	at java.lang.Thread.run(Thread.java:748)
```

A solution would be to treat the parameter value as an empty string

**Comment by odra** [comment]
I think it could be a good idea to log the parameter name if its value is null as well.

**Comment by gastaldi** [comment]
PR available in https://github.com/fabric8io/kubernetes-client/pull/1166
