### ISSUE TITLE
NullPointerException when running from spark-submit

### ISSUE THREAD

**Issue by dima-spire** [fabric8io/kubernetes-client#1196]
Hi, I'm not familiar with kubernetes-client, but I assume NullPointerException is always a bug:

```
Exception in thread "main" java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:103)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:97)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:719)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:707)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:70)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:144)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$2.apply(KubernetesClientApplication.scala:144)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2584)
	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:144)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:235)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$5.apply(KubernetesClientApplication.scala:227)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2585)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:227)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:192)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20
```

Obtained while trying to run spark example in cluster mode:
```
~/opt/spark/bin/spark-submit \
--master k8s://https://://10.0.123.321:7077 \
--deploy-mode cluster \
--name spark-pi \
--class org.apache.spark.examples.SparkPi \
--conf spark.kubernetes.container.image=gcr.io/my-project/spark:spark-test \
--conf spark.executor.instances=3 \
local:///opt/spark/examples/jars/spark-examples_2.11-2.3.0.jar 1000
```
Spark client & server versions: 2.3.0. Not sure what version of kubernetes-client it uses.

**Comment by dima-spire** [comment]
Found why it was happening:
`--master k8s://https://://10.0.123.321:7077` should probably be
`--master k8s://https://10.0.123.321:7077` or
`--master spark://://10.0.123.321:7077`.

However NullPointerException still stands.

**Comment by dima-spire** [comment]
@rohanKanojia Already shared, see above.

**Comment by rohanKanojia** [comment]
@dima-spire: Sorry, but I asked for a test which reproduces this issue. Stacktrace won't help since code has changed since then.

**Comment by dima-spire** [comment]
Hi @rohanKanojia ,

I'm running example that's included in Spark. The code for it is already in your `spark/examples/jars` directory, it's shipped with Spark. The whole code that I've run is shared above, every single line. Sorry, but don't see what else I can provide.
