### ISSUE TITLE
Does this client library support credential plugin (like aws-iam-authenticator) in kube config file?

### ISSUE THREAD

**Issue by lilida** [fabric8io/kubernetes-client#1200]
I did a quick look at the code and tested in my environment (a bit older version though) It looks like aws-iam-authenticator is not supported yet. Is this true?

**Comment by jglick** [comment]
Confirmed. After configuring `~/.kube/config` [like this](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/README.md#4-set-up-kubectl-to-use-authentication-tokens-provided-by-aws-iam-authenticator-for-kubernetes), which follows [this spec](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuration), e.g. `kubectl get pods` on the command line works but [this code](https://github.com/fabric8io/kubernetes-client/blob/cee8550053e671bb0b3489e37196924f4c949a3f/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L102-L108) fails to add a `Authorization: Bearer …` header from the `.status.token` output of my `aws-iam-authenticator` command, resulting in an error such as

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://….sk1.us-east-1.eks.amazonaws.com/api/v1/namespaces/…/pods. Message: Forbidden! User aws doesn't have permission. pods is forbidden: User "system:anonymous" cannot list pods in the namespace "…".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:476)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:413)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:598)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:63)
```

**Comment by rohanKanojia** [comment]
@jglick : Keeping it open till someone implements the rest of the parts of spec. Could you please specify what else parts need to be implemented for it to get closed?

**Comment by jglick** [comment]
Sorry, just saw your message. I am no longer actively using this library; I just implemented enough for it to work at least for testing purposes.
