### ISSUE TITLE
Class not found exception: io.fabric8.kubernetes.api.builder.VisitableBuilder

### ISSUE THREAD

**Issue by kedarparallel** [fabric8io/kubernetes-client#1263]
I am seeing following exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/api/builder/VisitableBuilder
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.mycompany.app.DeploymentExample.main(DeploymentExample.java:19)
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.api.builder.VisitableBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

My pom.xml looks like following

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>my-app</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>openshift-client</artifactId>
      <version>4.0.0</version>
    </dependency>
    <dependency>
        <groupId>io.fabric8</groupId>
        <artifactId>kubernetes-api</artifactId>
        <version>3.0.11</version>
    </dependency>
  </dependencies>
</project>
```

I will appreciate if someone can point to solution. I searched through issues filed here, stackoverflow and  googled but I cant find any solution.

**Comment by hrishin** [comment]
@kedarparallel looks like its dependency conflicts for `openshift-client`.

If you want to use `openshift-client > v3.2.0` then could you exclude `openshift-client` the dependency from `kubernetes-api` and give it a try if works?

There was breaking change happen in https://github.com/fabric8io/kubernetes-client/releases/tag/v4.0.0

**Comment by kedarparallel** [comment]
Thanks @hrishin, Removing following from pom.xml helped

```
<dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>openshift-client</artifactId>
      <version>4.0.0</version>
</dependency>
```
