### ISSUE TITLE
Switching from 4.0.3 to 4.1.0, WatchConnectionManager is broken

### ISSUE THREAD

**Issue by anthonydahanne** [fabric8io/kubernetes-client#1279]
Hello, after upgrading to 4.1.0, when I "watch" for CRDs , I get the following error : 

```
2018-11-27 12:44:07.061  WARN 90577 --- [99.100:8443/...] i.f.k.c.d.i.WatchConnectionManager       : Exec Failure

java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_192]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_192]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_192]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_192]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_192]
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593) ~[na:1.8.0_192]
	at sun.security.ssl.InputRecord.read(InputRecord.java:532) ~[na:1.8.0_192]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) ~[na:1.8.0_192]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) ~[na:1.8.0_192]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_192]
	at okio.Okio$2.read(Okio.java:139) ~[okio-1.13.0.jar:na]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.request(RealBufferedSource.java:67) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.require(RealBufferedSource.java:60) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:73) ~[okio-1.13.0.jar:na]
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204) ~[okhttp-3.9.1.jar:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) [okhttp-3.9.1.jar:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.9.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]

```

Here is the code that initiated the "watch" :

```java
createCRDIfNotExists(client, TerracottaCRD.CLUSTER_DEFINITION, TerracottaCRD.CLUSTER_FULL_NAME::equals);
    createCRDIfNotExists(client, TerracottaCRD.LICENSE_DEFINITION, TerracottaCRD.LICENSE_FULL_NAME::equals);
KubernetesDeserializer.registerCustomKind(TerracottaCRD.TERRACOTTA_GROUP + "/v1",
                                              TerracottaCRD.CLUSTER_SINGULAR_NAME,
                                              TerracottaDBCluster.class);
KubernetesDeserializer.registerCustomKind(TerracottaCRD.TERRACOTTA_GROUP + "/v1",
                                              TerracottaCRD.LICENSE_SINGULAR_NAME,
                                              License.class);
NonNamespaceOperation<TerracottaDBCluster, TerracottaDBClusterList, DoneableTerracottaDBCluster, Resource<TerracottaDBCluster, DoneableTerracottaDBCluster>> clusterClient
      = client.customResources(TerracottaCRD.CLUSTER_DEFINITION,
                               TerracottaDBCluster.class,
                               TerracottaDBClusterList.class,
                               DoneableTerracottaDBCluster.class).inNamespace(NAMESPACE);
clusterClient.watch(new ClusterWatcher(theService));

NonNamespaceOperation<License, LicenseList, DoneableLicense, Resource<License, DoneableLicense>> licenseClient
      = client.customResources(TerracottaCRD.LICENSE_DEFINITION,
                               License.class,
                               LicenseList.class,
                               DoneableLicense.class).inNamespace(NAMESPACE);
licenseClient.watch(new LicenseWatcher(theService));
``` 

no error happened using 4.0.3

**Comment by HarishHothi** [comment]
+1

**Comment by rohanKanojia** [comment]
@anthonydahanne @HarishHothi : Is it only breaking for CRDs or any other resources also? Would really appreciate if you could share some test which I can use to reproduce this issue? Right now what you shared seems like some snippet of your code.

**Comment by l0yu** [comment]
@rohanKanojia ^^ I run into same issue when switch from 4.0.3 to 4.10
can repo by sample code
https://github.com/fabric8io/kubernetes-client#following-events
```
client.events().inAnyNamespace().watch(new Watcher<Event>() {

  @Override
  public void eventReceived(Action action, Event resource) {
    System.out.println("event " + action.name() + " " + resource.toString());
  }

  @Override
  public void onClose(KubernetesClientException cause) {
    System.out.println("Watcher close due to " + cause);
  }

});
```

**Comment by rohanKanojia** [comment]
okay, let me look into this.

**Comment by l0yu** [comment]
Is it handshack (SSL) issue ? seems like k8s server and client does not use the same protocol somehow

**Comment by rohanKanojia** [comment]
ah, sorry. I could not find time to look into this. Could you please check and send PR if you're investigating?

**Comment by dhanuj** [comment]
Seeing same issue with 4.6.3 as well
2019-11-16 14:34:25.703  WARN 1 --- [0.100.200.1/...] i.f.k.c.d.i.WatchConnectionManager       : Exec Failure

javax.net.ssl.SSLException: Socket closed
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source) ~[na:na]
        at okio.Okio$2.read(Okio.java:140) ~[okio-1.17.2.jar!/:na]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.17.2.jar!/:na]
        at okio.RealBufferedSource.request(RealBufferedSource.java:72) ~[okio-1.17.2.jar!/:na]
        at okio.RealBufferedSource.require(RealBufferedSource.java:65) ~[okio-1.17.2.jar!/:na]
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:78) ~[okio-1.17.2.jar!/:na]
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117) ~[okhttp-3.14.0.jar!/:na]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[okhttp-3.14.0.jar!/:na]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) ~[okhttp-3.14.0.jar!/:na]
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209) ~[okhttp-3.14.0.jar!/:na]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[okhttp-3.14.0.jar!/:na]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.14.0.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
        Suppressed: java.net.SocketException: Socket closed
                at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source) ~[na:na]
                at java.base/java.net.SocketOutputStream.write(Unknown Source) ~[na:na]
                at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(Unknown Source) ~[na:na]
                ... 19 common frames omitted
Caused by: java.net.SocketException: Socket closed
        at java.base/java.net.SocketInputStream.socketRead0(Native Method) ~[na:na]
        at java.base/java.net.SocketInputStream.socketRead(Unknown Source) ~[na:na]
        at java.base/java.net.SocketInputStream.read(Unknown Source) ~[na:na]
        at java.base/java.net.SocketInputStream.read(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source) ~[na:na]
        ... 15 common frames omitted

**Comment by georgeharley** [comment]
Seeing it with version 4.9.1.

**Comment by softwareplumber** [comment]
+1

**Comment by softwareplumber** [comment]
I have the same problem. Spent a couple of hours looking into it. For what it is worth:

- my code seems to work perfectly well when connecting to kubernetes from outside the cluster (e.g. when running in my debugger)
- other API calls seem to be functioning perfectly well
- perhaps this is due to slightly different configuration (my ~/kube/config as opposed to the config delivered via the service account mount)?

And (grumbling) whyohwhyohwhy did the fabric8 folks decide to use an http client library written in kotlin... :-)

I'm entirely stumped at this point. Any pointers would be incredibly appreciated.

**Comment by rohanKanojia** [comment]
@softwareplumber : Would it be possible for you to share a reproducer project with us? Bdw, As far as I remember okhttp maintainers decided to move to kotlin last year. We haven't upgraded to 4.x

**Comment by softwareplumber** [comment]
Sure I think I can make both the helm package and gradle build repos public. Will that work?

My bad re okhttp wasn’t paying attention to the version numbers :-)

**Comment by rohanKanojia** [comment]
We would like a have a minimal example to reproduce this bug(a small project can help). You don't need to make your own projects public. You can create some dummy project which reproduces your problem.

**Comment by softwareplumber** [comment]
Hah. That will take time. I don't really use kubernetes-client, I use the https://github.com/ContainerSolutions/java-operator-sdk framework, and my 'application' at this point is close to a minimal example of a k8s operator using that framework. So I'd be starting from scratch to provide a 'minimal' example.

I turned on javax.net.debug=all and have some more observations:

I can see the original HTTP connection request go out with the upgrade header in it and the response comes back with the Sec-Websocket-Accept header. 

I can even see what appear to be 'ping' and 'pong' frames passing between the client and the server. In other words the websocket connection appears perfectly healthy.

My current theory therefore is that it's actually the health check on my application which is broken, which is causing Kube to shut it down, and the 'Socket closed' exception is simply something that happens during a forced shutdown.  So I'm going to investigate this possibility before wasting any more of your time...

**Comment by softwareplumber** [comment]
Ok... can confirm it was my mistake. The application closing was causing the error, rather than the error causing the application to close. Sorry!!

**Comment by manusa** [comment]
Is anyone else still affected by this issue? Can we close it?
