### ISSUE TITLE
 failed to parse kubeconfig with "Unrecognized field "expirationTimestamp"

### ISSUE THREAD

**Issue by waynegj** [fabric8io/kubernetes-client#1295]
spark-submit to AWS EKS, below error was thrown and authentication failed.

`2018-12-18 13:55:20 ERROR Config:552 - Failed to parse the kubeconfig.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:177)
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:531)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:452)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:204)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:192)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:16)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:13)
	at org.apache.spark.deploy.k8s.SparkKubernetesClientFactory$.createKubernetesClient(SparkKubernetesClientFactory.scala:71)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$7(KubernetesClientApplication.scala:232)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2500)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:232)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:201)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:852)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:931)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:940)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "expirationTimestamp" (class io.fabric8.kubernetes.client.Config$ExecCredentialStatus), not marked as ignorable (one known property: "token"])
 at [Source: (BufferedInputStream); line: 1, column: 122] (through reference chain: io.fabric8.kubernetes.client.Config$ExecCredential["status"]->io.fabric8.kubernetes.client.Config$ExecCredentialStatus["expirationTimestamp"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3077)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:235)
	... 20 more`

EKS generates a kubeconfig like below:
`apiVersion: v1
clusters:
- cluster:
    server: <endpoint-url>
    certificate-authority-data: <base64-encoded-ca-cert>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "<cluster-name>"
        # - "-r"
        # - "<role-arn>"
      # env:
        # - name: AWS_PROFILE
        #   value: "<aws-profile>"`

aws-iam-authenticator generates a token info as:

`{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1alpha1","spec":{},"status":{"expirationTimestamp":"2018-12-18T06:23:26Z","token":"***************************"}}`

The kubernetes-client building Spark is:

`./assembly/target/maven-shared-archive-resources/META-INF/DEPENDENCIES:  - zjsonpatch (https://github.com/fabric8io/zjsonpatch/) io.fabric8:zjsonpatch:bundle:0.3.0
./assembly/target/maven-shared-archive-resources/META-INF/DEPENDENCIES:  - Fabric8 :: Kubernetes :: Java Client (http://fabric8.io/kubernetes-client/) io.fabric8:kubernetes-client:jar:4.1.0
./assembly/target/maven-shared-archive-resources/META-INF/DEPENDENCIES:  - Fabric8 :: Kubernetes Model (http://fabric8.io/kubernetes-model-generator/kubernetes-model/) io.fabric8:kubernetes-model:bundle:4.1.0`

https://github.com/fabric8io/kubernetes-client/pull/1224 is the contribute to handle aws-iam-authenticator.

**Comment by waynegj** [comment]
@jglick , can you help shed some light on this? Thanks.

**Comment by jglick** [comment]
@waynegj see #1280.
