### ISSUE TITLE
Support for EC Private Keys

### ISSUE THREAD

**Issue by trevorndodds** [fabric8io/kubernetes-client#1314]
Hi,

The keys I have are EC Private Keys. 
-----BEGIN EC PRIVATE KEY-----

I noticed the official java kubernetes-client added support for EC Private keys in Feb 2018. 
Any plans to add support? 

```
Caused by: java.io.IOException: Invalid DER: object is not integer
        at io.fabric8.kubernetes.client.internal.PKCS1Util$Asn1Object.getInteger(PKCS1Util.java:125)
        at io.fabric8.kubernetes.client.internal.PKCS1Util.next(PKCS1Util.java:55)
        at io.fabric8.kubernetes.client.internal.PKCS1Util.decodePKCS1(PKCS1Util.java:46)
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:116)
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:197)
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:128)
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:122)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:78)
```

**Comment by rohanKanojia** [comment]
I think it's a nice feature. We should add this to our client also
