### ISSUE TITLE
Okhttp error : java.io.EOFException: \n not found: limit=0 content=…

### ISSUE THREAD

**Issue by ScrapCodes** [fabric8io/kubernetes-client#1321]
To reproduce, use the following snippet.

```scala
val statefulSet: StatefulSet = new StatefulSetBuilder()
    .withApiVersion("apps/v1")
    .withKind("StatefulSet")
    .withNewMetadata()
      .withName("zk")
    .endMetadata()
    .withNewSpec()
      .withReplicas(3)
      .withServiceName(Services.internalService.getMetadata.getName)
    .withNewSelector()
      .addToMatchLabels(Services.labels)
      .endSelector()
      .withNewUpdateStrategy()
        .withType("type")
        .withNewRollingUpdate()
          .endRollingUpdate()
      .endUpdateStrategy()
    .withPodManagementPolicy("Parallel")
    .withNewTemplate()
      .withNewMetadata()
        .withLabels(Services.labels)
        .endMetadata()
      .endTemplate()
    .endSpec()
    .build()
.apps()


   val ss =    new DefaultKubernetesClient().inNamespace("default")
.statefulSets().create(ZKStatefulSet.statefulSet)
```
client version: kubernetes-client-4.1.0
Error:
```
[error] (run-main-1f) io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [StatefulSet]  with name: [null]  in namespace: [default]  failed.
[error] io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [StatefulSet]  with name: [null]  in namespace: [default]  failed.
[error] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
[error] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
[error] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
[error] 	at Main$.main(Main.scala:39)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.io.IOException: unexpected end of stream on Connection{9.30.110.150:6443, proxy=DIRECT hostAddress=/9.30.110.150:6443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
[error] 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
[error] 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:66)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:109)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
[error] 	at okhttp3.RealCall.execute(RealCall.java:77)
[error] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
[error] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
[error] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227)
[error] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:780)
[error] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:349)
[error] 	at Main$.main(Main.scala:39)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.io.EOFException: \n not found: limit=0 content=…
[error] 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
[error] 	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
[error] 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
[error] 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:66)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:109)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[error] 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
[error] 	at okhttp3.RealCall.execute(RealCall.java:77)
[error] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
[error] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
[error] 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227)
[error] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:780)
[error] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:349)
[error] 	at Main$.main(Main.scala:39)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1

```

This error comes, on trying to create a stateful set, I can create services without any problem, using the same client as above.

**Comment by ScrapCodes** [comment]
There are many stack over flow, answers suggesting that, it happens due to request not closed. https://stackoverflow.com/questions/45838774/java-io-ioexception-unexpected-end-of-stream-on-connection-in-android

**Comment by ScrapCodes** [comment]
Hi All, any comments on the above mentioned issue? Is there a work around? Am I doing something wrong here?

**Comment by rohanKanojia** [comment]
@ScrapCodes : I haven't tried reproducing your bug. Could you please take a look at one of the tests and see if you missed something:

https://github.com/fabric8io/kubernetes-client/blob/67ec4dffe5d4754a49236d0a5284dcd821eba981/kubernetes-itests/src/test/java/io/fabric8/kubernetes/StatefulSetIT.java#L60-L100

**Comment by ScrapCodes** [comment]
By removing the section on 
```
      .withNewUpdateStrategy()
        .withType("type")
        .withNewRollingUpdate()
          .endRollingUpdate()
      .endUpdateStrategy()
```
It started working, makes me wonder, what is wrong with it. Or can we improve the error reporting?
