### ISSUE TITLE
jackson annotation jar version conflict.

### ISSUE THREAD

**Issue by ScrapCodes** [fabric8io/kubernetes-client#1323]
On building against 4.1.1 kubernetes client version, following exception is thrown.

```
[error] (run-main-0) java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
[error] java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
[error] 	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:50)
[error] 	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:291)
[error] 	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:44)
[error] 	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:466)
[error] 	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:452)
[error] 	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:204)
[error] 	at io.fabric8.kubernetes.client.Config.<init>(Config.java:192)
[error] 	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:16)
[error] 	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:13)
[error] 	at Main$.main(Main.scala:29)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonMerge
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:50)
[error] 	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:291)
[error] 	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:44)
[error] 	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:466)
[error] 	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:452)
[error] 	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:204)
[error] 	at io.fabric8.kubernetes.client.Config.<init>(Config.java:192)
[error] 	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:16)
[error] 	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:13)
[error] 	at Main$.main(Main.scala:29)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by rohanKanojia** [comment]
Closed via #1324
