### ISSUE TITLE
Rename apiVersion → apiGroupVersion breaks client

### ISSUE THREAD

**Issue by jglick** [fabric8io/kubernetes-client#1347]
What is the rename by @iocanel in #1322 about? It matches neither [documentation](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources) nor what I observe from `kubectl get -o json` in a `v1.11.5-gke.5` cluster. In fact using the `master` version of this library, I get errors such as

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "apiVersion" (class io.jenkins.x.client.kube.PipelineActivityList), not marked as ignorable (4 known properties: "items", "apiGroupVersion", "kind", "metadata"])
 at [Source: java.io.BufferedInputStream@73f07257; line: 1, column: 16] (through reference chain: io.jenkins.x.client.kube.PipelineActivityList["apiVersion"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1478)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1456)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2931)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:235)
Caused: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:384)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:328)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:168)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:593)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
	at …
```

from [this definition](https://github.com/jenkins-x/jx-java-client/blob/e78ede5a34484cb9a77f2134edad2f4bf716252f/src/main/java/io/jenkins/x/client/kube/PipelineActivityList.java#L5). The error is fixed by reverting the patch to `CustomResourceList`.

**Comment by jglick** [comment]
I guess this was a case of an overeager rename refactoring?

**Comment by iocanel** [comment]
Yeah!

**Comment by iocanel** [comment]
There are internals where apiVersion meant apiVersionGroup/apiVersionNumber
(which is how k8s treat it) and other where it meant apiVersionNumber. In
the effort to clarify things I overdid it.
