### ISSUE TITLE
Unable to specify file permissions in octal

### ISSUE THREAD

**Issue by alde** [fabric8io/kubernetes-client#1356]
When trying to specify filePermissions in octal, such as
```
        secret:
          secretName: ssh-key
          defaultMode: 0600
```
I get an error that it must be between 0 and 0777

In order to get around it, I had to set the mode to 384 (decimal representation of 0600). I'm using the jenkins-kubernetes plugin, but I believe the error comes from this library.

Attaching stacktrace:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/api/v1/namespaces/default/pods. Message: Pod "smith-xdw5q" is invalid: [spec.volumes[1].secret.defaultMode: Invalid value: 600: must be a number between 0 and 0777 (octal), both inclusive, spec.volumes[2].secret.defaultMode: Invalid value: 600: must be a number between 0 and 0777 (octal), both inclusive, spec.containers[0].volumeMounts[1].name: Not found: "secrets", spec.containers[0].volumeMounts[2].name: Not found: "ssh-key", spec.containers[1].volumeMounts[0].name: Not found: "secrets", spec.containers[1].volumeMounts[1].name: Not found: "secrets", spec.initContainers[0].volumeMounts[1].name: Not found: "secrets"]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.volumes[1].secret.defaultMode, message=Invalid value: 600: must be a number between 0 and 0777 (octal), both inclusive, reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.volumes[2].secret.defaultMode, message=Invalid value: 600: must be a number between 0 and 0777 (octal), both inclusive, reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.containers[0].volumeMounts[1].name, message=Not found: "secrets", reason=FieldValueNotFound, additionalProperties={}), StatusCause(field=spec.containers[0].volumeMounts[2].name, message=Not found: "ssh-key", reason=FieldValueNotFound, additionalProperties={}), StatusCause(field=spec.containers[1].volumeMounts[0].name, message=Not found: "secrets", reason=FieldValueNotFound, additionalProperties={}), StatusCause(field=spec.containers[1].volumeMounts[1].name, message=Not found: "secrets", reason=FieldValueNotFound, additionalProperties={}), StatusCause(field=spec.initContainers[0].volumeMounts[1].name, message=Not found: "secrets", reason=FieldValueNotFound, additionalProperties={})], group=null, kind=Pod, name=smith-xdw5q, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "smith-xdw5q" is invalid: [spec.volumes[1].secret.defaultMode: Invalid value: 600: must be a number between 0 and 0777 (octal), both inclusive, spec.volumes[2].secret.defaultMode: Invalid value: 600: must be a number between 0 and 0777 (octal), both inclusive, spec.containers[0].volumeMounts[1].name: Not found: "secrets", spec.containers[0].volumeMounts[2].name: Not found: "whitesource", spec.containers[1].volumeMounts[0].name: Not found: "secrets", spec.containers[1].volumeMounts[1].name: Not found: "secrets", spec.initContainers[0].volumeMounts[1].name: Not found: "secrets"], metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:476)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:415)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:780)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:349)
    at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:105)
    at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Nolaan** [comment]
I'm always baffled by guys in the Open Source community and their obscure unorthodox, antisocial choices.
We use for ages binary of hex representation, yet some dudes decides to use the octal just because why not!
