### ISSUE TITLE
v4.1.2 endpoints rest api been blocked

### ISSUE THREAD

**Issue by candyleer** [fabric8io/kubernetes-client#1359]
![image](https://user-images.githubusercontent.com/11530760/52924157-7094ee00-3366-11e9-9681-0265805473dd.png)
 the source file not found and the code  maybe not right for `endpointss` ,correct is `endpoint` that makes the rest api is 404 ,thus makes it's not avaiable

```java
java.util.concurrent.ExecutionException: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://xxx-cloud.com/api/v1/namespaces/default/endpointss?labelSelector=app%3Daabb-svc. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
```

I found the reason:
in `kubernetes-client/resources/resource-operation.vm`
```
  public ${model.name}OperationsImpl(OkHttpClient client, Config config, String apiGroupVersion, String namespace, String name, Boolean cascading, ${model.name} item, String resourceVersion, Boolean reloadingFromServer, long gracePeriodSeconds, Map<String, String> labels, Map<String, String> labelsNot, Map<String, String[]> labelsIn, Map<String, String[]> labelsNotIn, Map<String, String> fields) {
    super(client, config, "$apiGroupName", apiGroupVersion, "#pluralize ($model.name.toLowerCase())", namespace, name, cascading, item, resourceVersion, reloadingFromServer, gracePeriodSeconds, labels, labelsNot, labelsIn, labelsNotIn, fields);
  }
```

`pluralize` makes this error,but I dont know how to amend this error

**Comment by rohanKanojia** [comment]
@candyleer : Hmm, yeah. we can add a workaround until this gets fixed in sundrio

**Comment by candyleer** [comment]
`sundrio` have release the new version for your fix.so I make a PR to update the dependence?

**Comment by rohanKanojia** [comment]
@candyleer : go for it :+1:
