### ISSUE TITLE
Can't connect to Microk8s instance

### ISSUE THREAD

**Issue by jonathanknez** [fabric8io/kubernetes-client#1454]
My project runs outside kubernetes and connects to it to query and create ConfigMaps. I use the fabric8 kubernetes-client to connect to kubernetes. The fabric8 kubernetes client successfully connects to minikube instances but fails to connect to microk8s instances.

Kubernetes version: 1.13.4 (both minikube and microk8s use this version)
Fabric8 Kubernetes-Client: 4.1.0

Exception:

> io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Namespace]  with name: [alpha]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:221)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177)
...
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)[:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)[:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)[:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)[:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)[:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589)[:1.8.0_191]
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)

For minikube, the k8s client uses **~/.kube/config** for connection info. For microk8s, this file does not exist so I created one by running **microk8s.kubectl config view --raw > ~/mpc/kubeconfig** then passing that file to the k8s client. That config file looks good. 
> apiVersion: v1
clusters:
\- cluster:
    server: http://127.0.0.1:8080
  name: microk8s-cluster
contexts:
\- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
\- name: admin
  user:
    username: admin

I opened up http://127.0.0.1:8080 in a browser and confirmed I can perform API operations like listing namespaces and deleting a namespace without issues. The exception from the k8s client happens on my first API operation. It looks like a network issue but this is all loopback and no firewall is running. Minikube uses server and user certificates. Microk8s does not appear to need that stuff (for this local dev installation). Perhaps the k8s client assumes it will connect over https.

**Comment by jonathanknez** [comment]
I found a workaround. Previously, we were connecting using a kube config file as shown below.

`Config config = Config.fromKubeconfig(myFile);`
`KubernetesClient client = DefaultKubernetesClient(config);`

The kube config passed in was generated by Microk8s and is valid. The connection failed. So instead I switched to just using a simple URL for the connection:


`String url = "http://127.0.0.1:8080";`
`KubernetesClient client = DefaultKubernetesClient(url);`

That connection is opened successfully and can be used to query and create kubernetes objects. So I have a connection open from my application over to Microk8s and I can do work. My question remains though, why was connecting to that same url through the kube config file unsuccessful?
