### ISSUE TITLE
TextNode cannot be cast to ObjectNode

### ISSUE THREAD

**Issue by tprus** [fabric8io/kubernetes-client#1478]
There is problem with parsing YAML config with JSON element like that:

```
apiVersion: v1
data:
  staging.json: |
    {
      "type": "service_account",
      ...
    }
```

It throws error:
```
java.lang.ClassCastException: com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:73)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3079)
	at io.fabric8.kubernetes.api.KubernetesHelper.loadYaml(KubernetesHelper.java:513)
```

The purpose of that part is to be able to pipe json file so when we mount the configmap we can have a json file with the content from it.

It is well documented in kubernetes
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-directories

I'm able to apply it manually using kubectl apply -f

**Comment by rohanKanojia** [comment]
seems like a valid bug.

**Comment by sztwiorok** [comment]
what about this issue? is it solved?
