### ISSUE TITLE
The kubernetes-client is not optionally depending on bouncycastle.

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-client#1480]
I am using the client in a downstream project without the bouncycaslte dependencies and I am getting the error below:
    
       java.lang.IllegalStateException: Please make sure org.bouncycastle:bcprov-ext-jdk15on and org.bouncycastle:bcpkix-jdk15on are included in your project's classpath. 
        at io.ap4k.deps.kubernetes.client.Config.getKeyAlgorithm(Config.java:675)
        at io.ap4k.deps.kubernetes.client.Config.configFromSysPropsOrEnvVars(Config.java:291)
        at io.ap4k.deps.kubernetes.client.Config.autoConfigure(Config.java:216)
        at io.ap4k.deps.kubernetes.client.Config.<init>(Config.java:200)
        at io.ap4k.deps.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:16)
        at io.ap4k.deps.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:13)
        at io.ap4k.deps.kubernetes.client.BaseClient.<init>(BaseClient.java:48)
        at io.ap4k.deps.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:83)
        at io.ap4k.servicecatalog.mapping.ServiceCatalogMappingTest.shouldUnmarshallUsingTheClient(ServiceCatalogMappingTest.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
    Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
        at io.ap4k.deps.kubernetes.client.Config.getKeyAlgorithm(Config.java:668)
        ... 61 more
    Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 62 more
          at io.ap4k.deps.kubernetes.client.Config.getKeyAlgorithm(Config.java:675)
        at io.ap4k.deps.kubernetes.client.Config.configFromSysPropsOrEnvVars(Config.java:291)
        at io.ap4k.deps.kubernetes.client.Config.autoConfigure(Config.java:216)
        at io.ap4k.deps.kubernetes.client.Config.<init>(Config.java:200)
        at io.ap4k.deps.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:16)
        at io.ap4k.deps.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:13)
        at io.ap4k.deps.kubernetes.client.BaseClient.<init>(BaseClient.java:48)
        at io.ap4k.deps.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:83)
        at io.ap4k.servicecatalog.mapping.ServiceCatalogMappingTest.shouldUnmarshallUsingTheClient(ServiceCatalogMappingTest.java:48)

**Comment by rohanKanojia** [comment]
@iocanel : Apologies, I would push a fix as soon as I can maybe today or this weekend

**Comment by tareqhs** [comment]
Hi @rohanKanojia ,
I'm trying to upgrade to 4.2.0 and this is blocking the move. When is 4.2.1 planned to be released?
thank you

**Comment by rohanKanojia** [comment]
@tareqhs : Hi, It's planned to be released today

**Comment by rohanKanojia** [comment]
@tareqhs : Hi, Kubernetes client is released: http://repo2.maven.org/maven2/io/fabric8/kubernetes-client/4.2.1/ .
