### ISSUE TITLE
Unexpected response(403 Forbidden), to the authorization request. Missing header:[Location]!

### ISSUE THREAD

**Issue by mchoma** [fabric8io/kubernetes-client#1505]
With OCP 4.0 / 4.1 (Kubernetes Master Version v1.13.4+81fc896) we are facing problem with fabric8 client authenticating using username/password - `IOException: Unexpected response(403 Forbidden), to the authorization request. Missing header:[Location]!` We have workarounded it by using token. Same code works ok with OCP 3.11 

```
Caused by: java.io.IOException: Unexpected response(403 Forbidden), to the authorization request. Missing header:[Location]!
	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.authorize(OpenShiftOAuthInterceptor.java:133)
	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.acquireNewToken(OpenShiftOAuthInterceptor.java:111)
	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:63)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:826)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:243)
	... 47 more
```

**Comment by mnovak1** [comment]
The issue is that:
`curl -X GET -H "Authorization: Bearer $(echo -n kubeadmin:ivHQv-NM9xd-MtiPW-sejsD | base64)" https://api.eap-qe-ocp41-cluster.eap-qe-ocp41-cluster.fw.rhcloud.com:6443/oauth/authorize?response_type=token&client_id=openshift-challenging-client` gives

```
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
If token is used instead then it works:
```
curl -k -X GET -H "Authorization: Bearer mNv69W5OJMkumHZKN3Esr0niepkzj3x-7KIxNh58oFg" https://api.eap-qe-ocp41-cluster.eap-qe-ocp41-cluster.fw.rhcloud.com:6443/oauth/authorize?response_type=token&client_id=openshift-challenging-client
[1] 29212
[mchoma@10 openshift-eap-tests (ocp_41)]$ {
  "paths": [
    "/apis",
    "/metrics",
    "/swagger-ui/",
    "/version"
  ]
}
```

This appears to change in Openshift 4.1 API but it might be bug as well - I've reported issue https://bugzilla.redhat.com/show_bug.cgi?id=1706708 to make it clear.

**Comment by mchoma** [comment]
From OCP bugzilla there was change of url to get token from 

https://api.eap-qe-ocp41-cluster3.eap-qe-ocp41-cluster3.fw.rhcloud.com:6443/oauth/authorize
-> 
https://openshift-authentication-openshift-authentication.apps.eap-qe-ocp41-cluster3.eap-qe-ocp41-cluster3.fw.rhcloud.com/oauth/authorize

So that mean on [2] there should be instead of masterUrl some new parameter used? Default value can be derived from masterUrl

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1706708
[2] https://github.com/fabric8io/kubernetes-client/blob/cd12970936593382cb8b0ed2e77e4bce0308b9ff/openshift-client/src/main/java/io/fabric8/openshift/client/internal/OpenShiftOAuthInterceptor.java#L125

**Comment by mnovak1** [comment]
Based on comments in follow up bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1710857 Kubernetes client should query:
`https://<cluster-name>/.well-known/oauth-authorization-server` and use authorization endpoint to request token. For example:
https://api.eap-qe-ocp41-cluster.eap-qe-ocp41-cluster.fw.rhcloud.com:6443/.well-known/oauth-authorization-server will return Http response with following headers:

```
  "issuer": "https://oauth-openshift.apps.m051.devcluster.openshift.com",
  "authorization_endpoint": "https://oauth-openshift.apps.m051.devcluster.openshift.com/oauth/authorize",
  "token_endpoint": "https://oauth-openshift.apps.m051.devcluster.openshift.com/oauth/token",
  "scopes_supported": [
    "user:check-access",
    "user:full",
    "user:info",
    "user:list-projects",
    "user:list-scoped-projects"
  ],
  "response_types_supported": [
    "code",
    "token"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}

Kubernetes client library should be changed to this way of getting token.
```

**Comment by llowinge** [comment]
Done with https://github.com/fabric8io/kubernetes-client/pull/1659

**Comment by mchoma** [comment]
Works for me with client 4.6.1. Thanks.
