### ISSUE TITLE
Openshift SCC not applied when fabric8io client is used within a container

### ISSUE THREAD

**Issue by skonto** [fabric8io/kubernetes-client#1598]
This happens when Spark Operator tries to run a spark-submit from within its container.
Spark submit will run inside the container and will try to submit to the K8s api server the Spark driver pod. Spark backend called by Spark Submit creates the fabric8io client (k8s one not openshift one)[here](https://github.com/apache/spark/blob/54da3bbfb2c936827897c52ed6e5f0f428b98e9f/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/SparkKubernetesClientFactory.scala#L49-L69) and tries to create the pod.
That pod will then create the executor pods from within the cluster.
I have a new dummy scc (beyond the restricted one) which tries to enforce an fsGroup value to the driver pod:
```scc.yaml 
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-test
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs 
  ranges: 
  - max: 6000
    min: 1000 
```
I have added the service account `myaccount` used by the operator pod to the related scc above  and I was expecting the scc to be applied (I can easily apply the scc with a pod spec outside spark on the same cluster using a  non-privileged user).
Here is my driver's spec:
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "...."
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.3.jar"
  arguments:
    - "100000000"
  sparkVersion: "2.4.3"
  sparkConf:
  restartPolicy:
    type: Never
  driver:
    memory: "500m"
    labels:
      version: 2.4.3
    serviceAccount: myaccount
    securityContext:
      fsGroup: 1234
  executor:
    instances: 2
    memory: "500m"
    labels:
      version: 2.4.0
    securityContext:
      fsGroup: 1234
```
What I observed is that fabric8io client will pickup default token and ca and will try to use them... 

```
19/06/21 11:32:51 DEBUG Config: Did not find Kubernetes config at: [/.kube/config]. Ignoring.
19/06/21 11:32:51 DEBUG Config: Trying to configure client from service account...
19/06/21 11:32:51 DEBUG Config: Found service account host and port: 172.30.0.1:443
19/06/21 11:32:51 DEBUG Config: Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
19/06/21 11:32:51 DEBUG Config: Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
19/06/21 11:32:51 DEBUG Config: Trying to configure client namespace from Kubernetes service account namespace path...
19/06/21 11:32:51 DEBUG Config: Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
19/06/21 11:32:52 DEBUG WatchConnectionManager: Connecting websocket ... io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@40f70521
19/06/21 11:32:52 DEBUG WatchConnectionManager: WebSocket successfully opened
19/06/21 11:32:53 DEBUG WatchConnectionManager: Force closing the watch io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@40f70521
19/06/21 11:32:53 DEBUG LoggingPodStatusWatcherImpl: Stopping watching application spark-c8908838fd7340d9999166ef4b22423b with last-observed phase unknown
19/06/21 11:32:53 DEBUG WatchConnectionManager: Closing websocket okhttp3.internal.ws.RealWebSocket@757d6814
19/06/21 11:32:53 DEBUG WatchConnectionManager: Ignoring onFailure for already closed/closing websocket
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:67)
	at okio.RealBufferedSource.require(RealBufferedSource.java:60)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/spark/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "spark-pi-driver" is forbidden: unable to validate against any pod security policy: [fsGroup: Invalid value: []int64{1234}: 1234 is not an allowed group].
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(Op

```
If I use a privileged Openshift user and pass his token with the following spark options then it works:
```    
spark.kubernetes.authenticate.submission.oauthToken: 
   spark.kubernetes.authenticate.driver.oauthToken: 
```
It never worked with a service account though or a non-privileged user. Any ideas?
Why fabric8io client is picking up the container's default token above?
Why by default this does not work even if we added the related service account of the operator pod to the specific scc?

**Comment by skonto** [comment]
Do I need to switch to the Openshift client?

**Comment by skonto** [comment]
@iocanel any ideas?

**Comment by skonto** [comment]
I have verified that this works as expected with kubectl running withing the operator pod and I was able to create a pod with that command and the correct scc was applied. This seems to be fabric8io client specific @iocanel. I will try to debug what fabric does.

**Comment by chakpongchung** [comment]
@skonto 
same problem here:

spark-2.4.4-bin-hadoop2.7 $ ./run.sh
log4j:WARN No appenders could be found for logger (io.fabric8.kubernetes.client.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failed to start websocket

**Comment by dxxd116** [comment]
I have the same issue when I try to  lauch spark job using jupyter/pyspark-notebook image from Jupyterhub.

**Comment by rohanKanojia** [comment]
Thanks for reporting. We need to investigate why it's not working well with SCCs.

**Comment by rohanKanojia** [comment]
Hi guys, I'm trying to reproduce this issue. I build a sample reproducer project which tries to create a `SecurityContextConstraint` from within a Pod: https://github.com/r0haaaan/fabric8-securitycontextconstraints

It tries to run this simple code inside Pod:
```java
        try (final OpenShiftClient oc = new DefaultOpenShiftClient()) {
            logger.info("Loading SecurityContextConstraint from YAML manifest");
            SecurityContextConstraints scc = oc.securityContextConstraints().load(ApplySCC.class.getResourceAsStream("/test-scc.yml")).get();

            logger.info("Applying SecurityContextConstraint to OpenShift Cluster");
            oc.securityContextConstraints().createOrReplace(scc);
        }
```

I was doing all this using `default` ServiceAccount so I created a `ClusterRoleBinding` giving it required privileges:
```
oc  create clusterrolebinding default-pod --clusterrole cluster-admin --serviceaccount=myproject:default
```

I added this into a simple maven project and deployed this to OpenShift using [Eclipse JKube](https://github.com/eclipse/jkube) :
```
fabric8-securitycontextconstraints : $ mvn oc:deploy
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< org.example:fabric8-securitycontextconstraints >-----------
[INFO] Building fabric8-securitycontextconstraints 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> openshift-maven-plugin:1.0.2:deploy (default-cli) > install @ fabric8-securitycontextconstraints >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fabric8-securitycontextconstraints ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- openshift-maven-plugin:1.0.2:resource (jkube) @ fabric8-securitycontextconstraints ---
[INFO] oc: Using docker image name of namespace: myproject
[INFO] oc: Running generator java-exec
[INFO] oc: java-exec: Using Docker image quay.io/jkube/jkube-java-binary-s2i:0.0.8 as base / builder
[INFO] oc: Using resource templates from /home/rohaan/work/repos/fabric8-securitycontextconstraints/src/main/jkube
[INFO] oc: jkube-controller: Adding a default DeploymentConfig
[INFO] oc: jkube-service: Adding a default service 'fabric8-securitycontextconstraints' with ports [8080]
[INFO] oc: jkube-revision-history: Adding revision history limit to 2
[INFO] oc: validating /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/classes/META-INF/jkube/openshift/fabric8-securitycontextconstraints-service.yml resource
[INFO] oc: validating /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/classes/META-INF/jkube/openshift/fabric8-securitycontextconstraints-deploymentconfig.yml resource
[INFO] oc: validating /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/classes/META-INF/jkube/openshift/fabric8-securitycontextconstraints-route.yml resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fabric8-securitycontextconstraints ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fabric8-securitycontextconstraints ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/rohaan/work/repos/fabric8-securitycontextconstraints/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ fabric8-securitycontextconstraints ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ fabric8-securitycontextconstraints ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ fabric8-securitycontextconstraints ---
[INFO] Building jar: /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/fabric8-securitycontextconstraints-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-assembly-plugin:3.3.0:single (default) @ fabric8-securitycontextconstraints ---
[INFO] Building jar: /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/fabric8-securitycontextconstraints-1.0-SNAPSHOT-jar-with-dependencies.jar
[INFO] 
[INFO] --- openshift-maven-plugin:1.0.2:build (jkube) @ fabric8-securitycontextconstraints ---
[INFO] oc: Using OpenShift build with strategy S2I
[INFO] oc: Running in OpenShift mode
[INFO] oc: Running generator java-exec
[INFO] oc: java-exec: Using Docker image quay.io/jkube/jkube-java-binary-s2i:0.0.8 as base / builder
[INFO] oc: [fabric8-securitycontextconstraints:latest] "java-exec": Created docker source tar /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/docker/fabric8-securitycontextconstraints/latest/tmp/docker-build.tar
[INFO] oc: Updating BuildServiceConfig fabric8-securitycontextconstraints-s2i for Source strategy
[INFO] oc: Adding to ImageStream fabric8-securitycontextconstraints
[INFO] oc: Starting Build fabric8-securitycontextconstraints-s2i
[INFO] oc: Waiting for build fabric8-securitycontextconstraints-s2i-2 to complete...
[INFO] oc: Using quay.io/jkube/jkube-java-binary-s2i:0.0.8 as the s2i builder image
[INFO] oc: INFO S2I source build with plain binaries detected
[INFO] oc: INFO S2I binary build from fabric8-maven-plugin detected
[INFO] oc: INFO Copying binaries from /tmp/src/deployments to /deployments ...
[INFO] oc: fabric8-securitycontextconstraints-1.0-SNAPSHOT-jar-with-dependencies.jar
[INFO] oc: INFO Copying deployments from deployments to /deployments...
[INFO] oc: '/tmp/src/deployments/fabric8-securitycontextconstraints-1.0-SNAPSHOT-jar-with-dependencies.jar' -> '/deployments/fabric8-securitycontextconstraints-1.0-SNAPSHOT-jar-with-dependencies.jar'
[INFO] oc: INFO Cleaning up source directory (/tmp/src)
[INFO] oc: Pushing image 172.30.1.1:5000/myproject/fabric8-securitycontextconstraints:latest ...
[INFO] oc: Pushed 3/4 layers, 94% complete
[INFO] oc: Pushed 4/4 layers, 100% complete
[INFO] oc: Build fabric8-securitycontextconstraints-s2i-2 in status Complete
[INFO] oc: Found tag on ImageStream fabric8-securitycontextconstraints tag: sha256:fbdf2c99a5f0b75441c4ffeff45fdf48df542e5b946e8ab52038f3cc2052396b
[INFO] oc: ImageStream fabric8-securitycontextconstraints written to /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/fabric8-securitycontextconstraints-is.yml
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ fabric8-securitycontextconstraints ---
[INFO] Installing /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/fabric8-securitycontextconstraints-1.0-SNAPSHOT.jar to /home/rohaan/.m2/repository/org/example/fabric8-securitycontextconstraints/1.0-SNAPSHOT/fabric8-securitycontextconstraints-1.0-SNAPSHOT.jar
[INFO] Installing /home/rohaan/work/repos/fabric8-securitycontextconstraints/pom.xml to /home/rohaan/.m2/repository/org/example/fabric8-securitycontextconstraints/1.0-SNAPSHOT/fabric8-securitycontextconstraints-1.0-SNAPSHOT.pom
[INFO] Installing /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/classes/META-INF/jkube/openshift.yml to /home/rohaan/.m2/repository/org/example/fabric8-securitycontextconstraints/1.0-SNAPSHOT/fabric8-securitycontextconstraints-1.0-SNAPSHOT-openshift.yml
[INFO] Installing /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/fabric8-securitycontextconstraints-1.0-SNAPSHOT-jar-with-dependencies.jar to /home/rohaan/.m2/repository/org/example/fabric8-securitycontextconstraints/1.0-SNAPSHOT/fabric8-securitycontextconstraints-1.0-SNAPSHOT-jar-with-dependencies.jar
[INFO] Installing /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/fabric8-securitycontextconstraints-is.yml to /home/rohaan/.m2/repository/org/example/fabric8-securitycontextconstraints/1.0-SNAPSHOT/fabric8-securitycontextconstraints-1.0-SNAPSHOT-is.yml
[INFO] 
[INFO] <<< openshift-maven-plugin:1.0.2:deploy (default-cli) < install @ fabric8-securitycontextconstraints <<<
[INFO] 
[INFO] 
[INFO] --- openshift-maven-plugin:1.0.2:deploy (default-cli) @ fabric8-securitycontextconstraints ---
[INFO] oc: Using OpenShift at https://192.168.42.223:8443/ in namespace myproject with manifest /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/classes/META-INF/jkube/openshift.yml 
[INFO] oc: OpenShift platform detected
[INFO] oc: Using project: myproject
[INFO] oc: Creating a Service from openshift.yml namespace myproject name fabric8-securitycontextconstraints
[INFO] oc: Created Service: target/jkube/applyJson/myproject/service-fabric8-securitycontextconstraints.json
[INFO] oc: Creating a DeploymentConfig from openshift.yml namespace myproject name fabric8-securitycontextconstraints
[INFO] oc: Created DeploymentConfig: target/jkube/applyJson/myproject/deploymentconfig-fabric8-securitycontextconstraints.json
[INFO] oc: Creating Route myproject:fabric8-securitycontextconstraints host: null
[INFO] oc: HINT: Use the command `oc get pods -w` to watch your pods start up
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.250 s
[INFO] Finished at: 2020-12-15T16:43:56+05:30
[INFO] ------------------------------------------------------------------------
```

After this I check Pod logs if deployment was fine:
```
fabric8-securitycontextconstraints : $ mvn oc:log
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------< org.example:fabric8-securitycontextconstraints >-----------
[INFO] Building fabric8-securitycontextconstraints 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- openshift-maven-plugin:1.0.2:log (default-cli) @ fabric8-securitycontextconstraints ---
[INFO] oc: Using OpenShift at https://192.168.42.223:8443/ in namespace myproject with manifest /home/rohaan/work/repos/fabric8-securitycontextconstraints/target/classes/META-INF/jkube/openshift.yml 
[INFO] oc: OpenShift platform detected
[INFO] oc: Using project: myproject
[INFO] oc: Watching pods with selector LabelSelector(matchExpressions=[], matchLabels={app=fabric8-securitycontextconstraints, provider=jkube, group=org.example}, additionalProperties={}) waiting for a running pod...
[INFO] oc:  [NEW] fabric8-securitycontextconstraints-1-j8dmp status: Running 
[INFO] oc:  [NEW] Tailing log of pod: fabric8-securitycontextconstraints-1-j8dmp
[INFO] oc:  [NEW] Press Ctrl-C to stop tailing the log
[INFO] oc:  [NEW] 
[INFO] oc: Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
[INFO] oc: INFO exec  java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -javaagent:/usr/share/java/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=9779:/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/fabric8-securitycontextconstraints-1.0-SNAPSHOT-jar-with-dependencies.jar                                                                                                                                              
[INFO] oc: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[INFO] oc: SLF4J: Defaulting to no-operation (NOP) logger implementation
[INFO] oc: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] oc: WARNING: An illegal reflective access operation has occurred
[INFO] oc:  [NEW] fabric8-securitycontextconstraints-1-j8dmp status: Running 
[INFO] oc: WARNING: Illegal reflective access by org.jolokia.util.ClassUtil (file:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar) to constructor sun.security.x509.X500Name(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)                                                                                                                                                                                                   
[INFO] oc: WARNING: Please consider reporting this to the maintainers of org.jolokia.util.ClassUtil
[INFO] oc: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[INFO] oc: WARNING: All illegal access operations will be denied in a future release
[INFO] oc: Dec 15, 2020 11:14:00 AM io.fabric8.test.ApplySCC main
[INFO] oc: INFO: Loading SecurityContextConstraint from YAML manifest
[INFO] oc: I> No access restrictor found, access to any MBean is allowed
[INFO] oc: Jolokia: Agent started with URL https://172.17.0.8:8778/jolokia/
[INFO] oc: Dec 15, 2020 11:14:01 AM io.fabric8.test.ApplySCC main
[INFO] oc: INFO: Applying SecurityContextConstraint to OpenShift Cluster
```
I was able to see SecurityContextConstraint being applied : 
```
fabric8-securitycontextconstraints : $ oc get scc
NAME               PRIV      CAPS      SELINUX     RUNASUSER          FSGROUP     SUPGROUP    PRIORITY   READONLYROOTFS   VOLUMES
anyuid             false     []        MustRunAs   RunAsAny           RunAsAny    RunAsAny    10         false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]

...

scc-test           false     []        MustRunAs   MustRunAsRange     MustRunAs   RunAsAny    <none>     false            [none] 
```

What am I missing?

**Comment by rohanKanojia** [comment]
## Update

I tried reproducing this again with a dedicated `ServiceAccount` using my reproducer: https://github.com/r0haaaan/fabric8-securitycontextconstraints but I wasn't able to reproduce this issue. I created a simple `ServiceAccount` :
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
automountServiceAccountToken: false
```
I have configured my reproducer's [Eclispe JKube Configuration](https://github.com/r0haaaan/fabric8-securitycontextconstraints/blob/master/src/main/jkube/deployment.yml) to use this `ServiceAccount` while creating `DeploymentConfig` for this project. As admin user, I created `ClusterRole` and `ClusterRoleBinding` corresponding to this `ServiceAccount` like this:

clusterrole.yml
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scc-reader-writer
rules:
- apiGroups:
  - security.openshift.io
  resources: 
  - securitycontextconstraints
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch 
```

clusterrolebinding.yaml
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
  - kind: ServiceAccount
    name: build-robot
    namespace: myproject
roleRef:
  kind: ClusterRole
  name: scc-reader-writer
  apiGroup: rbac.authorization.k8s.io
```

While logged in as admin user, I created these resources:
```
fabric8-securitycontextconstraints : $ oc create -f serviceaccount.yml 
serviceaccount/build-robot created
fabric8-securitycontextconstraints : $ oc create -f clusterrole.yml 
clusterrole.rbac.authorization.k8s.io/scc-reader-writer created
fabric8-securitycontextconstraints : $ oc create -f clusterrolebinding.yml 
clusterrolebinding.rbac.authorization.k8s.io/read-secrets-global created
```

Then I logged out and logged in again as a non-privileged user:
```
kubernetes-client : $ oc login https://192.168.42.83:8443 --token=secret
Logged into "https://192.168.42.83:8443" as "developer" using the token provided.

You have one project on this server: "myproject"

Using project "myproject".
```

I deployed the application using Eclipse JKube:
```
mvn oc:deploy -POpenshift
```
When I check application logs, I can see that scc gets created:
```
fabric8-securitycontextconstraints : $ oc logs pod/fabric8-securitycontextconstraints-1-27fcx
'Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -javaagent:/usr/share/java/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=9779:/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/fabric8-securitycontextconstraints-1.0-SNAPSHOT-jar-with-dependencies.jar  
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jolokia.util.ClassUtil (file:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar) to constructor sun.security.x509.X500Name(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jolokia.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
[main] DEBUG io.fabric8.kubernetes.client.Config - Did not find Kubernetes config at: [/home/jboss/.kube/config]. Ignoring.
[main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from service account...
[main] DEBUG io.fabric8.kubernetes.client.Config - Found service account host and port: 172.30.0.1:443
[main] DEBUG io.fabric8.kubernetes.client.Config - Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
[main] DEBUG io.fabric8.kubernetes.client.Config - Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
[main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client namespace from Kubernetes service account namespace path...
[main] DEBUG io.fabric8.kubernetes.client.Config - Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
[main] INFO io.fabric8.test.ApplySCC - Listing current SecurityContextConstraint:
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL https://172.17.0.10:8778/jolokia/
[main] INFO io.fabric8.test.ApplySCC - anyuid
[main] INFO io.fabric8.test.ApplySCC - hostaccess
[main] INFO io.fabric8.test.ApplySCC - hostmount-anyuid
[main] INFO io.fabric8.test.ApplySCC - hostnetwork
[main] INFO io.fabric8.test.ApplySCC - nonroot
[main] INFO io.fabric8.test.ApplySCC - privileged
[main] INFO io.fabric8.test.ApplySCC - restricted
[main] INFO io.fabric8.test.ApplySCC - scc-test2
[main] INFO io.fabric8.test.ApplySCC - --------------------------------------
[main] INFO io.fabric8.test.ApplySCC - Loading SecurityContextConstraint from YAML manifest
[main] INFO io.fabric8.test.ApplySCC - Applying SecurityContextConstraint to OpenShift Cluster
[main] INFO io.fabric8.test.ApplySCC - Done!
```
