### ISSUE TITLE
LoadMultipleDocumentsFromFileExample Can't be executed.

### ISSUE THREAD

**Issue by wikicoo** [fabric8io/kubernetes-client#1603]
Exception in thread "main" java.lang.ClassCastException: io.fabric8.kubernetes.api.model.IntOrStringBuilder cannot be cast to io.fabric8.kubernetes.api.model.ObjectMetaBuilder
	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:118)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:115)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:115)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:115)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:109)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:11)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:293)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:281)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:64)
	at io.fabric8.kubernetes.examples.LoadMultipleDocumentsFromFileExample.main(LoadMultipleDocumentsFromFileExample.java:47)

**Comment by rohanKanojia** [comment]
@kunal-kushwaha : Could you please look into this if you have time?

**Comment by kunal-kushwaha** [comment]
> @kunal-kushwaha : Could you please look into this if you have time?

Sure, will do

**Comment by rohanKanojia** [comment]
much appreciated, Thanks

**Comment by kunal-kushwaha** [comment]
@rohanKanojia: 
https://github.com/fabric8io/kubernetes-client/blob/b3ce511c53ab42151a4d249e61d7bb84f38b1466/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/LoadMultipleDocumentsFromFileExample.java#L47
What is the use for accept()? It's only being used in 2 files (this one and LoadExample) and the multiple documents are loading with no issues without it. 
Also String master is unused.

**Comment by rohanKanojia** [comment]
I think it's for modifying list items. that function would be applied to all elements.

**Comment by manusa** [comment]
Caused by #1369
