### ISSUE TITLE
 java.io.IOException: PEM is invalid: no begin marker

### ISSUE THREAD

**Issue by eskuai** [fabric8io/kubernetes-client#1627]
Hello, 
I am trying to read secret using the api.
I am using  k8s 1.14 and kubernetes-client 4.3.0,java 8-181

the code is simple,
It is works ok using windows environment, not problem,  connect

``
10:56:24.877 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
10:56:24.892 [main] DEBUG io.fabric8.kubernetes.client.Config - Did not find Kubernetes config at: [C:\Users\jsanz\.kube\config]. Ignoring.
10:56:24.892 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from service account...
10:56:24.892 [main] DEBUG io.fabric8.kubernetes.client.Config - Did not find service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
10:56:24.893 [main] WARN io.fabric8.kubernetes.client.Config - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
10:56:24.893 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client namespace from Kubernetes service account namespace path...
10:56:24.893 [main] DEBUG io.fabric8.kubernetes.client.Config - Did not find service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace]. Ignoring.
10:56:24.916 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
10:56:24.917 [main] DEBUG io.fabric8.kubernetes.client.Config - Did not find Kubernetes config at: [C:\Users\jsanz\.kube\config]. Ignoring.
10:56:24.917 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from service account...
10:56:24.917 [main] DEBUG io.fabric8.kubernetes.client.Config - Did not find service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
10:56:24.917 [main] WARN io.fabric8.kubernetes.client.Config - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
10:56:24.917 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client namespace from Kubernetes service account namespace path...
10:56:24.917 [main] DEBUG io.fabric8.kubernetes.client.Config - Did not find service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace]. Ignoring.
10:56:26.016 [main] INFO paq.Application2 - Received pods: io.fabric8.kubernetes.client.dsl.internal.SecretOperationsImpl@f679a195
10:56:26.831 [main] INFO paq.Application2 - {password=ZXhhbXBsZS1wYXNzd29yZA==, username=ZXhhbXBsZS11c2Vy}
10:56:26.919 [main] INFO paq.Application2 - ZXhhbXBsZS11c2Vy
``

Source code is :

```

String master = "https://localhost:6443/";
String caCertData ="-----BEGIN CERTIFICATE-----\r\n" + 
		"MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl\r\n" + 
		"cm5ldGVzMB4XDTE5MDQwOTE1MTYxMVoXDTI5MDQwNjE1MTYxMVowFTETMBEGA1UE\r\n" + 
		"AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALi1\r\n" + 
		"/UGUiDeR9Mtd2DMOcyk6IMeDRi7j86B8Q/UndrSqmwJlrs9InFd8QVcUuS/yBNPz\r\n" + 
		"mnA/FdHtayP9Z974b1WFNzi0ZOOHoBtyLVwAOmreE6W6keTr4z4OCaq+PyxNTwHt\r\n" + 
		"/fIi99480R9MJ18OibPxtSni+4I0zc6Wamkvk6/dEhkv/TqS9obmTf4bek1QwQSA\r\n" + 
		"muvjR2cX8dN64tMUMrD989ycqvazhfVkg2ki4soCwf/SHwk8PAvl6NPCxj0w1XWF\r\n" + 
		"VeHU2u4WMIqk6kUBgypKvx8emYK713Z5o8JQfGnzvEafVphmYCeTwSqwQLkszzSa\r\n" + 
		"7LWs+/K63fO4MmptRUMCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB\r\n" + 
		"/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAC4efvMofKU0SJo4xZVCH2PxFJKq\r\n" + 
		"5dtWtUBvIL7inegz8wW81uvuTPvbHS8Jnfk3UbasZzqgvFohTPzza6KZyM0cGcMe\r\n" + 
		"UyiEyBdXzx+0SFX9OVQrM4TB53E5IGiHLVg+S9oNHwG9hyGNszVCVsiLwAAxWMwU\r\n" + 
		"MBYfzDd8RAvwlE62MuKshwYNwrhcNTJyCJyLnrjiZ4h/c1W0XYrgdxX8XXQYPtpZ\r\n" + 
		"LTEmByD1RaFi3nup/4MqZ0P87z1DWux769bD5h7lWKQ6t//H6LXdF062DzZiQJ73\r\n" + 
		"sQosqUoD+w6+IVARpPA/qb5Dvaaepkw+oQMLeMt3QcWY2tK/6HJoMaBp1i0=\r\n" + 
		"-----END CERTIFICATE-----";

Config config = new ConfigBuilder().withMasterUrl(master).withCaCertData(caCertData).withNamespace("default")
.withNamespace("default").withClientKeyPassphrase(clientKeyData).build();
config.setDisableHostnameVerification(true);
try (final KubernetesClient client = new AutoAdaptableKubernetesClient(config)) {
	log("Received pods", client.secrets().withName("demo"));
	Resource<Secret, DoneableSecret> s= client.secrets().withName("demo");
	logger.info(""+s.get().getData());
	logger.info(""+s.get().getData().get("username"));
```
But the same code, fat jar, running into linux environment, launch :

```
 java.io.IOException: PEM is invalid: no begin marker
10:50:38.992 [main] ERROR paq.Application - An error has occurred.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:169)
        at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:56)
        at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:92)
        at io.fabric8.kubernetes.client.AutoAdaptableKubernetesClient.<init>(AutoAdaptableKubernetesClient.java:85)
        at paq.Application.main(Application.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.IOException: PEM is invalid: no begin marker
        at io.fabric8.kubernetes.client.internal.CertUtils.decodePem(CertUtils.java:266)
        at io.fabric8.kubernetes.client.internal.CertUtils.handleOtherKeys(CertUtils.java:165)
        at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:134)
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:112)
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:242)
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:128)
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:122)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:73)
        ... 12 common frames omitted
live [root@k8s-gestion http]$
```

how can i do to manage the pem ?

**Comment by Alameyo** [comment]
Instead of \r\n try to use System.getProperty("line.separator") so newline character would depend on OS. 

Also I am not sure if you really need there newlines at all, maybe you could get rid off them.
