### ISSUE TITLE
Thread safety issue in KubernetesDeserializer leading to spurious deserialize exceptions from watches

### ISSUE THREAD

**Issue by k-wall** [fabric8io/kubernetes-client#1634]
Our application makes heavy use of watches of CRDs.  I am investigating a sporadic issue where the processing of watch events is failing whilst deserialising watch events.  It is clear from the exception that KubernetesDeserializer believes that the resource type has not been registered, however, we know this is the case.  We make our calls to registerCustomKind() from a static initialiser block within the application's main class.  What's more, the resource type that is complained about varies.

We are using kubernetes-client 4.1.3.

```
2019-07-15T01:19:23.682Z ERROR [WatchConnectionManager] Could not deserialize watch event: {"type":"ADDED","object":{"apiVersion":"admin.enmasse.io/v1beta1","kind":"StandardInfraConfig","metadata":{"creationTimestamp":"2019-07-15T01:19:23Z","generation":1,"name":"test-infra-1-standard","namespace":"enmasse-infra","resourceVersion":"55748","selfLink":"/apis/admin.enmasse.io/v1beta1/namespaces/enmasse-infra/standardinfraconfigs/test-infra-1-standard","uid":"946cdebb-a69e-11e9-a16a-fa163e2d2fe3"},"spec":{"admin":{"podTemplate":{"metadata":{"annotations":{},"labels":{"mycomponent":"admin"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-label-key","operator":"In","values":["myadminnode"]}]},"weight":1}]}},"containers":[],"nodeSelector":{},"tolerations":[{"effect":"NoSchedule","key":"admin","operator":"Exists"}]}},"resources":{"memory":"512Mi"}},"broker":{"addressFullPolicy":"FAIL","podTemplate":{"metadata":{"annotations":{},"labels":{"mycomponent":"broker"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-label-key","operator":"In","values":["mybrokernode"]}]},"weight":1}]}},"containers":[],"nodeSelector":{},"tolerations":[{"effect":"NoSchedule","key":"broker","operator":"Exists"}]}},"resources":{"memory":"512Mi","storage":"1Gi"}},"router":{"podTemplate":{"metadata":{"annotations":{},"labels":{"mycomponent":"router"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-label-key","operator":"In","values":["myrouternode"]}]},"weight":1}]}},"containers":[],"nodeSelector":{},"tolerations":[{"effect":"NoSchedule","key":"router","operator":"Exists"}]}},"resources":{"memory":"256Mi"}},"version":"0.29-SNAPSHOT"}}}
com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:admin.enmasse.io/v1beta1#StandardInfraConfig
 at [Source: (String)"{"type":"ADDED","object":{"apiVersion":"admin.enmasse.io/v1beta1","kind":"StandardInfraConfig","metadata":{"creationTimestamp":"2019-07-15T01:19:23Z","generation":1,"name":"test-infra-1-standard","namespace":"enmasse-infra","resourceVersion":"55748","selfLink":"/apis/admin.enmasse.io/v1beta1/namespaces/enmasse-infra/standardinfraconfigs/test-infra-1-standard","uid":"946cdebb-a69e-11e9-a16a-fa163e2d2fe3"},"spec":{"admin":{"podTemplate":{"metadata":{"annotations":{},"labels":{"mycomponent":"admin""[truncated 1298 chars]; line: 1, column: 1796] (through reference chain: io.fabric8.kubernetes.api.model.WatchEvent["object"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:271)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1718)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:78)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager.readWatchEvent(WatchHTTPManager.java:293)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:224)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by k-wall** [comment]
I believe the issue is thread-safety.  KubernetesDeserializer's map needs to thread-safe (wrapped in a Collections.synchronizedMap(), or a ConcurrentHashMap().

For the watch use-case, KubernetesDeserializer.registerCustomKind is potentially invoked concurrently, from pooled threads like so.  This means that the map is being mutated by multi-threads and without any form of memory barrier.  This is leading to the spurious key misses.

019-07-16T14:06:58.506Z WARN  [KubernetesDeserializer] KWDEBUG registerCustomKind : null BrokeredInfraConfig Thread-5 map size now 40
java.lang.Exception: null
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.registerCustomKind(KubernetesDeserializer.java:130)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.registerCustomKind(KubernetesDeserializer.java:120)
        at io.fabric8.kubernetes.client.dsl.internal.CustomResourceOperationsImpl.<init>(CustomResourceOperationsImpl.java:56)
        at io.fabric8.kubernetes.client.dsl.internal.CustomResourceOperationsImpl.withResourceVersion(CustomResourceOperationsImpl.java:127)
        at io.fabric8.kubernetes.client.dsl.internal.CustomResourceOperationsImpl.withResourceVersion(CustomResourceOperationsImpl.java:42)
        at io.enmasse.k8s.api.KubeCrdApi.lambda$watch$0(KubeCrdApi.java:58)
        at io.fabric8.kubernetes.client.WithRequestCallable.call(WithRequestCallable.java:35)
        at io.enmasse.k8s.api.KubeCrdApi.watch(KubeCrdApi.java:57)
        at io.enmasse.k8s.api.cache.Reflector.resync(Reflector.java:92)
        at io.enmasse.k8s.api.cache.Reflector.run(Reflector.java:53)
        at io.enmasse.k8s.api.cache.Controller.lambda$start$0(Controller.java:22)
