### ISSUE TITLE
Intermediately seeing java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by GaneshSPatil** [fabric8io/kubernetes-client#1672]
We're using fabric8io/kubernetes-client library to manage kubernetes Pods. In our setup, we nearly have close to 500 pods coming up and going down per second.
Lately, we've started seeing `io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.` while creating a new pod.

Here is the full stack trace:
```
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
	at cd.go.contrib.elasticagent.KubernetesAgentInstances.refreshAll(KubernetesAgentInstances.java:150)
	at cd.go.contrib.elasticagent.KubernetesAgentInstances.create(KubernetesAgentInstances.java:63)
	at cd.go.contrib.elasticagent.KubernetesAgentInstances.create(KubernetesAgentInstances.java:38)
	at cd.go.contrib.elasticagent.executors.CreateAgentRequestExecutor.execute(CreateAgentRequestExecutor.java:44)
	at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:82)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:152)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:149)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
	at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.createAgent(ElasticAgentExtensionV5.java:142)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:60)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:43)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:32)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:22)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:86)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:66)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:601)
	at okhttp3.internal.http2.Http2Stream$FramingSource.waitUntilReadable(Http2Stream.java:374)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:337)
	at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.read(Http2Codec.java:210)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:227)
	... 24 common frames omitted
```

**Comment by garo** [comment]
Have you set any timeouts to the kubernets client? There are kubernetes.request.timeout and kubernetes.connection.timeout -properties which can also be set via environment variables KUBERNETES_REQUEST_TIMEOUT and KUBERNETES_CONNECTION_TIMEOUT.

Just make sure you set these values in **milliseconds** and not seconds!

**Comment by GaneshSPatil** [comment]
Hello @garo,

Thanks for the information.

Do we suspect it to be the kubernetes endpoint being slow in the replies?

Looking at [this](https://github.com/fabric8io/kubernetes-client/pull/97/files) piece of code, it looks like the default value for `KUBERNETES_REQUEST_TIMEOUT` System Property is set to 10 secs (10 * 1000), which is a high enough value.

**Comment by garo** [comment]
I'm not a fabric8io developer and I'm even not very familiar with this library. I however was just debugging why my Spark driver kubernetes api connections timeouted and I stumbled these timeout settings (and ended up setting them as seconds instead of milliseconds). So that's why I found your ticket and offered some help.

As you are debugging this you can look on the Kubernetes API server Prometheus metrics. Here are some Prometheus queries which I found useful while debugging this:
 - **sum(irate(apiserver_request_count[1m]))** how many requests per second is the kube api server getting?
 - **sum(rate(apiserver_request_count{code="500",verb=~"LIST|POST"}[1m])) by (verb)** Number of 500 errors from the server side for listing pods and creating new pods. If your client disconnects before the kubernetes api server had time to finish the operation it can be seen as a 500 errors on the server side. (not sure why)

There's also bunch of etcd metrics for checking if your etcd is behaving slowly. I'm personally running in AWS EKS and doing around 250 req/s on peak on a 100 worker node cluster. I had to slightly increase the timeouts from the default 10 seconds to remove some of the long tail duration requests.

**Comment by GaneshSPatil** [comment]
@garo -- Many thanks for the above information. I definitely will check out these metrics.

**Comment by S-Dragon0302** [comment]
@garo I also met for this problem

**Comment by S-Dragon0302** [comment]
@garo I also met for this problem
