### ISSUE TITLE
unstable watcher

### ISSUE THREAD

**Issue by davidkarlsen** [fabric8io/kubernetes-client#1685]
I always get disconnected [2] when attempting to create a watcher [1].

[1]
```
package com.evry.fs.arch.icpautomate.kubernetes.watcher

import com.evry.fs.arch.icpautomate.infra.spring.ValidatedService
import com.github.seratch.jslack.shortcut.Shortcut
import com.github.seratch.jslack.shortcut.model.ChannelName
import io.fabric8.kubernetes.api.model.Namespace
import io.fabric8.kubernetes.client.KubernetesClient
import io.fabric8.kubernetes.client.KubernetesClientException
import io.fabric8.kubernetes.client.Watch
import io.fabric8.kubernetes.client.Watcher
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Value
import javax.annotation.PostConstruct
import javax.annotation.PreDestroy

@ValidatedService
class KubernetesWatcherServiceImpl(private val kubernetesClient: KubernetesClient,
                                   private val shortcut: Shortcut,
                                   @param:Value("\${watcher.channel}") private val channel: String) {
    private val logger = LoggerFactory.getLogger(javaClass)
    private lateinit var watch: Watch

    @PostConstruct
    protected fun init() {
        this.watch = this.kubernetesClient.events().inAnyNamespace().watch(watcher())
    }

    @PreDestroy
    protected fun destroy() {
        this.watch.close()
    }

    private fun watcher(): Watcher<Namespace> {
        return object : Watcher<Namespace> {
            override fun eventReceived(action: Watcher.Action, namespace: Namespace) {
                logger.info("Received action {} on {}", action, namespace)
                when (action) {
                    Watcher.Action.DELETED -> "Namespace ${namespace.metadata.name} deleted"
                    Watcher.Action.ADDED -> "Namespace ${namespace.metadata.name} created"
                    Watcher.Action.ERROR, Watcher.Action.MODIFIED -> null
                }?.apply { shortcut.post(ChannelName.of(channel), this) }
            }

            override fun onClose(cause: KubernetesClientException) {
                logger.warn("Error in watcher", cause)
            }
        }
    }

}


```

[2]
```
;2mweb   ESC[0m | java.net.SocketTimeoutException: sent ping but didn't receive pong within 1000ms (after 0 successful ping/pongs)
ESC[1;38;5;2mweb   ESC[0m |     at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:545) ~[okhttp-3.14.2.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:529) ~[okhttp-3.14.2.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
ESC[1;38;5;2mweb   ESC[0m |     at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
ESC[1;38;5;2mweb   ESC[0m |     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
ESC[1;38;5;2mweb   ESC[0m |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
ESC[1;38;5;2mweb   ESC[0m |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
ESC[1;38;5;2mweb   ESC[0m |     at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
ESC[1;38;5;2mweb   ESC[0m | 
ESC[1;38;5;2mweb   ESC[0m | ESC[2m2019-08-05 18:53:35.087ESC[0;39m ESC[33m WARNESC[0;39m ESC[35m24ESC[0;39m ESC[2m---ESC[0;39m ESC[2m[/10.201.0.1/...]ESC[0;39m ESC[3
6me.f.a.i.k.w.KubernetesWatcherServiceImplESC[0;39m ESC[2m:ESC[0;39m Error in watcher
ESC[1;38;5;2mweb   ESC[0m | 
ESC[1;38;5;2mweb   ESC[0m | io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 60 (13613243)
ESC[1;38;5;2mweb   ESC[0m |     at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:254) ~[kubernetes-client-
4.1.0.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322) ~[okhttp-3.14.2.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) ~[okhttp-3.14.2.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) ~[okhttp-3.14.2.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) ~[okhttp-3.14.2.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209) ~[okhttp-3.14.2.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[okhttp-3.14.2.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.14.2.jar:na]
ESC[1;38;5;2mweb   ESC[0m |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
ESC[1;38;5;2mweb   ESC[0m |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
ESC[1;38;5;2mweb   ESC[0m |     at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
```

**Comment by yanjia92** [comment]
encoutered similar issue. Can anyone take a look at this?

**Comment by shawkins** [comment]
@yanjia92 this issue is out of date.  If you have are experiencing something similar it would be best to open a new issue an link to this one.
