### ISSUE TITLE
Quarkus Fabric8 Extension 4.3.0 IntOrString$Serializer has no default (no arg) constructor

### ISSUE THREAD

**Issue by bframke** [fabric8io/kubernetes-client#1697]
I try to do a rolling update for a deployment. I always get this as a error response: 
`io.fabric8.kubernetes.client.KubernetesClientException: Could not calculate MD5 of RC
	at io.fabric8.kubernetes.client.dsl.internal.RollingUpdater.rollUpdate(RollingUpdater.java:169)
	at io.fabric8.kubernetes.client.dsl.internal.RollableScalableResourceOperation.replace(RollableScalableResourceOperation.java:161)
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.replace(DeploymentOperationsImpl.java:101)
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.replace(DeploymentOperationsImpl.java:45)
	at com.telekom.operator.deployment.DeploymentInstaller.handleEvent(DeploymentInstaller.java:68)
	at com.telekom.operator.cache.ResourceCache$PortBindingResourceWatcher.lambda$eventReceived$0(ResourceCache.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Class io.fabric8.kubernetes.api.model.IntOrString$Serializer has no default (no arg) constructor (through reference chain: io.fabric8.kubernetes.api.model.apps.Deployment["spec"]->io.fabric8.kubernetes.api.model.apps.DeploymentSpec["strategy"]->io.fabric8.kubernetes.api.model.apps.DeploymentStrategy["rollingUpdate"]->io.fabric8.kubernetes.api.model.apps.RollingUpdateDeployment["maxSurge"])
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1223)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1341)
	at com.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:668)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:64)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:897)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:705)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3905)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3219)
	at io.fabric8.kubernetes.client.internal.SerializationUtils.dumpWithoutRuntimeStateAsYaml(SerializationUtils.java:66)
	at io.fabric8.kubernetes.client.dsl.internal.RollingUpdater.md5sum(RollingUpdater.java:251)
	at io.fabric8.kubernetes.client.dsl.internal.RollingUpdater.rollUpdate(RollingUpdater.java:95)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Class io.fabric8.kubernetes.api.model.IntOrString$Serializer has no default (no arg) constructor
	at com.fasterxml.jackson.databind.util.ClassUtil.createInstance(ClassUtil.java:554)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializerInstance(DefaultSerializerProvider.java:135)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerFromAnnotation(BasicSerializerFactory.java:489)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:136)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1388)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1336)
	... 32 more`

What I try to do in Code:
`_client.apps().deployments().withName(filteredDeployment.getMetadata().getName()).rolling().patch(filteredDeployment);`

So is this now a bug on the serializer inner class from IntOrString or does this class get optimized away with quarkus and graalvm? I also tried to add 
`io.fabric8.kubernetes.api.model.IntOrString$Serializer
io.fabric8.kubernetes.api.model.IntOrString`
to the reflect-confing.json, but then the build always fails.

**Comment by Silvakilla** [comment]
Small update on this issue: my pc had problems with a quarkus and graalvm build, now it build it with the reflect-config.json and it works. 

So maybe the Innerclass or the Class itself needs register for reflection for the quarkus extension.

**Comment by Silvakilla** [comment]
Small update on this issue: my pc had problems with a quarkus and graalvm build, now it build it with the reflect-config.json and it works. 

So maybe the Innerclass or the Class itself needs register for reflection for the quarkus extension.

**Comment by jorsol** [comment]
Quarkus made a workaround for this, so it should not longer be necessary to fix this unless there is a major work to support GraalVM native-images directly in the kubernetes-client library.

**Comment by rohanKanojia** [comment]
@jorsol : oh, cool. Thanks for the update. Let's close this then.
