### ISSUE TITLE
Failure in determining private key algorithm type, defaulting to RSA

### ISSUE THREAD

**Issue by FreddyShen** [fabric8io/kubernetes-client#1726]
`13:50:31.841 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
13:50:31.858 [main] DEBUG io.fabric8.kubernetes.client.Config - Found for Kubernetes config at: [/Users/ws/.kube/config].
13:50:32.202 [main] DEBUG io.fabric8.kubernetes.client.Config - Failure in determining private key algorithm type, defaulting to RSA 
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.openshift.client.OpenshiftAdapterSupport.isOpenShiftAPIGroups(OpenshiftAdapterSupport.java:87)
	at io.fabric8.openshift.client.OpenshiftAdapterSupport.isOpenShift(OpenshiftAdapterSupport.java:61)
	at io.fabric8.openshift.client.OpenshiftAdapterSupport.isAdaptable(OpenshiftAdapterSupport.java:49)
	at io.fabric8.openshift.client.OpenShiftExtensionAdapter.adapt(OpenShiftExtensionAdapter.java:45)
	at io.fabric8.openshift.client.OpenShiftExtensionAdapter.adapt(OpenShiftExtensionAdapter.java:33)
	at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:133)
	at cci.ocpmgp.demo.controller.LoginExample.main(LoginExample.java:24)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1779)
	at sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:124)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1093)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1497)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
	at okhttp3.internal.connection.RealConnecti`

**Comment by regan-xu** [comment]
![image](https://user-images.githubusercontent.com/36719035/63927164-c1a53d80-ca7f-11e9-92db-16a509314439.png)
![image](https://user-images.githubusercontent.com/36719035/63927242-e1d4fc80-ca7f-11e9-91c0-a6490b5a75b2.png)

**Comment by FreddyShen** [comment]
oc login --token=*********** --server=https://*******:6443
After login with oc, config file will be generated, and then directly refer to it.
