### ISSUE TITLE
More lenient handling of proxy

### ISSUE THREAD

**Issue by davidkarlsen** [fabric8io/kubernetes-client#1733]
If the proxy var points to hostname/port, but not including protocol, it fails with:
```
Caused: io.fabric8.kubernetes.client.KubernetesClientException: Invalid proxy server configuration
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:160)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:55)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:47)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:83)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.parseFromYaml(PodTemplateUtils.java:491)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.validateYamlContainerNames(PodTemplateUtils.java:511)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.start(PodTemplateStepExecution.java:112)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:270)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:178)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.KubernetesDeclarativeAgentScript.run(jar:file
```

this could be more lenient and add http if defined w/o protocol.
Also it is debatable if the error should just be logged at error and continue w/o proxy.

**Comment by jorgesartori** [comment]
What version do you use?
At latest version this exception is in line 159 (in your trace is in 160), and does exactly you asked, puts HTTP always:

```
URL proxyUrl = getProxyUrl(config);
    if (proxyUrl != null) {
        httpClientBuilder.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyUrl.getHost(), proxyUrl.getPort())));
```

**Comment by davidkarlsen** [comment]
4.1.1 it seems: https://github.com/jenkinsci/kubernetes-plugin/blob/kubernetes-1.14.3/pom.xml#L56 - I'll see if we can get the plugin (and thus kubernetes-client lib) upgraded - thanks!
