### ISSUE TITLE
 call method task 3~4 seconds

### ISSUE THREAD

**Issue by zhangzerui20** [fabric8io/kubernetes-client#1812]
client version is 3.2.0.
         

            long be = System.currentTimeMillis();
            Config config = new ConfigBuilder().withMasterUrl("https://100.98.109.15:11229").
                    withTrustCerts(true).withUsername("admin").withPassword("Hnvlam9UaGesAlFEkXfkkDW6HHKH4xUt").build();
            
            client.extensions().deployments().inNamespace("default").
                    withName("alon-docker-provider").edit().editSpec().withReplicas(current).endSpec().done();

            long end = System.currentTimeMillis();

            System.out.println("cost " + (end - be) + "ms");

Running the above program will take 3~4 seconds.

When the thread hangs, the jstack shows:
`"http-nio-16000-exec-4" #33 daemon prio=5 os_prio=0 tid=0x00007f2388522800 nid=0x7211 runnable [0x00007f22f63ef000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Throwable.fillInStackTrace(Native Method)
        at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
        - locked <0x0000000088d619b8> (a java.io.FileNotFoundException)
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.io.IOException.<init>(IOException.java:58)
        at java.io.FileNotFoundException.<init>(FileNotFoundException.java:64)
        at org.springframework.boot.loader.jar.JarURLConnection.throwFileNotFound(JarURLConnection.java:186)
        at org.springframework.boot.loader.jar.JarURLConnection.connect(JarURLConnection.java:105)
        at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:170)
        at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:680)
        at sun.misc.URLClassPath$1.next(URLClassPath.java:240)
        at sun.misc.URLClassPath$1.hasMoreElements(URLClassPath.java:250)
        at java.net.URLClassLoader$3$1.run(URLClassLoader.java:601)
        at java.net.URLClassLoader$3$1.run(URLClassLoader.java:599)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader$3.next(URLClassLoader.java:598)
        at java.net.URLClassLoader$3.hasMoreElements(URLClassLoader.java:623)
        at sun.misc.CompoundEnumeration.next(CompoundEnumeration.java:45)
        at sun.misc.CompoundEnumeration.hasMoreElements(CompoundEnumeration.java:54)
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:354)
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
        at org.hibernate.validator.internal.util.privilegedactions.GetConstraintValidatorList.loadConstraintValidators(GetConstraintValidatorList.java:52)
        at org.hibernate.validator.internal.util.privilegedactions.GetConstraintValidatorList.run(GetConstraintValidatorList.java:42)
        at org.hibernate.validator.internal.util.privilegedactions.GetConstraintValidatorList.run(GetConstraintValidatorList.java:21)
        at org.hibernate.validator.internal.engine.ServiceLoaderBasedConstraintMappingContributor.run(ServiceLoaderBasedConstraintMappingContributor.java:96)
        at org.hibernate.validator.internal.engine.ServiceLoaderBasedConstraintMappingContributor.createConstraintMappings(ServiceLoaderBasedConstraintMappingContributor.java:49)
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.getConstraintMappings(ValidatorFactoryImpl.java:264)
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:165)
        at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:331)
        at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:110)
        at io.fabric8.kubernetes.api.builder.ValidationUtils.validate(ValidationUtils.java:18)
        at io.fabric8.kubernetes.api.model.VolumeBuilder.build(VolumeBuilder.java:97)
        at io.fabric8.kubernetes.api.model.VolumeBuilder.build(VolumeBuilder.java:7)
        at io.fabric8.kubernetes.api.builder.BaseFluent.build(BaseFluent.java:20)
        at io.fabric8.kubernetes.api.model.PodSpecFluentImpl.getVolumes(PodSpecFluentImpl.java:923)
        at io.fabric8.kubernetes.api.model.PodSpecBuilder.build(PodSpecBuilder.java:86)
        at io.fabric8.kubernetes.api.model.PodTemplateSpecFluentImpl.getSpec(PodTemplateSpecFluentImpl.java:69)
        at io.fabric8.kubernetes.api.model.PodTemplateSpecBuilder.build(PodTemplateSpecBuilder.java:44)
        at io.fabric8.kubernetes.api.model.extensions.DeploymentSpecFluentImpl.getTemplate(DeploymentSpecFluentImpl.java:237)
        at io.fabric8.kubernetes.api.model.extensions.DeploymentSpecBuilder.build(DeploymentSpecBuilder.java:58)
        at io.fabric8.kubernetes.api.model.extensions.DeploymentFluentImpl.getSpec(DeploymentFluentImpl.java:105)
        at io.fabric8.kubernetes.api.model.extensions.DeploymentBuilder.build(DeploymentBuilder.java:50)
        at io.fabric8.kubernetes.api.model.extensions.DoneableDeployment.done(DoneableDeployment.java:27)`

**Comment by zhangzerui20** [comment]
At the same time, the CPU occupancy rate has reached 100.

**Comment by rohanKanojia** [comment]
@zhangzerui20 : 3.2.0 is obsolete, please migrate to 4.x versions.
