### ISSUE TITLE
V1Binding API equivalent?

### ISSUE THREAD

**Issue by lalithsuresh** [fabric8io/kubernetes-client#1816]
Using the kubernetes-java client (https://github.com/kubernetes-client/java/), I can implement my own scheduling logic to assign pods to nodes by doing something like this:

```java
    private void bindOne(final String namespace, final String podName, final String nodeName, final CoreV1Api v1Api) throws ApiException {
        final V1Binding body = new V1Binding();
        final V1ObjectReference target = new V1ObjectReference();
        final V1ObjectMeta meta = new V1ObjectMeta();
        target.setKind("Node");
        target.setApiVersion("v1");
        target.setName(nodeName);
        meta.setName(podName);
        body.setTarget(target);
        body.setMetadata(meta);
        v1Api.createNamespacedBinding(namespace, body, null, null, null);
    }
```
How can I do the same thing using the fabric8io client? I'd love to avoid using another client in my system only to support the above code snippet.

Thanks!

**Comment by rohanKanojia** [comment]
Umm, `Binding` should be equivalent resource to `V1Binding`, but I'm not sure about the dsl equivalent. Could you please elaborate your use case? What endpioint does `createnamespacedBinding` trigger? We have rolebinding support, but not sure about namespaced binding. 

Do you have `kubectl` equivalent of this code snippet? that also might help.

**Comment by lalithsuresh** [comment]
I'm still new to the Kubernetes APIs, so apologies if I'm slow here. My use case is to mimic in Java what the Kubernetes default scheduler does internally in this specific line: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L559

**Comment by lalithsuresh** [comment]
From what I can tell, createNamespacedBinding() creates a POST to "/api/v1/namespaces/{namespace}/bindings/", if that's what you meant by the endpoint being triggered?

**Comment by rohanKanojia** [comment]
Yeah, that's what I asked for. I would look into this. For now, could you please check if you are able to create binding like this?

```
client.resource(bindingObj).createOrReplace();
```

**Comment by lalithsuresh** [comment]
When trying that, it triggers the following exception because there is no handler that can process Binding objects:

```
Exception in thread "ForkJoinPool.commonPool-worker-19" Exception in thread "ForkJoinPool.commonPool-worker-5" io.fabric8.kubernetes.client.KubernetesClientException: No handler found for object:Binding(apiVersion=v1, kind=Binding, metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels=null, managedFields=[], name=nginx-deployment-544fc49f79-lrlvv, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), target=ObjectReference(apiVersion=v1, fieldPath=null, kind=Node, name=kube-node-2, namespace=null, resourceVersion=null, uid=null, additionalProperties={}), additionalProperties={})
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:117)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient$4.<init>(DefaultKubernetesClient.java:147)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.resource(DefaultKubernetesClient.java:147)
```

**Comment by rohanKanojia** [comment]
ah, I suspected this. We need to add handler for binding.

**Comment by rohanKanojia** [comment]
@lalithsuresh : I've raised a PR for this. Would appreciate if you could try it out and share feedback ;-)

**Comment by lalithsuresh** [comment]
Will do, thanks!
