### ISSUE TITLE
No resource type found for:meta.k8s.io/v1#CreateOptions

### ISSUE THREAD

**Issue by FrederickSchulz** [fabric8io/kubernetes-client#1898]
There is no model for "CreateOptions" causing an exception while parsing the AdmissionReview.
The AdmissionReview object can be found in the official [kubernetes docs](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#webhook-request-and-response). 
This seems to be a problem for all cases (UpdateOptions, DeleteOptions) of the request->options portion of an AdmissionReview.

```java
  @Test
  public void testJacksonParsing() throws IOException {
    InputStream jsonStream = getClass().getResourceAsStream("/admissionReview.json");
    Serialization.unmarshal(jsonStream, AdmissionReview.class);
  }
```
### admissionReview.json :
```json
{
  "kind": "AdmissionReview",
  "apiVersion": "admission.k8s.io/v1beta1",
  "request": {
    "uid": "66105089-3471-46ff-b4c8-293546c2aa6c",
    "kind": {
      "group": "",
      "version": "v1",
      "kind": "Pod"
    },
    "resource": {
      "group": "",
      "version": "v1",
      "resource": "pods"
    },
    "requestKind": {
      "group": "",
      "version": "v1",
      "kind": "Pod"
    },
    "requestResource": {
      "group": "",
      "version": "v1",
      "resource": "pods"
    },
    "namespace": "myNamespace",
    "operation": "CREATE",
    "userInfo": {
      "username": "III#John.Doe@something.com",
      "groups": [
        "Group2"
      ]
    },
    "object": {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata": {
        "name": "example-pod",
        "namespace": "myNamespace",
        "creationTimestamp": null,
        "annotations": {
        }
      },
      "spec": {
        "volumes": [
        ],
        "containers": [

        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "serviceAccountName": "default",
        "serviceAccount": "default",
        "securityContext": {},
        "schedulerName": "default-scheduler",
        "tolerations": [
          {
            "key": "node.kubernetes.io/not-ready",
            "operator": "Exists",
            "effect": "NoExecute",
            "tolerationSeconds": 600
          },
          {
            "key": "node.kubernetes.io/unreachable",
            "operator": "Exists",
            "effect": "NoExecute",
            "tolerationSeconds": 600
          }
        ],
        "priority": 0,
        "enableServiceLinks": true
      },
      "status": {}
    },
    "oldObject": null,
    "dryRun": false,
    "options": {
      "kind": "CreateOptions",
      "apiVersion": "meta.k8s.io/v1"
    }
  }
}
```

```
An error has occurred.
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:243)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:195)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:182)
	at EndpointTest.testJacksonParsing(EndpointTest.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:meta.k8s.io/v1#CreateOptions
 at [Source: (BufferedInputStream); line: 108, column: 5] (through reference chain: io.fabric8.kubernetes.api.model.admission.AdmissionReview["request"]->io.fabric8.kubernetes.api.model.admission.AdmissionRequest["options"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:271)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.fromObjectNode(KubernetesDeserializer.java:107)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:83)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)

```

**Comment by rohanKanojia** [comment]
@Trinnox : Do you know since when CreateOptions is available in Kubernetes? I'm planning to upgrade the model this week and can take this up along with current upgrade work.

**Comment by Trinnox** [comment]
@rohanKanojia sadly I do not know the exact version CreateOptions was made available.
I would assume it was available since Webhook alpha in kubernetes 1.7 or since Admission Webhooks got promoted to beta in [kubernetes 1.9](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#api-machinery)

**Comment by rohanKanojia** [comment]
no problem, Iet me fix this alongwith #1872

**Comment by FrederickSchulz** [comment]
Sadly the parsing is still not working even with version 4.7.1.
```
com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing property 'options' (expected type: [simple type, class io.fabric8.kubernetes.api.model.HasMetadata]; 
actual type: `io.fabric8.kubernetes.api.model.CreateOptions`), 
problem: argument type mismatch
```

In the `AdmissionRequest` model `options` is expecting type `HasMetadata` while the new models like `CreateOptions` inherit directly from `KubernetesResource` and not from `HasMetadata`

**Comment by jasmdk** [comment]
I have the same error running with 4.7.1 and even with 4.9-SNAPSHOT.

**Comment by rohanKanojia** [comment]
@jasmdk : Umm, I remember I added CreateOptions https://github.com/fabric8io/kubernetes-client/blob/b2f35d6034ded9e346067b386c92bf87dc77acb7/kubernetes-model/cmd/generate/generate.go#L110

let me have a look at it again.

**Comment by jasmdk** [comment]
@rohanKanojia CreateOptions is there, but it implements only the KubernetesResource interface.
The AdmissionRequest type has an options attribute which is currently assumed to be of type HasMetadata, but when I try to implement a ValidatingWebhook, i get an AdmissionRequest with a CreateOptions in the options value and deserialization fails due to CreateOptions not being of type HasMetadata.

**Comment by rohanKanojia** [comment]
@jasmdk : Thanks, I could reproduce your issue. I had to override the default generated class in order to get parsing to work. I've created a PR for this https://github.com/fabric8io/kubernetes-client/pull/2073 . I'm not an expert about Admission/Subject Reviews. Could you please check if it would work for your use case and provide feedback?

**Comment by jasmdk** [comment]
@rohanKanojia: thank you for your quick response. I have tested your fix and it works.
