### ISSUE TITLE
Can't apply custom resource definition

### ISSUE THREAD

**Issue by cedar715** [fabric8io/kubernetes-client#1910]
I'm trying to apply [Projectcontour's CRD](https://projectcontour.io/quickstart/contour.yaml) via fabric8 but hitting with below error. It works fine when manually via 'oc apply -f' 

```
Failed to apply : 
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root-domain-hp
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: workers.dev.net
  routes:
    - services:
        - name: httpbin
          port: 5511
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:projectcontour.io/v1#HTTPProxy
 at [Source: (BufferedInputStream); line: 12, column: 21]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:271)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1718)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:78)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1188)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:129)
	... 105 more
```

**Comment by rohanKanojia** [comment]
Hmm, that link seems like a collection of kubernetes resources (one of which is your custom resource). Could you please share that CRD spec with us and also the code which you used to create it?

**Comment by rohanKanojia** [comment]
@cedar715 : Were you able to resolve this? How are you trying to create CRD?  Recommended way would be:
https://github.com/fabric8io/kubernetes-client/blob/75c749385cb95785d14988719de08bcd5ff5f584/kubernetes-itests/src/test/java/io/fabric8/kubernetes/CustomResourceDefinitionIT.java#L75-L85

**Comment by cedar715** [comment]
@rohanKanojia: Its resolved now. I'm creating CRDs like this. 
```
CustomResourceDefinitionContext crdContext = new CustomResourceDefinitionContext.Builder()
                    .withGroup("projectcontour.io")
                    .withPlural("httpproxies")
                    .withScope("Namespaced")
                    .withVersion("v1")
                    .build()

Map<String, Object> createdCustResource = client
                    .customResource(crdContext)
                    .createOrReplace(namespace, crdDefn)
```
