### ISSUE TITLE
failed to configure clinet from kubeconfig

### ISSUE THREAD

**Issue by TrsNium** [fabric8io/kubernetes-client#1941]
library version info 
io.fabric8:kubernetes-client:4.6.2
com.fasterxml.jackson.core:jackson-databind:2.10.1

I tried to configure kubernetes clinet through `io.fabric8.kubernetes.client.Config.fromKubeconfig`, but failed as below error.

```
io.fabric8.kubernetes.client.Config: Trying to configure client from Kubernetes config...
io.fabric8.kubernetes.client.Config: Found for Kubernetes config at: [/root/.kube/config].
io.fabric8.kubernetes.client.Config: Failed to parse the kubeconfig.
java.lang.IllegalStateException: AnnotationIntrospector returned Class com.fasterxml.jackson.databind.util.Converter$None; expected Class<Converter>
│     at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._createConverter(BasicBeanDescription.java:742)
│     at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findDeserializationConverter(BasicBeanDescription.java:669)
│     at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:347)
│     at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
│     at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
│     at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
│     at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
│     at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4191)
│     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4010)
│     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
│     at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:45)
│     at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:502)
│     at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:488)
│     at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:224)
│     at io.fabric8.kubernetes.client.Config.<init>(Config.java:208)
│     at io.fabric8.kubernetes.client.Config.fromKubeconfig(Config.java:459)
│     at io.fabric8.kubernetes.client.Config.fromKubeconfig(Config.java:453)
```

**Comment by rohanKanojia** [comment]
@TrsNium : Sorry for the late reply. Were you able to resolve this?
