### ISSUE TITLE
Openshift not available error

### ISSUE THREAD

**Issue by cedar715** [fabric8io/kubernetes-client#1944]
We upgraded Fabric8 from 4.1.1 to 4.7.0. And it is resulting in `OpenShift is not available.`

```
13:59:28  Caused by: io.fabric8.openshift.client.OpenShiftNotAvailableException: OpenShift is not available. Root paths at: https://192.168.64.1:443/ do not include oapi.
13:59:28  	at io.fabric8.openshift.client.OpenShiftExtensionAdapter.adapt(OpenShiftExtensionAdapter.java:46)
13:59:28  	at io.fabric8.openshift.client.OpenShiftExtensionAdapter.adapt(OpenShiftExtensionAdapter.java:33)
13:59:28  	at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:128)
```

- Impersonation is enabled and we are just setting the user and NOT group.
- Openshift 3.11

**Comment by cedar715** [comment]
It was related to impersonateGroup issue.

**Comment by rohanKanojia** [comment]
@cedar715 : Could you please elaborate how you were able to resolve this? I see someone also filed #1945 . Is this related?
