### ISSUE TITLE
Error when load yaml with parameters

### ISSUE THREAD

**Issue by marlonpatrick** [fabric8io/kubernetes-client#1979]
To reproduce the error run the code below with an multi-document yaml. Parameters must have the format `${param1}`. 

    public static void main(String[] args) {
    	try(DefaultKubernetesClient client = new DefaultKubernetesClient()){
    		
        	Map<String, String> parameters = new HashMap<>();
        	parameters.put("param1", "value1");
        	parameters.put("param2", "value2");

            client.load(MyClass.class.getResourceAsStream("/my-multiple-document.yaml"))
                	.withParameters(parameters).inNamespace("myNamespace").get();
    	}
    }

Log:

```
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
        at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:134)
        at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:95)
        at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:228)
        at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.withParameters(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:185)
        at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.withParameters(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:64)

Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (BufferedInputStream); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
        at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:360)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1704)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)
        at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:132)
        ... 25 more

```

**Comment by rohanKanojia** [comment]
Hmm, I'm not sure whether we supported replacing parameters earlier in Kubernetes manifests, it was only specific for templates I think(I might be wrong). Was it working for you in previous versions? If not, I think it's not a bad idea to support this in regular manifests too.

**Comment by manusa** [comment]
Relates to:
- #959

**Comment by marlonpatrick** [comment]
> Hmm, I'm not sure whether we supported replacing parameters earlier in Kubernetes manifests, it was only specific for templates I think(I might be wrong). Was it working for you in previous versions? If not, I think it's not a bad idea to support this in regular manifests too.

Hey guy,

I had never tested it in other versions, but the same document works when using Serialization.unmarshal.

So, from what I looked at quickly, it is as if he had been calling the method Serialization.unmarshal 2 times, once with the empty string which causes the error.
