### ISSUE TITLE
JobExample doesn't work

### ISSUE THREAD

**Issue by dlafreniere** [fabric8io/kubernetes-client#2054]
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/JobExample.java

This example doesn't work as the logs are checked right after the job is created and the pod isn't ready:

```
[main] INFO io.fabric8.kubernetes.examples.JobExample - Creating job pi.
[main] ERROR io.fabric8.kubernetes.examples.JobExample - Unable to create job
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://localhost:8443/api/v1/namespaces/catalog-service/pods/pi-7ggfj/log?pretty=false. Message: container "pi" in pod "pi-7ggfj" is waiting to start: ContainerCreating. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=container "pi" in pod "pi-7ggfj" is waiting to start: ContainerCreating, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.doGetLog(PodOperationsImpl.java:173)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.getLog(PodOperationsImpl.java:182)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.getLog(PodOperationsImpl.java:200)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.getLog(PodOperationsImpl.java:72)
	at io.fabric8.kubernetes.client.dsl.internal.JobOperationsImpl.getLog(JobOperationsImpl.java:168)
	at io.fabric8.kubernetes.client.dsl.internal.JobOperationsImpl.getLog(JobOperationsImpl.java:161)
	at io.fabric8.kubernetes.client.dsl.internal.JobOperationsImpl.getLog(JobOperationsImpl.java:51)
	at io.fabric8.kubernetes.examples.JobExample.main(JobExample.java:68)

**Comment by manusa** [comment]
We'll look into it and try to provide a more reliable example

**Comment by sandroalm** [comment]
is there a way of calling a java method from there? 
instead of the args you passed
