### ISSUE TITLE
KnativeClient seems not working

### ISSUE THREAD

**Issue by softputer** [fabric8io/kubernetes-client#2093]
final KnativeClient knativeClient = new DefaultKnativeClient(config);

        System.out.println(knativeClient);
        System.out.println(knativeClient.routes().inNamespace("defauklt").list().getItems());

after i execute the code above, there is the error below:

Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.client.dsl.base.OperationContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by rohanKanojia** [comment]
@softputer : Which version are you using?

**Comment by softputer** [comment]
4.8.0, but 4..9.0 does not work too

**Comment by rohanKanojia** [comment]
@softputer : Strange, I'm not able to reproduce this issue. Are you sure there isn't some problem with your configuration?

**Comment by manusa** [comment]
Is this still an issue after 4.9.1 release with updated models?

**Comment by rohanKanojia** [comment]
@softputer : Could you please try it out again with latest release? If you're still facing this, would appreciate if you could provide us with some reproducible sample project.
