### ISSUE TITLE
client.customResourceDefinitions().list(); returns error

### ISSUE THREAD

**Issue by gaurav-dhoot** [fabric8io/kubernetes-client#2131]
Hi,

I tried to retrieve the Custom Resource Definitions that I have in my minishift. I have gone through your CRDExample and have followed the steps. However, I end up getting an error. 

This is the code that I used:
```
		Config clientConfig = new ConfigBuilder().withUsername("admin").withPassword("ad").withMasterUrl("https://192.168.99.108:8443/").build();
		OpenShiftClient client=new DefaultOpenShiftClient(clientConfig);
		CustomResourceDefinition crd=new CustomResourceDefinition();
		client.customResourceDefinitions().list();
```

This is the error that I get:
```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:248)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:199)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:621)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
	at restAPI.CRs.Topic.test.main(test.java:37)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaPropsOrBool` (although at least one Creator exists): no boolean/Boolean-argument constructor/factory method to deserialize from boolean value (true)
 at [Source: (BufferedInputStream); line: 1, column: 7151] (through reference chain: io.fabric8.kubernetes.api.model.apiextensions.CustomResourceDefinitionList["items"]->java.util.ArrayList[1]->io.fabric8.kubernetes.api.model.apiextensions.CustomResourceDefinition["spec"]->io.fabric8.kubernetes.api.model.apiextensions.CustomResourceDefinitionSpec["validation"]->io.fabric8.kubernetes.api.model.apiextensions.CustomResourceValidation["openAPIV3Schema"]->io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaProps["properties"]->java.util.LinkedHashMap["spec"]->io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaProps["properties"]->java.util.LinkedHashMap["kafka"]->io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaProps["properties"]->java.util.LinkedHashMap["config"]->io.fabric8.kubernetes.api.model.apiextensions.JSONSchemaProps["additionalProperties"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1432)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1062)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromBoolean(ValueInstantiator.java:280)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromBoolean(StdValueInstantiator.java:393)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromBoolean(BeanDeserializerBase.java:1426)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:180)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3259)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:246)
	... 8 more
```

My main motive is to create a Custom Resource for which a CRD is already in place in the OpenShift. I am really new to coding applications for OpenShift and based on the examples, I could conclude that I first need to list the CRDs present in the cluster and then use one of those CRDs to create a CR.

I would like to know if there is any other way to create the CR that I may have missed.

Any help in this matter is highly appreciated.

Thanks in advance:)

**Comment by rohanKanojia** [comment]
@gaurav-dhoot : Please take a look at our Custom Resource examples to get some idea on how to create CRDs:

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDLoadExample.java

**Comment by gaurav-dhoot** [comment]
Hi @rohanKanojia ,

As I have already mentioned, I have a CRD already in place. Also, I have used the exact same method for listing the CRDs in the cluster which returns an error.

**Comment by rohanKanojia** [comment]
Would it be possible for you to share your CRD spec so that we can try reproducing it ?

**Comment by gaurav-dhoot** [comment]
Hi,

This is my CRD in yaml:
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.kafka.test
spec:
  group: kafka.test
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    plural: kafkatopics
    singular: kafkatopic
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KafkaTopic is the Schema for the kafkatopics API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KafkaTopicSpec defines the desired state of KafkaTopic
          properties:
            configs:
              additionalProperties: true
              description: Topic specific configuration properties
              type: object
            name:
              description: 'The actual name of the topic. The CR will be rejected
              if a topic with this name already exists on the cluster.'
              type: string
            partitions:
              description: Number of partitions
              format: int32
              minimum: 0
              type: integer
            replicationFactor:
              description: Replication factor
              minimum: 0
              format: int16
              type: integer
            tls:
              description: TLS settings to be used in order to connect to the cluster
              properties:
                clientCertificate:
                  description: Client certificate
                  properties:
                    certificate:
                      description: The name of the key from the secret holding the
                        client certificate
                      type: string
                    key:
                      description: The name of the key from the secret holding the
                        private key
                      type: string
                    secretName:
                      description: The name of the secret holding the client certificate
                      type: string
                  required:
                  - certificate
                  - key
                  - secretName
                  type: object
                rootCA:
                  description: Root CA
                  properties:
                    certificate:
                      description: The name of the key from the secret holding the
                        CA certificate
                      type: string
                    secretName:
                      description: The name of the secret holding the CA
                      type: string
                  required:
                  - certificate
                  - secretName
                  type: object
              required:
              - clientCertificate
              - rootCA
              type: object
          required:
          - name
          - partitions
          - replicationFactor
          type: object
        status:
          description: KafkaTopicStatus defines the observed state of KafkaTopic
          properties:
            lastUpdate:
              format: date-time
              type: string
            reason:
              type: string
            status:
              enum:
              - Success
              - Failure
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true


Coming to "CustomResourceDefinition crd=new CustomResourceDefinition();", sorry I forgot to delete this from the code. I was just trying around with whatever I found.

The only thing I want to achieve at the end is create the resources which have CRDs present at the cluster. I do not expect to create a new CRD.

**Comment by rohanKanojia** [comment]
Could you please format your yaml spec? 

> The only thing I want to achieve at the end is create the resources which have CRDs present at the cluster. I do not expect to create a new CRD.
You mean you want to create CustomResources based on this CRD?

**Comment by gaurav-dhoot** [comment]
I dint get you on the formatting.
Yes, I want to create CustomResources based on this CRD.

**Comment by rohanKanojia** [comment]
I'm saying could you please format the yaml spec you shared?

**Comment by gaurav-dhoot** [comment]
Sure. Here it is:

`apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.kafka.test
spec:
  group: kafka.test
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    plural: kafkatopics
    singular: kafkatopic
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KafkaTopic is the Schema for the kafkatopics API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KafkaTopicSpec defines the desired state of KafkaTopic
          properties:
            configs:
              additionalProperties: true
              description: Topic specific configuration properties
              type: object
            name:
              description: 'The actual name of the topic. The CR will be rejected
              if a topic with this name already exists on the cluster.'
              type: string
            partitions:
              description: Number of partitions
              format: int32
              minimum: 0
              type: integer
            replicationFactor:
              description: Replication factor
              minimum: 0
              format: int16
              type: integer
            tls:
              description: TLS settings to be used in order to connect to the cluster
              properties:
                clientCertificate:
                  description: Client certificate
                  properties:
                    certificate:
                      description: The name of the key from the secret holding the
                        client certificate
                      type: string
                    key:
                      description: The name of the key from the secret holding the
                        private key
                      type: string
                    secretName:
                      description: The name of the secret holding the client certificate
                      type: string
                  required:
                  - certificate
                  - key
                  - secretName
                  type: object
                rootCA:
                  description: Root CA
                  properties:
                    certificate:
                      description: The name of the key from the secret holding the
                        CA certificate
                      type: string
                    secretName:
                      description: The name of the secret holding the CA
                      type: string
                  required:
                  - certificate
                  - secretName
                  type: object
              required:
              - clientCertificate
              - rootCA
              type: object
          required:
          - name
          - partitions
          - replicationFactor
          type: object
        status:
          description: KafkaTopicStatus defines the observed state of KafkaTopic
          properties:
            lastUpdate:
              format: date-time
              type: string
            reason:
              type: string
            status:
              enum:
              - Success
              - Failure
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
`

**Comment by rohanKanojia** [comment]
I checked and I can reproduce your issue. Looks like client is failing to deserialize your yaml object.

**Comment by rohanKanojia** [comment]
Seems like client is failing to parse this line specifically on line 64:
```
                bmvCaCerts:
                  description: BMW root and intermediate certificates
                  type: string
                config:
                  **additionalProperties: true**
                  description: Kafka broker specific configuration properties
                  type: object
```
When I remove it I'm able to create CRD

**Comment by gaurav-dhoot** [comment]
So, are you creating the CRD through the client or directly importing this particular yaml file into OpenShift?

**Comment by rohanKanojia** [comment]
I tried importing yaml into an object and then create afterwards

**Comment by gaurav-dhoot** [comment]
Hi @rohanKanojia,

Thanks for the update. Actually, I am first importing the CRD.yaml file into the OpenShift platform and then retrieving it from there. Is this not possible?

Also, how do I create the classes for the CR? I'm a bit lost with the example program that you have provided. Could you help me with a class with my CRD? Appreciate any help in this regard.

**Comment by rohanKanojia** [comment]
Umm, if you don't have classes you can use Raw API for using CustomResources:
https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api
