### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version

### ISSUE THREAD

**Issue by alanbchristie** [fabric8io/kubernetes-client#2135]
Experiencing repeated **"too old resource version"** onClose() exceptions in a Watcher object. The resource being watched, a `Job`,  runs for several hours but (typically) after 80-100 minutes I always encounter a **"too old resource version"** exception. I re-create the `Watch` object, but after another period (35 minutes in one case) I encounter another **"too old resource version"** exception.

I keep re-creating the Watch object until the underlying Job completes.

The exception stack is as follows: -

```
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 22657715 (22658769)
    at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:263)
    at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
    at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
    at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
    at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

1. The Pod's resourceVersion at creation (and throughout its lifetime) in this example is `22657715`.

**Question 1**
What is the resource version `22658769` referred to in the exception? The Job's is `22657715` and I never specify a version anyway.

**Question 2**
Is this exception behaviour expected? i.e. am I required to handle this exception and re-create the Watch?

Significant versions and code examples shown below...

---

- Using `io.fabric8:openshift-client:4.9.0` from Java
- Kubernetes `v1.16.4` on AWS EC2

---

(_The code segments are edited here for clarity - e.g. try/catch blocks removed along with application-specific code_)

I declare my PodWatcher (significantly redacted): -

```
static class PodWatcher implements Watcher<Pod> {

    @Override
    public void eventReceived(Action action, Pod resource) {
    }

    @Override
    public void onClose(KubernetesClientException cause) {
    }
}
```

I create a watch object for the named Pod: -

```
OpenShiftClient client = new DefaultOpenShiftClient();
PodWatcher podWatcher = new PodWatcher(podName);
Watch watchObject = client.pods()
    .withName(podName)
    .watch(podWatcher);
```

I create my Pod (pod declaration is not important): -

```
client.pods().create(pod);
```

- The Pod runs typically for about 3 hours before terminating.
- During this time the `podWatcher` experiences a number of `onClose()` exceptions
- I am forced to instantiate a new `watchObject` in order to continue to monitor the Pod

What follows is some redacted log with the two exceptions and two replacement Watch objects being created. The Pod (Job) here has **resourceVersion** `24194326` and runs for approximately 2 hours 53 minutes. In that time two exceptions are encountered: -

- One after 1h 42m 28s at 11:09:11
- One after a further 35m 10s at 11:44:21

```
Apr 14, 2020 9:26:43 PM INFO: (Creating PodWatcher)
Apr 14, 2020 9:26:43 PM INFO: (Creating Pod)
Apr 14, 2020 9:26:43 PM INFO: (Waiting for Pod completion)
Apr 14, 2020 9:26:43 PM INFO: eventReceived
Apr 14, 2020 9:26:43 PM INFO: eventReceived
Apr 14, 2020 9:26:43 PM INFO: eventReceived
Apr 14, 2020 9:26:43 PM INFO: eventReceived
Apr 14, 2020 9:26:44 PM INFO: eventReceived
Apr 14, 2020 9:26:44 PM INFO: eventReceived
Apr 14, 2020 9:26:44 PM INFO: eventReceived
Apr 14, 2020 9:26:45 PM INFO: eventReceived
Apr 14, 2020 9:26:45 PM INFO: eventReceived
Apr 14, 2020 9:26:45 PM INFO: Pod is Running

io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 24194326 (24204707)
    at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:259)
    at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
    at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
    at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
    at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Apr 14, 2020 11:09:11 PM WARNING: cause.message=too old resource version: 24194326 (24204707)
Apr 14, 2020 11:09:11 PM INFO: (Re-creating PodWatcher)
Apr 14, 2020 11:09:11 PM INFO: eventReceived
Apr 14, 2020 11:09:11 PM INFO: eventReceived

io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 24194326 (24213765)
    at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:259)
    at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
    at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
    at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
    at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Apr 14, 2020 11:44:21 PM WARNING: cause.message=too old resource version: 24194326 (24213765)
Apr 14, 2020 11:44:22 PM INFO: (Re-creating PodWatcher)
```

**Comment by rohanKanojia** [comment]
seems related to #1943

**Comment by alanbchristie** [comment]
You may be right.

I am able to work-around the problem, as you can see, and execution seems fine if I continue to re-create the `Watcher` object. But it's not elegant.

**Comment by johnhec** [comment]
I have the same problem, How did you solve it？

**Comment by alanbchristie** [comment]
I am forced to instantiate a new `PodWatcher` object in order to continue to monitor the Pod.

It's probably easier to direct you to the open source code in our [squonk](https://github.com/InformaticsMatters/squonk/blob/master/components/core-services-exec/src/main/groovy/org/squonk/execution/runners/OpenShiftRunner.java) project.

The `OpenShiftRunner` is responsible for launching a Pod and monitoring events. It's this code that experiences the exception. I simply handle the `hasOnCloseException()` [on or around line 802] and use that to re-instantiate the `PodWatcher`.

**Comment by johnhec** [comment]
I did that too, but it was not very elegant

**Comment by alanbchristie** [comment]
Agreed but (imo) it's a problem caused by someone else so the solution is often "best effort" and development constraints often leave one with many other features to code and other problems to fix.

 _Elegant_ would be the code author...

1. fixing the implementation
2. telling me _"it's fixed in vx.y.z"_
2. providing an explanation and solution pattern if the behaviour is not considered a bug

Letting an issue simply go stale letting a "bot" close the issue without any feedback is also not _elegant_.
