### ISSUE TITLE
Upload data to pod within microk8s fails

### ISSUE THREAD

**Issue by srandoll** [fabric8io/kubernetes-client#2217]
When uploading data to a pod within a microk8s cluster using the upload functionality:
`                client.pods()
                        .inNamespace(namespace)
                        .withName(pod.getMetadata().getName())
                        .inContainer("<container>")
                        .file("/test")
                        .upload(testFile);
`
the operation fails with:

> `io.fabric8.kubernetes.client.KubernetesClientException: [text={"metadata":{},"status":"Success"}]
	at io.fabric8.kubernetes.client.dsl.internal.uploadable.PodUploadWebSocketListener.checkError(PodUploadWebSocketListener.java:91)
	at io.fabric8.kubernetes.client.dsl.internal.uploadable.PodUploadWebSocketListener.send(PodUploadWebSocketListener.java:114)
	at io.fabric8.kubernetes.client.dsl.internal.uploadable.PodUpload.copy(PodUpload.java:139)
	at io.fabric8.kubernetes.client.dsl.internal.uploadable.PodUpload.uploadFile(PodUpload.java:86)
	at io.fabric8.kubernetes.client.dsl.internal.uploadable.PodUpload.upload(PodUpload.java:64)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.lambda$upload$0(PodOperationsImpl.java:331)
	at io.fabric8.kubernetes.client.utils.OptionalDependencyWrapper.wrapRunWithOptionalDependency(OptionalDependencyWrapper.java:39)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.upload(PodOperationsImpl.java:329)
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.upload(PodOperationsImpl.java:76)`

It seems that Micro8s does returns a "text={"metadata":{},"status":"Success"}" string but the PodUploadWebSocketListener class does interpret all responses as errors. Actually I don't know what is correct regarding the standard but it seems to be a valid return value.

**Comment by kanakl** [comment]
I have the same problem with K3S (v1.20.4+k3s1). I tried the official library from Kubernetes (version 10.0.0) and it worked fine without any problems. The file is created but is not fully uploaded

**Comment by rohanKanojia** [comment]
@kanakl : ohk, this means we have a bug in our code regarding upload

**Comment by davinchia** [comment]
Running into this too. Interestingly this was fine when testing on Docker For Desktop and only started erroring out on GKE.

It actually succeeds the first time, then errors out all subsequent times until the client is restarted.

My docker desktop version
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

My GKE version:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.6-gke.1400", GitCommit:"b7ccf3218bdb80cd2d66ed6186d78f18f1ef03c6", GitTreeState:"clean", BuildDate:"2021-05-05T09:19:45Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}
```
