### ISSUE TITLE
SharedIndexInformer for non-namespaced resources not working

### ISSUE THREAD

**Issue by buehlmann** [fabric8io/kubernetes-client#2226]
Hi,

I'am trying to register an informer for the Namespace resource to get notified as soon a new Namespace is created or an existing is updated. The created URL by the KubernetesClient looks like `https://openshift.localhost:8443/api/v1/namespaces/myproject/namespaces` which is wrong. 

Snippet which I use to create the informer:
```
    @Inject
    KubernetesClient client;
...
        SharedInformerFactory informerFactory = client.informers();
        SharedIndexInformer<Namespace> namespaceInformer = informerFactory.sharedIndexInformerFor(Namespace.class, NamespaceList.class, 10 * 60 * 1000);
```

Same issue occurs for `ClusterRoleBinding`.

I tried to provide a custom `OperationContext` with different parameters which was not working due to https://github.com/fabric8io/kubernetes-client/pull/2213.

Log output:
```
2020-05-14 08:08:50,503 WARN  [io.fab.kub.cli.inf.cac.Controller] (informer-controller-Namespace) Reflector list-watching job exiting because the thread-pool is shutting down: java.util.concurrent.RejectedExecutionException: Error while starting ReflectorRunnable watch
        at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:85)
        at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:112)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Error while doing ReflectorRunnable list
        at io.fabric8.kubernetes.client.informers.cache.Reflector.getList(Reflector.java:73)
        at io.fabric8.kubernetes.client.informers.cache.Reflector.reListAndSync(Reflector.java:94)
        at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:80)
        ... 2 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://openshift.localhost:8443/api/v1/namespaces/myproject/namespaces. Message: the server could not find the requested resource. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=the server could not find the requested resource, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:621)
        at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:134)
        at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:127)
        at io.fabric8.kubernetes.client.informers.cache.Reflector.getList(Reflector.java:67)
        ... 4 more

```

Are there any ways to register an SharedInformer for non-namespaced resources?

**Comment by rohanKanojia** [comment]
strange, I wasn't able to reproduce this issue on minikube and Fabric8 Kubernetes Client v4.10.0. I tried with code like this:
```
try (KubernetesClient client = new DefaultKubernetesClient()) {
    // Get Informer Factory
    SharedInformerFactory sharedInformerFactory = client.informers();

    // Create instance for Namespace Informer
    SharedIndexInformer<Namespace> NamespaceInformer = sharedInformerFactory.sharedIndexInformerFor(Namespace.class, NamespaceList.class, 30 * 1000L);
    logger.info("Informer factory initialized.");

    // Add Event Handler for actions on all Namespace events received
    NamespaceInformer.addEventHandler(
            new ResourceEventHandler<Namespace>() {
                @Override
                public void onAdd(Namespace Namespace) {
                    logger.info("Namespace " + Namespace.getMetadata().getName() + " got added");
                }

                @Override
                public void onUpdate(Namespace oldNamespace, Namespace newNamespace) {
                    logger.info("Namespace " + oldNamespace.getMetadata().getName() + " got updated");
                }

                @Override
                public void onDelete(Namespace Namespace, boolean deletedFinalStateUnknown) {
                    logger.info("Namespace " + Namespace.getMetadata().getName() + " got deleted");
                }
            }
    );

    logger.info("Starting all registered informers");
    sharedInformerFactory.startAllRegisteredInformers();

    // Wait for 1 minute
    Thread.sleep(60 * 1000L);
} catch (InterruptedException e) {
    Thread.currentThread().interrupt();
    e.printStackTrace();
}
```
When I ran it, I was able to see informers printing correct events:
```
May 14, 2020 1:56:26 PM io.fabric8.NamespacedInformer main
INFO: Informer factory initialized.
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer main
INFO: Starting all registered informers
[informer-controller-Namespace] INFO io.fabric8.kubernetes.client.informers.cache.Controller - informer#Controller: ready to run resync and reflector runnable
[informer-controller-Namespace] INFO io.fabric8.kubernetes.client.informers.cache.Reflector - Started ReflectorRunnable watch for class io.fabric8.kubernetes.api.model.Namespace
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onAdd
INFO: Namespace default got added
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onUpdate
INFO: Namespace default got updated
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onAdd
INFO: Namespace kube-node-lease got added
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onUpdate
INFO: Namespace kube-node-lease got updated
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onAdd
INFO: Namespace kube-public got added
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onUpdate
INFO: Namespace kube-public got updated
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onAdd
INFO: Namespace kube-system got added
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onUpdate
INFO: Namespace kube-system got updated
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onAdd
INFO: Namespace kubernetes-dashboard got added
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onUpdate
INFO: Namespace kubernetes-dashboard got updated
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onAdd
INFO: Namespace tekton-pipelines got added
May 14, 2020 1:56:27 PM io.fabric8.NamespacedInformer$1 onUpdate
INFO: Namespace tekton-pipelines got updated
```

**Comment by buehlmann** [comment]
Yeah, that's what I would expect.

I am running the Quarkus based K8s client `io.quarkus:quarkus-kubernetes-client:1.4.2.Final` which references `io.fabric8:kubernetes-client:4.9.0` against an OpenShift 3.11 running on Minishift.

**Comment by rohanKanojia** [comment]
let me try to reproduce this on minishift and get back to you

**Comment by rohanKanojia** [comment]
I can reproduce this issue on minishift. Let me try to check why it's happening on minishift only :worried:

**Comment by buehlmann** [comment]
FYI: I can reproduce this behaviour against a real OpenShift 3.11 cluster as well.
