### ISSUE TITLE
Tests failing on windows 

### ISSUE THREAD

**Issue by stevemuk** [fabric8io/kubernetes-client#226]
Looks like an issue with java nio file handling on windows.

```
Illegal char <:> at index 2: /C:/Dev/git/kubernetes-client/kubernetes-client/target/test-classes/test-kubeconfig
```

```
Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.046 sec <<< FAILURE! - in io.fabric8.kubernetes.client.ConfigTest
testWithKubeConfigAndSytemPropertiesAndBuilder(io.fabric8.kubernetes.client.ConfigTest)  Time elapsed: 0.037 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Dev/git/kubernetes-client/kubernetes-client/target/test-classes/test-kubeconfig
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:236)
        at io.fabric8.kubernetes.client.Config.<init>(Config.java:106)
        at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:17)
        at io.fabric8.kubernetes.client.ConfigTest.testWithKubeConfigAndSytemPropertiesAndBuilder(ConfigTest.java:174)

testWithKubeConfigAndSystemProperties(io.fabric8.kubernetes.client.ConfigTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Dev/git/kubernetes-client/kubernetes-client/target/test-classes/test-kubeconfig
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:236)
        at io.fabric8.kubernetes.client.Config.<init>(Config.java:106)
        at io.fabric8.kubernetes.client.ConfigTest.testWithKubeConfigAndSystemProperties(ConfigTest.java:162)

testWithBuilderAndSystemProperties(io.fabric8.kubernetes.client.ConfigTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Dev/git/kubernetes-client/kubernetes-client/target/test-classes/test-kubeconfig
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:236)
        at io.fabric8.kubernetes.client.Config.<init>(Config.java:106)
        at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:17)
        at io.fabric8.kubernetes.client.ConfigTest.testWithBuilderAndSystemProperties(ConfigTest.java:138)

testWithKubeConfig(io.fabric8.kubernetes.client.ConfigTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Dev/git/kubernetes-client/kubernetes-client/target/test-classes/test-kubeconfig
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:236)
        at io.fabric8.kubernetes.client.Config.<init>(Config.java:106)
        at io.fabric8.kubernetes.client.ConfigTest.testWithKubeConfig(ConfigTest.java:149)

testWithBuilder(io.fabric8.kubernetes.client.ConfigTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Dev/git/kubernetes-client/kubernetes-client/target/test-classes/test-kubeconfig
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:236)
        at io.fabric8.kubernetes.client.Config.<init>(Config.java:106)
        at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:17)
        at io.fabric8.kubernetes.client.ConfigTest.testWithBuilder(ConfigTest.java:89)

testWithSystemProperties(io.fabric8.kubernetes.client.ConfigTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Dev/git/kubernetes-client/kubernetes-client/target/test-classes/test-kubeconfig
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:236)
        at io.fabric8.kubernetes.client.Config.<init>(Config.java:106)
        at io.fabric8.kubernetes.client.ConfigTest.testWithSystemProperties(ConfigTest.java:80)
```

**Comment by stevemuk** [comment]
I'm also seeing a problem running the fabric8 maven plugin on windows. The kubernetes-client is looking for the .kube\config in ```System.getProperty("user.home", ".")```
but oc uses the environment variable %HOME%. On my machine user.home!=%HOME%

**Comment by jimmidyson** [comment]
This is a bug in OpenShift... https://github.com/openshift/origin/issues/5335

Not quite sure how to handle it & not break backward/forward compatibility. I _think_ our functionality is correct but doesn't work with the current bug in `oc`.

**Comment by stevemuk** [comment]
Is it not just a case of matching the behaviour of oc which at the moment uses the environment variable HOME. You could change the client to use System.getenv("HOME") if present, otherwise default to System.getProperty("user.home", ".")

**Comment by jimmidyson** [comment]
Until they fix it when both paths will be valid... annoying & also inconsistent with `kubectl` which we also support.

**Comment by jimmidyson** [comment]
As an aside, we support the `KUBECONFIG` environment variable on all platforms to override default config path.

**Comment by iocanel** [comment]
Is it just me or you went off topic?

regardless of what happens in the runtime, we still have an issue at test time, which needs to be address (construct the path in a way that doesn't use /C: but C: as a prefix

**Comment by jimmidyson** [comment]
Well they're related - yes the path should be fixed, but it's not just the test it's broken functionality which needs to be fixed in general.

**Comment by jimmidyson** [comment]
So agree they're 2 separate issues but one has highlighted the other.

**Comment by jimmidyson** [comment]
@stevemuk This particular issue should be fixed. Will think about the other issue, wrong Windows path being used, separately.
