### ISSUE TITLE
How to gracefully terminate the watch over a custom resource

### ISSUE THREAD

**Issue by Galileo1** [fabric8io/kubernetes-client#2280]
I am creating a custom resource( Helm Release) that deploys the Helm Charts for my application in K8s cluster. How can I terminate the watch gracefully when the Custom resource is deployed successfully? Can someone please help me? 

Here is the code : 
```
            final CompletableFuture future = new CompletableFuture<>();
            client.customResource(crdContext).watch("namespace", new Watcher<String>() {
                @Override
                public void eventReceived(Action action, String resource) {
                    try {
                        JSONObject json = new JSONObject(resource);
                        logger.info(action + " : " + json.getJSONObject("metadata").getString("name"));
                        logger.info( " json : " + json);
                        if (json.getJSONObject("metadata").getString("name").equals("releasename")) {
                            if (json.getJSONObject("status").get("phase").equals("Succeeded")) {
                                future.complete(resource);
                            }
                        }
                    } catch (JSONException exception) {
                        log("failed to parse object");
                    }
                }
                @Override
                public void onClose(KubernetesClientException e) {
                    logger.info("Watcher onClose");
                    if (e != null) {
                       log(e.getMessage());
                    }
                }
            });
         future.get();
        } catch (InterruptedException exception ) {
            logger.info("Interrupted: " + exception.getMessage());
        } catch (IOException exception) {
            logger.info("Exception: " + exception.getMessage());
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
```
Error message I get - 
```
[OkHttp https://k8s-test-apiproxy-vip-dc1....] WARN io.fabric8.kubernetes.client.dsl.internal.RawWatchConnectionManager - Exec Failure
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:68)
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rohanKanojia** [comment]
Have you tried using `Watch` returned from `watch()` method:
```
    Watch watch = client.customResource(customResourceDefinitionContext)
      .watch("ns1", null, null, (ListOptions)null,
        new Watcher<String>() {
          @Override
          public void eventReceived(Action action, String resource) { anyEventReceived.countDown(); }
          @Override
          public void onClose(KubernetesClientException cause) { }
        });

    // ...
    watch.close();
```

**Comment by Galileo1** [comment]
@rohanKanojia Not at the moment. I saw an example(attached). And wanted to do something like this to gracefully close the watch and use "whenComplete((ok, ex) -> watch.close());" because in my case the control is in Async context and we want to return the CompletableFuture. 

I am going to give the above coed a try. Will share the outcome.

![image](https://user-images.githubusercontent.com/9716232/84353909-18959100-ac14-11ea-89c0-55e8535686af.png)

**Comment by Galileo1** [comment]
The behavior that I'm seeing is that it doesn't wait for the condition in the eventReceived() block. Do we need to have a countdown/latch? But why would it not wait for `if (json.getJSONObject("status").get("phase").equals("Succeeded")) ` condition? Might be missing alot.

 ```
final Watch watch = client.customResource(crdContext)
                    .watch("namespace", "releasename", null, null,
                            new Watcher<String>() {
                                @Override
                                public void eventReceived(Action action, String resource) {
                                    JSONObject json = new JSONObject(resource);
                                    logger.info(action + " : " + json.getJSONObject("metadata").getString("name"));
                                    //logger.info(" json : " + json);
                                    if (json.getJSONObject("metadata").getString("name").equals("releasename")) {
                                        if (json.getJSONObject("status").get("phase").equals("Succeeded")) {
                                            logger.info(" json : " + json);
                                            //future.complete(resource);
                                        }
                                    }
                                }

                                @Override
                                public void onClose(KubernetesClientException e) {
                                    logger.info("Watcher onClose");
                                    if (e != null) {
                                        logger.info(e.getMessage());
                                    }
                                }
                            });
            watch.close();
```

**Comment by Galileo1** [comment]
closing this. thanks for the help. Seems like there was a difference in behavior for library version 4.9.X and 4.10.X. we bumped the version and it worked.
