### ISSUE TITLE
RejectedExecutionException from LogWatchCallback

### ISSUE THREAD

**Issue by skabashnyuk** [fabric8io/kubernetes-client#2299]
I got this exception with 4.9.0 on che.openshift.io
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6dc25c5c rejected from java.util.concurrent.ThreadPoolExecutor@60b9cac4[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at io.fabric8.kubernetes.client.dsl.internal.LogWatchCallback.onResponse(LogWatchCallback.java:158)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
I can understand how important it is. 
Can someone help to explain what does it mean?

**Comment by rohanKanojia** [comment]
@skabashnyuk : Hi Sergii, Sorry for the late reply. According to [docs](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html), `RejectedExecutionException` is thrown by ThreadPoolExecutor when the executor has been shut down and we try to submit new tasks into it. 

`LogWatchCallback` is passed while doing okhttp request:
https://github.com/fabric8io/kubernetes-client/blob/df366139c011ff719f0c904f0b06d2950d13bd99/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java#L225-L228

In `LogWatchCallback` executor is submitted a new task on `onResponse()` call from within okhttp. 

https://github.com/fabric8io/kubernetes-client/blob/df366139c011ff719f0c904f0b06d2950d13bd99/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/LogWatchCallback.java#L145-L160

I think we should add a check of `executor.isShutdown()` before submitting any new task and throw some meaningful exception in case `RejectedExecutionException` is thrown.
