### ISSUE TITLE
Can I create a Catalog Source and Subscription using the Kubernetes or the OpenShift Client

### ISSUE THREAD

**Issue by prabhjotbawa** [fabric8io/kubernetes-client#2321]
Hi ,
This could be more of a question rather than an issue .However I am not able to figure out how to make it work.I would like to install a CatalogSource and Subscription to the cluster using the client,

Below is the code snippet I am using - 

```
void createResourcefromYaml(File resourceYaml){
KubernetesClient client = new DefaultKubernetesClient()
FileInputStream fileInputStream = new FileInputStream(resourceYaml)
client.load(fileInputStream).createOrReplace()
}

```
Below is sample catalogsource.yaml

```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: some-name
spec:
  sourceType: valid source type
  image: some image
  imagePullPolicy: Always
  displayName: some name
  publisher: some name

```

However I get the below error 
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:operators.coreos.com/v1alpha1#CatalogSource
 at [Source: (BufferedInputStream); line: 11, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:274)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.fromObjectNode(KubernetesDeserializer.java:85)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:57)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:46)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:138)
	... 7 more
```

I can do the above without any issue through commandline 
`oc apply -f catalog-source.yaml`
but not via the client.

Could you advice what am I missing here please?

Thank you

**Comment by manusa** [comment]
There are many OpenShift APIs we are missing, one of them being https://docs.openshift.com/container-platform/4.4/rest_api/operator_apis/operator-apis-index.html.

We may be able to provide model for this API structs.
