### ISSUE TITLE
Using Watcher<Event> leads to "JsonMappingException: No resource type found for:v1#Event"

### ISSUE THREAD

**Issue by michaelhixson** [fabric8io/kubernetes-client#2328]
When I try to listen for events with a `Watcher<Event>` like this...

```java
client.v1().events().inNamespace(namespaceName).watch(watcher)
```

... then the watcher doesn't receive any events as expected, and I see stack traces like this instead:

```
WARN [2020-07-02 13:25:40,217] io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager: Exec Failure
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
        at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:248)
        at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:167)
        at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:152)
        at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager.readWatchEvent(WatchHTTPManager.java:292)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:230)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:v1#Event
 at [Source: (BufferedInputStream); line: 1, column: 970] (through reference chain: io.fabric8.kubernetes.api.model.WatchEvent["object"])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:274)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.fromObjectNode(KubernetesDeserializer.java:85)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:57)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:46)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3259)
        at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:246)
        ... 14 common frames omitted
```

I started seeing this in an internal project after upgrading kubernetes-client from 4.9.0 to 4.10.2.

I'm working around the issue in my project by registering a `KubernetesResourceMappingProvider` that maps `"v1#Event"` to `io.fabric8.kubernetes.api.model.Event.class`.

I can't share that internal project, but I created a standalone project that demonstrates the same error along with a workaround.  See: https://github.com/michaelhixson/kubernetes-client-event-test

My dev environment where I'm seeing this issue:
* Windows 10
* Java 14.0.1
* Maven 3.6.3
* Docker Desktop 2.3.0.3
* Docker: 19.03.8
* Kubernetes: v1.16.5
* kubernetes-client library: 4.10.2

**Comment by rohanKanojia** [comment]
This looks like a regression introduced by #2256
