### ISSUE TITLE
Error when creating CRD resource

### ISSUE THREAD

**Issue by Traderjoe95** [fabric8io/kubernetes-client#2334]
I am trying to create a namespaced KubeDB MongoDB resource. Here is what I do:

```java
public void deploy(KubernetesClient client, String namespace) {
    client.customResource(CONTEXT)
          .create(namespace, resourceUtils.getCpResourceAsStream("k8s/mongodb/repository.mongodb.yml"));
}
```

where `CONTEXT` is a constant:

```java
private static final CustomResourceDefinitionContext CONTEXT =
            new CustomResourceDefinitionContext.Builder()
                    .withName("mongodbs.kubedb.com")
                    .withGroup("kubedb.com")
                    .withVersion("v1alpha1")
                    .withScope("Namespaced")
                    .withPlural("mongodbs")
                    .withKind("MongoDB")
                    .build();
```

The call to `resourceUtils.getCpResourceAsStream` loads a YAML resource file from the classpath.

**Expected behavior:** The resource is created in the passed namespace

**Actual behavior:** The request fails with a HTTP 403 status. The error message states that the namespace field was empty:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.3.186:6443/apis/kubedb.com/v1alpha1/namespaces/test-namespace/mongodbs/. Message: admission webhook "mongodb.mutators.kubedb.com" denied the request: an empty namespace may not be set when a resource name is provided. Received status: Status(apiVersion=v1, code=403, details=null, kind=Status, message=admission webhook "mongodb.mutators.kubedb.com" denied the request: an empty namespace may not be set when a resource name is provided, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568) ~[kubernetes-client-4.10.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:784) ~[kubernetes-client-4.10.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.validateAndSubmitRequest(RawCustomResourceOperationsImpl.java:799) ~[kubernetes-client-4.10.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.validateAndSubmitRequest(RawCustomResourceOperationsImpl.java:792) ~[kubernetes-client-4.10.2.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.create(RawCustomResourceOperationsImpl.java:152) ~[kubernetes-client-4.10.2.jar:?]
	at com.kobil.ssms.testing.load.k8s.resources.mongo.MongoDbResource.deploy(MongoDbResource.java:41) ~[classes/:?]
	at com.kobil.ssms.testing.load.cli.system.InitCommand.lambda$call$0(InitCommand.java:54) ~[classes/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1510) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at com.kobil.ssms.testing.load.cli.system.InitCommand.call(InitCommand.java:48) [classes/:?]
	at com.kobil.ssms.testing.load.cli.system.InitCommand.call(InitCommand.java:18) [classes/:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1853) [picocli-4.3.2.jar:4.3.2]
	at picocli.CommandLine.access$1100(CommandLine.java:145) [picocli-4.3.2.jar:4.3.2]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255) [picocli-4.3.2.jar:4.3.2]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2249) [picocli-4.3.2.jar:4.3.2]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2213) [picocli-4.3.2.jar:4.3.2]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080) [picocli-4.3.2.jar:4.3.2]
	at picocli.CommandLine.execute(CommandLine.java:1978) [picocli-4.3.2.jar:4.3.2]
	at com.kobil.ssms.testing.load.runner.LoadCtlRunner.run(LoadCtlRunner.java:26) [classes/:?]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at com.kobil.ssms.testing.load.LoadCtl.main(LoadCtl.java:18) [classes/:?]
```
I double checked the URL that is listed in the error message and it seems correct. When I create the resource manually via `kubectl apply -f <the file> -n test-namespace`, its `selfLink` points to exactly the same URL (plus the name of the resource). Still, I can't get the `KubernetesClient` to create it.

**Kubernetes Client Version:** 4.10.2

**Comment by rohanKanojia** [comment]
@Traderjoe95 : Could you please share your CRD spec and contents of `k8s/mongodb/repository.mongodb.yml` so that we can try to reproduce your issue?

**Comment by Traderjoe95** [comment]
The CRD spec is rather complicated. It's installed by KubeDB upon installation: [https://kubedb.com/docs/0.12.0/setup/install/](https://kubedb.com/docs/0.12.0/setup/install/)

The contents of the resource file are:
```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: repository-mongodb
spec:
  version: "4.1.7-v1"
  replicas: 3
  replicaSet:
    name: rs0
  storageType: Durable
  storage:
    storageClassName: nfs
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
```

**Comment by Traderjoe95** [comment]
Maybe I have found the reason already. I just ran `kubectl -n test-namespace --dry-run='client' -o yaml -f repository.mongodb.yml`, which showed that all default parameters as well as the namespace are automatically added by `kubectl` BEFORE the request is sent:
```yaml
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  creationTimestamp: "2020-07-07T15:00:06Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2020-07-07T15:00:53Z"
  finalizers:
  - kubedb.com
  generation: 4
  name: repository-mongodb
  namespace: load-testing
  resourceVersion: "71888271"
  selfLink: /apis/kubedb.com/v1alpha1/namespaces/load-testing/mongodbs/repository-mongodb
  uid: bfe1480f-27c4-4deb-945d-c15a8a36b9ac
spec:
  certificateSecret:
    secretName: repository-mongodb-keyfile
  databaseSecret:
    secretName: repository-mongodb-auth
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      livenessProbe:
        exec:
          command:
          - mongo
          - --eval
          - db.adminCommand('ping')
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        exec:
          command:
          - mongo
          - --eval
          - db.adminCommand('ping')
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      securityContext:
        fsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
  replicaSet:
    name: rs0
  replicas: 3
  serviceTemplate:
    metadata: {}
    spec: {}
  storage:
    accessModes:
    - ReadWriteOnce
    dataSource: null
    resources:
      requests:
        storage: 20Gi
    storageClassName: nfs
  storageType: Durable
  terminationPolicy: Pause
  updateStrategy:
    type: RollingUpdate
  version: 4.1.7-v1
status:
  phase: Creating
```

**Comment by rohanKanojia** [comment]
@Traderjoe95 : cool, Does it work when you add namespace inside YAML manifest?

**Comment by Traderjoe95** [comment]
Yes, indeed. But as the namespace has to be dynamic for my use case, I need to find another solution.

**Comment by jorgesartori** [comment]
This '... admission webhook "mongodb.mutators.kubedb.com" ...' is from kubeDB and each CRD operator has some webhooks that you must obey.
Try using a template engine like Mustache to interpolate your yaml ;)
