### ISSUE TITLE
Close watch used in tests after using it

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2358]
I've seen some tests where watch is not closed after usage. However it doesn't affect test suite that much, but it leaves an annoying stacktrace in test logs. Here is an example of `PodTest`:

https://github.com/fabric8io/kubernetes-client/blob/e7980045337c679eb95c7f9b6006ac93adc348a8/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/PodTest.java#L362

On running this test, I get a stack trace  due to watch not being closed explicitly:
```
~/go/src/github.com/fabric8io/kubernetes-client/kubernetes-tests : $ mvn test -Dtest="io.fabric8.kubernetes.client.mock.PodTest"
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ---------------------< io.fabric8:kubernetes-test >---------------------
[INFO] Building Fabric8 :: Kubernetes :: Tests 4.10-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- sundr-maven-plugin:0.21.0:generate-bom (default) @ kubernetes-test ---
[INFO] 
[INFO] --- build-helper-maven-plugin:3.2.0:parse-version (parse-version) @ kubernetes-test ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (default-prepare-agent) @ kubernetes-test ---
[INFO] argLine set to -javaagent:/home/rohaan/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/home/rohaan/go/src/github.com/fabric8io/kubernetes-client/kubernetes-tests/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ kubernetes-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/rohaan/go/src/github.com/fabric8io/kubernetes-client/kubernetes-tests/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ kubernetes-test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- jandex-maven-plugin:1.0.8:jandex (make-index) @ kubernetes-test ---
[INFO] [SKIP] Cannot process fileset in directory: /home/rohaan/go/src/github.com/fabric8io/kubernetes-client/kubernetes-tests/target/classes. Directory does not exist!
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ kubernetes-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 55 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ kubernetes-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ kubernetes-test ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.fabric8.kubernetes.client.mock.PodTest
Jul 17, 2020 3:28:29 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[48345] starting to accept connections
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[48345] received request: GET /api/v1/namespaces/test/pods/pod1 HTTP/1.1 and responded: HTTP/1.1 404 Client Error
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[48345] done accepting connections: Socket closed
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[48007] starting to accept connections
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[48007] received request: DELETE /api/v1/namespaces/test/pods/pod1 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[48007] received request: DELETE /api/v1/namespaces/ns1/pods/pod2 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[48007] received request: DELETE /api/v1/namespaces/any/pods/pod3 HTTP/1.1 and responded: HTTP/1.1 404 Client Error
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[48007] done accepting connections: Socket closed
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[39903] starting to accept connections
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[39903] done accepting connections: Socket is closed
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[57067] starting to accept connections
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[57067] received request: GET /api/v1/namespaces/test/pods?fieldSelector=key1%3Dvalue1%2Ckey2%3Dvalue2%2Ckey3%21%3Dvalue3%2Ckey3%21%3Dvalue4 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[57067] done accepting connections: Socket closed
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[41869] starting to accept connections
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[41869] done accepting connections: Socket closed
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[48839] starting to accept connections
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[48839] done accepting connections: Socket closed
Jul 17, 2020 3:28:30 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[59445] starting to accept connections
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[59445] received request: GET /api/v1/namespaces/test/pods?labelSelector=key1%3Dvalue1%2Ckey2%3Dvalue2%2Ckey3%3Dvalue3 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[59445] received request: GET /api/v1/namespaces/test/pods?labelSelector=key1%3Dvalue1%2Ckey2%3Dvalue2 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[59445] done accepting connections: Socket closed
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[57123] starting to accept connections
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[57123] received request: GET /api/v1/namespaces/test/pods/pod1 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[57123] done accepting connections: Socket closed
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[51073] starting to accept connections
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[51073] received request: POST /api/v1/namespaces/test/pods/pod1/eviction HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[51073] received request: POST /api/v1/namespaces/test/pods/pod2/eviction HTTP/1.1 and responded: HTTP/1.1 404 Client Error
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[51073] received request: POST /api/v1/namespaces/ns1/pods/pod2/eviction HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[51073] received request: POST /api/v1/namespaces/ns1/pods/pod3/eviction HTTP/1.1 and responded: HTTP/1.1 429 Client Error
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[51073] received request: POST /api/v1/namespaces/ns1/pods/pod3/eviction HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[51073] received request: POST /api/v1/namespaces/ns1/pods/pod4/eviction HTTP/1.1 and responded: HTTP/1.1 500 Server Error
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[51073] done accepting connections: Socket closed
Jul 17, 2020 3:28:31 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[35113] starting to accept connections
Jul 17, 2020 3:28:46 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[35113] done accepting connections: Socket closed
Jul 17, 2020 3:28:46 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[35113] received request: GET /api/v1/namespaces/test/pods?fieldSelector=metadata.name%3Dpod1&watch=true HTTP/1.1 and responded: HTTP/1.1 101 Switching Protocols
Jul 17, 2020 3:28:46 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[59623] starting to accept connections
Jul 17, 2020 3:28:46 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[59623] done accepting connections: Socket closed
Jul 17, 2020 3:28:46 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[59623] received request: GET /api/v1/namespaces/test/pods/pod1/exec?command=ls&stdout=true HTTP/1.1 and responded: HTTP/1.1 101 Switching Protocols
Jul 17, 2020 3:28:46 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[39825] starting to accept connections
Jul 17, 2020 3:28:46 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[39825] received request: GET /api/v1/namespaces/test/pods HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:47 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[39825] received request: GET /api/v1/namespaces/ns1/pods HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:47 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[39825] received request: GET /api/v1/pods HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:47 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[39825] done accepting connections: Socket closed
Jul 17, 2020 3:28:47 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[42313] starting to accept connections
Jul 17, 2020 3:28:47 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[42313] done accepting connections: Socket closed
Jul 17, 2020 3:28:47 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[36139] starting to accept connections
Jul 17, 2020 3:28:47 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[36139] received request: GET /api/v1/namespaces/test/pods/pod1 HTTP/1.1 and responded: HTTP/1.1 200 OK
[reconnectAttempt|Executor for Watch 138951949] WARN io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Exec Failure
java.io.InterruptedIOException: executor rejected
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:186)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186)
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:137)
	at okhttp3.RealCall.enqueue(RealCall.java:127)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:156)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$1200(WatchConnectionManager.java:50)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2$1.execute(WatchConnectionManager.java:320)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$NamedRunnable.run(WatchConnectionManager.java:409)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@363cc087 rejected from java.util.concurrent.ThreadPoolExecutor@6f5f4b17[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:183)
	... 15 more
[main] WARN io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Failed to close websocket
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[36139] received request: GET /api/v1/namespaces/test/pods?fieldSelector=metadata.name%3Dpod1&resourceVersion=1&watch=true HTTP/1.1 and responded: HTTP/1.1 101 Switching Protocols
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[36139] done accepting connections: Socket closed
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[41813] starting to accept connections
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[41813] received request: DELETE /api/v1/namespaces/test/pods/pod1 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[41813] done accepting connections: Socket closed
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[57479] starting to accept connections
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[57479] done accepting connections: Socket closed
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[59765] starting to accept connections
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[59765] done accepting connections: Socket closed
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[59765] received request: GET /api/v1/namespaces/test/pods/pod1/portforward?ports=123 HTTP/1.1 and responded: HTTP/1.1 101 Switching Protocols
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[55159] starting to accept connections
Jul 17, 2020 3:28:48 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[55159] received request: GET /api/v1/namespaces/test/pods/pod1/portforward?ports=123 HTTP/1.1 and responded: HTTP/1.1 101 Switching Protocols
[reconnectAttempt|Executor for Watch 138951949] WARN io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Exec Failure
java.io.InterruptedIOException: executor rejected
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:186)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186)
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:137)
	at okhttp3.RealCall.enqueue(RealCall.java:127)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:156)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$1200(WatchConnectionManager.java:50)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2$1.execute(WatchConnectionManager.java:320)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$NamedRunnable.run(WatchConnectionManager.java:409)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@79cef3fa rejected from java.util.concurrent.ThreadPoolExecutor@6f5f4b17[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:183)
	... 15 more
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[55159] done accepting connections: Socket closed
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[38191] starting to accept connections
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[38191] received request: DELETE /api/v1/namespaces/test/pods/pod1 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[38191] received request: DELETE /api/v1/namespaces/test/pods/pod2 HTTP/1.1 and responded: HTTP/1.1 404 Client Error
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[38191] received request: DELETE /api/v1/namespaces/ns1/pods/pod2 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[38191] done accepting connections: Socket closed
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[33829] starting to accept connections
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[33829] received request: GET /api/v1/namespaces/test/pods/pod1/log?pretty=true HTTP/1.1 and responded: HTTP/1.1 200 OK
[reconnectAttempt|Executor for Watch 138951949] WARN io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Exec Failure
java.io.InterruptedIOException: executor rejected
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:186)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186)
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:137)
	at okhttp3.RealCall.enqueue(RealCall.java:127)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:156)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$1200(WatchConnectionManager.java:50)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2$1.execute(WatchConnectionManager.java:320)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$NamedRunnable.run(WatchConnectionManager.java:409)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@b446dba rejected from java.util.concurrent.ThreadPoolExecutor@6f5f4b17[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:183)
	... 15 more
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[33829] received request: GET /api/v1/namespaces/test/pods/pod2/log?pretty=false HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[33829] received request: GET /api/v1/namespaces/test/pods/pod3/log?pretty=false&container=cnt3 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[33829] received request: GET /api/v1/namespaces/test4/pods/pod4/log?pretty=true&container=cnt4 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:53 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[33829] received request: GET /api/v1/namespaces/test4/pods/pod1/log?pretty=false&limitBytes=100 HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:54 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[33829] received request: GET /api/v1/namespaces/test5/pods/pod1/log?pretty=false&tailLines=1&timestamps=true HTTP/1.1 and responded: HTTP/1.1 200 OK
Jul 17, 2020 3:28:54 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[33829] done accepting connections: Socket closed
Jul 17, 2020 3:28:54 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[44291] starting to accept connections
Jul 17, 2020 3:28:54 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[44291] received request: GET /api/v1/namespaces/test/pods/pod5/log?pretty=true HTTP/1.1 and responded: HTTP/1.1 404 Client Error
Jul 17, 2020 3:28:54 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[44291] done accepting connections: Socket closed
Jul 17, 2020 3:28:54 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFO: MockWebServer[42125] starting to accept connections
Jul 17, 2020 3:28:54 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFO: MockWebServer[42125] done accepting connections: Socket closed
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.846 s - in io.fabric8.kubernetes.client.mock.PodTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29.831 s
[INFO] Finished at: 2020-07-17T15:28:54+05:30
[INFO] ------------------------------------------------------------------------
```

We need to add `watch.close()` statements in tests whenever watch is used after we're done with watch or maybe wrap it in try-with-resources block like done here:

https://github.com/fabric8io/kubernetes-client/blob/e7980045337c679eb95c7f9b6006ac93adc348a8/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/WatchTest.java#L76-L92

**Comment by Shivkumar13** [comment]
Hi Rohan,

Raised a PR https://github.com/fabric8io/kubernetes-client/pull/2362
