### ISSUE TITLE
Repeated "too old resource version" exception with BaseOperation.waitUntilCondition().

### ISSUE THREAD

**Issue by chrisr3** [fabric8io/kubernetes-client#2414]
We are using `kubernetes-client` 4.10.3. Our test code launches a job and then waits for that job to complete using `waitUntilCondition()`. However, if that job runs for long enough then the `Watch` throws an exception saying "too old resource version".

I understand why this exception happens. My problem is that any attempt to resume waiting by invoking `waitUntilCondition()`  again (after a brief pause) fails immediately with the same exception because _for some unfathomable reason_ the client has tried to recreate the `Watch` with the exact same resource version as before.

```
[2020-08-19T22:36:15.676Z] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 87596480 (87601828)
[2020-08-19T22:36:15.676Z] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 87596480 (87601981)
[2020-08-19T22:36:24.669Z] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 87596480 (87602090)
[2020-08-19T22:36:35.255Z] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 87596480 (87602090)
...
```
I have examined the code in `BaseOperation` and cannot understand why
```java
T item = fromServer().get();
```
isn't fetching the latest version of the named `Job` resource from the server, with the latest resource version inside, and then creating a new `Watch` using that. I can find no evidence that the `KubernetesClient` is caching HTTP responses. I have even tried adding
```
Cache-Control: no-cache
```
custom HTTP headers to the `KubernetesClient` in case our Cloud provider is caching HTTP requests and responses, but to no avail. Can anyone explain what is going wrong please? How can we use `waitUntilCondition()` to resume waiting for the same `Job` (identified by name) but with the latest resource version value?

Thanks for any help,
Cheers,
Chris

Here is a typical exception stack trace:
```
[2020-08-19T22:39:15.325Z] io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
[2020-08-19T22:39:15.325Z] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
[2020-08-19T22:39:15.325Z] 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
[2020-08-19T22:39:15.325Z] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilConditionWithRetries(BaseOperation.java:1128)
[2020-08-19T22:39:15.325Z] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilCondition(BaseOperation.java:1096)
[2020-08-19T22:39:15.325Z] 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.waitUntilCondition(BaseOperation.java:79)
[2020-08-19T22:39:15.325Z] 	at com.r3.testing.KubesTest.waitForJobToComplete(KubesTest.java:1116)
[2020-08-19T22:39:15.325Z] 	at com.r3.testing.KubesTest.runBuildAsJob(KubesTest.java:634)
[2020-08-19T22:39:15.325Z] 	at com.r3.testing.KubesTest.lambda$submitBuild$10(KubesTest.java:523)
[2020-08-19T22:39:15.325Z] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[2020-08-19T22:39:15.326Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2020-08-19T22:39:15.326Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2020-08-19T22:39:15.326Z] 	at java.lang.Thread.run(Thread.java:748)
[2020-08-19T22:39:15.326Z] Caused by: io.fabric8.kubernetes.client.dsl.base.WaitForConditionWatcher$WatchException: Watcher closed
[2020-08-19T22:39:15.326Z] 	at io.fabric8.kubernetes.client.dsl.base.WaitForConditionWatcher.onClose(WaitForConditionWatcher.java:62)
[2020-08-19T22:39:15.326Z] 	at io.fabric8.kubernetes.client.utils.WatcherToggle.onClose(WatcherToggle.java:56)
[2020-08-19T22:39:15.326Z] 	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.closeEvent(WatchConnectionManager.java:366)
[2020-08-19T22:39:15.326Z] 	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$700(WatchConnectionManager.java:50)
[2020-08-19T22:39:15.326Z] 	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:257)
[2020-08-19T22:39:15.326Z] 	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
[2020-08-19T22:39:15.326Z] 	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
[2020-08-19T22:39:15.326Z] 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
[2020-08-19T22:39:15.326Z] 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
[2020-08-19T22:39:15.326Z] 	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
[2020-08-19T22:39:15.326Z] 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
[2020-08-19T22:39:15.326Z] 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
[2020-08-19T22:39:15.326Z] 	... 3 more
[2020-08-19T22:39:15.326Z] Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 87596480 (87602655)
[2020-08-19T22:39:15.326Z] 	... 11 more
```

**Comment by chrisr3** [comment]
OK, I think I understand my problem. I was expecting the `resourceVersion` meta-data field to be updatable, but apparently it isn't. And since the `waitUntilCondition()` function reads the resource version from the `item`, it means that it can _never_ succeed once that resource version has expired. I think this is a bug in `waitUntilCondition()`. I have written a new function that just uses the `WaitForConditionWatcher` instead.
