### ISSUE TITLE
Update namespace - invalid character ',' looking for beginning of value

### ISSUE THREAD

**Issue by sidharthnayyar** [fabric8io/kubernetes-client#2434]
Hi,

I'm trying to update an existing namespace and add a label to it but I get the error:

`Internal error occurred: Internal error occurred: invalid character ',' looking for beginning of value`

The code that I'm using to update the namespace is:

`
            context.getClient()
                    .namespaces()
                    .withName(item.getMetadata().getName())
                    .edit()
                    .editMetadata()
                    .addToLabels("core.k8s/rbac-processed", String.valueOf(true))
                    .endMetadata()
                    .done();
`

`
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://192.168.56.102:8443/api/v1/namespaces/my-k8s-core. Message: Internal error occurred: Internal error occurred: invalid character ',' looking for beginning of value. Received status: Status(apiVersion=v1, code=500, details=StatusDetails(causes=[StatusCause(field=null, message=Internal error occurred: invalid character ',' looking for beginning of value, reason=null, additionalProperties={})], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Internal error occurred: Internal error occurred: invalid character ',' looking for beginning of value, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=InternalError, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568) ~[kubernetes-client-4.10.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507) ~[kubernetes-client-4.10.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471) ~[kubernetes-client-4.10.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430) ~[kubernetes-client-4.10.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:316) ~[kubernetes-client-4.10.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:858) ~[kubernetes-client-4.10.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:132) ~[kubernetes-client-4.10.1.jar:na]
	at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:26) ~[kubernetes-model-core-4.10.1.jar:4.10.1]
	at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:5) ~[kubernetes-model-core-4.10.1.jar:4.10.1]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:138) ~[kubernetes-client-4.10.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$edit$0(HasMetadataOperation.java:46) ~[kubernetes-client-4.10.1.jar:na]
	at io.fabric8.kubernetes.api.model.DoneableNamespace.done(DoneableNamespace.java:26) ~[kubernetes-model-core-4.10.1.jar:4.10.1]
`

Am I doing something wrong or is this a bug? Its an existing namespace and all I'm doing is adding a label to it - which doesn't have ",".

BTW I'm doing this on the controller side of my operator - so I've a got a watch and I get an event when the resource is changed. So I received an HasMetadata resource (which is named "item" above) and I use that to get the namespace, edit it, edit metadata and then add a label to it.

Thanks!

**Comment by rohanKanojia** [comment]
somehow I'm not able to reproduce this issue, I tried testing on minikube v1.12.2 but for me, label gets added without any problem.

**Comment by sidharthnayyar** [comment]
Hi Rohan,
Yes it looks like another issue was causing it but the exception was thrown on the namespace update which threw me off.
Thanks for your help.
Kind regards
