### ISSUE TITLE
NPE received during createOrReplace for new Service resource

### ISSUE THREAD

**Issue by k-wall** [fabric8io/kubernetes-client#2511]
I have a multi threaded application which creates a large number of services.  Very occasionally I see the code fail with a NPE.  The code seems to be erroneously following the replace path even though the object is new.

version: 4.10.3

Is this a recognised defect?

```
Caused by: java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.ServiceOperationsImpl.replace(ServiceOperationsImpl.java:65) ~[kubernetes-client-4.10.3.jar:?]
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.ServiceOperationsImpl.replace(ServiceOperationsImpl.java:37) ~[kubernetes-client-4.10.3.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:415) ~[kubernetes-client-4.10.3.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:79) ~[kubernetes-client-4.10.3.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:410) ~[kubernetes-client-4.10.3.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:79) ~[kubernetes-client-4.10.3.jar:?]
	at io.kafka.performance.k8s.KubeClient.createOrReplaceService(KubeClient.java:506) ~[classes/:?]
	at io.kafka.performance.OMB.createWorker(OMB.java:208) ~[classes/:?]
	at io.kafka.performance.OMB.lambda$deployWorkers$0(OMB.java:107) ~[classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
```

**Comment by k-wall** [comment]
Pardon, this was my own defect in my own code.
