### ISSUE TITLE
Jenkins WatchConnectionManager RejectedExecutionException

### ISSUE THREAD

**Issue by Philippe-Bailer-ck** [fabric8io/kubernetes-client#2575]
I'm seeing repetitive error logs around WatchConnectionManager

```
2020-10-26 12:18:18.274+0000 [id=185]	WARNING	i.f.k.c.d.i.WatchConnectionManager$1#onFailure: Exec Failure
java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@844a86 rejected from java.util.concurrent.ThreadPoolExecutor@49723d6a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 41]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:183)
Caused: java.io.InterruptedIOException: executor rejected
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:186)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186)
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:137)
	at okhttp3.RealCall.enqueue(RealCall.java:127)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:156)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$1200(WatchConnectionManager.java:50)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2$1.execute(WatchConnectionManager.java:320)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$NamedRunnable.run(WatchConnectionManager.java:409)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The exact same log, same id, same ThreadPoolExecutor@49723d6a for over 20k events. I'm not sure whats going on but our jenkins seems to be working fine generally. We are having some stability issues were jobs die in the middle randomly but I'm not sure this is to blame as this is not a one to one occurrence with the failed jobs.

In the last 2 weeks we've had about 7 of these warns and 4 of them went turned into repeating events, most of them stop repeating after about 2000 but one of them lasted several days and hit 22k.

I'm not sure if there is anything for me to fix here as this seems like a malfunctioning queue but any guidance would be appreciated.

**Comment by seglo** [comment]
Version: `4.12.0`

We're experiencing this issue in our project when running tests from an sbt session (a JVM project build tool often used in Scala projects).  We have a test that exercises an `SharedIndexInformer` with a `KubernetesServer` in CRUD mode. A `WatchConnectionManager` is spawned at some point by the informer (in the `ListWatcher` I think?), but it's never explicitly closed by calling [`WatchConnectionManager.close()`](https://javadoc.io/static/io.fabric8/kubernetes-client/4.12.0/io/fabric8/kubernetes/client/dsl/internal/WatchConnectionManager.html#close--).  In situations where the test process isn't shutdown after a test run (i.e. in sbt's REPL) we will see this exception repeat continuously.

I couldn't find a way to close this `Watch` from the existing informer API.

```
info] Run completed in 2 seconds, 11 milliseconds.                                                                                                                                                            
[info] Total number of tests run: 3                                                                                                                                                                            
[info] Suites: completed 1, aborted 0                                                                                                                                                                          
[info] Tests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0                                                                                                                                          
[info] All tests passed.                                                                                                                                                                                       
[success] Total time: 6 s, completed Nov. 2, 2020, 4:27:53 p.m.                                                                                                                                                
[2020-11-02 16:27:54,626] [DEBUG] [io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager] [] - Connecting websocket ... io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@5f02f5a4   
[2020-11-02 16:27:54,627] [WARN] [io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager] [] - Exec Failure                                                                                          
java.io.InterruptedIOException: executor rejected                                                                                                                                                              
        at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:186)                                                                                                                                             
        at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186)                                                                                                                                           
        at okhttp3.Dispatcher.enqueue(Dispatcher.java:137)                                                                                                                                                     
        at okhttp3.RealCall.enqueue(RealCall.java:127)                                                                                                                                                         
        at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193)                                                                                                                                   
        at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)                                                                                                                                            
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:156)                                                                                          
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$1200(WatchConnectionManager.java:50)                                                                                        
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2$1.execute(WatchConnectionManager.java:321)                                                                                       
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$NamedRunnable.run(WatchConnectionManager.java:410)                                                                                 
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)                                                                                                                   
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                                                  
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)                                                                            
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)                                                                                                           
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                                                                                                           
        at java.base/java.lang.Thread.run(Thread.java:834)                                                                                                                                                     
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@65ae9985 rejected from java.util.concurrent.ThreadPoolExecutor@499d130e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
        at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:183)
        ... 15 common frames omitted
[2020-11-02 16:27:54,628] [DEBUG] [io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager] [] - Submitting reconnect task to the executor
[2020-11-02 16:27:54,628] [DEBUG] [io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager] [] - Scheduling reconnect task
[2020-11-02 16:27:54,628] [DEBUG] [io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager] [] - Current reconnect backoff is 2000 milliseconds (T1)
[2020-11-02 16:27:56,629] [DEBUG] [io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager] [] - Connecting websocket ... io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@5f02f5a4
[2020-11-02 16:27:56,630] [WARN] [io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager] [] - Exec Failure
java.io.InterruptedIOException: executor rejected
        at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:186)
        at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186)
        at okhttp3.Dispatcher.enqueue(Dispatcher.java:137)
        at okhttp3.RealCall.enqueue(RealCall.java:127)
        at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193)
        at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:156)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$1200(WatchConnectionManager.java:50)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2$1.execute(WatchConnectionManager.java:321)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$NamedRunnable.run(WatchConnectionManager.java:410)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@1df67fba rejected from java.util.concurrent.ThreadPoolExecutor@499d130e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
        at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:183)
        ... 15 common frames omitted

...
```
