### ISSUE TITLE
watchLog outputstream fails with java.io.InterruptedIOException: executor rejected

### ISSUE THREAD

**Issue by PrakashNair** [fabric8io/kubernetes-client#2577]
While processing async request via StreamingResponseBody, the watchlog fails with below exception

```
	java.io.InterruptedIOException: executor rejected
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:157) ~[okhttp-3.14.7.jar:na]
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:204) [okhttp-3.14.7.jar:na]
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:144) [okhttp-3.14.7.jar:na]
	at okhttp3.RealCall.enqueue(RealCall.java:93) [okhttp-3.14.7.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.watchLog(PodOperationsImpl.java:228) [kubernetes-client-4.11.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.watchLog(PodOperationsImpl.java:83) [kubernetes-client-4.11.1.jar:na]
	at com.example.demo.PostProcessEngine.lambda$export$0(PostProcessEngine.java:40) [classes/:na]
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:111) ~[spring-webmvc-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:98) ~[spring-webmvc-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:328) ~[spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@15385485 rejected from java.util.concurrent.ThreadPoolExecutor@64f0a773[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[na:1.8.0_91]
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:154) ~[okhttp-3.14.7.jar:na]
	... 14 common frames omitted
```

Code snippet for the same:

```
   @RequestMapping(value = "/podlogs", method = RequestMethod.GET)
    @ResponseBody
    public ResponseEntity<StreamingResponseBody> podLogs() {

        try (KubernetesClient client = new DefaultKubernetesClient()) {
            ...

            StreamingResponseBody responseBody = outputStream -> client.pods().inNamespace("namespace-test")
                    .withName("busybox")
                    .watchLog(outputStream);

           ...

            return ResponseEntity.ok()
                    .contentType(MediaType.APPLICATION_OCTET_STREAM)
                    .body(responseBody);

        } catch (KubernetesClientException ex) {
          ...
        }
    }
```

The code works fine if I switch it to `getLog()` and `String`.

**Comment by PrakashNair** [comment]
This now stands resolved. Below solution works just fine.

```
StreamingResponseBody responseBody = new StreamingResponseBody() {
            @Override
            public void writeTo(OutputStream out) throws IOException {

                try (KubernetesClient client = new DefaultKubernetesClient()) {

                    client.pods().inNamespace("namespace-test")
                            .withName("busybox")
                            .watchLog(out);
                   .... 
                    out.flush();
                } catch (KubernetesClientException ex) {
                         ...
                } catch (InterruptedException e) {
                    .....
                }
            }
```
