### ISSUE TITLE
ConcurrentModificationException in KubernetesCrudDispatcher

### ISSUE THREAD

**Issue by patriknw** [fabric8io/kubernetes-client#2592]
Version: 4.12.0

We have some tests that are using crud mode of the KubernetesMockServer. It's using the client from several threads so there can be concurrent requests.

```
2020-11-05T21:23:48.8345479Z [2020-11-05 21:23:38,807] [ERROR] [okhttp3.mockwebserver.MockWebServer] [] - MockWebServer[56575] connection from /127.0.0.1 crashed
2020-11-05T21:23:48.8346602Z java.util.ConcurrentModificationException: null
2020-11-05T21:23:48.8347653Z  at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1751)
2020-11-05T21:23:48.8348861Z  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2020-11-05T21:23:48.8350319Z  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2020-11-05T21:23:48.8351739Z  at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2020-11-05T21:23:48.8353089Z  at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2020-11-05T21:23:48.8354162Z  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2020-11-05T21:23:48.8356613Z  at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
2020-11-05T21:23:48.8358470Z  at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.handleGet(KubernetesCrudDispatcher.java:126)
2020-11-05T21:23:48.8360972Z  at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.dispatch(KubernetesCrudDispatcher.java:80)
2020-11-05T21:23:48.8362688Z  at okhttp3.mockwebserver.MockWebServer$3.processOneRequest(MockWebServer.java:558)
2020-11-05T21:23:48.8363728Z  at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:516)
2020-11-05T21:23:48.8364690Z  at okhttp3.mockwebserver.MockWebServer$3.execute(MockWebServer.java:443)
2020-11-05T21:23:48.8365560Z  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
2020-11-05T21:23:48.8473670Z  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-05T21:23:48.8475170Z  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-05T21:23:48.8476137Z  at java.base/java.lang.Thread.run(Thread.java:834)
```

I suggest that the methods (dispatch, peek, shutdown) of `KubernetesCrudDispatcher` are made `synchronized` or making the access to the `map` thread safe in some other way.

**Comment by rohanKanojia** [comment]
@patriknw : Thanks a lot for reporting this. We're planning to cut a release soon within 1-2 weeks. Would really appreciate if you could create a quick PR to fix this issue..

**Comment by patriknw** [comment]
Sure, I'll do that.
