### ISSUE TITLE
SharedInformers are not correctly filtering by namespace

### ISSUE THREAD

**Issue by jonathanvila** [fabric8io/kubernetes-client#2619]
Using informers and constraining by namespace I still receive this issue : 
```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/windup.jboss.org/v1/windups. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. windups.windup.jboss.org is forbidden: User "system:serviceaccount:mta:windup-operator" cannot list resource "windups" in API group "windup.jboss.org" at the cluster scope.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:589)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:526)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:492)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:451)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:433)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:160)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:673)
	at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:161)
```

This is the code:
```java
        OperationContext operationContext = new OperationContext().withNamespace(NAMESPACE);
        SharedInformerFactory informersFactory = k8Client.informers(); 
        informersFactory.sharedIndexInformerForCustomResource(crdContext, 
                  WindupResource.class, 
                  WindupResourceList.class, 
                  operationContext, 
                  resyncPeriodInMillis)
            .addEventHandler(windupController);
```

The serviceaccount has namespace access, and it has to be this way.
Changed to watchers as a workaround.

Using Quarkus 1.9.0 Kubernetes client.

**Comment by michaeljohnalbers** [comment]
I'm seeing this problem, too. Using 4.13.0 of the client library with a 1.17 Kubernetes cluster.

**Comment by rohanKanojia** [comment]
@jonathanvila @michaeljohnalbers : Is this still an issue with latest release of client?

**Comment by shawkins** [comment]
This can be marked as out of date based upon #3239 - we don't want direct usage of the OperationContext for the factory. In this specific issue there was likely some problem with needing to also set withNamespaceFromGlobalConfig(false).
