### ISSUE TITLE
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:helm.fluxcd.io/v1#HelmRelease at [Source: (BufferedInputStream); line: 1, column: 1757] (through reference chain: io.fabric8.kubernetes.api.model.WatchEvent["object"])

### ISSUE THREAD

**Issue by acmlearn** [fabric8io/kubernetes-client#2625]
I have an application for which I am trying to add SharedIndexInformer to watch for events for the helm releases custom resource and I have followed https://github.com/rohanKanojia/kubernetes-client-demo/blob/master/src/main/java/io/fabric8/CustomResourceInformerDemo.java and added all the necessary classes for my project based on CronTab classes example (CronTab, CronTabList, CronTabSpec, CronTabStatus). I have also added the required fields to the new classes. Now when I run the application in docker-desktop, the logs is spammed with below exceptions. I am using kubernetes-client - 4.12.0. Any idea what I might be missing. 

The error can be reproduced using the project: https://github.com/acmlearn/fabric8crd/tree/main/src/main/java/com/example/fabric8crd
Follow the steps from the readme file at https://github.com/acmlearn/fabric8crd/blob/main/README.md

Errors found in the log:
```
2020-11-23 02:01:33.082 WARN 1 --- [//10.96.0.1/...] i.f.k.c.d.i.WatchConnectionManager : Exec Failure
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[kubernetes-client-4.12.0.jar!/:na]
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[kubernetes-client-4.12.0.jar!/:na]
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:249) ~[kubernetes-client-4.12.0.jar!/:na]
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:168) ~[kubernetes-client-4.12.0.jar!/:na]
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:153) ~[kubernetes-client-4.12.0.jar!/:na]
at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager.readWatchEvent(WatchHTTPManager.java:292) ~[kubernetes-client-4.12.0.jar!/:na]
at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:228) ~[kubernetes-client-4.12.0.jar!/:na]
at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322) ~[okhttp-3.14.6.jar!/:na]
at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) ~[okhttp-3.14.6.jar!/:na]
at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) ~[okhttp-3.14.6.jar!/:na]
at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) ~[okhttp-3.14.6.jar!/:na]
at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209) ~[okhttp-3.14.6.jar!/:na]
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) [okhttp-3.14.6.jar!/:na]
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.14.6.jar!/:na]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_252]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_252]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:helm.fluxcd.io/v1#HelmRelease
at [Source: (BufferedInputStream); line: 1, column: 1757] (through reference chain: io.fabric8.kubernetes.api.model.WatchEvent["object"])
at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:271) ~[jackson-databind-2.10.2.jar!/:2.10.2]
at io.fabric8.kubernetes.internal.KubernetesDeserializer.fromObjectNode(KubernetesDeserializer.java:85) ~[kubernetes-model-core-4.12.0.jar!/:4.12.0]
at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:57) ~[kubernetes-model-core-4.12.0.jar!/:4.12.0]
at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:46) ~[kubernetes-model-core-4.12.0.jar!/:4.12.0]
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.10.2.jar!/:2.10.2]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.10.2.jar!/:2.10.2]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar!/:2.10.2]
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202) ~[jackson-databind-2.10.2.jar!/:2.10.2]
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3250) ~[jackson-databind-2.10.2.jar!/:2.10.2]
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:247) ~[kubernetes-client-4.12.0.jar!/:na]
... 14 common frames omitted
```

**Comment by manusa** [comment]
You probably need to register your Custom Resource classes to be able to use deserialization:

https://github.com/fabric8io/kubernetes-client/blob/bddc79e8c04551737dc4565d81f92e5450d15aa5/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java#L132

**Comment by acmlearn** [comment]
Thank you @manusa , it worked for me.
