### ISSUE TITLE
io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize java.lang.StackOverflowError

### ISSUE THREAD

**Issue by ashishkshukla** [fabric8io/kubernetes-client#2697]
I am working on a spring based project and  getting below exception while creating deployments in k8s-
below is the code snippet-

`kubernetesClient.apps().deployments().create(deploymentObj);`

below is the exception-

  ```
org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is 
  java.lang.StackOverflowError
        at org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1280)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:958)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
-
-
-
-
Caused by: java.lang.StackOverflowError
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:249)
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:437)
        at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:261)
       at com.fasterxml.jackson.databindshaded.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databindshaded.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databindshaded.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databindshaded.ObjectMapper._readValue(ObjectMapper.java:4495)
        at com.fasterxml.jackson.databindshaded.ObjectMapper.readTree(ObjectMapper.java:2838)
        at com.fasterxml.jackson.coreshaded.JsonParser.readValueAsTree(JsonParser.java:1829)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:55)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:46)
        at com.fasterxml.jackson.databindshaded.ObjectMapper._readValue(ObjectMapper.java:4495)
        at com.fasterxml.jackson.databindshaded.ObjectMapper.readValue(ObjectMapper.java:2728)
        at com.fasterxml.jackson.databindshaded.ObjectMapper.treeToValue(ObjectMapper.java:3181)
        at io.fabric8.kubernetes.internal.KubernetesDeserializer.fromObjectNode(KubernetesDeserializer.java:87)
```

Can someone help me on this please.

**Comment by ashishkshukla** [comment]
help is required.

**Comment by rohanKanojia** [comment]
@ashishkshukla : Hi, Do you have any reproducer project which we can use to reproduce this issue? However, I'm not really sure if your issue is caused by client since we have a test to verify create:
https://github.com/fabric8io/kubernetes-client/blob/6a717e44e0600358068d87cc60628863a117f7f8/kubernetes-tests/src/test/java/io/fabric8/kubernetes/client/mock/DeploymentTest.java#L435-L450

**Comment by manusa** [comment]
The exception looks like one of the fields might be referring to a parent field and deserialization runs into an infinite loop.

However, this should not be possible when retrieving data from the server (you can force something like this if you manually instantiate a Model object though).

As Rohan says, we need something to reproduce. If it's the case that this happens while retrieving a deployment from the cluster, please share the YAML of that deployment (`kubectl get deployments.apps your-deployment -o yaml`)

**Comment by ashishkshukla** [comment]
ok. Let me check.
