### ISSUE TITLE
Raw CustomResource API: Unable to edit CustomResource via InputStream

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#2717]
let's say I have a CustomResource `Dummy` present in my kubernetes cluster like this:
```
jkube : $ kubectl get dummies
NAME           AGE
first-dummy    20m
second-dummy   20m
```
If I try to edit `first-dummy` by providing contents via an `InputStream` like this:
```java
try (KubernetesClient client = new DefaultKubernetesClient()) {
    CustomResourceDefinitionContext context = new CustomResourceDefinitionContext.Builder()
            .withGroup("demo.fabric8.io")
            .withVersion("v1")
            .withScope("Namespaced")
            .withPlural("dummies")
            .build();
    InputStream crInputStream = RawCustomResourceEdit.class.getResourceAsStream("/dummy-cr.yml");

    client.customResource(context).edit("default", "first-dummy", crInputStream);
}
```
I'm getting this error:
```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://192.168.39.3:8443/apis/demo.fabric8.io/v1/namespaces/default/dummies/first-dummy. Message: dummies.demo.fabric8.io "first-dummy" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.resourceVersion, message=Invalid value: 0x0: must be specified for an update, reason=FieldValueInvalid, additionalProperties={})], group=demo.fabric8.io, kind=dummies, name=first-dummy, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=dummies.demo.fabric8.io "first-dummy" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.makeCall(RawCustomResourceOperationsImpl.java:800)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.validateAndSubmitRequest(RawCustomResourceOperationsImpl.java:815)
	at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl.validateAndSubmitRequest(RawCustomResourceOperationsImpl.java:808)
```

I don't face this error when providing the edited resource as a string or Hashmap.

**Comment by manusa** [comment]
Your code is not describing an edit procedure but a **replacement** procedure.

What you are expecting (if I'm not mistaken) is that the client gets the resource defined in your YAML and **replaces** the one in the cluster.

What I see is that this operation should either not be allowed, or perform a diff operation on both resources.

The outcome of this issue should either be:

A) Remove these methods where I accept an InputStream as an argument to the edit methods.

B) Create some sort of logic that will retrieve the edited resource from the cluster, and a merge operation will be performed with the resource loaded from the local YAML. Fields defined in the local YAML should prevail on top of those existent in the cluster defined resource.

**Comment by rohanKanojia** [comment]
I think we can cover B separately by providing better patching support https://github.com/fabric8io/kubernetes-client/issues/2645
