### ISSUE TITLE
[k8s 1.19.5]Exec Failure (io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager:205)

### ISSUE THREAD

**Issue by echang0929** [fabric8io/kubernetes-client#2727]
When I run spark job on Kubernetes 1.19.5, got the following WARN:
```
[2021-01-17 15:57:19,033] WARN Exec Failure (io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager:205)
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2021-01-17 15:57:20,215] WARN Kubernetes client has been closed (this is expected if the application is shutting down.) (org.apache.spark.scheduler.cluster.k8s.ExecutorPodsWatchSnapshotSource:90)
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 345010054 (345014516)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:258)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
My Spark version is spark-3.0.1-bin-hadoop3.2. In order to match compatibility, I have upgraded all kubernetes related jars of Spark into version 4.13.0:
```
kubernetes-client-4.13.0.jar
kubernetes-model-4.13.0.jar
kubernetes-model-admissionregistration-4.13.0.jar
kubernetes-model-apiextensions-4.13.0.jar
kubernetes-model-apps-4.13.0.jar
kubernetes-model-autoscaling-4.13.0.jar
kubernetes-model-batch-4.13.0.jar
kubernetes-model-certificates-4.13.0.jar
kubernetes-model-common-4.13.0.jar
kubernetes-model-coordination-4.13.0.jar
kubernetes-model-core-4.13.0.jar
kubernetes-model-discovery-4.13.0.jar
kubernetes-model-events-4.13.0.jar
kubernetes-model-extensions-4.13.0.jar
kubernetes-model-metrics-4.13.0.jar
kubernetes-model-networking-4.13.0.jar
kubernetes-model-node-4.13.0.jar
kubernetes-model-policy-4.13.0.jar
kubernetes-model-rbac-4.13.0.jar
kubernetes-model-scheduling-4.13.0.jar
kubernetes-model-settings-4.13.0.jar
kubernetes-model-storageclass-4.13.0.jar
```

Do you think there are compatibility problems yet? How to fix it? Thanks

**Comment by rohanKanojia** [comment]
I think this is due to limitation of watcher. We should either reconnect on getting 410 or use informers[0] in spark code(which already seem to have reconnect logic)

[0] https://issues.apache.org/jira/browse/SPARK-33737
