### ISSUE TITLE
JsonMappingException while loading yaml Kafka configuration

### ISSUE THREAD

**Issue by aarexer** [fabric8io/kubernetes-client#2928]
Hello!
I have a problem with kubernetes-client using.

What i want: Creating Kafka cluster with Strimzi operator in Kubernetes.
If i do all steps from [Strimzi quickstart guide](https://strimzi.io/docs/operators/latest/quickstart.html) with CLI and kubectl it's all good.

But when i load yaml resources with `kubernetes-client:5.2.1` library from Java code, there is an Exception occurs:

```java
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
  at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
  at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
  at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:140)
  at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:101)
  at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:272)
  at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:252)
  at io.fabric8.kubernetes.client.DefaultKubernetesClient$1.<init>(DefaultKubernetesClient.java:175)
  at io.fabric8.kubernetes.client.DefaultKubernetesClient.load(DefaultKubernetesClient.java:175)
  at app.test.main(test.java:38)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:kafka.strimzi.io/v1#Kafka
 at [Source: (String)"{"apiVersion":"kafka.strimzi.io/v1","kind":"Kafka","metadata":{"name":"my-cluster"},"spec":{"kafka":{"replicas":1,"listeners":[{"name":"plain","port":9092,"type":"internal","tls":false},{"name":"tls","port":9093,"type":"internal","tls":true,"authentication":{"type":"tls"}},{"name":"external","port":9094,"type":"nodeport","tls":false}],"storage":{"type":"jbod","volumes":[{"id":0,"type":"persistent-claim","size":"1Gi","deleteClaim":false}]},"config":{"offsets.topic.replication.factor":1,"transacti"[truncated 226 chars]; line: 1, column: 726]
 ```

Problem occurs when i load this file: [yaml config](https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/kafka/kafka-ephemeral.yaml).

I load resource like:
```java
 KubernetesClient client = new DefaultKubernetesClient();
InputStream is = ...;
client.load(is).inNamespace("my_namespace").createOrReplace();
```

Please help me!

P.S: And sorry for my English.

**Comment by rohanKanojia** [comment]
Hi, Kafka seems to be a Custom Resource. Please check our guides for using CustomResources and see if it helps

[0] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typed-api
[1] https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api

**Comment by rohanKanojia** [comment]
I think you should be able to do it like this:
```java
     CustomResourceDefinitionContext crdContext = new CustomResourceDefinitionContext.Builder()
                    .withGroup("kafka.strimzi.io")
                    .withVersion("v1")
                    .withScope("Namespaced")
                    .withPlural("kafkas")
                    .build();
      client.customResource(crdContext).inNamespace("my_namespace").createOrReplace(is);
```

**Comment by aarexer** [comment]
Yes, it works fine!
It's good solution!
