### ISSUE TITLE
Concurrency issues when using SharedInformers and closing the KubernetesClient

### ISSUE THREAD

**Issue by hanikesn** [fabric8io/kubernetes-client#2939]
There seem to be concurrency issues when calling `stopAllRegisteredInformers` and directly afterwards calling `close` on the Kubernetes client itself. This is just one example:

```
java.io.InterruptedIOException: executor rejected
	at okhttp3.internal.connection.RealCall$AsyncCall.executeOn(RealCall.kt:501)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.kt:184)
	at okhttp3.Dispatcher.enqueue$okhttp(Dispatcher.kt:125)
	at okhttp3.internal.connection.RealCall.enqueue(RealCall.kt:164)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.kt:165)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.kt:281)
	at io.fabric8.kubernetes.client.dsl.internal.WebSocketClientRunner.run(WebSocketClientRunner.java:38)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.runWatch(AbstractWatchManager.java:160)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener$1$1.execute(WatcherWebSocketListener.java:174)
	at io.fabric8.kubernetes.client.dsl.internal.NamedRunnable.run(NamedRunnable.java:39)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.connection.RealCall$AsyncCall@66693bf6 rejected from java.util.concurrent.ThreadPoolExecutor@7381ab5d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at okhttp3.internal.connection.RealCall$AsyncCall.executeOn(RealCall.kt:498)
	... 15 common frames omitted
```

Anonther time the following happened:

```
[informer-controller-Node] INFO io.fabric8.kubernetes.client.informers.cache.Controller - informer#Controller: ready to run resync and reflector runnable
[informer-controller-Endpoints] INFO io.fabric8.kubernetes.client.informers.cache.Controller - informer#Controller: ready to run resync and reflector runnable
[informer-controller-Endpoints] INFO io.fabric8.kubernetes.client.informers.cache.Reflector - Started ReflectorRunnable watch for class io.fabric8.kubernetes.api.model.Endpoints
[informer-controller-Node] INFO io.fabric8.kubernetes.client.informers.cache.Reflector - Started ReflectorRunnable watch for class io.fabric8.kubernetes.api.model.Node
[pool-1-thread-1] WARN io.fabric8.kubernetes.client.informers.cache.ProcessorListener - Processor thread interrupted: null
[informer-controller-Endpoints] WARN io.fabric8.kubernetes.client.informers.cache.Controller - Reflector list-watching job exiting because the thread-pool is shutting down
[informer-controller-Node] WARN io.fabric8.kubernetes.client.informers.cache.Controller - Reflector list-watching job exiting because the thread-pool is shutting down
java.util.concurrent.RejectedExecutionException: Error while starting ReflectorRunnable watch
	at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:89)
	at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:109)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Error while doing ReflectorRunnable list
	at io.fabric8.kubernetes.client.informers.cache.Reflector.getList(Reflector.java:77)
	at io.fabric8.kubernetes.client.informers.cache.Reflector.reListAndSync(Reflector.java:102)
	at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:84)
	... 2 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Node]  with name: [null]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:168)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:664)
	at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:246)
	at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:241)
	at io.fabric8.kubernetes.client.informers.cache.Reflector.getList(Reflector.java:71)
	... 4 more
Caused by: java.io.InterruptedIOException
	at okhttp3.internal.http2.Http2Stream.waitForIo$okhttp(Http2Stream.kt:662)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:140)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:282)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:485)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:448)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:431)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:161)
	... 8 more
java.util.concurrent.RejectedExecutionException: Error while starting ReflectorRunnable watch
	at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:89)
	at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:109)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Error while doing ReflectorRunnable list
	at io.fabric8.kubernetes.client.informers.cache.Reflector.getList(Reflector.java:77)
	at io.fabric8.kubernetes.client.informers.cache.Reflector.reListAndSync(Reflector.java:102)
	at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:84)
	... 2 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Endpoints]  with name: [null]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:168)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:664)
	at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:246)
	at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:241)
	at io.fabric8.kubernetes.client.informers.cache.Reflector.getList(Reflector.java:71)
	... 4 more
Caused by: java.io.InterruptedIOException
	at okhttp3.internal.http2.Http2Stream.waitForIo$okhttp(Http2Stream.kt:662)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:140)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:282)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:485)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:448)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:431)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:161)
	... 8 more
```

**Comment by hanikesn** [comment]
I modified the code not not close the kubernetes client and it seems that the watches are still active after calling `stopAllRegisteredInformers`:

```
W0322 13:38:23.545000 0 0] [i.f.k.c.i.c.ProcessorListener] Processor thread interrupted: null [pool-7-thread-1]
W0322 13:38:23.547000 0 0] [i.f.k.c.i.c.Controller] DefaultController#processLoop got interrupted null [informer-controller-Endpoints]
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1627)
	at io.fabric8.kubernetes.client.informers.cache.DeltaFIFO.pop(DeltaFIFO.java:322)
	at io.fabric8.kubernetes.client.informers.cache.Controller.processLoop(Controller.java:158)
	at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:112)
	at java.base/java.lang.Thread.run(Thread.java:832)
W0322 13:38:23.547000 0 0] [i.f.k.c.i.c.Controller] DefaultController#processLoop got interrupted null [informer-controller-Node]
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1627)
	at io.fabric8.kubernetes.client.informers.cache.DeltaFIFO.pop(DeltaFIFO.java:322)
	at io.fabric8.kubernetes.client.informers.cache.Controller.processLoop(Controller.java:158)
	at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:112)
	at java.base/java.lang.Thread.run(Thread.java:832)
D0322 13:39:22.988000 0 0] [i.f.k.c.i.ResyncRunnable] ResyncRunnable#resync .. .. [pool-9-thread-1]
D0322 13:39:23.506000 0 0] [i.f.k.c.i.c.Reflector] Listing items (1) for resource class io.fabric8.kubernetes.api.model.Endpoints v750373335 [pool-10-thread-1]
D0322 13:42:03.949000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Socket closing:  [OkHttp https://10.130.16.1/...]
D0322 13:42:03.950000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] WebSocket close received. code: 1000, reason:  [OkHttp WebSocket https://10.130.16.1/... writer]
D0322 13:42:03.951000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Submitting reconnect task to the executor [OkHttp WebSocket https://10.130.16.1/... writer]
D0322 13:42:03.951000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Scheduling reconnect task [scheduleReconnect|Executor for Watch 1196526679]
D0322 13:42:03.952000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Current reconnect backoff is 1000 milliseconds (T0) [scheduleReconnect|Executor for Watch 1196526679]
D0322 13:42:04.952000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Watching https://10.130.16.1/api/v1/nodes?resourceVersion=750375823&watch=true... [reconnectAttempt|Executor for Watch 1196526679]
D0322 13:42:05.010000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] WebSocket successfully opened [OkHttp https://10.130.16.1/...]
D0322 13:43:22.987000 0 0] [i.f.k.c.i.ResyncRunnable] ResyncRunnable#resync .. .. [pool-13-thread-1]
D0322 13:43:23.509000 0 0] [i.f.k.c.i.c.Reflector] Listing items (31) for resource class io.fabric8.kubernetes.api.model.Node v750377306 [pool-14-thread-1]
D0322 13:56:45.659000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Socket closing:  [OkHttp https://10.130.16.1/...]
D0322 13:56:45.660000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] WebSocket close received. code: 1000, reason:  [OkHttp WebSocket https://10.130.16.1/... writer]
D0322 13:56:45.660000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Submitting reconnect task to the executor [OkHttp WebSocket https://10.130.16.1/... writer]
D0322 13:56:45.661000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Scheduling reconnect task [scheduleReconnect|Executor for Watch 2110676876]
D0322 13:56:45.661000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Current reconnect backoff is 1000 milliseconds (T0) [scheduleReconnect|Executor for Watch 2110676876]
D0322 13:56:46.662000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Watching https://10.130.16.1/api/v1/namespaces/steffen-resolver/endpoints?fieldSelector=metadata.name%3Dmantis-worker-partition-osm-us-ca-sf-bay-area&resourceVersion=750342380&watch=true... [reconnectAttempt|Executor for Watch 2110676876]
D0322 13:56:46.718000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] WebSocket successfully opened [OkHttp https://10.130.16.1/...]
E0322 13:56:46.723000 0 0] [i.f.k.c.i.c.ReflectorWatcher] Watch closing [OkHttp https://10.130.16.1/...]
D0322 13:56:46.780000 0 0] [i.f.k.c.i.c.Reflector] Listing items (1) for resource class io.fabric8.kubernetes.api.model.Endpoints v750390686 [OkHttp https://10.130.16.1/...]
D0322 13:56:46.780000 0 0] [i.f.k.c.i.c.Reflector] Starting watcher for resource class io.fabric8.kubernetes.api.model.Endpoints v750390686 [OkHttp https://10.130.16.1/...]
D0322 13:56:46.780000 0 0] [i.f.k.c.i.c.Reflector] Stopping previous watcher [OkHttp https://10.130.16.1/...]
D0322 13:56:46.780000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Force closing the watch io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@7dce5f8c [OkHttp https://10.130.16.1/...]
D0322 13:56:46.780000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Ignoring duplicate firing of onClose event [OkHttp https://10.130.16.1/...]
D0322 13:56:46.780000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Closing ExecutorService [OkHttp https://10.130.16.1/...]
D0322 13:56:46.781000 0 0] [i.f.k.c.i.c.Reflector] Watcher already started, delaying execution of new watcher [OkHttp https://10.130.16.1/...]
D0322 13:56:51.781000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Force closing the watch io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@7dce5f8c [OkHttp https://10.130.16.1/...]
D0322 13:56:51.781000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Ignoring duplicate firing of onClose event [OkHttp https://10.130.16.1/...]
D0322 13:56:51.781000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Socket closing:  [OkHttp https://10.130.16.1/...]
D0322 13:56:51.782000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] WebSocket close received. code: 1000, reason:  [OkHttp WebSocket https://10.130.16.1/... writer]
D0322 13:56:51.782000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Ignoring onClose for already closed/closing websocket [OkHttp WebSocket https://10.130.16.1/... writer]
D0322 14:32:00.792000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Socket closing:  [OkHttp https://10.130.16.1/...]
D0322 14:32:00.793000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] WebSocket close received. code: 1000, reason:  [OkHttp WebSocket https://10.130.16.1/... writer]
D0322 14:32:00.793000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Submitting reconnect task to the executor [OkHttp WebSocket https://10.130.16.1/... writer]
D0322 14:32:00.793000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] Scheduling reconnect task [scheduleReconnect|Executor for Watch 1196526679]
D0322 14:32:00.794000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Current reconnect backoff is 1000 milliseconds (T0) [scheduleReconnect|Executor for Watch 1196526679]
D0322 14:32:01.794000 0 0] [i.f.k.c.d.i.AbstractWatchManager] Watching https://10.130.16.1/api/v1/nodes?resourceVersion=750425855&watch=true... [reconnectAttempt|Executor for Watch 1196526679]
D0322 14:32:01.849000 0 0] [i.f.k.c.d.i.WatcherWebSocketListener] WebSocket successfully opened [OkHttp https://10.130.16.1/...]
```

**Comment by akram** [comment]
@hanikesn can you PTAL at #3029 ? 
I wonder if you were not hitting that issue.

**Comment by shawkins** [comment]
I'd say this can be marked as resolved based upon all of the informer related changes in 5.3 - 5.5.

**Comment by hanikesn** [comment]
I agree, will test everything with the new changes at a later point in time.
