### ISSUE TITLE
With wrong CA certificate kubernetes client is able to get pod list

### ISSUE THREAD

**Issue by vishal549** [fabric8io/kubernetes-client#2945]
Below code is responsible to get pod list.

```java
public void testConnectionWithOnlyContents(RegisterInfra infra) {
		boolean skipTlsverify = false;
		if (infra.getAccessInfo().getSkipTlsVerify().equalsIgnoreCase(SkipTlsVerify.TRUE.name())) {
			skipTlsverify = true;
		}
		Config config = null;
		try {
			config = new ConfigBuilder().withMasterUrl(infra.getInterfaceInfo().getServerAddress())
					.withClientCertData(infra.getAccessInfo().getClientCertificateData())
					.withClientKeyData(infra.getAccessInfo().getClientCertificateKey())
					.withCaCertData(infra.getAccessInfo().getCaCertificateData()).withTrustCerts(skipTlsverify).build();
		} catch (Exception e) {
			logger.error("testConnectionWithOnlyContents: config: exception {}", e.getMessage());
		}

		try {
			KubernetesClient client = new DefaultKubernetesClient(config);
			PodList podList = client.pods().list();
			logger.info("PodList: {}", podList);
			client.close();
		} catch (Exception e) {
			logger.error("testConnectionWithOnlyContents exception: {}", e.getMessage());
		}
	}
```

As input to this function i gave wrong CA certificate by removing last character from the CA cert base64 string.
With wrong CA certificate also this API is able to get pod list. But if i use kubectl command to get pods by using kubeconfig file with wrong CA cert it fails showing error in CA cert.

**Comment by manusa** [comment]
What's the effective value of `skipTlsVerify`?
Because if that's true, CA certificate will be omitted.

**Comment by vishal549** [comment]
@manusa 
skipTlsVerify is false

**Comment by manusa** [comment]
Relates to: #2888

**Comment by rohanKanojia** [comment]
@vishal549 : Hello, Do you have `insecure-skip-tls-verify` set in your `.kube/config`?
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <Invalid Cert Data>
    server: https://api.crc.testing:6443
    insecure-skip-tls-verify: true
  name: api.crc.testing:6443
```
When I set this in my `.kube/config` file I'm able to do pod list with client since `k8s.getConfiguration().isTrustCerts()` becomes `true` when `insecure-skip-tls-verify` is set to `true`

However, when I remove `insecure-skip-tls-verify` from my `.kube/config` Client gives me this error for not being able to parse certificate:
```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:226)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:66)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:51)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:43)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:139)
	at io.fabric8.kubernetes.examples.kubectl.equivalents.PodListEquivalent.main(PodListEquivalent.java:33)
Caused by: java.security.cert.CertificateException: Unable to initialize, java.io.IOException: insufficient data
	at java.base/sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:198)
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:105)
	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355)
	at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:103)
	at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:81)
	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:115)
	at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:94)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:122)
	... 5 more
Caused by: java.io.IOException: insufficient data
	at java.base/sun.security.util.DerInputBuffer.truncate(DerInputBuffer.java:134)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:284)
	at java.base/sun.security.util.DerInputStream.getDerValue(DerInputStream.java:457)
	at java.base/sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1829)
	at java.base/sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
	... 12 more

Process finished with exit code 1
```

**Comment by rohanKanojia** [comment]
@vishal549 : Was the last character you removed was a `=`? When you remove the last character from CA cert base64 encoded string, do you verify whether the trimmed string is still a valid base64 decoded string? When I removed the last character, it seemed to make no difference to the resulting decoded certificates. 

I tried your code like this with a valid CA base64 encoded string, `=` trimmed at the end and it seemed to be working in both cases. I checked and seems like `=` at the end of base64 string serve as [padding](https://en.wikipedia.org/wiki/Base64)
```java
try {
    config = new ConfigBuilder().withMasterUrl("https://api.crc.testing:6443")
            .withClientCertData(null)
            .withClientKeyData(null)
            .withCaCertData("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lJS3p2ZURscHdZTkV3RFFZSktvWklodmNOQVFFTEJRQXdKakVrTUNJR0ExVUUKQXd3YmFXNW5jbVZ6Y3kxdmNHVnlZWFJ2Y2tBeE5qRTJNRFF3TXpFNU1CNFhEVEl4TURNeE9EQTBNRFV5TUZvWApEVEl6TURNeE9EQTBNRFV5TVZvd0hURWJNQmtHQTFVRUF3d1NLaTVoY0hCekxXTnlZeTUwWlhOMGFXNW5NSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxYk1zNUoyREdJaVYzV2Uwb1pLcGpLM3EKcEFYSHJLUHRJZTFzVWY1SU5vOVQzclVqSTVZLzJ6c2YzbXIzUEwweHk5QmhVR1M1QlJSN081Tkt2dUtWMkdpMwpUMDVDNGhtQTQ1ZlJVZk02VnRkVTZsbGthYkV6RUxFSzgvR2hrcDJJUFNJRi9ocFpIUHdYazEreVJvVlhIZXhlCnhrWFplcENMbUVjQ0JGTGJmUGg5ZDlaZHU1MXdiVzhNam5oeC9mMVFlWEhDMHRJUG90WjZBYVZqWGRoQ01KMVUKVThnVUZWR0twNUFBUjIwQm0xR0xVd2xpakJWM00zTXlkMjVJQTdrQkRteTJRdzhvSndnUVRVSitDTmxJU0VaNwpPYzJaNENTZDhVa2l5cWZ0SkJjZm5oajNJUjVaT2hYTEoyOUNkQ2Fxb2E5cXJlTWhOWkJKREJKc05uUUdUUUlECkFRQUJvNEdWTUlHU01BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQU0KQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVGxNMDJFTDBZeE15T1NoeEVBQnVoZ3ZoQktrakFmQmdOVgpIU01FR0RBV2dCUnRGQms1TlVDeFdrcG5qa01yVmgwU3ZQUnpYakFkQmdOVkhSRUVGakFVZ2hJcUxtRndjSE10ClkzSmpMblJsYzNScGJtY3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRlRxWFZlVzRKK0hPMk9PTnZ1ZkRsWTcKd2hJaTg4S2hIWUtrNkUrTVM4VWlzd1pSR1RiS0tDcjRyclFaSFRER3J5WGVoei9YSWd4Yy9yWUdHbUhXWHlieQppaXRiZDI5enRJcEo3SW9RWUhPV0dXNERYZHpvOWxpVlFRUzlxVWpIL2RxUkJzWU9LWkFtekpoTFF6WlNUQmVoCkZDQU5Obi9jcjRSTXFaM3ZSaFhmS09kV1pUSjBDSlVBTHUvY1hvZWw0dk53Y1pOZlpBdkQzMU1BcXFKZ2NxMnkKMk0vcEZtVDJsK1RGZldnL2R2VDdhTFpsRDN2c1RsM2lkbnNwMnk0V01HYy9pSGJDSFY5WkhqdE1OZlh6VG9VUgpWa0JuVmtreDdEMDZHWXZ6MVZpbDUxUDMvRCtqdWdJMFBRVzJ2MG0xWmFDQzFGOFV6d0x1R29vdFRkSURvYW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0cGJtZHkKWlhOekxXOXdaWEpoZEc5eVFERTJNVFl3TkRBek1Ua3dIaGNOTWpFd016RTRNRFF3TlRFNVdoY05Nak13TXpFNApNRFF3TlRJd1dqQW1NU1F3SWdZRFZRUUREQnRwYm1keVpYTnpMVzl3WlhKaGRHOXlRREUyTVRZd05EQXpNVGt3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURSTEVUd09aUnA0SVNiK2NOMExsMWgKSUVHSk9VaFEzKzAyMlhpZHBBY2FOQ2dBZk9uc3NzeVhyWDFteVVEcXRydzVaS0tLTXBYczE1YWROZzhwQnhZVAptdWpkZVhiR0k1UHFyeHJORXFOWlV3d3Z0WXkza1h2REx6VW5KeUc0RE55VFJobHJtTHhFYkx6WEk5eSthZTJKCjBOUmhERUtqQUlwR2t3L0NjdFNUUjdjUUlWaXJKRXAzaUdyQ1JNU0c5UXRmalZwVUpUSitsNUxTL2FyRDBEVy8KWVQ0VlFWWUtrNUhYWTJpMGxQYklFUnhSaUlVbUd1MGdJM0dpeVg0T09SNS82QVZMb2p3ZkZOQ2xFWVhPbDEyRAo5UFBPWDdocGQ2S3VEckQ2cTZGSVdqRmV6SWpFbzBrN0ppbU9VMHUvbnltVk00MVJRMkVPb0pKdHFoc1diVnJ6CkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lDcERBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEcKQTFVZERnUVdCQlJ0RkJrNU5VQ3hXa3BuamtNclZoMFN2UFJ6WGpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpNY1JXVmVBZjNsZHZORjRlRXZEZjl6MU4yK0V4cDRnYm9zNGE2QW9JcU1pRm1NbU96MjhYMGxPY1BaRGtlcEVvCmdOK3F1djl6clkvRmJBVWpmeDA4b3ZkekpvTjhRR2xiZ3RBQTdDRUQxWlgyWXNWZEllU2dlNnBwU1ZVVmkvRWcKQ1BwVTJNdlBjOUtQSldOZzdzM2pmWGVKQzhDenFKWmt6Q2RCVGFaWjBMVTdnckNWeFllYlhKQlNIZVg5T3hoaQpySXJHV0ZhYjJaS0ZFbHp1bUNpWkdJR0YwWEdHc3FXQUl0bUFxSkNiWHZuRytVWUhnd1RNcmFWeTgyNC8vWEZSClJyNnYxVlVRNVIzUEVqTCtvS1FPY09yTjl2cXlUT3huY1B1YTUxbndIRDl3MUNMdW9MQm40SjVBa0NRSjE0N3UKMmFpeTRSZ04rMitiOVhnZmEwVjI4Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lJS3p2ZURscHdZTkV3RFFZSktvWklodmNOQVFFTEJRQXdKakVrTUNJR0ExVUUKQXd3YmFXNW5jbVZ6Y3kxdmNHVnlZWFJ2Y2tBeE5qRTJNRFF3TXpFNU1CNFhEVEl4TURNeE9EQTBNRFV5TUZvWApEVEl6TURNeE9EQTBNRFV5TVZvd0hURWJNQmtHQTFVRUF3d1NLaTVoY0hCekxXTnlZeTUwWlhOMGFXNW5NSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxYk1zNUoyREdJaVYzV2Uwb1pLcGpLM3EKcEFYSHJLUHRJZTFzVWY1SU5vOVQzclVqSTVZLzJ6c2YzbXIzUEwweHk5QmhVR1M1QlJSN081Tkt2dUtWMkdpMwpUMDVDNGhtQTQ1ZlJVZk02VnRkVTZsbGthYkV6RUxFSzgvR2hrcDJJUFNJRi9ocFpIUHdYazEreVJvVlhIZXhlCnhrWFplcENMbUVjQ0JGTGJmUGg5ZDlaZHU1MXdiVzhNam5oeC9mMVFlWEhDMHRJUG90WjZBYVZqWGRoQ01KMVUKVThnVUZWR0twNUFBUjIwQm0xR0xVd2xpakJWM00zTXlkMjVJQTdrQkRteTJRdzhvSndnUVRVSitDTmxJU0VaNwpPYzJaNENTZDhVa2l5cWZ0SkJjZm5oajNJUjVaT2hYTEoyOUNkQ2Fxb2E5cXJlTWhOWkJKREJKc05uUUdUUUlECkFRQUJvNEdWTUlHU01BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQU0KQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVGxNMDJFTDBZeE15T1NoeEVBQnVoZ3ZoQktrakFmQmdOVgpIU01FR0RBV2dCUnRGQms1TlVDeFdrcG5qa01yVmgwU3ZQUnpYakFkQmdOVkhSRUVGakFVZ2hJcUxtRndjSE10ClkzSmpMblJsYzNScGJtY3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRlRxWFZlVzRKK0hPMk9PTnZ1ZkRsWTcKd2hJaTg4S2hIWUtrNkUrTVM4VWlzd1pSR1RiS0tDcjRyclFaSFRER3J5WGVoei9YSWd4Yy9yWUdHbUhXWHlieQppaXRiZDI5enRJcEo3SW9RWUhPV0dXNERYZHpvOWxpVlFRUzlxVWpIL2RxUkJzWU9LWkFtekpoTFF6WlNUQmVoCkZDQU5Obi9jcjRSTXFaM3ZSaFhmS09kV1pUSjBDSlVBTHUvY1hvZWw0dk53Y1pOZlpBdkQzMU1BcXFKZ2NxMnkKMk0vcEZtVDJsK1RGZldnL2R2VDdhTFpsRDN2c1RsM2lkbnNwMnk0V01HYy9pSGJDSFY5WkhqdE1OZlh6VG9VUgpWa0JuVmtreDdEMDZHWXZ6MVZpbDUxUDMvRCtqdWdJMFBRVzJ2MG0xWmFDQzFGOFV6d0x1R29vdFRkSURvYW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0cGJtZHkKWlhOekxXOXdaWEpoZEc5eVFERTJNVFl3TkRBek1Ua3dIaGNOTWpFd016RTRNRFF3TlRFNVdoY05Nak13TXpFNApNRFF3TlRJd1dqQW1NU1F3SWdZRFZRUUREQnRwYm1keVpYTnpMVzl3WlhKaGRHOXlRREUyTVRZd05EQXpNVGt3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURSTEVUd09aUnA0SVNiK2NOMExsMWgKSUVHSk9VaFEzKzAyMlhpZHBBY2FOQ2dBZk9uc3NzeVhyWDFteVVEcXRydzVaS0tLTXBYczE1YWROZzhwQnhZVAptdWpkZVhiR0k1UHFyeHJORXFOWlV3d3Z0WXkza1h2REx6VW5KeUc0RE55VFJobHJtTHhFYkx6WEk5eSthZTJKCjBOUmhERUtqQUlwR2t3L0NjdFNUUjdjUUlWaXJKRXAzaUdyQ1JNU0c5UXRmalZwVUpUSitsNUxTL2FyRDBEVy8KWVQ0VlFWWUtrNUhYWTJpMGxQYklFUnhSaUlVbUd1MGdJM0dpeVg0T09SNS82QVZMb2p3ZkZOQ2xFWVhPbDEyRAo5UFBPWDdocGQ2S3VEckQ2cTZGSVdqRmV6SWpFbzBrN0ppbU9VMHUvbnltVk00MVJRMkVPb0pKdHFoc1diVnJ6CkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lDcERBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEcKQTFVZERnUVdCQlJ0RkJrNU5VQ3hXa3BuamtNclZoMFN2UFJ6WGpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpNY1JXVmVBZjNsZHZORjRlRXZEZjl6MU4yK0V4cDRnYm9zNGE2QW9JcU1pRm1NbU96MjhYMGxPY1BaRGtlcEVvCmdOK3F1djl6clkvRmJBVWpmeDA4b3ZkekpvTjhRR2xiZ3RBQTdDRUQxWlgyWXNWZEllU2dlNnBwU1ZVVmkvRWcKQ1BwVTJNdlBjOUtQSldOZzdzM2pmWGVKQzhDenFKWmt6Q2RCVGFaWjBMVTdnckNWeFllYlhKQlNIZVg5T3hoaQpySXJHV0ZhYjJaS0ZFbHp1bUNpWkdJR0YwWEdHc3FXQUl0bUFxSkNiWHZuRytVWUhnd1RNcmFWeTgyNC8vWEZSClJyNnYxVlVRNVIzUEVqTCtvS1FPY09yTjl2cXlUT3huY1B1YTUxbndIRDl3MUNMdW9MQm40SjVBa0NRSjE0N3UKMmFpeTRSZ04rMitiOVhnZmEwVjI4Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lJU0xOQ1l0a2lkOHd3RFFZSktvWklodmNOQVFFTEJRQXdQakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1TZ3dKZ1lEVlFRREV4OXJkV0psTFdGd2FYTmxjblpsY2kxc2IyTmhiR2h2YzNRdApjMmxuYm1WeU1CNFhEVEl4TURNeE9EQXpOREV3TWxvWERUTXhNRE14TmpBek5ERXdNbG93UGpFU01CQUdBMVVFCkN4TUpiM0JsYm5Ob2FXWjBNU2d3SmdZRFZRUURFeDlyZFdKbExXRndhWE5sY25abGNpMXNiMk5oYkdodmMzUXQKYzJsbmJtVnlNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXcxei8vcUkvK0dUMQpYVDJmekZ0RnhCOWtaU3JNQnFncWJESlVvQzc4aS9BeFlZS1FjWGVneVc4T0lCNTIzUks2YzAzOVZMS0pCd2plCkZTMTN1QzRlOFdvM0tqWEcxMHNCUHpDZSt0cGRKUFc0MDBlZGJDNHhYM0tTNCtCTnpyVkdMaFNocmZjYUl0VVAKNUZidk5WaTZsVm1WdGIwaG0xeEdsYWgzV3YyTGs0Y3duMnhPaFkvZTJzR1UwRER0Tk5EaDYvQW5uV2VjcUQzVAo5SENOQjYrMzRxZ0NXNXh5SFEya2VtOHBxY0xKKzd6bnAxSUNmaVVwNlE1dXU1bmFhdjRScHV4L2xDWi9HSWhwCkhrN0JLSHJ1SzhpWk5LU1hKN0FjdnpiUFZMRUxGay92QnFDVHkyNUlrMmdZVnRxcXhlZ0NOakIzUFhIa2J1aDQKUzR0ZkE4eVdZd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVZys2SmZndkV3ajFlOGZJZlVWNkVacEJCWTlZd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSVFERy9mbnhlSCthVUdnV2RSclpJU3JoTjZlUTNBNFJTRkVDMTB1SHhrQVRiZWpJazAyVVlLMGRFK2cKeXRMRVJSeWhPbXUwalhuUGlZUFVVNmczcExVSzN0cW1HT2cxWjZLWGJqS0VaVzlMckZMVGQ0OUxud0Ryd1Y1ZQpJcjQ1cUg3RzlZb0NJNytaUm1kbWh0NmFpWHRQWWplaXQ2YU9LNXJXaU1jaGd6cGFDcW96NEZwbTF3dEYxUTBjCm9WeXNWMmJkWkNBTEh6ZHdSSVZXZTJaRFNFSE5WQmdPcGVhVnhKalZPS3BTZDExUWluSGY2S3ZpWVVFS1RSY3oKQUVnZkxnbG1hNTdLbUFMK1hTcTF1WlZ6Y0Z3ZDBQbTNHQUNtSjhKOUg4TVJmY1lJMEpraEpYVmF1Vzh5dEVZOQp4Qmc0RFE3RzMwTDlMeFFoc1B1UEhqdDRsc2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURURENDQWpTZ0F3SUJBZ0lJSWtuMjJoeWhnMFV3RFFZSktvWklodmNOQVFFTEJRQXdSREVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1TNHdMQVlEVlFRREV5VnJkV0psTFdGd2FYTmxjblpsY2kxelpYSjJhV05sTFc1bApkSGR2Y21zdGMybG5ibVZ5TUI0WERUSXhNRE14T0RBek5ERXdNMW9YRFRNeE1ETXhOakF6TkRFd00xb3dSREVTCk1CQUdBMVVFQ3hNSmIzQmxibk5vYVdaME1TNHdMQVlEVlFRREV5VnJkV0psTFdGd2FYTmxjblpsY2kxelpYSjIKYVdObExXNWxkSGR2Y21zdGMybG5ibVZ5TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBMFJIODlxV2xia2dDb2ZvNGFYUlZIc2s2K3dKSGhydSs1RVdqbFA4VzhDM3Ntb05LamVobkpPZ29SOTl3CnN5ZklYc3BoUU5VdDRsYk1jRVQ4RmFicTcrQ0piemg1RGJNNXVLdHJIa3c5cTB5L3FzSmpTeEViN1g0KzgzZHgKY2kzUGxzc2h5V0ppL2lQNzRWQitXZ2lmejZCQTdRTFlON20zZXhXYXAycVhKekhZUy9IenliTCtIWENVWkcxQQpqOFhQelI4blhid2gyMkk0QUtzUzMrQzNjYTJ6cldQYTgrTkJUL1NJZy8zTytXZ2wyTFc4MURobzhoaWVGK1ZvCmtHZGdIenZRZFpXZnZncEROU0I2OEdwK096L3dhRmdDczdvSWZHN0k2d2F3bUM5dWtXaHgzZ1RFTHVDaU41N2oKZHZiYVRvazZrTEJjcDl6OHk0NkV6OXpGTXdJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUVQa0dkelkrMnk1ZHJRck1RMFdDRS9CSHAxTXdEUVlKCktvWklodmNOQVFFTEJRQURnZ0VCQUZnRitnaW85Wmx6aGN3U2NUMUtYWlFZcXhKVU1LTHFrUks5R0grNUhGRlIKeHlTSWFUakozdkZZcHpwMlRlUlJLb3k3dE5qczNVdFhTVHg1MWx5MVVhZXQxVWVPTkJGU01XL2NSWk9CZDFsSgpsd3R3Y2JPdkg5QjROVnEzTlU4aU5UUll2SzdBNHo4L1Fhcy85aDhEb1ZOUjJ6RzZCU1JJYmtBYVRDUmxLUmpVClhsNS9RZU1wTnIzY3lYYXg3MDFpL1JQUGxjS2ZZQlB0THhxdDdCc2pIeERZendxaHBvSlRSQ1lacmNaczZsWkIKMWpXanBaQm84L3NwY1ZrNVR1cTlxNEpMMVo3eFRxVHM5MWVLMkFwb1NrSURBeWhHNjBtRVJOMUFTWUI1cEtDRQpPdmdmVWZ6ZkJDNGF4NGRYZW9Nck52elhJcmhkU1NBc1BQcXpnR0ZKZS9zPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlETWpDQ0FocWdBd0lCQWdJSUpvMmpxVXgvL0FFd0RRWUpLb1pJaHZjTkFRRUxCUUF3TnpFU01CQUdBMVVFCkN4TUpiM0JsYm5Ob2FXWjBNU0V3SHdZRFZRUURFeGhyZFdKbExXRndhWE5sY25abGNpMXNZaTF6YVdkdVpYSXcKSGhjTk1qRXdNekU0TURNME1UQXpXaGNOTXpFd016RTJNRE0wTVRBeldqQTNNUkl3RUFZRFZRUUxFd2x2Y0dWdQpjMmhwWm5ReElUQWZCZ05WQkFNVEdHdDFZbVV0WVhCcGMyVnlkbVZ5TFd4aUxYTnBaMjVsY2pDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUpxSFhoaWdjOUI1S0FRb21RTmFSRGFKZHc1ZkMrNU8KM0FjaEVKbGorc2VLSlVpNUVsUUw3Qk5PazVBMyt5WVhaSmMraFl4QlptSXBqREtrVTBKYjJpbTN2ajJ6eURqQQo1RWVIbnQ0RE1tbWhad1FoVmVEMWFTbURLTmdMNW8rRjdvYUpjV3hxVGpPdDBMQWcrVTVPemtjMDFYTlpJb3lHCmJCVDV1ajlCL2YxMHlTUDAwbkdvR3F5TFNCOE83MkVSWWtNYkxLZlkyem9tOVppZEcycE9ySTFXREpJeTlMQ2QKUkVMaXNZTVd2aFRzNndGRHNIMTJwOFhtOC9qNlNuL0ZzdFFZRzdkdzZPeXVFUlRyWTJqbTdKbUtPTXkzZFRsKwpCeTc0WHlrRFF0MVBCVitsODhSUEp2WjZ1OSthaTREelVQLy9vN3Y5MnYvQ0dGUFB5UVA2azJVQ0F3RUFBYU5DCk1FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLZDcKaGgrVDhrbTd3ZnVRU0RKNXRrMHl2OHpuTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCcEFzclZJckkzQmZKWQpHcmJVektxSWcxWldTa21yVjZzSHlNS3ZHV1VpbDJ5WXFFenI0UTQ1VEdicHhRd0ZsajRBVWlsaXRYTmpZYTBtCjl5TmFVM3JlSFU0YUNURlIwWVZnWFpHNUZYMXZQUC9Rd25ZRTVHV0lWNlM2aTE0SUhSdDFKbFptSmxSc3VuN0YKdDlJcWtwSElYeVFaTE5ESnBKQXFCQ3dJY2t4cUY3Wk5iemt6cFVwRFhSSjhGV2tvRmQycXpxMmdEOHhEampUNwpvOGZLRGI5Zll4VWJXOW05QmVGc3c0N3VsNU1aL3NEd1Rxdis3SkR1MCtiQ1M0a25TWVVtSHFOdVQ4SGNEa0R1CnYwUzNhNFMxcHV2UjR2YlArNDFzaWZDck1GTU1ocGlwcitGR0RPOFlZS3FlYTZCaGgzckJndkJiemhqNElxKzMKc1VaMmFRak8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=")
            .withTrustCerts(false)
            .build();
} catch (Exception e) {
    logger.error("testConnectionWithOnlyContents: config: exception {}", e.getMessage());
}

try {
    KubernetesClient client = new DefaultKubernetesClient(config);
    PodList podList = client.pods().list();
    podList.getItems().forEach(p -> logger.info(p.getMetadata().getName()));
    client.close();
} catch (Exception e) {
    logger.error("testConnectionWithOnlyContents exception: {}", e.getMessage());
}
```
However, when I remove more characters. I do see failures:
```
[main] ERROR CertificateSkipVerifyTesting - testConnectionWithOnlyContents exception: An error has occurred.
```
