### ISSUE TITLE
Multiple sharedInformer creation: NullPointerException while running

### ISSUE THREAD

**Issue by akram** [fabric8io/kubernetes-client#2978]
While migrating a project that uses many watchers for different object types to shared informers, I am facing the following error after informers get started:
```
2021-04-09 08:48:43 WARNING io.fabric8.kubernetes.client.informers.cache.Controller run Reflector list-watching job exiting because the thread-pool is shutting down
java.util.concurrent.RejectedExecutionException: Error while starting ReflectorRunnable watch
	at io.fabric8.kubernetes.client.informers.cache.Reflector.listAndWatch(Reflector.java:87)
	at io.fabric8.kubernetes.client.informers.cache.Controller.run(Controller.java:109)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
```
I tried to reuse the `sharedInformer` or have different ones, but in both cases, I see this exception happening around 60 times for a total of 120 created informers.

**Comment by hanikesn** [comment]
This is related to #2753

**Comment by rohanKanojia** [comment]
@hanikesn : Could you please elaborate? How is it related to these?

**Comment by hanikesn** [comment]
> @hanikesn : Could you please elaborate? How is it related to these?

Sorry, they only seem related on the first look.

**Comment by akram** [comment]
fixed by: https://github.com/fabric8io/kubernetes-client/pull/3019
