### ISSUE TITLE
Expected HTTP 101 response but was '400 Bad Request' Bad Request

### ISSUE THREAD

**Issue by waytoharish** [fabric8io/kubernetes-client#2988]
Hi Team,
I am trying to use the code provided in the link but getting below error with latest version of fabric

io.fabric8:kubernetes-client:5.3.0

OpenShift version -3.11

Code-
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/ExecuteCommandOnPodExample.java

```
Expected HTTP 101 response but was '400 Bad Request' Bad Request
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: a container name must be specified for pod backup1-deployment-36-gfkjm, choose one of: [backup1 vault] or one of the init containers: [init-vault]
	at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.onFailure(ExecWebSocketListener.java:239)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:532)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:171)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:150)
		at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.waitUntilReady(ExecWebSocketListener.java:188)
		at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:331)
		at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:86)
		at com.axp.microdose.oc.client.ExecuteCommandOnPodExample.execCmd(ExecuteCommandOnPodExample.java:66)
		at com.axp.microdose.oc.client.ExecuteCommandOnPodExample.execCommandOnPod(ExecuteCommandOnPodExample.java:50)
		at com.axp.microdose.oc.client.ExecuteCommandOnPodExample.main(ExecuteCommandOnPodExample.java:104)
```

**Comment by manusa** [comment]
Your Pod has multiple containers. You need to set the name of the container (`inContainer()`) where you want to execute the command:
```java
client.pods()
      .inNamespace(pod.getMetadata().getNamespace())
      .withName(pod.getMetadata().getName())
      .inContainer("vault")
      .writingOutput(baos)
      .writingError(baos)
      .usingListener(new SimpleListener(data, baos))
      .exec(command);
```
