### ISSUE TITLE
EnableKubernetesMockClient fails for @Nested junit5 classes

### ISSUE THREAD

**Issue by dlafreniere** [fabric8io/kubernetes-client#3032]
A test class annotated with `@EnableKubernetesMockClient` will execute `@BeforeAll` for any nested classes as well, except it will fail to retrieve the annotation.

To Reproduce:
```
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import io.fabric8.kubernetes.client.KubernetesClient;
import io.fabric8.kubernetes.client.server.mock.EnableKubernetesMockClient;

@EnableKubernetesMockClient(crud = true)
class OuterTest {
  static KubernetesClient client;
  @Test
  void shouldPass() {
    assertTrue(true);
  }
  @Nested
  class NestedTest {
    @Test
    void shouldPass() {
      assertTrue(true);
    }
  }
}
```

Stack Trace:
```
Test ignored.

java.lang.NullPointerException
	at io.fabric8.kubernetes.client.server.mock.KubernetesMockServerExtension.initializeKubernetesClientAndMockServer(KubernetesMockServerExtension.java:88)
	at io.fabric8.kubernetes.client.server.mock.KubernetesMockServerExtension.setKubernetesClientAndMockServerFields(KubernetesMockServerExtension.java:123)
	at io.fabric8.kubernetes.client.server.mock.KubernetesMockServerExtension.beforeAll(KubernetesMockServerExtension.java:72)
	....
```

**Comment by rohanKanojia** [comment]
I think it'll work if you specify `@EnableKubernetesMockClient` annotation like this:
```java
@EnableKubernetesMockClient(crud = true)
class OuterTest {
  static KubernetesClient client;
  @Test
  void shouldPass() {
    assertTrue(true);
  }
  @Nested
  @EnableKubernetesMockClient(crud = true)
  class NestedTest {
    @Test
    void shouldPass() {
      assertTrue(true);
    }
  }
}
```

**Comment by dlafreniere** [comment]
> I think it'll work if you specify `@EnableKubernetesMockClient` annotation like this:
> 
> ```java
> @EnableKubernetesMockClient(crud = true)
> class OuterTest {
>   static KubernetesClient client;
>   @Test
>   void shouldPass() {
>     assertTrue(true);
>   }
>   @Nested
>   @EnableKubernetesMockClient(crud = true)
>   class NestedTest {
>     @Test
>     void shouldPass() {
>       assertTrue(true);
>     }
>   }
> }
> ```

Thanks, yea, I tried this as well. Although it doesn't crash, the `client` doesn't get cleaned up in the `afterEach` for the nested tests.

**Comment by rohanKanojia** [comment]
Code for this extension is here: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/EnableKubernetesMockClient.java

Would it be possible for you to debug what's wrong here and submit a PR?

**Comment by wind57** [comment]
@dlafreniere can you provide an actual sample of what you mean? You have the annotation `@EnableKubernetesMockClient(crud = true)` on the `@Nested` class, but you do not have neither the `KubernetesMockServer` nor the `KubernetesClient` in that nested class, so this is a bit confusing.

A sample of your exact use-case would help debug this further.

**Comment by rohanKanojia** [comment]
I bumped into this issue while writing some test involving nested Junit5 class.

I've attached a reproducer project that's using Kubernetes Client v6.10.0

[nested-kubernetes-mock-server-reproducer.zip](https://github.com/fabric8io/kubernetes-client/files/13922320/nested-kubernetes-mock-server-reproducer.zip)

**Comment by manusa** [comment]
Sorry, yes I confirmed earlier this week that this was still failing.

Shouldn't be that hard to fix. We just need to toggle the part of the extension where it's setting the injected fields.

In any case, we might want to delay this change to after we completely analyze the more extensive MockWebServer changes (#5632).

**Comment by manusa** [comment]
Was fixed in #5712.
It was left open because JUnit 4 wasn't addressed at the moment.
However, JUnit4 is not longer supported.
We can close this issue now.
