### ISSUE TITLE
java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.V1APIGroupClient

### ISSUE THREAD

**Issue by yeikel** [fabric8io/kubernetes-client#3063]
Hi team, 

I have the following configuration in my pom : 

        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>openshift-client</artifactId>
            <version>5.3.1</version>
        </dependency>

And I am creating my client : 

```
final Config config = new ConfigBuilder().withOauthToken(token).withMasterUrl(env.url()).build();
this.client = new DefaultKubernetesClient(config).adapt(OpenShiftClient.class);
```

And then, I am calling the following api to get the list of events : 

`client.v1().events().inNamespace(project).list().getItems();`

But that is producing the following runtime exception : 

```
20:46:41  Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.V1APIGroupClient
20:46:41  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:46:41  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
20:46:41  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:46:41  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
20:46:41  	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
20:46:41  	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
20:46:41  	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
20:46:41  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
20:46:41  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
20:46:41  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
20:46:41  	at com.aexp.c360.sre.UnHealthyPodReStarter.main(UnHealthyPodReStarter.java:132)
20:46:41  Caused by: java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.V1APIGroupClient
20:46:41  	at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:130)
20:46:41  	at io.fabric8.openshift.client.DefaultOpenShiftClient.v1(DefaultOpenShiftClient.java:654)
```

I tried adding both dependencies  : 

```
       <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>openshift-client</artifactId>
            <version>5.3.1</version>
        </dependency>

        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>5.3.1</version>
        </dependency>
```

But that produced a different runtime exception  

If it helps in any way, I am using Java 11 and Maven

Also, it does not seem to happen when I run the project locally. It only happens when I shade the build : 

```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <minimizeJar>true</minimizeJar>
                            <createDependencyReducedPom>true</createDependencyReducedPom>
                            <dependencyReducedPomLocation>
                                ${java.io.tmpdir}/dependency-reduced-pom.xml
                            </dependencyReducedPomLocation>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by rohanKanojia** [comment]
This issue is not just with V1APIGroupClient but with any Client whose Adapter is discovered via ServiceLoader:

https://github.com/fabric8io/kubernetes-client/blob/e580fe4dc18828d1995648f390409243353cb1ba/kubernetes-client/src/main/resources/META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter#L17-L40

**Comment by manusa** [comment]
https://github.com/fabric8io/kubernetes-client/issues/2218

**Comment by rohanKanojia** [comment]
@yeikel : Hello, I think `maven-shade-plugin` needs to be configured to avoid service entry declaration collision in `kubernetes-client` and `openshift-client` modules. If you add [ServiceResourceTransformer](http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer) in your `maven-shade-plugin` configuration you should get merged service entry declarations from both jars:
```xml
<configuration>
       <transformers>
              <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />                            
       </transformers>
</configuration>
```

I tested it with this project and I'm able to run the fat jar with the above configuration: https://github.com/r0haaaan/fabric8-kubernetes-client-demo-shaded

I've tested with both `openshift-client` and `kubernetes-client` dependencies and also with single `openshift-client` dependencies and it seems to work in both cases.

**Comment by yeikel** [comment]
Confirmed to be the solution. Thank you @rohanKanojia
