### ISSUE TITLE
NullPointerException when setting up SharedIndexInformer

### ISSUE THREAD

**Issue by leonz** [fabric8io/kubernetes-client#3139]
Hi!  I am trying to set up a SharedIndexInformer and struggling to get the API working for me.  I'm running fabric8 4.7.1:

```
Config config = new ConfigBuilder().build();
KubernetesClient kubernetesClient = new DefaultKubernetesClient(config);

OperationContext context = new OperationContext().withConfig(config).withNamespace(namespace).withLabels(MY_LABELS).withPlural(Utils.getPluralFromKind(Pod.class.getSimpleName()));
SharedIndexInformer<Pod> informer = kubernetesClient.informers().sharedIndexInformerFor(Pod.class, PodList.class, context, RESYNC_PERIOD_IN_MILLIS);
podInformer.addEventHandler(...);
factory.startAllRegisteredInformers();
```

To me, it seems like I'm following the examples exactly.  However, my logs are littered with:

```
{"type":"service.1","level":"INFO","time":"2021-05-18T04:25:58.479734Z","origin":"io.fabric8.kubernetes.client.informers.cache.ReflectorRunnable","thread":"pool-34-thread-1","message":"{}#Start listing and watching...","params":{},"uid":null,"sid":null,"tokenId":null,"traceId":null,"stacktrace":null,"unsafeParams":{"0":"class io.fabric8.kubernetes.api.model.Pod"},"tags":{}}
{"type":"service.1","level":"ERROR","time":"2021-05-18T04:25:58.480063Z","origin":"io.fabric8.kubernetes.client.informers.cache.ReflectorRunnable","thread":"pool-34-thread-1","message":"Failure in list-watch: {}","params":{},"uid":null,"sid":null,"tokenId":null,"traceId":null,"stacktrace":null,"unsafeParams":{"0":null},"tags":{}}
java.lang.NullPointerException
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:469)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:412)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:151)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:608)
    at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:130)
    at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:123)
    at io.fabric8.kubernetes.client.informers.cache.ReflectorRunnable.run(ReflectorRunnable.java:60)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

What am I missing?  It's super difficult to tell from the logs what I should actually be adding.

**Comment by leonz** [comment]
Okay, I think upgrading to 4.10.2 resolved this for me.
