### ISSUE TITLE
NoSuchMethodException when doing Pod operation

### ISSUE THREAD

**Issue by rouzwawi** [fabric8io/kubernetes-client#315]
This seems to be a regression introduced by https://github.com/fabric8io/kubernetes-client/commit/11b83525b31c92d70fa4f061f3926000eefcc1ac#diff-f97f7e5381172790f1294e7696201bac

Here's a stack trace from doing `client.pods().withResourceVersion(resourceVersion)`.

```
com.spotify.apollo.standalone.LoadingException: Something went wrong
	at com.spotify.apollo.standalone.StandaloneService.failure(StandaloneService.java:281) ~[apollo-standalone-service-1.0.1.jar:1.0.1]
	at com.spotify.apollo.standalone.StandaloneService.boot(StandaloneService.java:230) ~[apollo-standalone-service-1.0.1.jar:1.0.1]
	at com.spotify.apollo.standalone.StandaloneService.boot(StandaloneService.java:170) ~[apollo-standalone-service-1.0.1.jar:1.0.1]
	at com.spotify.apollo.standalone.StandaloneService.boot(StandaloneService.java:116) ~[apollo-standalone-service-1.0.1.jar:1.0.1]
	at com.spotify.apollo.standalone.StandaloneService.boot(StandaloneService.java:107) ~[apollo-standalone-service-1.0.1.jar:1.0.1]
	at com.spotify.styx.Styx.main(Styx.java:68) ~[styx-service.jar:9e64884-1456261124308]
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57) ~[kubernetes-client-1.3.71.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withResourceVersion(BaseOperation.java:462) ~[kubernetes-client-1.3.71.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withResourceVersion(BaseOperation.java:56) ~[kubernetes-client-1.3.71.jar:na]
	at com.spotify.styx.docker.KubernetesDockerRunner.<init>(KubernetesDockerRunner.java:56) ~[styx-service.jar:9e64884-1456261124308]
	at com.spotify.styx.docker.DockerRunner.kubernetes(DockerRunner.java:44) ~[styx-service.jar:9e64884-1456261124308]
	at com.spotify.styx.Styx.init(Styx.java:90) ~[styx-service.jar:9e64884-1456261124308]
	at com.spotify.styx.Styx$$Lambda$1/785992331.create(Unknown Source) ~[na:na]
	at com.spotify.apollo.environment.ApolloEnvironmentModule$ApolloEnvironmentImpl.initialize(ApolloEnvironmentModule.java:156) ~[apollo-environment-1.0.1.jar:1.0.1]
	at com.spotify.apollo.standalone.StandaloneModule.lambda$bindAppInit$0(StandaloneModule.java:83) ~[apollo-standalone-service-1.0.1.jar:1.0.1]
	at com.spotify.apollo.standalone.StandaloneModule$$Lambda$5/2009221452.init(Unknown Source) ~[na:na]
	at com.spotify.apollo.standalone.StandaloneModule.requestHandler(StandaloneModule.java:93) ~[apollo-standalone-service-1.0.1.jar:1.0.1]
	at com.spotify.apollo.standalone.StandaloneService.boot(StandaloneService.java:203) ~[apollo-standalone-service-1.0.1.jar:1.0.1]
	... 4 common frames omitted
Caused by: java.lang.NoSuchMethodException: io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.<init>(com.squareup.okhttp.OkHttpClient, io.fabric8.kubernetes.client.Config, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, io.fabric8.kubernetes.api.model.Pod, java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_45]
	at java.lang.Class.getConstructor(Class.java:1825) ~[na:1.8.0_45]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withResourceVersion(BaseOperation.java:459) ~[kubernetes-client-1.3.71.jar:na]
	... 14 common frames omitted
```

The culprit seems to be this unsafe reference (from `BaseOperation`) to the constructor of `PodOperationsImpl` which was changed recently:

```java
  @Override
  public Watchable<Watch, Watcher<T>> withResourceVersion(String resourceVersion) {
    try {
      return getClass()
              .getConstructor(OkHttpClient.class, Config.class, String.class, String.class, String.class, Boolean.class, type, String.class)
              .newInstance(client, config, apiVersion, namespace, name, cascading, item, resourceVersion);
    } catch (Throwable t) {
      throw KubernetesClientException.launderThrowable(t);
    }
  }
```

**Comment by rouzwawi** [comment]
Starting to see this error from version `1.3.69`
