### ISSUE TITLE
OpenshiftExtensionAdapter not working when KubernetesClient is a mock

### ISSUE THREAD

**Issue by r00ta** [fabric8io/kubernetes-client#3184]
Hi!

In my application I'm trying to use the `KubernetesClient` in some classes and the `OpenshiftClient` in some others when the underlying platform is Openshift. In my code I have something like 
```java
@Dependent
public class NetworkingServiceBeanProducer {

    private static final Logger LOGGER = LoggerFactory.getLogger(NetworkingServiceBeanProducer.class);

    @ConfigProperty(name = "baaas.k8s.platform", defaultValue = "openshift")
    String platform;

    @Inject
    KubernetesClient kubernetesClient;

    @Produces
    public NetworkingService produceNetworkingServiceBean() {
        LOGGER.info("Platform is {}", platform);
        if ("openshift".equals(platform)) {
            OpenShiftExtensionAdapter adapter = new OpenShiftExtensionAdapter();
            adapter.adapt(kubernetesClient);
            return new OpenshiftNetworkingService(adapter.adapt(kubernetesClient));
        }
        return new KubernetesNetworkingService(kubernetesClient);
    }
}
```

And it works like a charm. But in the tests I have the following mock of the `KubernetesClient`

```java
@ApplicationScoped
public class PlatformClientProducer {

    private final KubernetesServer mockKubernetesServer;

    private final KubernetesClient mockKubernetesClient;

    public PlatformClientProducer() {
        List<CustomResourceDefinitionContext> crds = new ArrayList<>();
        crds.add(PIPELINE_RUN_CONTEXT);
        this.mockKubernetesServer = new KubernetesServer(false, true, crds);
        this.mockKubernetesServer.before();
        this.mockKubernetesClient = mockKubernetesServer.getClient();
    }

    @Produces
    KubernetesServer getMockKubernetesServer() {
        return mockKubernetesServer;
    }

    @Produces
    KubernetesClient getMockKubernetesClient() {
        return mockKubernetesClient;
    }
}
```

And it crashes when I try to run the test suite with the Openshift client

```
Caused by: io.fabric8.openshift.client.OpenShiftNotAvailableException: OpenShift is not available. Root paths at: http://jrota.remote.csb:38987/ do not include oapi.
	at io.fabric8.openshift.client.OpenShiftExtensionAdapter.adapt(OpenShiftExtensionAdapter.java:46)
	at org.kie.baaas.dfs.service.networking.NetworkingServiceBeanProducer.produceNetworkingServiceBean(NetworkingServiceBeanProducer.java:46)
	at org.kie.baaas.dfs.service.networking.NetworkingServiceBeanProducer_ProducerMethod_produceNetworkingServiceBean_6f161c08c75c6013166bda983f8241541e01587d_Bean.create(NetworkingServiceBeanProducer_ProducerMethod_produceNetworkingServiceBean_6f161c08c75c6013166bda983f8241541e01587d_Bean.zig:131)
	at org.kie.baaas.dfs.service.networking.NetworkingServiceBeanProducer_ProducerMethod_produceNetworkingServiceBean_6f161c08c75c6013166bda983f8241541e01587d_Bean.get(NetworkingServiceBeanProducer_ProducerMethod_produceNetworkingServiceBean_6f161c08c75c6013166bda983f8241541e01587d_Bean.zig:170)
	at org.kie.baaas.dfs.service.networking.NetworkingServiceBeanProducer_ProducerMethod_produceNetworkingServiceBean_6f161c08c75c6013166bda983f8241541e01587d_Bean.get(NetworkingServiceBeanProducer_ProducerMethod_produceNetworkingServiceBean_6f161c08c75c6013166bda983f8241541e01587d_Bean.zig:205)
	at org.kie.baaas.dfs.networking.NetworkingTestUtilsProvider_Bean.create(NetworkingTestUtilsProvider_Bean.zig:270)
```

I think the problem is that the openshift adapter does not work with the `KubernetesClient` mock. Is there any workaround to cover this kind of scenario (have the `KubernetesClient` in some classes and the `OpenshiftClient` in some others?). Is the adapter supposed to work with the mocked k8s client? 

Thank you very much for the help!

**Comment by manusa** [comment]
There's an OpenShift specific MockServer implmentation, why aren't you using that one?

**Comment by shawkins** [comment]
Even with the openshift MockServer, it will not pass the isAdaptable check.  The only workaround currently is not use isAdaptable/adapt and start off with an OpenShiftClient.  It may be good to address in some way with changes related to #3294

**Comment by shawkins** [comment]
Now that we have made progress with #3487 we should revisit this - either by adding support in the mock, or by changing the isAdaptable logic further.
