### ISSUE TITLE
Invalid header field name "Impersonate-Extra-authentication.kubernetes.io/pod-uid" on OpenShift 4.8

### ISSUE THREAD

**Issue by skabashnyuk** [fabric8io/kubernetes-client#3253]
During testing of Eclipse Che on  OpenShift 4.8 discovered such an issue https://github.com/eclipse/che/issues/19988
```
2021-06-16 15:25:19,254[nio-8080-exec-1]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2021-06-16 15:25:19
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/apis/authorization.openshift.io/v1/namespaces/admin-che/rolebindings/admin. Message: Get "https://172.30.0.1:443/apis/rbac.authorization.k8s.io/v1/namespaces/admin-che/rolebindings/admin": net/http: invalid header field name "Impersonate-Extra-authentication.kubernetes.io/pod-uid". Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=Get "https://172.30.0.1:443/apis/rbac.authorization.k8s.io/v1/namespaces/admin-che/rolebindings/admin": net/http: invalid header field name "Impersonate-Extra-authentication.kubernetes.io/pod-uid", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:639)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:578)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:543)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:504)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:471)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:453)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:947)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:221)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:187)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:86)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.lambda$createOrReplace$1(BaseOperation.java:416)
	at io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:59)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:419)

```
The issue happened during the execution of such a code
```
        openshiftClient
            .roleBindings()
            .inNamespace(projectName)
            .createOrReplace(
                new RoleBindingBuilder()
                    .withNewMetadata()
                    .withName("admin")
                    .endMetadata()
                    .addToUserNames(osClient.currentUser().getMetadata().getName())
                    .withNewRoleRef()
                    .withApiVersion("rbac.authorization.k8s.io")
                    .withKind("RoleBinding")
                    .withName("admin")
                    .endRoleRef()
                    .build());
```
which is trying to grant necessary role binding after project/namespace creation.
This error might be related to the latest changes https://github.com/eclipse-che/che-server/pull/7 or to the upgrade of the client to 5.4.1 https://github.com/eclipse-che/che-server/pull/22 or it's something incompatible with Openshift 4.8.

Can you help me identify the cause?

**Comment by skabashnyuk** [comment]
Thanks to https://github.com/eclipse/che/issues/19988#issuecomment-866660008  we found an already known bug https://bugzilla.redhat.com/show_bug.cgi?id=1972687 in OpenShift 4.8 that should be fixed  by https://github.com/openshift/openshift-apiserver/pull/219
