### ISSUE TITLE
reload token when kube config file does not exist, errors shows

### ISSUE THREAD

**Issue by PeterPerter** [fabric8io/kubernetes-client#3312]
we ran into a problem when the token is refreshed : 
```
Caused by: java.io.FileNotFoundException: /home/common/.kube/config (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:343) ~[jackson-dataformat-yaml-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:14) ~[jackson-dataformat-yaml-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413) ~[jackson-databind-2.12.2.jar:2.12.2]
        at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfig(KubeConfigUtils.java:42) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:44) ~[kubernetes-client-5.1.1.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.12.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.12.jar:?]
        at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[kubernetes-client-5.1.1.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.12.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.12.jar:?]
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:282) ~[kubernetes-client-5.1.1.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.12.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.12.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257) ~[okhttp-3.12.12.jar:?]
        at okhttp3.RealCall.execute(RealCall.java:93) ~[okhttp-3.12.12.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:472) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:402) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:384) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:925) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:220) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186) ~[kubernetes-client-5.1.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:85) ~[kubernetes-client-5.1.1.jar:?]
```

We checked the environment and found that the /.kube/config file not exist, so in function intercept() it throws out  an exception in KubeConfigUtils.parseConfig, and codes in else{} would not execute.

```
  public Response intercept(Chain chain) throws IOException {
    Request request = chain.request();
    Response response = chain.proceed(request);
    if (response.code() == HttpURLConnection.HTTP_UNAUTHORIZED) {
      **io.fabric8.kubernetes.api.model.Config kubeConfig = KubeConfigUtils.parseConfig(new File(Config.getKubeconfigFilename()));**
      Context currentContext = null;
      String currentContextName = null;
      if (config.getCurrentContext() != null) {
        currentContext = config.getCurrentContext().getContext();
        currentContextName = config.getCurrentContext().getName();
      }
      AuthInfo currentAuthInfo = KubeConfigUtils.getUserAuthInfo(kubeConfig, currentContext);
      // Check if AuthProvider is set or not
      if (currentAuthInfo != null) {
        response.close();
        String newAccessToken;
        // Check if AuthProvider is set to oidc
        if (currentAuthInfo.getAuthProvider() != null && currentAuthInfo.getAuthProvider().getName().equalsIgnoreCase("oidc")) {
          newAccessToken = OpenIDConnectionUtils.resolveOIDCTokenFromAuthConfig(currentAuthInfo.getAuthProvider().getConfig());
        } else {
          Config newestConfig = Config.autoConfigure(currentContextName);
          newAccessToken = newestConfig.getOauthToken();
        }
        // Delete old Authorization header and append new one
        Request authReqWithUpdatedToken = chain.request().newBuilder()
          .header("Authorization", "Bearer " + newAccessToken).build();
        config.setOauthToken(newAccessToken);
        return chain.proceed(authReqWithUpdatedToken);
      }
    }
```

While in autoConfigure() function, error is ignored if /.kube/config not exist, so it will continue to tryServiceAccount.

```
private static Config (Config config, String context) {
    if (!tryKubeConfig(config, context)) {
      tryServiceAccount(config);
      tryNamespaceFromPath(config);
    }
    configFromSysPropsOrEnvVars(config);

    config.masterUrl = ensureHttps(config.masterUrl, config);
    config.masterUrl = ensureEndsWithSlash(config.masterUrl);

    return config;
  }
```

Could you help to check  in intercept()  whether the error should be ignored if read kubeconfig file failed?

**Comment by shawkins** [comment]
We hit this too a while back. @rohanKanojia WDYT?

**Comment by PeterPerter** [comment]
> We hit this too a while back. @rohanKanojia WDYT?

Do you have any workaround for this problem ? :)

**Comment by rohanKanojia** [comment]
Are you facing this problem when kubernetes-cilent is running inside a pod? We use KubeConfig file to extract things like currentContext and current auth info (like auth server URL for refresh token):

```
users:
- name: mmosley
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: 1db158f6-177d-4d9c-8a8b-d36869918ec5
        id-token: eyJraWQiOiJDTj1vaWRjaWRwLnRyZW1vbG8ubGFuLCBPVT1EZW1vLCBPPVRybWVvbG8gU2VjdXJpdHksIEw9QXJsaW5ndG9uLCBTVD1WaXJnaW5pYSwgQz1VUy1DTj1rdWJlLWNhLTEyMDIxNDc5MjEwMzYwNzMyMTUyIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL29pZGNpZHAudHJlbW9sby5sYW46ODQ0My9hdXRoL2lkcC9PaWRjSWRQIiwiYXVkIjoia3ViZXJuZXRlcyIsImV4cCI6MTQ4MzU0OTUxMSwianRpIjoiMm96US15TXdFcHV4WDlHZUhQdy1hZyIsImlhdCI6MTQ4MzU0OTQ1MSwibmJmIjoxNDgzNTQ5MzMxLCJzdWIiOiI0YWViMzdiYS1iNjQ1LTQ4ZmQtYWIzMC0xYTAxZWU0MWUyMTgifQ.w6p4J_6qQ1HzTG9nrEOrubxIMb9K5hzcMPxc9IxPx2K4xO9l-oFiUw93daH3m5pluP6K7eOE6txBuRVfEcpJSwlelsOsW8gb8VJcnzMS9EnZpeA0tW_p-mnkFc3VcfyXuhe5R3G7aa5d8uHv70yJ9Y3-UhjiN9EhpMdfPAoEB9fYKKkJRzF7utTTIPGrSaSU6d2pcpfYKaxIwePzEkT4DfcQthoZdy9ucNvvLoi1DIC-UocFD8HLs8LYKEqSxQvOcvnThbObJ9af71EwmuE21fO5KzMW20KtAeget1gnldOosPtz1G5EwvaQ401-RPQzPGMVBld0_zMCAwZttJ4knw
        idp-certificate-authority: /root/ca.pem
        idp-issuer-url: https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP
        refresh-token: q1bKLFOyUiosTfawzA93TzZIDzH2TNa2SMm0zEiPKTUwME6BkEo6Sql5yUWVBSWpKUGphaWpxSVAfekBOZbBhaEW+VlFUeVRGcluyVF5JT4+haZmPsluFoFu5XkpXk5BXq
      name: oidc
```

If it's possible to extract these things from ServiceAccount. I think it might be possible handle case when kube config file doesn't exist and use service account instead.

**Comment by PeterPerter** [comment]
@rohanKanojia  Thanks for your comments!
_Are you facing this problem when kubernetes-cilent is running inside a pod?_ 
Yes we had this problem when we use kubernetes-client in a pod and kubeconfig file does not exist.

_If it's possible to extract these things from ServiceAccount. I think it might be possible handle case when kube config file doesn't exist and use service account instead._
Actually in init stage there's no exception threw out, because in autoConfigure() function the error of reading kube config file is ignored, and it will continue to tryServiceAccount(config) to extract information from service account, and I got logs:
```
{"version":"0.2.0","timestamp":"2021-07-13T07:05:53Z","severity":"debug","service_id":"eric-nrf-config-agent","metadata":{"function":"NRF","ul_id":"Config.java:519"},"message":"Trying to configure client from Kubernetes config..."}
{"version":"0.2.0","timestamp":"2021-07-13T07:05:53Z","severity":"debug","service_id":"eric-nrf-config-agent","metadata":{"function":"NRF","ul_id":"Config.java:525"},"message":"Did not find Kubernetes config at: [/home/common/.kube/config]. Ignoring."}
{"version":"0.2.0","timestamp":"2021-07-13T07:05:53Z","severity":"debug","service_id":"eric-nrf-config-agent","metadata":{"function":"NRF","ul_id":"Config.java:451"},"message":"Trying to configure client from service account..."}
{"version":"0.2.0","timestamp":"2021-07-13T07:05:53Z","severity":"debug","service_id":"eric-nrf-config-agent","metadata":{"function":"NRF","ul_id":"Config.java:456"},"message":"Found service account host and port: 10.96.0.1:443"}
{"version":"0.2.0","timestamp":"2021-07-13T07:05:53Z","severity":"debug","service_id":"eric-nrf-config-agent","metadata":{"function":"NRF","ul_id":"Config.java:462"},"message":"Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt]."}
{"version":"0.2.0","timestamp":"2021-07-13T07:05:53Z","severity":"debug","service_id":"eric-nrf-config-agent","metadata":{"function":"NRF","ul_id":"Config.java:469"},"message":"Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token]."}
{"version":"0.2.0","timestamp":"2021-07-13T07:05:53Z","severity":"debug","service_id":"eric-nrf-config-agent","metadata":{"function":"NRF","ul_id":"Config.java:724"},"message":"Trying to configure client namespace from Kubernetes service account namespace path..."}
{"version":"0.2.0","timestamp":"2021-07-13T07:05:53Z","severity":"debug","service_id":"eric-nrf-config-agent","metadata":{"function":"NRF","ul_id":"Config.java:729"},"message":"Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace]."}

```
But when token is refreshed the exception threw out in intercept(Chain chain) and the autoconfigure would not be excuted.


BTW, since you have run into this problem before, do you have any temporary solution for this issue?

**Comment by shawkins** [comment]
> BTW, since you have run into this problem before, do you have any temporary solution for this issue?

In our case I believe this error was just masking another problem.  During an operator upgrade the new version failed to report as ready so olm was attempting to roll it back - it removed the necessary accounts/secrets but left the pod running.

**Comment by PeterPerter** [comment]
> > BTW, since you have run into this problem before, do you have any temporary solution for this issue?
> 
> In our case I believe this error was just masking another problem. During an operator upgrade the new version failed to report as ready so olm was attempting to roll it back - it removed the necessary accounts/secrets but left the pod running.
In our case we need to load token successfully, otherwise it will stuck.
So should the logic in intercept() be changed to similar with autoconfigure() ?

**Comment by louygan** [comment]
@rohanKanojia I think this is bug, as BoundServiceAccountTokenVolume is a Beta feature in k8s 1.21,  the service account admission controller will add a projected service account token volume instead of a secret volume. The service account token will expire after 1 hour by default or the pod is deleted.  

So support ServiceAccount Refreshment is mandatory.

**Comment by cassar1** [comment]
Any updates on this please? I have a similar problem, and cannot use kube config file as I have an application with multiple client instances interacting with different kubernetes cluster in a multi tenant way. The kubernetes parameters are being obtained dynamically.
