### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: not ready after 10000 MILLISECONDS

### ISSUE THREAD

**Issue by ChandrashekarAppaji** [fabric8io/kubernetes-client#3324]
Hi ,

I'm getting the below error continuously even after increasing the socket wait time to 10000 MS. (default=5000).
any hint here please  what is missing:

```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [ocslf]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:150)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:555)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:90)
        at DownloadFileFromPod.main(DownloadFileFromPod.java:17)
**Caused by: javax.net.ssl.SSLException: Read timed out**
        at sun.security.ssl.Alert.createSSLException(Alert.java:127)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:138)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1383)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1291)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:290)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall.execute(RealCall.java:93)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.retryWithExponentialBackoff(OperationSupport.java:585)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:558)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:521)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:504)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:143)
        ... 3 more
**Caused by: java.net.SocketTimeoutException: Read timed out**
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457)
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
        ... 42 more
``` 

 ---------------------------------
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
Kubernetes client-5.5.0

**Comment by ChandrashekarAppaji** [comment]
Any input here please

**Comment by manusa** [comment]
Could you include the portion of code that is throwing this exception?

**Comment by ChandrashekarAppaji** [comment]
Hi @manusa ,
I'm just trying to print the pod list in using the default client :
======================================
import io.fabric8.kubernetes.client.DefaultKubernetesClient;
import io.fabric8.kubernetes.client.KubernetesClient;
import java.io.File;
import java.nio.file.Path;


public class DownloadFileFromPod {
    public static void main(String[] args) {
            System.setProperty("kubernetes.websocket.timeout", "10000");
        try (KubernetesClient client = new DefaultKubernetesClient()) {
            System.out.println(client.pods().inNamespace("ocslf").list());

        }
    }
}

**Comment by manusa** [comment]
Cluster information?

**Comment by ChandrashekarAppaji** [comment]
Cluster is having 3 master nodes with 4 worker nodes

**Comment by ChandrashekarAppaji** [comment]
Sorry its working fine
it was proxy issue. :)
Thanks for all the support

**Comment by mortenbirkelund** [comment]
@ChandrashekarAppaji Could you tell what kind of proxy issue it was? I am facing the same thing.

**Comment by vijitgosain** [comment]
Faced the same issue, there were http_proxy and https_proxy set in the pod.
After resetting these proxies the error was resolved.

**Comment by Cxs1103** [comment]
> Faced the same issue, there were http_proxy and https_proxy set in the pod. After resetting these proxies the error was resolved.

How to reset the proxy？

**Comment by vijitgosain** [comment]
Resetting the http_proxy and https_proxy in the Kubernetes pod can be done by setting value of HTTP_PROXY and HTTPS_PROXY to null.
This can be done in the corresponding deployment file by adding 2 variables in the env.

The following is an example that worked for me:

```
spec:
  template:
    spec:
      containers:
        env:
        - name: HTTP_PROXY
          value: null
        - name: HTTPS_PROXY
          value: null
```
          
This can be further verified by doing exec into the pod and running the following command:

```
export | grep "HTTP_PROXY"
export | grep "HTTPS_PROXY"
```

Thanks and Regards,
Vijit

**Comment by vijitgosain** [comment]
> > Faced the same issue, there were http_proxy and https_proxy set in the pod. After resetting these proxies the error was resolved.
> 
> How to reset the proxy？

Resetting the http_proxy and https_proxy in the Kubernetes pod can be done by setting value of HTTP_PROXY and HTTPS_PROXY to null.
This can be done in the corresponding deployment file by adding 2 variables in the env.

The following is an example that worked for me:

spec:
  template:
    spec:
      containers:
        env:
        - name: HTTP_PROXY
          value: null
        - name: HTTPS_PROXY
          value: null

This can be further verified by doing exec into the pod and running the following command:

export | grep "HTTP_PROXY"
export | grep "HTTPS_PROXY"

Thanks and Regards,
Vijit

**Comment by rg970197** [comment]
I'm getting same Error, but this solution did not work for me. any idea whats going wrong here. 
All my Jenkins server giving same Error.  This is my configuration

`controller:
  tag: "2.319.2"
  imagePullPolicy: "Always"
  javaOpts: >-
    -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout=90
    -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.websocketConnectionTimeout=80000
    -Dkubernetes.websocket.timeout=70000
    -Xms2G
    -Xmx2G
  env:
    - name: "HTTP_PROXY"
      value: "null"
    - name: "HTTPS_PROXY"
      value: "null"`

**Comment by vijitgosain** [comment]
> I'm getting same Error, but this solution did not work for me. any idea whats going wrong here. All my Jenkins server giving same Error. This is my configuration
> 
> controller: tag: "2.319.2" imagePullPolicy: "Always" javaOpts: >- -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout=90 -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.websocketConnectionTimeout=80000 -Dkubernetes.websocket.timeout=70000 -Xms2G -Xmx2G env: - name: "HTTP_PROXY" value: "null" - name: "HTTPS_PROXY" value: "null"

It will be great if we can try with the following java option:

`-Dhttp.nonProxyHosts="<IP of kube api server>"`

If still not resolved we can enable logging by setting logging.level.org.springframework.cloud.kubernetes to TRACE in the application to identify any problem.

Thanks and Regards,
Vijit

**Comment by rg970197** [comment]
Thanks Vijit, 
Kubernetes is running inside AKS Cluster as pods. In this case what will be kube api server?
Trying  hard to enable TRACE for Logs. Where do i need to add this logging.level.org.springframework.cloud.kubernetes ?

**Comment by rg970197** [comment]
Is this Correct? 
javaOpts: >-
    -Xms2G
    -Xmx2G
    -Dlogging.level.org.springframework.cloud.kubernetes= TRACE

**Comment by priyadharsanR** [comment]
Hi ,

I'm getting the below error continuously getting this error after updating new plugin image , i created the new image by using plugin compactibility script in script console , but still i am getting this error
hudson.remoting.ProxyException: io.fabric8.kubernetes.client.KubernetesClientException: name not specified for an operation requiring one.
