### ISSUE TITLE
ClassCastException: class io.fabric8.kubernetes.api.model.Secret cannot be cast to class io.fabric8.kubernetes.api.model.GenericKubernetesResource

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/kubernetes-client#3328]
I have an operator where I set up watcher using the `customResource` to be able to watch any kind of resource, something like:

```java
CustomResourceDefinitionContext ctx = createCRDContext("v1", "Secret");

return kubernetesClient
    .customResource(ctx)
    .inNamespace(namespace)
    .watch(namespace, null, labels, new ListOptionsBuilder().build(), watcher);
```

When an event happen on a secret, the following exception is thrown:

```
15:22:51.278 ERROR [io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager] (OkHttp http://localhost:57207/...) Received wrong type of object for watch: java.lang.ClassCastException: class io.fabric8.kubernetes.api.model.Secret cannot be cast to class io.fabric8.kubernetes.api.model.GenericKubernetesResource (io.fabric8.kubernetes.api.model.Secret and io.fabric8.kubernetes.api.model.GenericKubernetesResource are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @32a822c0)
        at io.fabric8.kubernetes.client.dsl.internal.RawCustomResourceOperationsImpl$DelegateWatcher.eventReceived(RawCustomResourceOperationsImpl.java:936)
        at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
        at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:176)
        at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:232)
        at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
````

**Comment by lburgazzoli** [comment]
@manusa unfortunately I didn't spot this issue when you originally asked me to check the PR where `GenericKubernetesResource` has been introduced.

**Comment by shawkins** [comment]
There's handling for this in the ReflectorWatcher that needs moved up into
the AbstractWatchManager.

**Comment by manusa** [comment]
I wouldn't agree 100% on this being a bug.

If you are dealing with a known type, why do you want to handle this as a Raw/Unstructured/CustomResource type?
I mean, the runtime error is really bad and it would be much better to prevent this, but my point is that you should be using `kubernetesClient.secrets()` instead.

What's the main reason you are using a CRD definition and the extra hassle instead of using the known type?

**Comment by lburgazzoli** [comment]
> I wouldn't agree 100% on this being a bug.
> 
> If you are dealing with a known type, why do you want to handle this as a Raw/Unstructured/CustomResource type?
> I mean, the runtime error is really bad and it would be much better to prevent this, but my point is that you should be using `kubernetesClient.secrets()` instead.
> 

I can't because my operator does not know the type of the resources as they are retrieved from another service, then the operator set-up a watcher on them and reacts upon changes in a generic way. 

Of course I can eventually come up with something like a switch case to check if it is a know resource, but since the operator does not care about the type, I think that it would just make the code hard to maintain.

**Comment by shawkins** [comment]
Since it's just a small fix and makes the unstructured logic work with anything, I'll produce a pr for this.

**Comment by manusa** [comment]
> I can't because my operator does not know the type of the resources as they are retrieved from another service, then the operator set-up a watcher on them and reacts upon changes in a generic way.

OK, this is what I imagined. In your snippet you provided a hard-coded "v1"+"Secret" group-version + kind combination, I understand that in your operator these values are dynamic.

One of the next steps for the GenericKubernetesResource is to be able to use this with resource with DSL methods such as `resouce` or `resourceList` without the need to provide additional context. This should eventually take care of the full round-trip (deserialize any kind of resource, both known and unknown, and be able to handle it).

> Since it's just a small fix and makes the unstructured logic work with anything, I'll produce a pr for this.

:raised_hands: cool, thx!
