### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/api/builder/Visitable

### ISSUE THREAD

**Issue by emrealpogunc** [fabric8io/kubernetes-client#3352]
Hello and Greetings, 
I'm new to k8s and for my tasks I have to use Fabric8. To do that I downloaded and added the .jar file to the eclipse IDE as a external .jar file but unfortunately, whenever I try to create a client I face with an issue like this:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/api/builder/Visitable
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1088)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:182)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:814)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:735)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:660)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1088)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:182)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:814)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:735)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:660)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1088)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:182)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:814)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:735)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:660)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at test/test.test2.main(test2.java:9)
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.api.builder.Visitable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 31 more
```

What could be the reason behind of this? I tried to make some changes to the **"pom.xml"** file but nothing has changed. It's still giving me the same error. I don't know if I'm over-complicating this problem but right now I'm pretty much stuck. I installed both OpenShift and K8s Java Client FYI.

Even a comment is highly appreciated,
Thank you.

**Comment by manusa** [comment]
You're missing some transitive dependencies.

Do you have a Maven project? have you tried adding the maven dependency (instead of adding a Jar package to your Eclipse IDE)?

**Comment by emrealpogunc** [comment]
> You're missing some transitive dependencies.
> 
> Do you have a Maven project? have you tried adding the maven dependency (instead of adding a Jar package to your Eclipse IDE)?

That was exactly the problem. Just solved it mere minutes ago, thank you so much for your help!
