### ISSUE TITLE
Issue while using client inside cluster with service account

### ISSUE THREAD

**Issue by saurabrana** [fabric8io/kubernetes-client#3360]
My application is running as a daemon set on the **windows node** in **EKS cluster**
Following is the client config : 
>Config config = new ConfigBuilder()
                .withCaCertData(eksKubernetesCluster.getClusterCAData())
                .withMasterUrl(eksKubernetesCluster.getClusterEndpoint())
                .withApiVersion("v1")
                .withTrustCerts(true)
                .withOauthTokenProvider(eksKubernetesCluster)
                .build();

But on running the application I am getting the following exception while trying to list pods in namespace

> Caused by: java.io.FileNotFoundException: C:\Users\ContainerAdministrator\.kube\config (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:343) ~[jackson-dataformat-yaml-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:14) ~[jackson-dataformat-yaml-2.11.4.jar!/:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3333) ~[jackson-databind-2.11.4.jar!/:2.11.4]
	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfig(KubeConfigUtils.java:42) ~[kubernetes-client-5.3.1.jar!/:?]
	at io.fabric8.kubernetes.client.utils.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.java:44) ~[kubernetes-client-5.3.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:?]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68) ~[kubernetes-client-5.3.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:?]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createApplicableInterceptors$6(HttpClientUtils.java:284) ~[kubernetes-client-5.3.1.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:?]

Following is my **Service Account yml**

> apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cxp.adobe.io/app: <APP-NAME>
  name: <SERVICE-ACCOUNT-NAME>
  annotations:
    eks.amazonaws.com/role-arn: <IAM-ROLE-ARN>

**Cluster Role Binding**

> apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <BINDING-NAME>
  labels:
    cxp.adobe.io/app: <APP-NAME>
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: <SERVICE-ACCOUNT-NAME>
    namespace: {{ .Release.Namespace }}

From my application, I am able to see that the IAM role is property applied but on listing pods for the namespace I am getting the above Error.

I am configuring Oauth Token provider as follows : https://gist.github.com/saurabrana/ca2114f854da1811c519b421e518bf37

What is it that I am doing wrong ?

**Comment by rohanKanojia** [comment]
I think this is related to https://github.com/fabric8io/kubernetes-client/issues/3312 . We need to fix this.  We had added support for token refresh a few months ago. Our TokenRefreshInterceptor is not handling in-cluster case

https://github.com/fabric8io/kubernetes-client/blob/8d380a350231c7d26710b68f02731659418aa999/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/TokenRefreshInterceptor.java#L44

**Comment by saurabrana** [comment]
@rohanKanojia  My Application works fine within cluster if I don't give any Service account.
In that case, I think k8s applies  the default service account.
I was wondering if this works with the default service then why is it not working with my service account.

![image](https://user-images.githubusercontent.com/77790151/127546182-0b172a2c-e734-4b15-aa39-b42efd32bddc.png)

Also is there any other way of doing this and not using TokenRefreshInterceptor?
