### ISSUE TITLE
Exec failure due to timeout

### ISSUE THREAD

**Issue by gentaliti** [fabric8io/kubernetes-client#3381]
I am getting TimeoutException while trying to run a command with exec into Pod. This is only happening for a few moments per day but it is causing some of our jobs to fail. I still wasn't able to reproduce it.

Also I am getting these logs whenever the timeout is happening (while running exec):

```
Exec Failure: HTTP:0. Message:No response
java.io.EOFException: null
	at okio.RealBufferedSource.require(RealBufferedSource.java:65)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:78)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Are timeouts related to this stacktrace? What may be causing this timeout?

EDIT: it is important to mention that this seems to only be affecting "exec" commands

**Comment by rohanKanojia** [comment]
@gentaliti : strange, Could you please review our exec implementation[0] and see what could be causing this issue?

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/core/v1/PodOperationsImpl.java#L321

**Comment by gentaliti** [comment]
Looks like this is related to Kubernetes and not to the client. It is happening while nodes are scaling up/down even though these nodes are not the ones on which the pod is. It seems that scaling is affecting communication between existing nodes and api-server.

See:
https://issuetracker.google.com/issues/156556218
https://issuetracker.google.com/issues/174499379

Closing this as is not related to the client.
