### ISSUE TITLE
NullPointerException for CustomResource - (missing default handler for GenericKubernetesResource)

### ISSUE THREAD

**Issue by arturk9** [fabric8io/kubernetes-client#3392]
Hello!

I would like to ask you if it would be possible to implement default handler for GenericKubernetesResource?

For example, resource [:](https://www.consul.io/docs/connect/config-entries/service-defaults)

`
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: web
spec:
  protocol: http
`

when loaded by:

`
var contentsInputStream = MethodHandles.lookup().lookupClass().getResourceAsStream(customResourceYamlPath)
kubernetesClient.load(contentsInputStream).get()
`

Returns:
`
Exception in thread "main" java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:291)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:283)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.get(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:63)
`

**Comment by shawkins** [comment]
The NPE has been replaced with a KubernetesClientException.  I don't think you can do this generically as the item does not provide if it's namespaced nor what the plural is.

Try instead:
kubernetesClient.genericKubernetesResource(context).load(stream)

**Comment by manusa** [comment]
> `kubernetesClient.load(contentsInputStream).get()`

Being able to do this is part of the Generic Resource next steps and should be possible after implementing:
- #3294
- #3303 
- https://github.com/fabric8io/kubernetes-client/issues/3294#issuecomment-874002876

So for those (valid) resources for which we don't have enough information to interact with the API server, we could perform (and cache) a request to the ApiGroupList and ApiResourceList endpoints to fetch the required parameters (scope, plural, etc.). With this information, then we can interact with the API server for any valid (and known) resource.

**Comment by shawkins** [comment]
> With this information, then we can interact with the API server for any valid (and known) resource.

There is a placeholder method for that in Handlers https://github.com/fabric8io/kubernetes-client/blob/8d380a350231c7d26710b68f02731659418aa999/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Handlers.java#L49 which can eventually be expanded to support this.  For now passing in the context is the only option.
