### ISSUE TITLE
Additional ConcurrentModificationException in KubernetesCrudDispatcher

### ISSUE THREAD

**Issue by rnorth** [fabric8io/kubernetes-client#3429]
Similar to #2592 

We've observed another `ConcurrentModificationException` coming out of `KubernetesCrudDispatcher`, this time coming out of the `handleWatch` method. Specifically, the lambda provided to the `WatchEventsListener`:

```
  java.util.ConcurrentModificationException: null
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1842)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.fabric8.kubernetes.client.server.mock.KubernetesCrudDispatcher.lambda$handleWatch$8(KubernetesCrudDispatcher.java:275)
        at io.fabric8.kubernetes.client.server.mock.WatchEventsListener.onOpen(WatchEventsListener.java:61)
        at okhttp3.mockwebserver.MockWebServer.handleWebSocketUpgrade(MockWebServer.java:743)
        at okhttp3.mockwebserver.MockWebServer.access$1800(MockWebServer.java:103)
        at okhttp3.mockwebserver.MockWebServer$4.processOneRequest(MockWebServer.java:589)
        at okhttp3.mockwebserver.MockWebServer$4.processConnection(MockWebServer.java:531)
        at okhttp3.mockwebserver.MockWebServer$4.execute(MockWebServer.java:456)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

We're seeing intermittent failures with `io.fabric8:kubernetes-server-mock:5.7.0`, in tests/code that make use of watches.

**Comment by manusa** [comment]
Fixed by #3434
