### ISSUE TITLE
SharedInformer Unhandled exception encountered in watcher event handler

### ISSUE THREAD

**Issue by flavioschuindt** [fabric8io/kubernetes-client#3437]
Hi, guys.

I have something weird happening here and would like some direction. I wrote an operator using [Java Operator SDK](https://github.com/java-operator-sdk/java-operator-sdk) that does basically these steps:

1. Start a Job in the cluster;
2. Register a shared informer to receive events for this job;
3. Wait for Job completion event (regardless of job success or failure);
4. Receive event for job completion and do some internal business logic;
5. Finally, **deletes** the CR and all resources created in this process, including the job.

The operator is running fine and works well in majority of the cases. There is one thing that I don't understand tough: The more I create CRs, the more load I add, there is a point in time that I see for some jobs created this stack trace in my operator code:

```java
2021-09-02 03:22:03.169 ERROR [-] [] 1 --- [/10.233.0.1/...] i.f.k.c.d.i.WatcherWebSocketListener     : Unhandled exception encountered in watcher event handler

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.233.0.1/apis/batch/v1/namespaces/test/jobs/test-e74bde85-927e-486c-a848-8ec086f8bb0a. Message: jobs.batch "test-e74bde85-927e-486c-a848-8ec086f8bb0a" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=batch, kind=jobs, name=test-e74bde85-927e-486c-a848-8ec086f8bb0a, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=jobs.batch "test-e74bde85-927e-486c-a848-8ec086f8bb0a" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=NotFound, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:583)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:522)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:487)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:448)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:431)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:161)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:664)
	at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:245)
	at io.fabric8.kubernetes.client.informers.SharedInformerFactory$1.list(SharedInformerFactory.java:240)
	at io.fabric8.kubernetes.client.informers.cache.Reflector.getList(Reflector.java:68)
	at io.fabric8.kubernetes.client.informers.cache.Reflector.reListAndSync(Reflector.java:94)
	at io.fabric8.kubernetes.client.informers.cache.ReflectorWatcher.lambda$onClose$0(ReflectorWatcher.java:76)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.fabric8.kubernetes.client.informers.cache.ReflectorWatcher.onClose(ReflectorWatcher.java:76)
	at io.fabric8.kubernetes.client.utils.WatcherToggle.onClose(WatcherToggle.java:56)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.closeEvent(AbstractWatchManager.java:85)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$TypedWatcherWebSocketListener.onMessage(WatchConnectionManager.java:103)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:290)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:220)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:100)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:247)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:181)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-09-02 03:22:03.169  WARN [-] [] 1 --- [/10.233.0.1/...] i.f.k.c.i.cache.ReflectorWatcher         : Watch closing with exception

io.fabric8.kubernetes.client.WatcherException: too old resource version: 175764291 (175794630)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$TypedWatcherWebSocketListener.onMessage(WatchConnectionManager.java:103)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:290)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:220)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:100)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:247)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:181)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 175764291 (175794630)
	... 10 common frames omitted
```

The error is clear: There is a deletion attempt in a job that was already deleted because of step (5) above. And that is what I don't understand: I already delete the job and looks like these job completion events are being received again and again which leads to this situation.

P.S1.: Note that once job is done, I always remove it from the shared informer cache:

```java
private void removeJobFromSharedInformer(Job job){
        log.info("Removing job from sharedInformer cache.");
        SharedIndexInformer<Job> existingSharedIndexInformer = sharedInformerFactory.getExistingSharedIndexInformer(Job.class);
        existingSharedIndexInformer.getIndexer().delete(job);
        log.info("Job removed successfully from sharedInformer cache.");
    }
```

P.S.2: even tough I see this in the logs, the end-to-end process with all above steps works fine. It's just annoying seeing this polluting the operator logs.

Does anyone know about it? The fabric8 client used is 5.3.1.

Thank you in advance!

**Comment by shawkins** [comment]
Ideally you would move to a later fabric8 release there were a lot of changes refining the informers and related logging in 5.4 and at least one in 5.6 - #3318

**Comment by flavioschuindt** [comment]
Hi, @shawkins, thanks a lot for the updates.

So, I was following your advice and checking the releases and indeed has a lot of changes for the informer. Therefore, I am trying to update it to 5.7.0 (I used the java operator SDK and can't go beyond this). However, I am having a super hard time with all these changes and the [examples in the fabric8 repo](https://github.com/fabric8io/kubernetes-client/tree/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples) are confusing as they stop the informer always after a certain amount of time (the thread actually blocks in a Thread.sleep as per the examples). This won't work for me. I need to stop the informer just after the job is done regardless of the amount of time it takes. I am doing something like this:

1. Start the informer for the specific job I am interested in:

```java
kubernetesClient()
                             .batch().v1().jobs()
                             .inNamespace(spec.getNamespace())
                             .withName(resource.getSpec().getJobName())
                             .inform(getInformer());
```
2. The ```getInformer()``` returns an object from a new class that implements ```ResourceEventHandler<T>```
3. All business logic happens inside the ```getInformer()``` object and just works fine...But now, after the job is done I want to stop the shared informer **only for that particular job without impacting informers of other jobs**. For this, I don't know how to do because I don't have the reference for the original informer anymore...

Any idea here? As I said above, all examples that I see in the repo they do this based on a timer and then after expires as you are in the same method, you just stop the informer. I want it to be event based, i.e., when the job is done, stop the informer.

Thank you!

**Comment by shawkins** [comment]
>  the examples in the fabric8 repo are confusing as they stop the informer always after a certain amount of time (the thread actually blocks in a Thread.sleep as per the examples

That's because the example isn't doing any other work on the main thread, so it just sleeps until the informer has demonstrated what it's supposed to do.  Once an informer is started it will continue to run asynchronously the starting thread is free to do whatever it wants after that.

> All business logic happens inside the getInformer() object and just works fine...But now, after the job is done I want to stop the shared informer only for that particular job without impacting informers of other jobs. For this, I don't know how to do because I don't have the reference for the original informer anymore...

Informers should be thought of as a more heavy weight watch.  They will currently use at least two threads based upon the underlying okhttp implementation.  Creating them down to an individual resource may not be the best approach.  For your scenario whether you use the dsl api or the informer factory it would probably be best to establish the informer more broadly and put whatever business logic you need in the ResourceEventHandler if you are only interested in a subset of the resources.

>  But looks like in version 5.7.0 the method delete() does not exist anymore.

Direct manipulation of the informer cache should not be needed - it is supposed to be managed by the informer and it can change the meaning of events if you manually add/remove.

**Comment by flavioschuindt** [comment]
Hi, @shawkins.

Thanks again. So, trying to follow what you are saying, but having trouble to understand what the informer is doing:

* Yes, I could validate the async behavior of the SharedInformer. Starts on the main thread and free it;
* I have two fake jobs:

```yaml
NAMESPACE      NAME                                                COMPLETIONS   DURATION   AGE
default        hello-job                                           1/1           4s         85d
default        hello-job1                                          1/1           4s         85d
```

Using the DSL, If I start the informer like this  (1) ```kubernetesClient.batch().v1().jobs().inform``` I don't receive the ADD event. In the other hand, If I start it with (2) ```kubernetesClient.batch().v1().jobs().inNamespace("default").inform``` then it always outputs the ADD event. Could you please clarify here why this difference? Note that I have other jobs in another namespaces and they have mixed behavior for (2): For some namespaces doesn't work, for others work. For (1) it always working, but would like to avoid it as my operator really doesn't know in advance in which namespace user will create the job.

Thank you!

**Comment by shawkins** [comment]
> kubernetesClient.batch().v1().jobs().inform

This will use whatever is configured as your default namespace.  You can use kubernetesClient.getNamespace() to confirm what namespace the client is using.

> kubernetesClient.batch().v1().jobs().inNamespace("default").inform

This is explicitly using the default namespace.

> It seems that some jobs are not being added in the informer and any subsequent event is just being ignored.

I don't completely follow what you are describing.  The underlying watch will either be specific to a namespace, or follow all namespaces if you use jobs().inAnyNamespace().  Unless you do some kind of filtering, by label, or name, etc. then you will see all events as you expect from the resources.  It doesn't appear to be the case here but if you do some kind of filtering - for example by a label, then the removal of a matching label from a resource will actually be expressed as a delete event by the informer.

**Comment by flavioschuindt** [comment]
Cool, @shawkins. Your explanation is very clear, I was missing the label filtering and the ```inAnyNamespace ```, now I am receiving the proper events. With this new approach then I went ahead and did some performance test. Created one CR every 40 seconds. All good, until around in iteration number 40, I get this:

```java
2021-09-10 00:18:13.363  WARN [-] [] 1 --- [/10.233.0.1/...] i.j.o.p.e.i.CustomResourceEventSource    : Received error for watch, will try to reconnect.

io.fabric8.kubernetes.client.WatcherException: too old resource version: 181716961 (181717175)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onStatus(AbstractWatchManager.java:265)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:249)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:290)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:220)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:100)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:247)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:181)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 181716961 (181717175)
	... 12 common frames omitted

2021-09-10 00:18:13.366  INFO [-] [] 1 --- [/10.233.0.1/...] i.j.o.p.e.i.CustomResourceEventSource    : Closing watch 'workflowjobcontroller' Controller -> io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@5d573055
```

After it, no more events received because looks like from the above logs the controller watcher is closed.

Here is my SharedInformer:

```java
kubernetesClient.batch().v1().jobs().inAnyNamespace().withLabel("owner", "wo").inform(workflowJobInformer);
```
workflowJobInformer implements ResourceEventHandler.

The above error is the same I added in the beginning of this thread. Not sure what I am missing here.

**Comment by shawkins** [comment]
> io.fabric8.kubernetes.client.WatcherException: too old resource version

That is expected.  The resource version the watch was started against is now too old for kubernetes to track changes from.  The informer logic will automatically re-establish the watch off of a fresh listing and emit the appropriate events.

It appears that your code is calling close on the informer at some point.  After this it will stop watching and cannot be restarted.

**Comment by flavioschuindt** [comment]
Hi, @shawkins.

I was investigating more and last stacktrace is an issue with the javaoperatorsdk, not the informer. So, we are good in this case. I have one last question though: I see that the ```inform``` method is overloaded:

```java
  default SharedIndexInformer<T> inform(ResourceEventHandler<T> handler);
```

```java
SharedIndexInformer<T> inform(ResourceEventHandler<T> handler, long resync);
```
What is exactly the significance of the resync parameter? Looking at the java docs seems to be just a periodic interval where the informer will go in the cluster, do relist and update its own cache. Is that correct? Also, what happens if I don't use the resync? When use resync and when not?

Thank you once again for the valuable inputs.

**Comment by shawkins** [comment]
> Looking at the java docs seems to be just a periodic interval where the informer will go in the cluster, do relist and update its own cache. Is that correct?

A relist is not performed on a resync.  Relists are performed automatically when needed by the informer.  There is currently no mechanism to trigger them.

A resync simply produces an update event for each resource in the cache and supplies that update to interested handlers.

There are two resync values.  The one for the informer and the one for each event handler.

The one for the informer is generally the base rate at which resyncs are performed.  The one for each handler is then understood to be performed at some multiple of the base rate.

> Also, what happens if I don't use the resync?

Nothing - which is better than getting extra update events if you are not expecting them.

> When use resync and when not?

In my own usage of informers, I haven't come across a scenario where the built-in resync is useful.  But if you have something like a period reconciliation and you don't have any other means of scheduling that job, you could use the resync.

This all comes from the go client implementation, fabric8 is just trying to provide similar apis for anyone looking to port.

**Comment by flavioschuindt** [comment]
Got it, @shawkins. Your explanation is very useful and I learned a lot here. For now, I am closing this ticket as all my questions are answered and seems that the stack trace is related to the java operator sdk. I will opend this ticket if more information is needed. Once again, thank you!

**Comment by metacosm** [comment]
Thanks @shawkins for the explanations! That was indeed interesting.

**Comment by shawkins** [comment]
No problem.  It sounds like we need more javadocs on resync.
