### ISSUE TITLE
okhttp3 StreamResetException: stream was reset: NO_ERROR

### ISSUE THREAD

**Issue by csumutaskin** [fabric8io/kubernetes-client#3449]
` 
    Note that: io.fabric8.openshift.client.OpenShiftClient client and Map<String, String> data  are initialized above successfully.
   
    io.fabric8.kubernetes.api.model.ConfigMap configMap = new io.fabric8.kubernetes.api.model.ConfigMap();
    ObjectMeta objectMeta = new ObjectMeta();
    objectMeta.setNamespace("a namespace value here...");
    objectMeta.setName("a config map name here...");
    configMap.setMetadata(objectMeta);
    configMap.setData(data);
    client.configMaps().createOrReplace(configMap); 
    //at exactly the line above - when trying to create a ConfigMap for the OpenShift client - , a KubernetesClientException is thrown with the following stack trace:`

**Exception Thrown:**

   io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [ConfigMap]  with name: [ ...config name here...]  in namespace: [null]  failed.

**Stack trace below:**

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [ConfigMap]  with name: [......config name here......]  in namespace: [null]  failed.
                at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
                at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:374)
                at io.fabric8.kubernetes.client.utils.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:53)
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:412)
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:85)
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:395)
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:85)
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
                at okhttp3.internal.http2.Http2Stream.checkOutNotClosed(Http2Stream.java:628)
                at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:553)
                at okhttp3.internal.http2.Http2Stream$FramingSink.close(Http2Stream.java:600)
                at okio.ForwardingSink.close(ForwardingSink.java:47)
                at okio.RealBufferedSink.close(RealBufferedSink.java:248)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:133)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:69)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
                at okhttp3.RealCall.execute(RealCall.java:93)
                at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:472)
                at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435)
                at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:250)
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:871)
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:366)
                ... 79 more

**Details about my local environment, where I get the exception is:**

- My kubernetes-client jar version is 5.0.0
- I can reach the openshift environment from my local using the CLI tool (no network issues detected)
- I am using Intellij IDEA 2021.2 Ultimate as the IDE version. 
- My java run time env information is as follows:
        java version "1.8.0_161"
        Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
        Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by manusa** [comment]
Could you try to reproduce with the most recent release? (I recall we did some changes to the createOrReplace method since 5.0.0)

**Comment by rohanKanojia** [comment]
@csumutaskin: If I omit `objectMeta.setNamespace("a namespace value here...");` line your code works for me. Note that namespace is set in my current context:

```yaml
- context:
    cluster: api-***-openshiftapps-com:6443
    namespace: rokumar-dev
    user: rokumar/api-***-openshiftapps-com:6443
  name: rokumar-dev/api-sandbox-***-openshiftapps-com:6443/rokumar
```

If I set namespace to some other namespace(let's say `rokumar-stage`), I get namespace mismatch error:
```
Namespace mismatch. Item namespace:rokumar-stage. Operation namespace:rokumar-dev
```

**Comment by shawkins** [comment]
How big is the configmap?  I get the same error when creating an object where the json size over 500KB.

**Comment by jwojcie** [comment]
Hi

I accidentally stumbled up your issue, I think I had something similar. That one helped in my case, maybe it is relevant for you also:

https://stackoverflow.com/questions/35374030/invalid-http-method-patch-executing-patch-caused-by-feign-retryableexcepti

if not then I'm sorry. Good luck.
