### ISSUE TITLE
RejectedExecutionException / LogWatchCallback

### ISSUE THREAD

**Issue by DanielKastner-Baloise** [fabric8io/kubernetes-client#3498]
We're having troubles getting the log from our pod/container. Usually the first time it works fine. But the second time it fails with root cause RejectedExecutionException:
```
2021-09-28 10:25:00.181 ERROR 1 --- [RestartPodTask2] i.f.k.c.dsl.internal.LogWatchCallback    : Log Callback Failure.

java.io.InterruptedIOException: executor rejected
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:157) ~[okhttp-3.14.9.jar!/:na]
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:204) [okhttp-3.14.9.jar!/:na]
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:144) [okhttp-3.14.9.jar!/:na]
	at okhttp3.RealCall.enqueue(RealCall.java:93) [okhttp-3.14.9.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.watchLog(PodOperationsImpl.java:230) [kubernetes-client-5.7.3.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.watchLog(PodOperationsImpl.java:83) [kubernetes-client-5.7.3.jar!/:na]
	at x.y.z.RestartService.restart(RestartService.java:36) [classes!/:1.0.9]
	at x.y.z.RestartPodTask.run(RestartPodTask.java:27) [classes!/:1.0.9]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.3.6.jar!/:5.3.6]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) [spring-context-5.3.6.jar!/:5.3.6]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_275]
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@530a9708 rejected from java.util.concurrent.ThreadPoolExecutor@6d0ac035[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[na:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) [na:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) [na:1.8.0_275]
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:154) ~[okhttp-3.14.9.jar!/:na]
	... 16 common frames omitted
```
This is the code I'm using for doing this:
```
public class RestartService {

    private final OpenShiftClient openShiftClient;

    public RestartService(OpenShiftClient openShiftClient) {
        this.openShiftClient = openShiftClient;
    }

    public String restart(final String namespace, final String name, final String container) {
        final DeployableScalableResource<DeploymentConfig> deploymentConfigDeployableScalableResource = openShiftClient.deploymentConfigs().inNamespace(namespace).withName(name);
        ByteArrayOutputStream logOutputStream = new ByteArrayOutputStream();
        deploymentConfigDeployableScalableResource.scale(0);
        final NonNamespaceOperation<Pod, PodList, PodResource<Pod>> podsInNamespace = openShiftClient.pods().inNamespace(namespace);
        final String podId = podsInNamespace.list().getItems().get(0).getMetadata().getName();
        try {
            final LogWatch logWatch = podsInNamespace.withName(podId).inContainer(container).tailingLines(50).watchLog(logOutputStream);
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ie) {
                ie.printStackTrace();
            }
            logWatch.close();
        } catch (Exception e) {
            e.printStackTrace();
            try {
                logOutputStream.write("Exception reading Log from Pod:\n\n".getBytes(StandardCharsets.UTF_8));
                logOutputStream.write(e.toString().getBytes(StandardCharsets.UTF_8));
            } catch (IOException ioException) {
                ioException.printStackTrace();
            }
        }
        openShiftClient.close();
        try {
            return logOutputStream.toString("UTF-8");
        } catch (UnsupportedEncodingException uee) {
            uee.printStackTrace();
            return uee.toString();
        }
    }
}
```
I noticed that there has been a similar issue (#2299) which has been resolved last year and we're using version 5.7.3 of Kubernetes Client.

**Comment by shawkins** [comment]
openShiftClient.close(); - will close the threadpool used by the okhttp client.  That should cause the subsequent rejected executions.

**Comment by DanielKastner-Baloise** [comment]
> openShiftClient.close(); - will close the threadpool used by the okhttp client. That should cause the subsequent rejected executions.

Sounds like you could be right 😄 I'll check that out
