### ISSUE TITLE
kubernetes client with watcher doesn't seem to work on vanilla kubernetes

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#35]
I get this in the hubot-notifier when I remove the use of the custom $KUBERNETES_SERVICE_HOST env var pointing at DNS. 

```
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
Exception 0 :
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:110)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.getIfExists(BaseOperation.java:117)
	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1261)
	at io.fabric8.cdi.Services.toServiceUrl(Services.java:38)
	at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:47)
	at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:26)
	at io.fabric8.cdi.bean.ProducerBean.create(ProducerBean.java:42)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:761)
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:861)
	at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)
	at org.jboss.weld.injection.ConstructorInjectionPoint.getParameterValues(ConstructorInjectionPoint.java:150)
	at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:75)
	at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:116)
	at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:179)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:141)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
	at io.fabric8.hubot.notifier.KubernetesHubotNotifier$Proxy$_$$_WeldClientProxy.toString(Unknown Source)
	at io.fabric8.cdi.eager.EagerCDIExtension.afterDeploymentValidation(EagerCDIExtension.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:306)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:121)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:284)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:262)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:54)
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:447)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:143)
	at org.jboss.weld.environment.se.StartMain.go(StartMain.java:48)
	at org.jboss.weld.environment.se.StartMain.main(StartMain.java:58)
Caused by: java.util.concurrent.ExecutionException: java.net.UnknownHostException: kubernetes.default.svc.cluster.local: Name or service not known
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.abort(NettyRequestSender.java:420)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:288)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:140)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:115)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:87)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:517)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:229)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:466)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:499)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:108)
	... 48 more
Caused by: java.net.UnknownHostException: kubernetes.default.svc.cluster.local: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:922)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1316)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1269)
	at java.net.InetAddress.getAllByName(InetAddress.java:1185)
	at java.net.InetAddress.getAllByName(InetAddress.java:1119)
	at java.net.InetAddress.getByName(InetAddress.java:1069)
	at com.ning.http.client.NameResolver$JdkNameResolver.resolve(NameResolver.java:28)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.remoteAddress(NettyRequestSender.java:356)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.connect(NettyRequestSender.java:367)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:281)
	... 56 more

	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:37)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:447)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:143)
	at org.jboss.weld.environment.se.StartMain.go(StartMain.java:48)
	at org.jboss.weld.environment.se.StartMain.main(StartMain.java:58)
```

**Comment by jstrachan** [comment]
looks like this code
https://github.com/fabric8io/kubernetes-client/blob/9df08b6128b19c07437f4df60ab7fa0aacfe1b54/src/main/java/io/fabric8/kubernetes/client/DefaultKubernetesClient.java#L306

I wonder can we just use the traditional $KUBERNETES_SERVICE_HOST / $KUBERNETES_SERVICE_PORT?

**Comment by iocanel** [comment]
Agree

**Comment by jstrachan** [comment]
Just trying a patch...

**Comment by jstrachan** [comment]
Hmm doesn't seem to work - no idea why - the URL looks right to me:
```
masterUrl: https://10.254.0.1:443/api/v1/
Starting HubotNotifier using address: http://10.254.59.240:8080
About to get: https://10.254.0.1:443/api/v1/namespaces/default/services/fabric8
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
Exception 0 :
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:111)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.getIfExists(BaseOperation.java:118)
	at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1261)
	at io.fabric8.cdi.Services.toServiceUrl(Services.java:38)
	at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:47)
	at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:26)
	at io.fabric8.cdi.bean.ProducerBean.create(ProducerBean.java:42)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:761)
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:861)
	at org.jboss.weld.injection.ParameterInjectionPointImpl.getValueToInject(ParameterInjectionPointImpl.java:76)
	at org.jboss.weld.injection.ConstructorInjectionPoint.getParameterValues(ConstructorInjectionPoint.java:150)
	at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:75)
	at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:116)
	at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:179)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:141)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
	at io.fabric8.hubot.notifier.KubernetesHubotNotifier$Proxy$_$$_WeldClientProxy.toString(Unknown Source)
	at io.fabric8.cdi.eager.EagerCDIExtension.afterDeploymentValidation(EagerCDIExtension.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:306)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:121)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:284)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:262)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:54)
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:447)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:143)
	at org.jboss.weld.environment.se.StartMain.go(StartMain.java:48)
	at org.jboss.weld.environment.se.StartMain.main(StartMain.java:58)
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException: connection timed out: /10.254.0.1:443
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:135)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:143)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:142)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: connection timed out: /10.254.0.1:443
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:131)
	... 13 more
Caused by: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: /10.254.0.1:443
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:139)
	... 8 more

	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:37)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:447)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:143)
	at org.jboss.weld.environment.se.StartMain.go(StartMain.java:48)
	at org.jboss.weld.environment.se.StartMain.main(StartMain.java:58)
```

**Comment by jimmidyson** [comment]
Are you sure the service ip is correct? Looks like network issues if it is. We should 100% be able to rely on DNS. Any issues relating to DNS should be reported to openshift or kubernetes.

**Comment by jstrachan** [comment]
@jimmidyson DNS is definitely not working on vanilla kubernetes - see the first stack trace

**Comment by jstrachan** [comment]
FWIW is is when using our kubernetes vagrant image: https://github.com/fabric8io/fabric8-installer/tree/master/vagrant/kubernetes/latest

**Comment by jimmidyson** [comment]
On kubernetes isn't DNS an add-on, deployed by default using the normal deploy scripts, but I guess not if you're using the binaries directly. We should be able to assume DNS is available as it will be almost always & we should ensure it's deployed in our vagrant box.

**Comment by jstrachan** [comment]
@jimmidyson so its always available - except when its not right? :) DNS FTW

**Comment by jstrachan** [comment]
is it still true that we can't use $KUBERNETES_SERVICE_HOST / $KUBERNETES_SERVICE_PORT - which always always set in k8s however you run it (when clearly DNS is not)? 

The main reason for switching to DNS was due to that cert issue with the $KUBERNETES_SERVICE_HOST IP address right - is that still the case?

**Comment by jimmidyson** [comment]
Not my fault you didn't follow the kubernetes deployment instructions ;)

Switching to DNS will solve the server cert issue. On kubernetes using the ip should also work but annoyingly not on openshift -they rejected adding it to the cert SANs

**Comment by jstrachan** [comment]
any volunteers for figuring out the DNS installation magic for kubernetes on our vagrant box?
https://github.com/fabric8io/fabric8-installer/tree/master/vagrant/kubernetes/latest

**Comment by jimmidyson** [comment]
See https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/README.md

**Comment by jstrachan** [comment]
tried this - but no luck 
https://gist.github.com/jstrachan/2ffcee7babe38ace9f1c

**Comment by jimmidyson** [comment]
Solution is to either use configure DNS or to set `KUBERNETES_MASTER` env var to `https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}` & `KUBERNETES_TRUST_CERTIFICATES=true`.

DNS should be preferred option.
