### ISSUE TITLE
NPE in BuildConfigOperationsImpl.submitToApiServerWithRequestBody

### ISSUE THREAD

**Issue by simkam** [fabric8io/kubernetes-client#3501]
We have a code like 
```
OpenShiftClient client = new DefaultOpenShiftClient();
InputStream dummy = new ByteArrayInputStream("".getBytes());
client.buildConfigs().withName("testBC").instantiateBinary().fromInputStream(dummy);
```
which started throwing NPE after upgrade to 5.7.x
```
Exception in thread "main" java.lang.NullPointerException: unit == null
	at okhttp3.internal.Util.checkDuration(Util.java:496)
	at okhttp3.OkHttpClient$Builder.readTimeout(OkHttpClient.java:596)
	at io.fabric8.openshift.client.dsl.internal.build.BuildConfigOperationsImpl.submitToApiServerWithRequestBody(BuildConfigOperationsImpl.java:283)
	at io.fabric8.openshift.client.dsl.internal.build.BuildConfigOperationsImpl.fromInputStream(BuildConfigOperationsImpl.java:186)
	at io.fabric8.openshift.client.dsl.internal.build.BuildConfigOperationsImpl.fromInputStream(BuildConfigOperationsImpl.java:167)
	at io.fabric8.openshift.client.dsl.internal.build.BuildConfigOperationsImpl.fromInputStream(BuildConfigOperationsImpl.java:72)
	at reproducer.NpeReproducer.main(NpeReproducer.java:29)
```

The same code worked with 4.13.3.

**Comment by shawkins** [comment]
Please call withTimeout or withTimeoutInMilliseconds as a workaround. This is a regression from #3364 changes - since there's nothing calling a method that alters the BuildConfigOperationContext, the timeout field is being left as null.  I'll open a pr with a fix.

**Comment by shawkins** [comment]
> so withTimeoutInMillis might not help.

Seems strange.  Those calls make this work locally for me.  In any case, see #3508
