### ISSUE TITLE
Throw a meanful exception error instead of NPE when no plurals are set

### ISSUE THREAD

**Issue by lordofthejars** [fabric8io/kubernetes-client#3620]
### Is your enhancement related to a problem? Please describe

When you create manually a `ResourceDefinitionContext` and you don't set the plurals field a NPE exception is thrown  when you get it using the Kubernetes client 

```
final ResourceDefinitionContext resourceDefinitionContext = new ResourceDefinitionContext.Builder()
            .withGroup("networking.istio.io")
            .withVersion("v1alpha3")
            .withKind("VirtualService")
            .build();

        System.out.println("Namespace: " + namespace);

        final GenericKubernetesResource virtualResource = kubernetesClient.genericKubernetesResources(resourceDefinitionContext).inNamespace(namespace).withName(virtualServiceName).get();

```

```
Caused by: java.lang.NullPointerException
	at java.base/java.net.URI$Parser.parse(URI.java:3129)
	at java.base/java.net.URI.<init>(URI.java:623)
	at io.fabric8.kubernetes.client.utils.URLUtils.join(URLUtils.java:50)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.getNamespacedUrl(OperationSupport.java:164)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.getNamespacedUrl(OperationSupport.java:169)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getCompleteResourceUrl(BaseOperation.java:818)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:188)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:156)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:89)
```

### Describe the solution you'd like

Inform why it is failing.

**Comment by shawkins** [comment]
Let's make sure that kind is required, then default to default to pluralizing the kind if plural is not specified.
