### ISSUE TITLE
Cannot instantiate DefaultKubernetesClient due to NoSuchMethodError

### ISSUE THREAD

**Issue by youngbo89** [fabric8io/kubernetes-client#3633]
### Describe the bug

When create DefaultKubernetesClient(), there is a java exception

### Fabric8 Kubernetes Client version

5.9.0

### Steps to reproduce

1. Create DefaultKubernetesClient
```java
        MyKubernetesInfo info;
        Config config = new ConfigBuilder()
                .withMasterUrl(info.getUrl())
                .withOauthToken(info.getToken())
                .withDisableHostnameVerification(true)
                .withTrustCerts(true)
                .build();

        return new DefaultKubernetesClient(config);
```
2. See the exception

### Expected behavior

DefaultKubernetesClient() should be instantiated like version `5.4.1`

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
java.lang.NoSuchMethodError: 'java.lang.String io.fabric8.kubernetes.api.model.HasMetadata.getGroup(java.lang.Class)'
	at io.fabric8.kubernetes.client.dsl.base.ResourceDefinitionContext.fromResourceType(ResourceDefinitionContext.java:51) ~[kubernetes-client-5.9.0.jar:na]
	at io.fabric8.kubernetes.client.ResourceHandlerImpl.<init>(ResourceHandlerImpl.java:43) ~[kubernetes-client-5.9.0.jar:na]
	at io.fabric8.kubernetes.client.Handlers.register(Handlers.java:50) ~[kubernetes-client-5.9.0.jar:na]
	at io.fabric8.kubernetes.client.BaseKubernetesClient.<clinit>(BaseKubernetesClient.java:132) ~[kubernetes-client-5.9.0.jar:na]
	at MyPackage.getNewKubernetesClient(Fabric8KubernetesApiClientPool.java:70) ~[main/:na]
```

### Additional context
Kubernetes API version: `1.18`, `1.21`
That code snippet worked at the lib version `5.4.1`

**Comment by rohanKanojia** [comment]
@KHU-YoungBo : Could you please share some reproducer project? Is there any `<exclusion>` in your project regarding Kubernetes model dependencies ?

**Comment by KHU-YoungBo** [comment]
1. I'm using gradle, so here is gradle configuration and there is no `exclusion`:
```
dependencies {
	implementation 'io.fabric8:kubernetes-client:5.10.1'
}
```

There is the same error exceptions -
```
java.lang.NoSuchMethodError: 'java.lang.String io.fabric8.kubernetes.api.model.HasMetadata.getGroup(java.lang.Class)'
	at io.fabric8.kubernetes.client.dsl.base.ResourceDefinitionContext.fromResourceType(ResourceDefinitionContext.java:51) ~[kubernetes-client-5.10.1.jar:na]
	at io.fabric8.kubernetes.client.ResourceHandlerImpl.<init>(ResourceHandlerImpl.java:43) ~[kubernetes-client-5.10.1.jar:na]
	at io.fabric8.kubernetes.client.Handlers.register(Handlers.java:50) ~[kubernetes-client-5.10.1.jar:na]
	at io.fabric8.kubernetes.client.BaseKubernetesClient.<clinit>(BaseKubernetesClient.java:133) ~[kubernetes-client-5.10.1.jar:na]
	at Fabric8KubernetesApiClientPool.getNewKubernetesClient(Fabric8KubernetesApiClientPool.java:70) ~[main/:na]

``` 


The code behave depending on lib ver:
- 5.4.1: WORK
- 5.9.0 : NOT WORK
- 5.10.1: NOT WORK, too.

**Comment by KHU-YoungBo** [comment]
I found something.. I think there is a conflict with `Spring-Cloud`

## Without Spring cloud
In `build.gradle`:
```
dependencies {
	implementation 'com.fasterxml.jackson.core:jackson-core:2.12.3'
	implementation 'io.fabric8:kubernetes-client:5.7.0'
}
```

Result:
```
11:41:59 AM: Executing task 'MyTest.main()'...

> Task :compileJava
> Task :processResources UP-TO-DATE
> Task :classes

> Task :MyTest.main()
```


## with spring-cloud configuration

In `build.gradle`:
```
ext {
	set('springCloudVersion', "2020.0.3")
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

dependencies {
	implementation 'com.fasterxml.jackson.core:jackson-core:2.12.3'
	implementation 'io.fabric8:kubernetes-client:5.7.0'
}
```

Result: 
```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String io.fabric8.kubernetes.api.model.HasMetadata.getGroup(java.lang.Class)'
	at io.fabric8.kubernetes.client.dsl.base.ResourceDefinitionContext.fromResourceType(ResourceDefinitionContext.java:60)
	at io.fabric8.kubernetes.client.ResourceHandlerImpl.<init>(ResourceHandlerImpl.java:42)
	at io.fabric8.kubernetes.client.Handlers.register(Handlers.java:49)
	at io.fabric8.kubernetes.client.BaseKubernetesClient.<clinit>(BaseKubernetesClient.java:133)
	at com.samsung.sco.dso.cnf.monitoring.operation.MyTest.main(MyTest.java:7)

Execution failed for task ':MyTest.main()'.
```

## Compatibility table
Just for creating test of `DefaultKubernetesClient` Object.

The result is depends on the version of `spring-cloud` and  `fabric8-kubernetes`

| version                  | Spring-Cloud-Version | Result With   Spring-Cloud | Without Spring   cloud |  
|--------------------------|----------------------|----------------------------|------------------------|
| kubernetes-client-5.4.1  | 2020.0.3             | O                          | O                      |   
| kubernetes-client-5.6.0  | 2020.0.3             | O                          | O                      |   
| kubernetes-client-5.7.0  | 2020.0.3             | X                          | O                      |   
| kubernetes-client-5.8.0  | 2020.0.3             | X                          | O                      |   
| kubernetes-client-5.11.0 | 2020.0.3             | X                          | O                      |

**Comment by manusa** [comment]
> Compatibility table [...]

Thanks for this, I think that this issue might be affecting others, since we are seeing similar reports of classes clashing.

I'm not sure what version Spring Cloud is running on, but it might be worthy to spend some of our time updating the dependency there.
