### ISSUE TITLE
Expected a single document in the stream

### ISSUE THREAD

**Issue by ParriePierre** [fabric8io/kubernetes-client#3648]
### Describe the bug

Hello,

Kubernetes-client cannot read documents that contains one ressource and end with "---", snakeyaml throws exception "expected a single document in the stream".
It used to work with kubernetes-client 4.13.3.

Using Kubernetes-client:4.13.0, this used to work.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

Using example LoadMultipleDocumentsFromFileExample, modify the file multiple-document-template.yml to keep only one resource and ending the file with "---" : 

```
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    tier: backend
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: backend
    role: master
---
```

snakeyaml throws exception 

```
expected a single document in the stream
 in 'reader', line 17, column 1:
    apiVersion: v1
    ^
but found another document
 in 'reader', line 33, column 1:
    ---
    ^

	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:114)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:452)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshalYaml(Serialization.java:369)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:191)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:156)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.getItems(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:81)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.getOperations(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:92)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.accept(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:215)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.accept(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:53)
	at com.dassault_systemes.infra.cloud.kubernetes.driver.action.LoadMultipleDocumentsFromFileExampleTest.test(LoadMultipleDocumentsFromFileExampleTest.java:49)
```

### Expected behavior

Kubernetes-client should be able to serialize YAML files that have only one resource and ends with "---".

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Additional context

Issue is not related to K8S API.

**Comment by rohanKanojia** [comment]
I can reproduce this issue. While processing YAML document, I can see YAML document is parsed correctly; however, since it's just one document this condition is not satisfied:

https://github.com/fabric8io/kubernetes-client/blob/ef50b9069e19da1b401c16f004c15e49c9822b56/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java#L325-L329

This behavior seems to be correct. Since it's only a single document control goes to Single document unmarshal method. But at this point there is still `---` present in YAML document which causes the error.

https://github.com/fabric8io/kubernetes-client/blob/ef50b9069e19da1b401c16f004c15e49c9822b56/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Serialization.java#L153-L156

Removing leading/trailing Document delimiters `---` should fix this issue.

**Comment by ParriePierre** [comment]
Thank you very much @rohanKanojia !

**Comment by rohanKanojia** [comment]
@ParriePierre : Np, Would appreciate if you could also review my PR :-)
