### ISSUE TITLE
HTTP(S) Proxy Port is not Defaulted or Validated

### ISSUE THREAD

**Issue by andrewm-aero** [fabric8io/kubernetes-client#3671]
### Describe the bug

In https://github.com/fabric8io/kubernetes-client/blob/v5.10.1/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L201 , the proxy port is not assigned a default, if not provided in the URL, resulting in `java.lang.IllegalArgumentException: port out of range:-1`.

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

Set HTTP_PROXY or HTTPS_PROXY environment variables to a URL without a port, attempt to connect to a k8s api server through a proxy (or neglect to add your api server to NO_PROXY if it shouldn't be proxied)

### Expected behavior

The proxy port to be assigned a sensible default based on the protocol, or for an informative exception to be thrown indicating that the port is required.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.21.6

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
2021-12-21 19:44:47.108+0000 [id=32]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed KubernetesCredentialProvider.startWatchingForSecrets
java.lang.IllegalArgumentException: port out of range:-1
        at java.base/java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
        at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:201)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:85)
        at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:53)
        at io.fabric8.kubernetes.client.BaseKubernetesClient.<init>(BaseKubernetesClient.java:159)
        at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:40)
        at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.KubernetesCredentialProvider.getKubernetesClient(KubernetesCredentialProvider.java:97)   
        at com.cloudbees.jenkins.plugins.kubernetes_credentials_provider.KubernetesCredentialProvider.startWatchingForSecrets(KubernetesCredentialProvider.java:109)
```

### Additional context

Using as part of the jenkins kubernetes credentials provider plugin.

**Comment by rohanKanojia** [comment]
@andrewm-aero : Thanks for reporting, I can reproduce this issue with this unit test:

```java
  @Test
  void getProxyUrl_whenHttpsProxyUrlProvided_shouldReturnValidProxyUrl() throws MalformedURLException {
    // Given
    Config config = new ConfigBuilder()
      .withMasterUrl("http://localhost")
      .withHttpProxy("http://192.168.0.1")
      .build();

    // When
    URL url = HttpClientUtils.getProxyUrl(config);

    // Then
    assertThat(url).isNotNull();
    assertThat(url.getHost()).isEqualTo("192.168.0.1");
    assertThat(url.getPort()).isEqualTo(-1);
  }
```

How shall we proceed here? Shall we provide some default value in case port is found `-1`? Would the default value would be `3128`? Or do we want to throw IllegalArgumentException when port is `-1`?

**Comment by rohanKanojia** [comment]
@andrewm-aero : I've created a PR for throwing IllegalArgumentException when port isn't resolved. Please let me know what you think about this.
