### ISSUE TITLE
Could not receive any events using shared informer in a vert.x application due to okhttp3 call gets rejected

### ISSUE THREAD

**Issue by marshopy** [fabric8io/kubernetes-client#3791]
### Describe the bug

When deploy our vertx application to openshift and use sharedinformer to track the change of the k8s custom resources, the watch has been failed to established and no add/update/delete event can be tracked

### Fabric8 Kubernetes Client version

5.10.1@latest

### Steps to reproduce

1. Create a vertx verticle below and stand up a shared informer event listener to watch a custom resource
2. After running on Openshift 4.8, found the below exception

``` Exception: An error has occurred.
       ...
Caused by: java.io.InterruptedIOException: executor rejected
        at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:186)
        at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186)
        at okhttp3.Dispatcher.enqueue(Dispatcher.java:137)
        at okhttp3.RealCall.enqueue(RealCall.java:127)
        at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193)
        at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
        at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl.buildAsync(OkHttpWebSocketImpl.java:55)
        ... 15 common frames omitted
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@57480e4f rejected from java.util.concurrent.ThreadPoolExecutor@1cc40243[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
        at  ```
3. Watch is down and no ADD/UPDATE/DELETE events will be captured

The main code is listed as attached file.
[WatchVerticle.java.zip](https://github.com/fabric8io/kubernetes-client/files/7961734/WatchVerticle.java.zip)



### Expected behavior

All events can be watched through using event informer API

### Runtime

OpenShift

### Kubernetes API Server version

1.21.6

### Environment

Dev Sandbox (workspaces.openshift.com)

### Fabric8 Kubernetes Client Logs

```shell
Exception: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:103)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:97)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.lambda$run$2(WatchConnectionManager.java:133)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946)
        at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.run(WatchConnectionManager.java:112)
        at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.runWatch(AbstractWatchManager.java:225)
        at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.<init>(AbstractWatchManager.java:92)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:72)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:79)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:570)
        at io.fabric8.kubernetes.client.informers.cache.Reflector.startWatcher(Reflector.java:106)
        at io.fabric8.kubernetes.client.informers.cache.Reflector.listSyncAndWatch(Reflector.java:96)
        at io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer.run(DefaultSharedIndexInformer.java:146)
        at io.fabric8.kubernetes.client.informers.SharedInformerFactory.lambda$startInformerAsync$2(SharedInformerFactory.java:359)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: java.lang.Throwable: waiting here
                at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:168)
                at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:179)
                at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:96)
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:572)
                ... 9 common frames omitted
Caused by: java.io.InterruptedIOException: executor rejected
        at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:186)
        at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186)
        at okhttp3.Dispatcher.enqueue(Dispatcher.java:137)
        at okhttp3.RealCall.enqueue(RealCall.java:127)
        at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193)
        at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
        at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl.buildAsync(OkHttpWebSocketImpl.java:55)
        ... 15 common frames omitted
```

### Additional context
Test the same code but using ConfigMap instead of a CRD, resulting the same issue
_No response_

**Comment by shawkins** [comment]
The dispatcher threadpool appears to have been shutdown.  This could happen with a call to KubernetesClient.close, or if you customized the creation of the HttpClient and shutdown the threadpool you associated with the dispatcher.

**Comment by marshopy** [comment]
Yes. Just noted the thread has been shutdown due to the inappropriate vertx integration here. The blocking code is not executed properly. I will close this issue as I had worked it out after adjusting the verticle configurations and implementations. Thanks for the reply
