### ISSUE TITLE
No adapter available for type:class io.fabric8.kubernetes.client.AppsAPIGroupClient

### ISSUE THREAD

**Issue by prabhjotlalli** [fabric8io/kubernetes-client#3847]
### Describe the bug

I try to create and replace my stateful set after editing anything. For example:
``` java
var statefulSet = loadYaml(StatefulSet.class, "/kubernetes/statefulset.yaml");
    statefulSet
        .getSpec()
        .getTemplate()
        .getSpec()
        .getContainers()
        .get(1)
        .setArgs(List.of("--release_channel=test"));
    kubernetesClient
        .apps()
        .statefulSets()
        .inNamespace(resource.getMetadata().getNamespace())
        .createOrReplace(statefulSet);
```

I get the following exception:

```
11:52:26.535 [EventHandler-my-servicereconciler] ERROR i.j.o.p.e.ReconciliationDispatcher - Error during event processing ExecutionScope{ resource id: CustomResourceID{name='my-service', namespace='my-namespace'}, version: 510444777} failed.
java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.AppsAPIGroupClient
	at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:109)
	at io.fabric8.kubernetes.client.BaseKubernetesClient.apps(BaseKubernetesClient.java:527)
	at com.mycompany.mypackage.operator.MyServiceReconciler.reconcile(MyServiceReconciler.java:96)
	at com.mycompany.mypackage.operator.MyServiceReconciler.reconcile(MyServiceReconciler.java:23)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:101)
	at io.javaoperatorsdk.operator.processing.Controller$2.execute(Controller.java:76)
	at io.javaoperatorsdk.operator.api.monitoring.Metrics.timeControllerExecution(Metrics.java:34)
	at io.javaoperatorsdk.operator.processing.Controller.reconcile(Controller.java:75)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.reconcileExecution(ReconciliationDispatcher.java:151)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleReconcile(ReconciliationDispatcher.java:117)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleDispatch(ReconciliationDispatcher.java:82)
	at io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher.handleExecution(ReconciliationDispatcher.java:51)
	at io.javaoperatorsdk.operator.processing.event.EventProcessor$ControllerExecution.run(EventProcessor.java:385)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

My pom.xml which brings in 

io.fabric8 | kubernetes-client | 5.12.0 

```xml
<dependency>
  <groupId>io.javaoperatorsdk</groupId>
  <artifactId>operator-framework</artifactId>
  <version>2.1.1</version>
</dependency>

<dependency>
  <groupId>io.fabric8</groupId>
  <artifactId>crd-generator-apt</artifactId>
  <version>5.12.0</version>
  <scope>provided</scope>
</dependency>
```

I also have a somewhat weird annotation setup to get it working with Dagger. I'm not sure if this would cause issues.

```xml
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.8.0</version>
  <configuration>
    <annotationProcessorPaths>
      <path>
        <groupId>com.google.dagger</groupId>
        <artifactId>dagger-compiler</artifactId>
        <version>2.16</version>
      </path>
      <path>
        <groupId>io.fabric8</groupId>
        <artifactId>crd-generator-apt</artifactId>
        <version>5.12.0</version>
      </path>
    </annotationProcessorPaths>
    <compilerArgs>
      <arg>-Xlint:deprecation,-options,-path</arg>
      <arg>-XDignore.symbol.file</arg>
    </compilerArgs>
    <fork>true</fork>
  </configuration>
</plugin>
```

More oddly if I point to my main and run through IntelliJ it works fine. It only throws this exception after creating the jar with dependencies and running from the jar. I'm assuming I'm missing something trivial but any pointers to how I can debug this?

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

1. Running from Intellij works.
2. Running jar with dependencies from command line throws exception.

### Expected behavior

Statefulset to update.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.20.12

### Environment

macOS

**Comment by shawkins** [comment]
> It only throws this exception after creating the jar with dependencies and running from the jar.

This adapter is made available normally by kubernetes-client jar META-INF/services/io.fabric8.kubernetes.client.ExtensionAdapter - it has an entry for io.fabric8.kubernetes.client.AppsAPIGroupExtensionAdapter

If this file has been omitted / replaced in the jar that dagger is creating, then you'll see this exception.

**Comment by prabhjotlalli** [comment]
You're right that file is the issue. But only `io.fabric8.openshift.client` are appearing, `io.fabric8.kubernetes.client` are not in the file.

**Comment by prabhjotlalli** [comment]
The issue was with `maven-assembly-plugin`. Swapped to `maven-assembly-plugin` and it works great. Thanks again @shawkins
