### ISSUE TITLE
Errors in the Karaf platform logs

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#3890]
The platform test logs are filled with.  This occurred before and after #3865 - so need to check further back if it was occurring before the api split.

```
2022-02-23T10:23:59,522 | WARN  | features-3-thread-1 | BaseActivator                    | 62 - org.apache.aries.spifly.dynamic.bundle - 1.3.0 | Could not load provider io.fabric8.openshift.client.OpenShiftHiveAPIGroupExtensionAdapter of service io.fabric8.kubernetes.client.ExtensionAdapter
java.lang.NullPointerException: null
	at org.apache.aries.spifly.BaseActivator.lambda$registerProviderBundle$3(BaseActivator.java:268) ~[?:?]
	at java.util.Map.compute(Map.java:1171) ~[?:?]
	at java.util.Collections$SynchronizedMap.compute(Collections.java:2692) ~[?:?]
	at org.apache.aries.spifly.BaseActivator.registerProviderBundle(BaseActivator.java:261) ~[?:?]
	at org.apache.aries.spifly.ProviderBundleTrackerCustomizer.addingBundle(ProviderBundleTrackerCustomizer.java:173) ~[?:?]
	at org.apache.aries.spifly.ProviderBundleTrackerCustomizer.addingBundle(ProviderBundleTrackerCustomizer.java:64) ~[?:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475) ~[osgi.core-7.0.0.jar:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:420) ~[osgi.core-7.0.0.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[osgi.core-7.0.0.jar:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[osgi.core-7.0.0.jar:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) ~[osgi.core-7.0.0.jar:?]
	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915) ~[?:?]
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834) ~[?:?]
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516) ~[?:?]
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4817) ~[?:?]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2393) ~[?:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308) ~[?:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[?:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[?:?]
	at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160) ~[?:?]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

I'd like for things to be clean before addressing #3878

**Comment by shawkins** [comment]
These errors are present in the 5.12.1 log as well, so I will consider them separate from the api and extension work.  I guess the karaf tests need updated to use adapt calls to see if these built-in extensions actually work as expected.

**Comment by manusa** [comment]
Did the changes in the pom.xml configurations fix the issue?

**Comment by manusa** [comment]
> Did the changes in the pom.xml configurations fix the issue?

@rohanKanojia  ?
