### ISSUE TITLE
Suggestions on log level

### ISSUE THREAD

**Issue by saowu** [fabric8io/kubernetes-client#3920]
### Is your enhancement related to a problem? Please describe

java.io.InterruptedIOException: thread interrupted
at okio.Timeout.throwIfReached(Timeout.java:145)
at okio.Okio$2.read(Okio.java:136)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
at okio.RealBufferedSource.request(RealBufferedSource.java:67)
at okio.RealBufferedSource.require(RealBufferedSource.java:60)
at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:294)
at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
at io.fabric8.kubernetes.client.utils.InputStreamPumper.transferTo(InputStreamPumper.java:76)
at io.fabric8.kubernetes.client.utils.InputStreamPumper.lambda$pump$0(InputStreamPumper.java:89)
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)

### Describe the solution you'd like

It seems that the log level here should not be error, because this often happens

**Comment by shawkins** [comment]
It seems that okhttp is throwing an InterruptedIOException, but not actually interrupting the thread:

https://github.com/fabric8io/kubernetes-client/blob/677884ca88f3911f9b41ec919db152d441ad2cdd/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/utils/InputStreamPumper.java#L91

If it were, this would be at a debug level.  The check will need to be expanded to include InterruptedIOException

**Comment by sunix** [comment]
Hi @saowu would you be interested to provide a PR? :)

**Comment by saowu** [comment]
Sorry, the code format doesn't pass. I don't know how to pass the check. Modify it yourself. I have too little experience.

**Comment by rohanKanojia** [comment]
@saowu : Please don't close your PR. We can address these code format issues before merging this PR

**Comment by sunix** [comment]
Fixed with https://github.com/fabric8io/kubernetes-client/pull/3976
Thanks a lot @saowu !!!
