### ISSUE TITLE
Executor rejected when watching deployments in a Runnable

### ISSUE THREAD

**Issue by subnetmarco** [fabric8io/kubernetes-client#4025]
### Describe the bug

I am watching deployments in a `Runnable` class with:

```java
  @Override
  public void run() {
    kubernetesClient.apps().deployments().watch(new Watcher<Deployment>() {
       ..
    }
  }
```

And I get the following error when the `Runnable` is being initiated in a `Thread`:

```
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
```

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

`client.watch(..)` in a `Runnable` class that is initialized with either a `Thread` or `ExecutorService`.

### Expected behavior

I would expect the exception to not happen.

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:103) ~[kubernetes-client-5.12.1.jar:na]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:97) ~[kubernetes-client-5.12.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.lambda$run$2(WatchConnectionManager.java:133) ~[kubernetes-client-5.12.1.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2340) ~[na:na]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.run(WatchConnectionManager.java:112) ~[kubernetes-client-5.12.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.runWatch(AbstractWatchManager.java:225) ~[kubernetes-client-5.12.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.<init>(AbstractWatchManager.java:92) ~[kubernetes-client-5.12.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:72) ~[kubernetes-client-5.12.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:79) ~[kubernetes-client-5.12.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:570) ~[kubernetes-client-5.12.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:547) ~[kubernetes-client-5.12.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:83) ~[kubernetes-client-5.12.1.jar:na]
	at com.test.TestJob.run(TestJob.java:56) ~[classes/:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
	Suppressed: java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:168) ~[kubernetes-client-5.12.1.jar:na]
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:179) ~[kubernetes-client-5.12.1.jar:na]
		at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:96) ~[kubernetes-client-5.12.1.jar:na]
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:572) ~[kubernetes-client-5.12.1.jar:na]
		... 4 common frames omitted
Caused by: java.io.InterruptedIOException: executor rejected
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:186) ~[okhttp-3.12.12.jar:na]
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186) ~[okhttp-3.12.12.jar:na]
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:137) ~[okhttp-3.12.12.jar:na]
	at okhttp3.RealCall.enqueue(RealCall.java:127) ~[okhttp-3.12.12.jar:na]
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193) ~[okhttp-3.12.12.jar:na]
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435) ~[okhttp-3.12.12.jar:na]
	at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl.buildAsync(OkHttpWebSocketImpl.java:55) ~[kubernetes-client-5.12.1.jar:na]
	... 10 common frames omitted
Caused by: java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@25f0e745 rejected from java.util.concurrent.ThreadPoolExecutor@31cc6ad7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365) ~[na:na]
	at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:183) ~[okhttp-3.12.12.jar:na]
	... 16 common frames omitted
```

### Additional context

kubernetes-client version 5.12.1 running with a Kubernetes mock server in a JUnit test.

**Comment by shawkins** [comment]
Something has closed the KubernetesClient.

**Comment by subnetmarco** [comment]
You are absolutely right @shawkins, this was the cause of my problem. Closing this issue now.
