### ISSUE TITLE
When calling client.templates().inAnyNamespace().list(), java.lang.NoSuchMethodError is raised.

### ISSUE THREAD

**Issue by ho-yasla** [fabric8io/kubernetes-client#4075]
```java
client = OpenShiftConnect.getConnectClient().getClient().adapt(OpenShiftClient.class);
 ` templateList = client.templates().inAnyNamespace().list();
```

```
java.lang.NoSuchMethodError: io.fabric8.kubernetes.internal.KubernetesDeserializer.isInTemplate()Z
	at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.shouldUseAnySetter(SettableBeanPropertyDelegate.java:175)
	at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:133)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:131)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3295)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.fromObjectNode(KubernetesDeserializer.java:87)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:57)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:46)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:131)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:131)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:317)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:271)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:557)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518)
	at io.fabric8.openshift.client.dsl.internal.core.TemplateOperationsImpl.handleResponse(TemplateOperationsImpl.java:287)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:133)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:415)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:404)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:83)
	at com.innogrid.tabcloudit.openshift.workloads.template.service.TemplateService.selectTemplateList(TemplateService.java:103)
	at com.innogrid.tabcloudit.openshift.workloads.template.api.TemplateController.selectTemplateList(TemplateController.java:31)
	at com.innogrid.tabcloudit.openshift.workloads.template.api.TemplateController$$FastClassBySpringCGLIB$$3ee7af68.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.innogrid.tabcloudit.openshift.workloads.template.api.TemplateController$$EnhancerBySpringCGLIB$$43195454.selectTemplateList(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by shawkins** [comment]
You have an issue in your dependency structure - you must have a mismatched kubernetes-model-core.  Check your dependency tree to see where this a mis-alignment.

**Comment by ho-yasla** [comment]
> You have an issue in your dependency structure - you must have a mismatched kubernetes-model-core. Check your dependency tree to see where this a mis-alignment.
![image](https://user-images.githubusercontent.com/92026433/164749782-9bdd1501-b839-4cf7-ae4c-50b8f118035b.png)

A few new dependencies were made. But the symptoms are the same. The same error is occurring locally with all developers working together.

**Comment by ho-yasla** [comment]
static class Mapping {

        private static final String KEY_SEPARATOR = "#";

        // n.b. Packages sorted in order of precedence, deserialization of resources with no
        // specific version will default to first available Class in one of these packages:
        private static final String[] PACKAGES = {
                "io.fabric8.kubernetes.api.model.",
                "io.fabric8.kubernetes.api.model.admission.v1.",
                "io.fabric8.kubernetes.api.model.admission.v1beta1.",
                "io.fabric8.kubernetes.api.model.admissionregistration.v1.",
                "io.fabric8.kubernetes.api.model.admissionregistration.v1beta1.",
                "io.fabric8.kubernetes.api.model.authentication.",
                "io.fabric8.kubernetes.api.model.authorization.v1.",
                "io.fabric8.kubernetes.api.model.authorization.v1beta1.",
                "io.fabric8.kubernetes.api.model.apiextensions.v1.",
                "io.fabric8.kubernetes.api.model.apiextensions.v1beta1.",
                "io.fabric8.kubernetes.api.model.apps.",
                "io.fabric8.kubernetes.api.model.autoscaling.v1.",
                "io.fabric8.kubernetes.api.model.autoscaling.",
                "io.fabric8.kubernetes.api.model.autoscaling.v2beta1.",
                "io.fabric8.kubernetes.api.model.autoscaling.v2beta2.",
                "io.fabric8.kubernetes.api.model.batch.v1.",
                "io.fabric8.kubernetes.api.model.batch.v1beta1.",
                "io.fabric8.kubernetes.api.model.certificates.v1.",
                "io.fabric8.kubernetes.api.model.certificates.v1beta1.",
                "io.fabric8.kubernetes.api.model.coordination.v1.",
                "io.fabric8.kubernetes.api.model.coordination.",
                "io.fabric8.kubernetes.api.model.discovery.v1.",
                "io.fabric8.kubernetes.api.model.events.v1.",
                "io.fabric8.kubernetes.api.model.events.v1beta1.",
                "io.fabric8.kubernetes.api.model.flowcontrol.v1beta1.",
                "io.fabric8.kubernetes.api.model.discovery.v1beta1.",
                "io.fabric8.kubernetes.api.model.metrics.v1beta1.",
                "io.fabric8.kubernetes.api.model.networking.v1.",
                "io.fabric8.kubernetes.api.model.networking.v1beta1.",
                "io.fabric8.kubernetes.api.model.policy.v1.",
                "io.fabric8.kubernetes.api.model.policy.v1beta1.",
                "io.fabric8.kubernetes.api.model.rbac.",
                "io.fabric8.kubernetes.api.model.storage.",
                "io.fabric8.kubernetes.api.model.scheduling.v1.",
                "io.fabric8.kubernetes.api.model.scheduling.v1beta1.",
                "io.fabric8.kubernetes.api.model.storage.",
                "io.fabric8.kubernetes.api.model.storage.v1beta1.",
                "io.fabric8.kubernetes.api.model.node.v1alpha1.",
                "io.fabric8.kubernetes.api.model.node.v1beta1.",
                "io.fabric8.openshift.api.model.",
                "io.fabric8.openshift.api.model.clusterautoscaling.v1.",
                "io.fabric8.openshift.api.model.clusterautoscaling.v1beta1.",
                "io.fabric8.openshift.api.model.runtime.",
                "io.fabric8.openshift.api.model.console.v1.",
                "io.fabric8.openshift.api.model.console.v1alpha1.",
                "io.fabric8.openshift.api.model.monitoring.v1.",
                "io.fabric8.openshift.api.model.machine.v1beta1.",
                "io.fabric8.openshift.api.model.operator.",
                "io.fabric8.openshift.api.model.operator.v1.",
                "io.fabric8.openshift.api.model.operator.v1alpha1.",
                "io.fabric8.openshift.api.model.imageregistry.v1.",
                "io.fabric8.openshift.api.model.operatorhub.manifests.",
                "io.fabric8.openshift.api.model.operatorhub.v1.",
                "io.fabric8.openshift.api.model.operatorhub.v1alpha1.",
                "io.fabric8.openshift.api.model.operatorhub.lifecyclemanager.v1.",
                "io.fabric8.openshift.api.model.machineconfig.v1.",
                "io.fabric8.openshift.api.model.tuned.v1.",
                "io.fabric8.openshift.api.model.whereabouts.v1alpha1.",
                "io.fabric8.openshift.api.model.storageversionmigrator.v1alpha1.",
                "io.fabric8.openshift.api.model.miscellaneous.cloudcredential.v1.",
                "io.fabric8.openshift.api.model.miscellaneous.cncf.cni.v1.",
                "io.fabric8.openshift.api.model.miscellaneous.metal3.v1alpha1.",
                "io.fabric8.openshift.api.model.miscellaneous.network.operator.v1.",
                "io.fabric8.openshift.api.model.miscellaneous.imageregistry.operator.v1.",
                "io.fabric8.kubernetes.api.model.extensions."
        };
위의 내용은 KubernetesDeserializer에 선언 되어 있는 것이다.
![image](https://user-images.githubusercontent.com/92026433/164750573-ba30a7f0-3d84-49a5-8174-163ec04d2d54.png)

If you look at DefaultOpenShiftClient, there are some missing. Is this the problem? How can I download all the files?

**Comment by ho-yasla** [comment]
> You have an issue in your dependency structure - you must have a mismatched kubernetes-model-core. Check your dependency tree to see where this a mis-alignment.


The dependency is as follows.

If only open shift was a dependency, the client could not be received, so both were dependent.

<dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>5.12.2</version>
        </dependency>
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>openshift-client</artifactId>
            <version>5.12.2</version>
            <exclusions>
                <exclusion>
                    <groupId>io.fabric8</groupId>
                    <artifactId>kubernetes-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by ho-yasla** [comment]
> static class Mapping {
> 
> ```
>     private static final String KEY_SEPARATOR = "#";
> 
>     // n.b. Packages sorted in order of precedence, deserialization of resources with no
>     // specific version will default to first available Class in one of these packages:
>     private static final String[] PACKAGES = {
>             "io.fabric8.kubernetes.api.model.",
>             "io.fabric8.kubernetes.api.model.admission.v1.",
>             "io.fabric8.kubernetes.api.model.admission.v1beta1.",
>             "io.fabric8.kubernetes.api.model.admissionregistration.v1.",
>             "io.fabric8.kubernetes.api.model.admissionregistration.v1beta1.",
>             "io.fabric8.kubernetes.api.model.authentication.",
>             "io.fabric8.kubernetes.api.model.authorization.v1.",
>             "io.fabric8.kubernetes.api.model.authorization.v1beta1.",
>             "io.fabric8.kubernetes.api.model.apiextensions.v1.",
>             "io.fabric8.kubernetes.api.model.apiextensions.v1beta1.",
>             "io.fabric8.kubernetes.api.model.apps.",
>             "io.fabric8.kubernetes.api.model.autoscaling.v1.",
>             "io.fabric8.kubernetes.api.model.autoscaling.",
>             "io.fabric8.kubernetes.api.model.autoscaling.v2beta1.",
>             "io.fabric8.kubernetes.api.model.autoscaling.v2beta2.",
>             "io.fabric8.kubernetes.api.model.batch.v1.",
>             "io.fabric8.kubernetes.api.model.batch.v1beta1.",
>             "io.fabric8.kubernetes.api.model.certificates.v1.",
>             "io.fabric8.kubernetes.api.model.certificates.v1beta1.",
>             "io.fabric8.kubernetes.api.model.coordination.v1.",
>             "io.fabric8.kubernetes.api.model.coordination.",
>             "io.fabric8.kubernetes.api.model.discovery.v1.",
>             "io.fabric8.kubernetes.api.model.events.v1.",
>             "io.fabric8.kubernetes.api.model.events.v1beta1.",
>             "io.fabric8.kubernetes.api.model.flowcontrol.v1beta1.",
>             "io.fabric8.kubernetes.api.model.discovery.v1beta1.",
>             "io.fabric8.kubernetes.api.model.metrics.v1beta1.",
>             "io.fabric8.kubernetes.api.model.networking.v1.",
>             "io.fabric8.kubernetes.api.model.networking.v1beta1.",
>             "io.fabric8.kubernetes.api.model.policy.v1.",
>             "io.fabric8.kubernetes.api.model.policy.v1beta1.",
>             "io.fabric8.kubernetes.api.model.rbac.",
>             "io.fabric8.kubernetes.api.model.storage.",
>             "io.fabric8.kubernetes.api.model.scheduling.v1.",
>             "io.fabric8.kubernetes.api.model.scheduling.v1beta1.",
>             "io.fabric8.kubernetes.api.model.storage.",
>             "io.fabric8.kubernetes.api.model.storage.v1beta1.",
>             "io.fabric8.kubernetes.api.model.node.v1alpha1.",
>             "io.fabric8.kubernetes.api.model.node.v1beta1.",
>             "io.fabric8.openshift.api.model.",
>             "io.fabric8.openshift.api.model.clusterautoscaling.v1.",
>             "io.fabric8.openshift.api.model.clusterautoscaling.v1beta1.",
>             "io.fabric8.openshift.api.model.runtime.",
>             "io.fabric8.openshift.api.model.console.v1.",
>             "io.fabric8.openshift.api.model.console.v1alpha1.",
>             "io.fabric8.openshift.api.model.monitoring.v1.",
>             "io.fabric8.openshift.api.model.machine.v1beta1.",
>             "io.fabric8.openshift.api.model.operator.",
>             "io.fabric8.openshift.api.model.operator.v1.",
>             "io.fabric8.openshift.api.model.operator.v1alpha1.",
>             "io.fabric8.openshift.api.model.imageregistry.v1.",
>             "io.fabric8.openshift.api.model.operatorhub.manifests.",
>             "io.fabric8.openshift.api.model.operatorhub.v1.",
>             "io.fabric8.openshift.api.model.operatorhub.v1alpha1.",
>             "io.fabric8.openshift.api.model.operatorhub.lifecyclemanager.v1.",
>             "io.fabric8.openshift.api.model.machineconfig.v1.",
>             "io.fabric8.openshift.api.model.tuned.v1.",
>             "io.fabric8.openshift.api.model.whereabouts.v1alpha1.",
>             "io.fabric8.openshift.api.model.storageversionmigrator.v1alpha1.",
>             "io.fabric8.openshift.api.model.miscellaneous.cloudcredential.v1.",
>             "io.fabric8.openshift.api.model.miscellaneous.cncf.cni.v1.",
>             "io.fabric8.openshift.api.model.miscellaneous.metal3.v1alpha1.",
>             "io.fabric8.openshift.api.model.miscellaneous.network.operator.v1.",
>             "io.fabric8.openshift.api.model.miscellaneous.imageregistry.operator.v1.",
>             "io.fabric8.kubernetes.api.model.extensions."
>     };
> ```
> 
> The above is declared in KubernetesDeserializer. ![image](https://user-images.githubusercontent.com/92026433/164750573-ba30a7f0-3d84-49a5-8174-163ec04d2d54.png)
> 
> If you look at DefaultOpenShiftClient, there are some missing. Is this the problem? How can I download all the files?

static class Mapping {

    private static final String KEY_SEPARATOR = "#";

    // n.b. Packages sorted in order of precedence, deserialization of resources with no
    // specific version will default to first available Class in one of these packages:
    private static final String[] PACKAGES = {
            "io.fabric8.kubernetes.api.model.",
            "io.fabric8.kubernetes.api.model.admission.v1.",
            "io.fabric8.kubernetes.api.model.admission.v1beta1.",
            "io.fabric8.kubernetes.api.model.admissionregistration.v1.",
            "io.fabric8.kubernetes.api.model.admissionregistration.v1beta1.",
            "io.fabric8.kubernetes.api.model.authentication.",
            "io.fabric8.kubernetes.api.model.authorization.v1.",
            "io.fabric8.kubernetes.api.model.authorization.v1beta1.",
            "io.fabric8.kubernetes.api.model.apiextensions.v1.",
            "io.fabric8.kubernetes.api.model.apiextensions.v1beta1.",
            "io.fabric8.kubernetes.api.model.apps.",
            "io.fabric8.kubernetes.api.model.autoscaling.v1.",
            "io.fabric8.kubernetes.api.model.autoscaling.",
            "io.fabric8.kubernetes.api.model.autoscaling.v2beta1.",
            "io.fabric8.kubernetes.api.model.autoscaling.v2beta2.",
            "io.fabric8.kubernetes.api.model.batch.v1.",
            "io.fabric8.kubernetes.api.model.batch.v1beta1.",
            "io.fabric8.kubernetes.api.model.certificates.v1.",
            "io.fabric8.kubernetes.api.model.certificates.v1beta1.",
            "io.fabric8.kubernetes.api.model.coordination.v1.",
            "io.fabric8.kubernetes.api.model.coordination.",
            "io.fabric8.kubernetes.api.model.discovery.v1.",
            "io.fabric8.kubernetes.api.model.events.v1.",
            "io.fabric8.kubernetes.api.model.events.v1beta1.",
            "io.fabric8.kubernetes.api.model.flowcontrol.v1beta1.",
            "io.fabric8.kubernetes.api.model.discovery.v1beta1.",
            "io.fabric8.kubernetes.api.model.metrics.v1beta1.",
            "io.fabric8.kubernetes.api.model.networking.v1.",
            "io.fabric8.kubernetes.api.model.networking.v1beta1.",
            "io.fabric8.kubernetes.api.model.policy.v1.",
            "io.fabric8.kubernetes.api.model.policy.v1beta1.",
            "io.fabric8.kubernetes.api.model.rbac.",
            "io.fabric8.kubernetes.api.model.storage.",
            "io.fabric8.kubernetes.api.model.scheduling.v1.",
            "io.fabric8.kubernetes.api.model.scheduling.v1beta1.",
            "io.fabric8.kubernetes.api.model.storage.",
            "io.fabric8.kubernetes.api.model.storage.v1beta1.",
            "io.fabric8.kubernetes.api.model.node.v1alpha1.",
            "io.fabric8.kubernetes.api.model.node.v1beta1.",
            "io.fabric8.openshift.api.model.",
            "io.fabric8.openshift.api.model.clusterautoscaling.v1.",
            "io.fabric8.openshift.api.model.clusterautoscaling.v1beta1.",
            "io.fabric8.openshift.api.model.runtime.",
            "io.fabric8.openshift.api.model.console.v1.",
            "io.fabric8.openshift.api.model.console.v1alpha1.",
            "io.fabric8.openshift.api.model.monitoring.v1.",
            "io.fabric8.openshift.api.model.machine.v1beta1.",
            "io.fabric8.openshift.api.model.operator.",
            "io.fabric8.openshift.api.model.operator.v1.",
            "io.fabric8.openshift.api.model.operator.v1alpha1.",
            "io.fabric8.openshift.api.model.imageregistry.v1.",
            "io.fabric8.openshift.api.model.operatorhub.manifests.",
            "io.fabric8.openshift.api.model.operatorhub.v1.",
            "io.fabric8.openshift.api.model.operatorhub.v1alpha1.",
            "io.fabric8.openshift.api.model.operatorhub.lifecyclemanager.v1.",
            "io.fabric8.openshift.api.model.machineconfig.v1.",
            "io.fabric8.openshift.api.model.tuned.v1.",
            "io.fabric8.openshift.api.model.whereabouts.v1alpha1.",
            "io.fabric8.openshift.api.model.storageversionmigrator.v1alpha1.",
            "io.fabric8.openshift.api.model.miscellaneous.cloudcredential.v1.",
            "io.fabric8.openshift.api.model.miscellaneous.cncf.cni.v1.",
            "io.fabric8.openshift.api.model.miscellaneous.metal3.v1alpha1.",
            "io.fabric8.openshift.api.model.miscellaneous.network.operator.v1.",
            "io.fabric8.openshift.api.model.miscellaneous.imageregistry.operator.v1.",
            "io.fabric8.kubernetes.api.model.extensions."
    };
The above is declared in KubernetesDeserializer.
image

If you look at DefaultOpenShiftClient, there are some missing. Is this the problem? How can I download all the files?

**Comment by manusa** [comment]
Could you please provide the related dependency section of your project?

**Comment by ho-yasla** [comment]
> Could you please provide the related dependency section of your project?
 
       <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>5.12.2</version>
        </dependency>
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>openshift-client</artifactId>
            <version>5.12.2</version>
            <exclusions>
                <exclusion>
                    <groupId>io.fabric8</groupId>
                    <artifactId>kubernetes-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
