### ISSUE TITLE
Client version update 4.x to 5.x report error Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/MismatchedInputException

### ISSUE THREAD

**Issue by qhh0205** [fabric8io/kubernetes-client#4086]
hi, i hava upgrate client version from 4.10.1 to 5.10.0, but report error when interact with kubernetes api, the following is my pom.xml change:
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/12775142/164652251-1fe662be-acf0-4bfa-a0c5-c1b9e3f427fe.png">

the error report as following:
```
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/MismatchedInputException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_171]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_171]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/MismatchedInputException
	at io.fabric8.kubernetes.client.utils.serialization.UnmatchedFieldTypeModule$1.lambda$updateBuilder$0(UnmatchedFieldTypeModule.java:55) ~[kubernetes-client-5.10.0.jar!/:na]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_171]
	at io.fabric8.kubernetes.client.utils.serialization.UnmatchedFieldTypeModule$1.updateBuilder(UnmatchedFieldTypeModule.java:54) ~[kubernetes-client-5.10.0.jar!/:na]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:279) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:184) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3915) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3810) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2931) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:312) ~[kubernetes-client-5.10.0.jar!/:na]
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:266) ~[kubernetes-client-5.10.0.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:569) ~[kubernetes-client-5.10.0.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:527) ~[kubernetes-client-5.10.0.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:510) ~[kubernetes-client-5.10.0.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:140) ~[kubernetes-client-5.10.0.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:422) ~[kubernetes-client-5.10.0.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:411) ~[kubernetes-client-5.10.0.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:91) ~[kubernetes-client-5.10.0.jar!/:na]
	at com.baidu.weiyun.service.impl.FabricKbsServiceImpl.listDeployment(FabricKbsServiceImpl.java:1120) ~[classes!/:0.0.1-SNAPSHOT]
	at com.baidu.weiyun.service.impl.AppServiceImpl.fillInstanceInfo(AppServiceImpl.java:1142) ~[classes!/:0.0.1-SNAPSHOT]
	at com.baidu.weiyun.service.impl.AppServiceImpl.lambda$formatAppResponse$1(AppServiceImpl.java:1092) ~[classes!/:0.0.1-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_171]
	... 3 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.exc.MismatchedInputException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[weiyun-console-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
	... 30 common frames omitted

```

**Comment by qhh0205** [comment]
Urgent!😭

**Comment by manusa** [comment]
It seems you have two different dependencies to Jackson. The one that's effectively in your project is not supported by our version. You should try to update it.
