### ISSUE TITLE
java.lang.RuntimeException: invalid key or spec in GCM mode

### ISSUE THREAD

**Issue by mscbalakrishnan** [fabric8io/kubernetes-client#4091]
### Is your task related to a problem? Please describe

```
2022-04-18 12:32:46,213 [][][] WARN  internal.WatchConnectionManager [OkHttp https://10.96.0.1/...]  - Exec Failure
java.lang.RuntimeException: invalid key or spec in GCM mode
        at sun.security.ssl.SSLCipher$T12GcmWriteCipherGenerator$GcmWriteCipher.encrypt(SSLCipher.java:1703) ~[?:1.8.0_302]
        at sun.security.ssl.OutputRecord.t10Encrypt(OutputRecord.java:411) ~[?:1.8.0_302]
        at sun.security.ssl.OutputRecord.encrypt(OutputRecord.java:347) ~[?:1.8.0_302]
        at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:78) ~[?:1.8.0_302]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:355) ~[?:1.8.0_302]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[?:1.8.0_302]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[?:1.8.0_302]
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1563) ~[?:1.8.0_302]
        at sun.security.ssl.SSLSocketImpl.access$400(SSLSocketImpl.java:73) ~[?:1.8.0_302]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:973) ~[?:1.8.0_302]
        at okio.Okio$2.read(Okio.java:138) ~[okio-1.11.0.jar!/:?]
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:236) ~[okio-1.11.0.jar!/:?]
        at okio.RealBufferedSource.request(RealBufferedSource.java:66) ~[okio-1.11.0.jar!/:?]
        at okio.RealBufferedSource.require(RealBufferedSource.java:59) ~[okio-1.11.0.jar!/:?]
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:72) ~[okio-1.11.0.jar!/:?]
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113) ~[okhttp-3.6.0.jar!/:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) ~[okhttp-3.6.0.jar!/:?]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262) [okhttp-3.6.0.jar!/:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201) [okhttp-3.6.0.jar!/:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135) [okhttp-3.6.0.jar!/:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.6.0.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_302]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.security.InvalidKeyException: Could not initialize cipher
        at sun.security.pkcs11.P11AEADCipher.implInit(P11AEADCipher.java:330) ~[sunpkcs11.jar:1.8.0_302]
        at sun.security.pkcs11.P11AEADCipher.engineInit(P11AEADCipher.java:248) ~[sunpkcs11.jar:1.8.0_302]
        at javax.crypto.Cipher.init(Cipher.java:1397) ~[?:1.8.0_302]
        at sun.security.ssl.SSLCipher$T12GcmWriteCipherGenerator$GcmWriteCipher.encrypt(SSLCipher.java:1699) ~[?:1.8.0_302]
        ... 23 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_OPERATION_ACTIVE
        at sun.security.pkcs11.wrapper.PKCS11.C_EncryptInit(Native Method) ~[sunpkcs11.jar:1.8.0_302]
        at sun.security.pkcs11.P11AEADCipher.initialize(P11AEADCipher.java:404) ~[sunpkcs11.jar:1.8.0_302]
        at sun.security.pkcs11.P11AEADCipher.implInit(P11AEADCipher.java:328) ~[sunpkcs11.jar:1.8.0_302]
        at sun.security.pkcs11.P11AEADCipher.engineInit(P11AEADCipher.java:248) ~[sunpkcs11.jar:1.8.0_302]
        at javax.crypto.Cipher.init(Cipher.java:1397) ~[?:1.8.0_302]
        at sun.security.ssl.SSLCipher$T12GcmWriteCipherGenerator$GcmWriteCipher.encrypt(SSLCipher.java:1699) ~[?:1.8.0_302]
        ... 23 more
```
### Describe the solution you'd like

I am getting the above exception from OKhttp3 which is internally used by kubernetes-client library

**Comment by manusa** [comment]
Could you try adding the optional Bouncy Castle dependencies to your project:

```xml
   <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
      <version>1.70</version>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcpkix-jdk15on</artifactId>
      <version>1.70</version>
    </dependency>
```

**Comment by mscbalakrishnan** [comment]
I tried. But it is throwing the same error. 

Please let me know, there any kubernetes client version which is not using okhttp3 library?
This is the kubernetes client we are using,
<dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>4.1.1</version>
        </dependency>

**Comment by mscbalakrishnan** [comment]
I have used below dependency which resolved this issue

`<dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>4.13.3</version>
        </dependency>
`
