### ISSUE TITLE
Can not create customized resource via raw JSON string in scala

### ISSUE THREAD

**Issue by SparkSnail** [fabric8io/kubernetes-client#4101]
I need to submit a custom resource via Resource Typeless API, and follow official doc here https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#resource-typeless-api.    
![image](https://user-images.githubusercontent.com/22682999/165669217-1ca76113-2963-447a-8588-ec468e84dba7.png)

Here is my code:
```
val jsonString: String = MY_JSON_STRING
client.genericKubernetesResources(resourceDefinitionContext).inNamespace(namespace).load(jsonString).create()
```
And it throw such error when I execute the code:
```
2022-04-28T02:57:31,169 ERROR [qtp467401150-43] org.apache.livy.server.SessionServlet$: internal error
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:103) ~[kubernetes-client-5.12.2.jar:?]
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:97) ~[kubernetes-client-5.12.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.load(BaseOperation.java:278) ~[kubernetes-client-5.12.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.load(BaseOperation.java:284) ~[kubernetes-client-5.12.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.load(BaseOperation.java:83) ~[kubernetes-client-5.12.2.jar:?]
                                                       ... ...
Caused by: java.io.FileNotFoundException: {"metadata":{"name":"32fd44bdeb374f7fde310b3850701013","namespace":"default"},"spec":{"retryPolicy":{"fancyRetryPolicy":true,"maxRetryCount":3},..........."} (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_202]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_202]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_202]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.load(BaseOperation.java:275) ~[kubernetes-client-5.12.2.jar:?]
        ... 100 more
```
Obviously it takes my json content as a file path and try to load the file.

Then I changed to use 
```
client.customResource(customResourceDefinitionContext).create(namespace, jsonString)
```
It can submit successfully in this `client.customResource()` way, is it supported to use? I noticed this method is deprecated in my IDE hint.
![image](https://user-images.githubusercontent.com/22682999/165670076-5e8e51d5-31d4-4556-bd4c-f4e2db00f29f.png)
****

Please help to take a look, what is correct way to create customized resource via raw JSON string in scala? My kubernetes client version is 5.12.2.

**Comment by SparkSnail** [comment]
> > And it throw such error when I execute the code:
> 
> Definitely looks like the cheatsheet needs updated.
> 
> > Please help to take a look, what is correct way to create customized resource via raw JSON string in scala? My kubernetes client version is 5.12.2.
> 
> In 5.12.2 you can use:
> 
> ```
> client.resource(jsonString).inNamespace(namespace).createOrReplace();
> ```
> 
> In 6.0 there will be more flexibility, such as just the create method:
> 
> ```
> client.resource(jsonString).inNamespace(namespace).create();
> ```

Thanks for the reply.
I need to use CustomResourceDefinitionContext to initialize the client first, and finally I submit resource using
```
client.customResource(customResourceDefinitionContext).inNamespace(namespace).create(jsonString)
```
This method is not deprecated in 5.12.2, and can submit my customized resource successfully.
