### ISSUE TITLE
Mocking kubectl exec with KubernetesServer

### ISSUE THREAD

**Issue by Snazzythat** [fabric8io/kubernetes-client#4116]
Hi guys,

I'm trying to mock the kubectl exec command in my unit test using KubernetesServer.

As per documentation, I instantiate the server via:

@Rule
public KubernetesServer server = new KubernetesServer(true, true);

then I call the client:
KubernetesClient client = server.getClient();

then I try to mock the API call to exec through the server:

server.expect().withpath("/api/v1/namespaces/test/pods/mock-pod-1/exec?command=bash&command=-c&command=pwd&stdout=true&stderr=true").andReturn(200, someOutput).once();

Essentially I want to run "pwd" in the mocked pod (mock-pod-1) that I also created via client using PodBuilder.

Is this even possible? When I'm executing the above approach, I'm getting the following:

`2022-05-02 20:23:16.882 -0400 [main]  INFO  c.e.m.c.i.s.KubernetesClientService.executeCommandInPod l.89 - Executing command "pwd" in pod: mock-pod-1 
May 02, 2022 8:23:19 PM okhttp3.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[59559] received request: GET /api/v1/namespaces/test/pods/mock-pod-1/exec?command=bash&command=-c&command=pwd&stdout=true&stderr=true HTTP/1.1 and responded: HTTP/1.1 200 OK
2022-05-02 20:23:22.208 -0400 [OkHttp http://localhost:59559/...]  ERROR i.f.k.c.d.i.ExecWebSocketListener.onError l.215 - Exec Failure
io.fabric8.kubernetes.client.http.WebSocketHandshakeException: null
	at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onFailure(OkHttpWebSocketImpl.java:66)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:199)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:169)
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:180)
		at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:332)
		at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:85)
		at com....service.KubernetesClientService.executeCommandInPod(KubernetesClientService.java:92)
		at com.....service.KubernetesClientServiceTest.givenRunningInAPod_shouldExecACommandInAPod_success(KubernetesClientServiceTest.java:133)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
		at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
		at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
		at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
		at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
		at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
		at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
		at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess(RealWebSocket.java:224)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:195)
	... 5 common frames omitted
May 02, 2022 8:23:22 PM okhttp3.mockwebserver.MockWebServer$4 processOneRequest
`

It looks like the client expects the web socket connection to be established first with a 101 response, however, the mock immediately responds with 200. 

Not sure what I'm doing wrong, some hint is much appreciated!

**Comment by Snazzythat** [comment]
@shawkins 

Thanks for the feedback, I was actually able to properly mock the behavior, I had to use websocket for exec and return an an instance of OutputStreamMessage:

`server.expect().withPath(someApiPath).andUpgradeToWebSocket().open(new OutputStreamMessage("hello!")).done().once()`

I got the desired output as the result. 

This issue can be closed.
