### ISSUE TITLE
docker-maven-plugin hangs when starting a container

### ISSUE THREAD

**Issue by sebastiankirsch** [fabric8io/kubernetes-client#416]
Hi there!

We've configured our application like this

    <image>
      
      <run>
        
        <wait>
          <url>http://${docker.host.address}:${app.port}/revision</url>
          <time>180000</time>
        </wait>
      </run>
    </image>

Now for some cases calling docker:start fails with a timeout on our build server. In the log files we see

    [16:41:47][INFO] DOCKER> [is24-comm-service/comm-service] "app": Start container 64ccf13a7d7b
    [16:50:24]The build ... has been running for more than 10 minutes. Terminating...

followed by a thread dump

    2016-05-25 16:50:24
    Full thread dump OpenJDK 64-Bit Server VM (25.91-b14 mixed mode):
    ...

    "main" #1 prio=5 os_prio=0 tid=0x00007fcc3000c000 nid=0x731 runnable [0x00007fcc3925f000]
    java.lang.Thread.State: RUNNABLE
	at com.kenai.jffi.Foreign.invokeN3O1(Native Method)
	at com.kenai.jffi.Invoker.invokeN3(Invoker.java:1061)
	at jnr.enxio.channels.Native$LibC$jnr$ffi$1.read(Unknown Source)
	at jnr.enxio.channels.Native.read(Native.java:95)
	at jnr.enxio.channels.NativeSocketChannel.read(NativeSocketChannel.java:70)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
	- locked <0x0000000705320d48> (a java.lang.Object)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	- locked <0x0000000705321158> (a sun.nio.ch.ChannelInputStream)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136)
	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.post(ApacheHttpClientDelegate.java:83)
	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.post(ApacheHttpClientDelegate.java:89)
	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.startContainer(DockerAccessWithHcClient.java:178)
	at io.fabric8.maven.docker.service.RunService.startContainer(RunService.java:363)
	at io.fabric8.maven.docker.service.RunService.createAndStartContainer(RunService.java:99)
	at io.fabric8.maven.docker.StartMojo.executeInternal(StartMojo.java:85)
	- locked <0x0000000705008ff0> (a io.fabric8.maven.docker.StartMojo)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:164)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

Now, for whatever the reason this hangs (the application ususally starts in ~30s), it should at least be interrupted by the configured `wait` condition.

**Comment by rhuss** [comment]
wrong project ;-) Could you please reopen it at fabric8io/docker-maven-plugin ?

**Comment by jimmidyson** [comment]
Issue moved to [fabric8io/docker-maven-plugin #458](https://github.com/fabric8io/docker-maven-plugin/issues/458) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by sebastiankirsch** [comment]
sorry about that :/

**Comment by rhuss** [comment]
np :)
