### ISSUE TITLE
rc rollingupdate seems broken

### ISSUE THREAD

**Issue by ravilr** [fabric8io/kubernetes-client#426]
@jimmidyson 
since this commit: https://github.com/fabric8io/kubernetes-client/commit/c815f6e927ea68b250bb4b8acb71f4ce2b9d8e51

client.replicationControllers().inNamespace(namespace).withName(rc.getMetadata().getName()).rolling().replace(rc);

io.fabric8.kubernetes.client.KubernetesClientException: Resource not found!
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:164)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.edit(HasMetadataOperation.java:59)
        at io.fabric8.kubernetes.client.dsl.internal.ReplicationControllerOperationsImpl.edit(ReplicationControllerOperationsImpl.java:210)
        at io.fabric8.kubernetes.client.dsl.internal.ReplicationControllerOperationsImpl.edit(ReplicationControllerOperationsImpl.java:54)
        at io.fabric8.kubernetes.client.dsl.internal.ReplicationControllerOperationsImpl.scale(ReplicationControllerOperationsImpl.java:136)
        at io.fabric8.kubernetes.client.dsl.internal.ReplicationControllerOperationsImpl.scale(ReplicationControllerOperationsImpl.java:54)
        at io.fabric8.kubernetes.client.dsl.internal.RollingUpdater.rollUpdate(RollingUpdater.java:130)
        at io.fabric8.kubernetes.client.dsl.internal.ReplicationControllerOperationsImpl.replace(ReplicationControllerOperationsImpl.java:236)
        at io.fabric8.kubernetes.client.dsl.internal.ReplicationControllerOperationsImpl.replace(ReplicationControllerOperationsImpl.java:54)

**Comment by ravilr** [comment]
@jimmidyson 
createClone() here is not creating the rc on server instead returning just the rc object
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ReplicationControllerRollingUpdater.java#L39

**Comment by ravilr** [comment]
Also, the update/deleteDeploymentKey shouldn't edit the replicas back to 0.

**Comment by jimmidyson** [comment]
Very sloppy... will fix up today. Got to start thinking about some proper integration tests for this library.
