### ISSUE TITLE
empty subtype data can't be unmarshalled into unwrapped class

### ISSUE THREAD

**Issue by yimoucao** [fabric8io/kubernetes-client#4277]
### Describe the bug

for istio extension model VirtualService, deserializing it with empty uri `uri: {}` throws Exception
```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class io.fabric8.istio.api.networking.v1beta1.IsStringMatchMatchType]: Cannot deduce unique subtype of `io.fabric8.istio.api.networking.v1beta1.IsStringMatchMatchType` (3 candidates match)
 at [Source: (BufferedInputStream); line: 18, column: 17] (through reference chain: com.example.model.api.network.v1beta1.VirtualService["spec"]-]io.fabric8.istio.api.networking.v1beta1.VirtualServiceSpec["http"]-]java.util.ArrayList[0]-]io.fabric8.istio.api.networking.v1beta1.HTTPRoute["match"]-]java.util.ArrayList[0]-]io.fabric8.istio.api.networking.v1beta1.HTTPMatchRequest["uri"]-]io.fabric8.istio.api.networking.v1beta1.StringMatch["MatchType"])
 at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
 at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:2083)
 at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1596)
 at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:307)
 at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:185)
 at com.fasterxml.jackson.databind.jsontype.impl.AsDeductionTypeDeserializer.deserializeTypedFromObject(AsDeductionTypeDeserializer.java:147)
 at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
 at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:131)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
 at io.fabric8.kubernetes.model.jackson.JsonUnwrappedDeserializer.deserialize(JsonUnwrappedDeserializer.java:139)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
 at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:131)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
 at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:131)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
 at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:131)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
 at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:131)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
 at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
 at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
 at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)

```

the same can be true for DestinationRule if `IsLoadBalancerSettingsLbPolicy` receives empty data
```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class io.fabric8.istio.api.networking.v1beta1.IsLoadBalancerSettingsLbPolicy]: Cannot deduce unique subtype of `io.fabric8.istio.api.networking.v1beta1.IsLoadBalancerSettingsLbPolicy` (2 candidates match)
 at [Source: (BufferedInputStream); line: 16, column: 9] (through reference chain: com.example.model.api.network.v1beta1.DestinationRule["spec"]-]io.fabric8.istio.api.networking.v1beta1.DestinationRuleSpec["trafficPolicy"]-]io.fabric8.istio.api.networking.v1beta1.TrafficPolicy["portLevelSettings"]-]java.util.ArrayList[0]-]io.fabric8.istio.api.networking.v1beta1.TrafficPolicyPortTrafficPolicy["loadBalancer"]-]io.fabric8.istio.api.networking.v1beta1.LoadBalancerSettings["LbPolicy"])
 at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
 at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:2083)
 at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1596)
 at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:307)
 at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:185)
 at com.fasterxml.jackson.databind.jsontype.impl.AsDeductionTypeDeserializer.deserializeTypedFromObject(AsDeductionTypeDeserializer.java:147)
 at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
 at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
 at io.fabric8.kubernetes.client.utils.serialization.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:131)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
 at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
 at io.fabric8.kubernetes.model.jackson.JsonUnwrappedDeserializer.deserialize(JsonUnwrappedDeserializer.java:139)
```

### Fabric8 Kubernetes Client version

5.12.2

### Steps to reproduce

1. add new yaml as a file in test
```yaml
# /extensions/istio/tests/src/test/resources/v1beta1/virtual-service-empty-uri.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-vs
  namespace: ts
spec:
  http:
    - match:
        - gateways: []
          port: 80
          uri: {}
```
2. run test case
```java
  @Test
  public void emptyURIShouldWork() throws IOException {
    final InputStream inputStream = VirtualServiceTest.class.getResourceAsStream("/v1beta1/virtual-service-empty-uri.yaml");
    final VirtualService virtualService = Serialization.yamlMapper().readValue(inputStream, VirtualService.class);
  }
```

for `DestinationRule` test yaml can be
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bookinfo-ratings
spec:
  host: ratings.prod.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - loadBalancer:
          localityLbSetting:
            distribute:
              - from: "*"
                to:
                  lvs/lvsaz03: 50
                  slc/slcaz03: 50
        port:
          number: 18080
        tls:
          mode: SIMPLE
          sni: regression-223.example.com
```

### Expected behavior

an empty uri will cause type induction failure, because there's no way find out which subtype class to use by looking at properties.

empty uri shoud be ignored by returning null.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Additional context

enterprise-cutomized k8s clusters

**Comment by yimoucao** [comment]
thx @shawkins . may I know when that fix will be released? by any chance it can be a patch release for 5.12.x ?

**Comment by shawkins** [comment]
> thx @shawkins . may I know when that fix will be released? by any chance it can be a patch release for 5.12.x ?

It's currently just targeted to 6.1, but you can certainly tag it for 5.12.x as well.  Can you check if it will cherry-pick cleanly, if not could you open a pr with the backport?

**Comment by yimoucao** [comment]
@shawkins I tried cherry-pick. no good for me because Serialization was moved from kubenetes-client to kubenertes-client-api.
I'll file a backport PR.
if backport is ok and good, what date you think it can be targeted for releasing to public?

**Comment by shawkins** [comment]
It's @manusa that handles the releases.  I'd assume that it would be in the next month - well before a 6.1 was available.

**Comment by yimoucao** [comment]
sorry for bothering @shawkins . I'm trying to build locally `mvn clean install` from branch `5.12` but always get 
```
[ERROR] /Users/yimoucao/vcs/github.com/fabric8io/kubernetes-client/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java:[39,39] cannot find symbol
  symbol:   class KubernetesListBuilder
  location: package io.fabric8.kubernetes.api.model
```
tried `./generateMode.sh`. same error pops up. could you please help? I'm trying to backport your fix to 5.12

**Comment by shawkins** [comment]
> could you please help? I'm trying to backport your fix to 5.12

That seems odd.  The KubernetesListBuilder should be created by the sundrio annotation processor - that should run even without doing generateModel.sh.  If you think you have the code correctly backported, try just opening a pr and then we'll see what the build results look like from the github run.

**Comment by yimoucao** [comment]
@shawkins filed PR here: https://github.com/fabric8io/kubernetes-client/pull/4282
let's see what results look like

**Comment by yimoucao** [comment]
> sorry for bothering @shawkins . I'm trying to build locally `mvn clean install` from branch `5.12` but always get 
> 
> ```
> 
> [ERROR] /Users/yimoucao/vcs/github.com/fabric8io/kubernetes-client/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java:[39,39] cannot find symbol
> 
>   symbol:   class KubernetesListBuilder
> 
>   location: package io.fabric8.kubernetes.api.model
> 
> ```
> 
> tried `./generateMode.sh`. same error pops up. also global search doesn't find this`KubernetesListBuilder`
> 
> 
> 
> could you please help? I'm trying to backport your fix to 5.12

Hi @manusa I found https://github.com/sundrio/sundrio/issues/164 to be related here. Could you help me get local builds pass?

**Comment by shawkins** [comment]
> let's see what results look like

Looks good.  The test error is due to a flaky test that has since been fixed on master.

**Comment by shawkins** [comment]
> Hi @manusa I found https://github.com/sundrio/sundrio/issues/164 to be related here. Could you help me get local builds pass?

It was brought up in a gitter chat that he's using Apache Maven 3.8.6 on mac with JDK 1.8.292.

Is there anyone else on mac that can verify this setup?
