### ISSUE TITLE
Delete operation on DeploymentConfig is broken in 1.3.93/94

### ISSUE THREAD

**Issue by dsimansk** [fabric8io/kubernetes-client#428]
Hi,
when trying to delete existing DeploymentConfigs I'm getting the following exception
```
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:464)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:455)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:57)
	at com.redhat.xpaas.openshift.OpenshiftUtil.lambda$deleteDeploymentConfig$34(OpenshiftUtil.java:481)
	at com.redhat.xpaas.openshift.OpenshiftUtil.withDefaultUser(OpenshiftUtil.java:169)
	at com.redhat.xpaas.openshift.OpenshiftUtil.deleteDeploymentConfig(OpenshiftUtil.java:481)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.redhat.xpaas.openshift.OpenshiftUtil.cleanProject(OpenshiftUtil.java:909)
	at com.redhat.xpaas.openshift.OpenshiftUtil.cleanProject(OpenshiftUtil.java:878)
	at com.redhat.xpaas.openshift.OpenshiftUtil.cleanProject(OpenshiftUtil.java:871)
	at com.redhat.xpaas.amq.template.AbstractAmqTemplateTest.createApplicationFromTemplate(AbstractAmqTemplateTest.java:64)
	at com.redhat.xpaas.amq.template.AbstractAmqTemplateTest.createApplicationFromTemplate(AbstractAmqTemplateTest.java:52)
	at com.redhat.xpaas.amq.template.BasicTemplateTest.testCreateApplication(BasicTemplateTest.java:20)

```
The DCs are retrieved through list
```
client.deploymentConfigs().list().getItems()
```

@jimmidyson wondering if [this change is the cause](https://github.com/fabric8io/kubernetes-client/commit/d10e4ed8c519daddf4d35754ccf33e31eaf21e1d)?

**Comment by jimmidyson** [comment]
Yes it is... fixing. Another reason to get working on #427 ASAP.

**Comment by dsimansk** [comment]
Cool, thanks for the quick fix.
