### ISSUE TITLE
[openshift-client] Instantiating BuildConfig with BuildRequest returns "resourceVersion may not be set on objects to be created"

### ISSUE THREAD

**Issue by donovanmuller** [fabric8io/kubernetes-client#451]
Using the `OpenShiftClient` and trying to kick off a `Build` for an existing `BuildConfig`:

```
        BuildRequest buildRequest = new BuildRequestBuilder()
                .withNewMetadata()
                    .withName("test-build")
                .and()
                .build();

        client.builds().create(client.buildConfigs()
                .withName("test-build")
                .instantiate(buildRequest));
```

I get the following:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.28.128.4:8443/oapi/v1/namespaces/default/builds. Message: resourceVersion may not be set on objects to be created. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=resourceVersion may not be set on objects to be created, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:310) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:263) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:207) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:547) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:243) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
```

Despite this, the build **does get triggered**.

Perhaps the `.instantiate(buildRequest)` copies over the `resourceVersion` on the `Build` and it doesn't like it?

**Comment by iocanel** [comment]
Its more like instantiate(...) returns an object that contains a resource number, that is then passed to build.
