### ISSUE TITLE
Null pointer exception executing `java-generator-cli`

### ISSUE THREAD

**Issue by andreaTP** [fabric8io/kubernetes-client#4534]
### Describe the bug

`java-generator-cli` artifact is causing a `NullPointerException` when executed via `jbang` (I haven't tested yet other configurations).

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

```
jbang io.fabric8:java-generator-cli:6.2.0 -s java-generator/core/src/test/resources/crontab-crd.yml -t ./tmp
```

### Expected behavior

The java classes are correctly generated.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell
java.lang.NullPointerException
        at io.fabric8.java.generator.cli.GenerateJavaSources.run(GenerateJavaSources.java:74)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.executeHelpRequest(CommandLine.java:1929)
        at picocli.CommandLine.executeHelpRequest(CommandLine.java:1909)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2176)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.fabric8.java.generator.cli.GenerateJavaSources.main(GenerateJavaSources.java:80)
```

**Comment by andreaTP** [comment]
cc. @manusa if something in the dependencies might have caused this to happen ...

**Comment by andreaTP** [comment]
cc. @remkop if you have something on top of your head, but the `picocli` version remained stable ...

**Comment by remkop** [comment]
Perhaps You can get more details with picocli's tracing function. 

https://picocli.info/#_tracing

**Comment by manusa** [comment]
> cc. @manusa if something in the dependencies might have caused this to happen ...

I need to check, I didn't even remember we had this (running cli through JBang) as a feature. 
We should probably create an IT to make sure it doesn't beak again once we fix it.
