### ISSUE TITLE
facing classloader issue with gradle

### ISSUE THREAD

**Issue by shawkins** [fabric8io/kubernetes-client#4563]
```
io.fabric8.kubernetes.client.KubernetesClientException: No httpclient implementations found on the context classloader, please ensure your classpath includes an implementation jar
    at io.fabric8.kubernetes.client.utils.HttpClientUtils.getHttpClientFactory(HttpClientUtils.java:164)
    at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:76)
    at com.metalbear.mirrord.KubeDataProvider.<init>(KubeDataProvider.kt:8)
    at com.metalbear.mirrord.MirrordListener.processStartScheduled$lambda-3(MirrordListener.kt:43)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
    at ...

```

just added the dependency like so:

```
dependencies {
    implementation("com.github.zafarkhaja:java-semver:0.9.0")
    implementation("io.fabric8:kubernetes-client:6.2.0") {
        exclude(group = "org.slf4j", module = "slf4j-api")
    }
}
```

Would really appreciate any solutions, thanks

_Originally posted by @infiniteregrets in https://github.com/fabric8io/kubernetes-client/issues/4248#issuecomment-1304583337_

**Comment by shawkins** [comment]
@infiniteregrets it's best to start this as a separate thread.  As @manusa showed on the other issue there seems to be something specifically that JMeter is doing to cause groovy to handle transitive dependencies in a different way.  For your situation, please post the dependency tree - it would appear that the default okhttp dependency is not in your runtime classpath.

**Comment by infiniteregrets** [comment]
it worked for when i did 
```
Thread.currentThread().contextClassLoader = JdkHttpClientFactory::class.java.classLoader
```
on init and added `implementation("io.fabric8:kubernetes-httpclient-jdk:6.2.0")` as a dependency

**Comment by shawkins** [comment]
@infiniteregrets in your first example it appeared that you trying to use the default okhttp implementation.  Now you have included the jdk http client, and explicitly set the context class loader.  In theory you should not have to explicitly set the contextClassLoader - is your runtime / application setting a context classloader by default that does not include the fabric8 http client dependencies?

**Comment by sunix** [comment]
@infiniteregrets I am closing this issue, feel free to reopen if needed.

**Comment by adietish** [comment]
I face the same problem in the kubernetes plugin for IDEA, intellij-kubernetes. When I try to instantiate a `DefaultKubernetesClient` things blow up with the error message in the title of this issue. Working around it is to override the classloader of the current thread by the classloader of my (plugin-) class (as shown in https://github.com/fabric8io/kubernetes-client/issues/4563#issuecomment-1305572066):

```kotlin
Thread.currentThread().contextClassLoader = javaClass.classLoader
```

**Comment by jeffmaury** [comment]
I think we should rename the issue as "facing classloader issue with IntelliJ"

**Comment by shawkins** [comment]
> To solve it I'd suggest a [fallback](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/KubernetesClientBuilder.java#L55-L63) to the classloader of HttpClientUtils class like you do in KubernetesClientBuilder.

That change would also be needed in ServiceOperationsImpl.getUrlHelper.  

The reason that I didn't put the the workaround / fallback in by default is that it assumes the caller has not appropriately set the context class loader and that a flat classloader is being used for everything else - which may not be the case.  Ideally the intellij plugin would take responsibility for setting the appropriate context class loader.  That said I'm not opposed to putting the fallback in the client as we are already doing it in other places.

**Comment by shawkins** [comment]
> IMHO mangling the classpath of the current thread is not great because it affects every other participant that's on the same thread

I'm not suggesting that the fabric8 client alter the thread context class loader.  It seems like that would be the responsibility of the calling environment (the plugin) if / when the context class loader is not representative what includes the fabric8 classes.

> or even better allowing consumers to easily override/provide the classloader allows the best of both worlds.

Using an explicit class loader would be quite involved to add - beyond the client builder, there's HttpClientUtils, ServiceOperationImpl, Adapters, KubernetesResourceUtils, KubernetesDeserializer (that one's problematic as it's currently static).  For now I think we would just recommend that the caller set the context class loader - at least until we finish the additional refactoring that's needed to get rid of the static nature of deserialization logic.

**Comment by jeffmaury** [comment]
I don't think search should be done a single class loader.
I'm thinking of using those different class loaders:

- current thread context class loaders (JEE, ...)
- class loader of Kube client (IDEA,....)

I can't find a use case for caller class loader
