### ISSUE TITLE
how to avoid 1 second timeout when createorreplace with dryrun

### ISSUE THREAD

**Issue by smartkuk** [fabric8io/kubernetes-client#4571]
https://github.com/fabric8io/kubernetes-client/blob/ba04a46bf369f3b56f041d3bd87774e484374137/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java#L293

hi I use createorreplace method with dryrun option for validate.
but I can execute successfully createorreplace method, cause by timeout

How to avoid 1 second timeout

```java
Caused by: io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [1000] milliseconds for [VirtualService] with name:[bookinfo-pythonapp-ns] in namespace [bookinfo].
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:857)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:88)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.lambda$createOrReplace$0(BaseOperation.java:293)
	at io.fabric8.kubernetes.client.utils.internal.CreateOrReplaceHelper.createOrReplace(CreateOrReplaceHelper.java:55)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:296)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.createOrReplace(BaseOperation.java:88)
	at bxcr.web.admin.workload.service.istio.VirtualServiceService.apply(VirtualServiceService.java:322)
	at bxcr.web.admin.workload.service.istio.VirtualServiceService.apply(VirtualServiceService.java:292)
	at bxcr.web.admin.workload.service.bxcr.federation.istio.FedVirtualServiceServiceImpl.dryrun(FedVirtualServiceServiceImpl.java:56)
	at bxcr.web.admin.workload.service.bxcr.AppService.dryrun(AppService.java:1827)
	at bxcr.web.admin.workload.service.bxcr.AppService.insertAppInfo(AppService.java:966)
	... 111 more
```

**Comment by smartkuk** [comment]
I've been programming in Java for a long time, but I expected that there might be a special way because I mainly do simple coding, but it's not!
Thank you for solving my concerns through simplification of thinking!
