### ISSUE TITLE
java.net.ConnectException: Connection refused while trying to test with kubernetes server mock

### ISSUE THREAD

**Issue by SudharshanaSL** [fabric8io/kubernetes-client#4629]
I have a function which creates a secret as below

```
    public void upsertSecret(String name, Map<String, String> map) throws InfraException {
        
        try {
            kubernetesClient.secrets().inNamespace(getNamespace()).createOrReplace(
                    new SecretBuilder().withNewMetadata().withName(name).endMetadata().withData(map).build());
        } catch (Exception e) {
        // handler
        }
    }
```

And in my unit test class, I have a test written as below:

```
    private KubernetesServer k8sServer;
    private KubernetesClient k8sClient;
    private KubernetesService kubeService;

    @BeforeEach
    public void init() {
        k8sServer = new KubernetesServer();
        k8sServer.before();
        k8sClient = k8sServer.getClient();
        kubeService = new KubernetesService();
        kubeService.setKubernetesClient(k8sClient);
    }
    @Test
    public void testUpsertSecretSuccessWhenMapNotEmpty() {
        k8sServer.expect().get().withPath("/api/v1/namespaces/test/secrets").andReturn(
                HttpURLConnection.HTTP_CREATED, new Secret()).once();

        Map<String, String> secretsMap = new HashMap<>();
        secretsMap.put("a", "b");
        kubeService.upsertSecret("sec", secretsMap);
    }
```

When I try to run the test, I am getting below error

```
13:33:41.915 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from service account...
Dec 01, 2022 1:33:41 PM okhttp3.mockwebserver.MockWebServer$3 execute
INFO: MockWebServer[62574] starting to accept connections
....
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Secret]  with name: [sec]  in namespace: [test]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
...
Dec 01, 2022 1:33:41 PM okhttp3.mockwebserver.MockWebServer$4 execute
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
...
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:62574
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
...
Caused by: java.net.ConnectException: Connection refused: connect
...
```
Using:
kubernetes-server-mock 4.13.2

Is there any configuration that needs to be done before running it?

**Comment by manusa** [comment]
4.x is a very old version of the client. Have you tried with a newer version?
