### ISSUE TITLE
Custom Resource watch might hang during initilization

### ISSUE THREAD

**Issue by winniegy** [fabric8io/kubernetes-client#4645]
### Describe the bug

We use fabric8 kubernetes client to watch for our specific custom resource.
Basically, we use KubernetesClientBuilder() to build a client, and use the following sample code to start to watch the custom resource.

Watch watch = client.resources(MyCR.class).watch(watchCallback);

We met once that the above code hangs for more than half an hour when deploying the microservice in a k8s cluster.
There is an OKHttp thread throwing an exception at first.
We found out that there might be a connection issue with k8s API server when the hanging issue happens. 

However, in general, the watch should not hang the thread and we found a suspicious code part, which might cause the hanging.

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java#L624

Basically, the theory is that when calling watch(), internally it first instantiates a WatchConnectionManager with a dedicated WebSocketTimeout. But if the other peer responds with .e.g, 503, then it falls into the error handling and tries to fall back on WatchHTTPManager, which then has readTimeout 0 (indefinite). In our case, we are not sure but it seems that after a possible 503 response, the k8s API server might not respond on the specific connection. Other components are able to talk to the k8s server but the watch seems to hang due to the indefinite read timeout.

It is hard to reproduce the issue though.

Therefore, we would like to ask,
1. if the above theory is possible
2. if there is any specific reason to use a persistent hanging HTTP GET instead of a resonable timeout, as stated in the comment part of the code.
3. if it is OK to introduce a reasonable readTimeout for WatchHTTPManager, to avoid hanging the thread in this case?

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

It is hard to reproduce the issue. But if a tester can control the k8s server side, it might be to reproduce.
1. respond with 503 with the first connection
2. accept the 2nd connection but does not respond.

### Expected behavior

Even though it is a rare case, the watch() should not hang the thread if there is no response from k8s server for a long time.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.23

### Environment

Linux

**Comment by shawkins** [comment]
> We met once that the above code hangs for more than half an hour when deploying the microservice in a k8s cluster.

@winniegy do you have a thread dump showing the hang on the watch call?

The calling thread should not hang when starting the http watch, even if the server does not respond.

**Comment by winniegy** [comment]
Hi @shawkins,
Thanks for the answer. Unfortunately, we do not have a thread dump because the test env. is cleaned up afterward.
However, we start the watch on the main thread and it does hang and does not proceed with the rest logic according the collected pod log.
And it seems that the http watch is in a Completable future so should be on another thread.
However,
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java#L583

It seems that watch method does wait indefinitely for the future to complete.
Since watcherToggle.disable() is called at https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/BaseOperation.java#L618
maybe that's why it waits indefinitely and does not get any notification.

Anyway, I am just guessing here and we will try to get the dump if we are able to reproduce it.

**Comment by shawkins** [comment]
> It seems that watch method does wait indefinitely for the future to complete.

The full sequence:

We attempt to start the web socket, represented by a completable future.  If that completes successfully, the future returns the resulting websocket based Watch.  If it fails with a 200 or 503, then we complete with an http based Watch instead.  Otherwise the exception bubbles up.

What the BaseOperation logic is waiting on is the completion with a Watch or an exception.  Once the WebSocket fails, the completion with the http watch is immediate - there is nothing that blocks as the call to start the http operation is async and success / failure are just handled via the appropriate callbacks on the Watcher.

Could you provide what your Watcher is doing?  We're removing some of the synchronization on master that would have been present in 6.2 - what I'm wondering with the thread dump is if somehow the eventReceived or onClose is leading to a dead lock.

**Comment by winniegy** [comment]
``Hi @shawkins 

Thanks for the info and sorry for the late reply.
We are actually trying to switch the underlying implementation of httpClient meanwhile. And I have switched from okhttp3 to the native jdk one in our test env.

However, this hanging scenario seems to happen more often now with the native jdk client.

I succeed to have a dump and I paste the relevant dump here with some modifications of the classes name as the project is not open source.


"main" #1 prio=5 os_prio=0 cpu=3399.12ms elapsed=835.81s allocated=164M defined_classes=7874 tid=0x00007f77040156a0 nid=0x9 waiting on condition  [0x00007f770d8c0000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.5/Native Method)
	- parking to wait for  <0x00000000d064cce0> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.5/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.5/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.5/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.5/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.5/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.get(java.base@17.0.5/CompletableFuture.java:2072)
	at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:161)
	at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:184)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.watch(BaseOperation.java:582)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.watch(BaseOperation.java:569)
	at test.kubernetes.crmonitor.CrMonitor.watchCrEvents(CrMonitor.java:192)
	- locked <0x00000000d1510b18> (a test.kubernetes.crmonitor.CrMonitor)
	at test.kubernetes.crmonitor.CrMonitor.start(CrMonitor.java:170)
	at test.App.startCrMonitor(App.java:302)
	at test.App.startService(App.java:260)
	at test.App.main(App.java:231)

   Locked ownable synchronizers:
	- None


"HttpClient-1-SelectorManager" #88 daemon prio=5 os_prio=0 cpu=40.15ms elapsed=826.68s allocated=186K defined_classes=14 tid=0x00007f77054056f0 nid=0x5f runnable  [0x00007f76483f6000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@17.0.5/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@17.0.5/EPollSelectorImpl.java:118)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@17.0.5/SelectorImpl.java:129)
	- locked <0x00000000d0d716c8> (a sun.nio.ch.Util$2)
	- locked <0x00000000d0d71560> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@17.0.5/SelectorImpl.java:141)
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(java.net.http@17.0.5/HttpClientImpl.java:889)

   Locked ownable synchronizers:
	- None
	
"Thread-46" #91 daemon prio=5 os_prio=0 cpu=80.19ms elapsed=826.18s allocated=1303K defined_classes=60 tid=0x00007f76280275b0 nid=0x62 waiting for monitor entry  [0x00007f76481f3000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at test.kubernetes.crmonitor.CrMonitor.handleCrEvent(CrMonitor.java:206)
	- waiting to lock <0x00000000d1510b18> (a test.kubernetes.crmonitor.CrMonitor)
	at test.kubernetes.crmonitor.CrMonitor$MyCRWatcher.eventReceived(CrMonitor.java:341)
	- locked <0x00000000d0765428> (a test.kubernetes.crmonitor.CrMonitor$MyCRWatcher)
	at test.kubernetes.crmonitor.CrMonitor$MyCRWatcher.eventReceived(CrMonitor.java:331)
	at io.fabric8.kubernetes.client.utils.internal.WatcherToggle.eventReceived(WatcherToggle.java:49)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:191)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:268)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.onMessage(WatchConnectionManager.java:113)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:55)
	- locked <0x00000000d07a2408> (a io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener)
	at io.fabric8.kubernetes.client.jdkhttp.JdkWebSocketImpl$ListenerAdapter.onText(JdkWebSocketImpl.java:125)
	at jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processText(java.net.http@17.0.5/WebSocketImpl.java:635)
	at jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(java.net.http@17.0.5/WebSocketImpl.java:443)
	at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(java.net.http@17.0.5/SequentialScheduler.java:149)
	at jdk.internal.net.http.common.SequentialScheduler$TryEndDeferredCompleter.complete(java.net.http@17.0.5/SequentialScheduler.java:347)
	at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(java.net.http@17.0.5/SequentialScheduler.java:151)
	at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(java.net.http@17.0.5/SequentialScheduler.java:230)
	at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(java.net.http@17.0.5/HttpClientImpl.java:157)
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(java.net.http@17.0.5/SequentialScheduler.java:305)
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(java.net.http@17.0.5/SequentialScheduler.java:274)
	at jdk.internal.net.http.websocket.WebSocketImpl.signalOpen(java.net.http@17.0.5/WebSocketImpl.java:713)
	at jdk.internal.net.http.websocket.WebSocketImpl.newInstance(java.net.http@17.0.5/WebSocketImpl.java:155)
	at jdk.internal.net.http.websocket.WebSocketImpl.lambda$newInstanceAsync$0(java.net.http@17.0.5/WebSocketImpl.java:125)
	at jdk.internal.net.http.websocket.WebSocketImpl$$Lambda$585/0x000000010066e038.apply(java.net.http@17.0.5/Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(java.base@17.0.5/CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17.0.5/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.postFire(java.base@17.0.5/CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@17.0.5/CompletableFuture.java:844)
	at java.util.concurrent.CompletableFuture$Completion.run(java.base@17.0.5/CompletableFuture.java:482)
	at java.lang.Thread.run(java.base@17.0.5/Thread.java:833)

   Locked ownable synchronizers:
	- None


As you can see from the main thread dump.
at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:184)
The functionality does hang at the waitUntilReadyOrFail, while internally the BaseOperation is trying to get either websocket or http based Watch.

Our code logic here is simple.
Frist get a k8s client with autoconfig but explicitly specify the master URI as DEFAULT_MASTER_URL ("https://kubernetes.default.svc").
Then start a watch to watch for our own custom resource (which is defined in a separate class, let's say MyCR). The related CRD has been deployed in the cluster before.

I am not sure what's going wrong here. And thanks in advance for the help.

**Comment by shawkins** [comment]
> - locked <0x00000000d1510b18> (a test.kubernetes.crmonitor.CrMonitor)
> - waiting to lock <0x00000000d1510b18> (a test.kubernetes.crmonitor.CrMonitor)

What locking is present in CrMonitor?

It looks like the main thread is holding lock that is needed by a Watch callback.

**Comment by winniegy** [comment]
Hi @shawkins,

Thanks for the feedback. I just figured this out as well.

Our CrMonitor class defines a synchronized method watchCrEvents(), which starts the watch.
And the callback from Watch is to another object, but the object would call on CrMonitor::handleCrEvent(...), which is synchronized on CrMonitor class object as well.
As we have some kind of recovery mechanism to recreate a watch in handling exception cases, we define both of the above methods as sync on the safe side, so that when an event is still being handled, the watch would not be closed. 

However, it seems that in this initial case, when creating and starting a watch, it might get events from k8s API immediately, which would invoke the callback before the BaseOperation::watch() method returns.
Therefore, it becomes a deadlock since the callback waits for the watch() method to finish first, while the watch() waits for the callback to finish processing the event.

And most of the time, there is no coming event for the first we start a watch, then it continues without any problem.
I am not sure if anything needs to be improved in kubernetes client, but we will get rid of the sync from our source code to avoid the deadlock.

Thank you again for your help!

**Comment by shawkins** [comment]
> Thank you again for your help!

No problem.  In the case of watch events I think we document to make sure that the callbacks are minimally blocking, but could also mention in the javadocs about the dangers of locking as well.

**Comment by winniegy** [comment]
> > Thank you again for your help!
> 
> No problem. In the case of watch events I think we document to make sure that the callbacks are minimally blocking, but could also mention in the javadocs about the dangers of locking as well.

That would be great! Thanks.

**Comment by winniegy** [comment]
As mentioned in the above comments, the issue is in the user's code, not in Kubernetes client. A possible improvement for Kubernetes client is to have a reminder in the doc. Therefore, I will close this ticket then.
