### ISSUE TITLE
Can we use k8s client latest version with k8s 1.3.x with ssl

### ISSUE THREAD

**Issue by danushkaf** [fabric8io/kubernetes-client#472]
I am trying $subject. In http it works fine. But when I try with ssl I am getting error below.
Then I tried setting kubernetes.tls.protocols=TLSv1.2  as well. But didn't work.

[1] Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version 
       at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) 
       at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) 
       at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979) 
       at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086) 
       at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332) 
       at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359) 
       at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343) 
       at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192) 
       at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149) 
       at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) 
       at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) 
       at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) 
       at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) 
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) 
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) 
       at com.squareup.okhttp.Call.getResponse(Call.java:286) 
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) 
       at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:85) 
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232) 
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) 
       at com.squareup.okhttp.Call.execute(Call.java:80) 
       at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230) 
       at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:416)

**Comment by jimmidyson** [comment]
Wow something changed in Kubernetes that's not release noted... I've reproduced & am working on a fix, although I don't want to break compatibility against any previous versions.

**Comment by jimmidyson** [comment]
I'll get a release out ASAP.

**Comment by danushkaf** [comment]
1.3.102 contains the fix right?
