### ISSUE TITLE
v1.3.102 is too strict in required TLS versions

### ISSUE THREAD

**Issue by danushkaf** [fabric8io/kubernetes-client#481]
1.3.101 is not there in http://repo.maven.apache.org/maven2/io/fabric8/kubernetes-client/

**Comment by jimmidyson** [comment]
Sometimes we skip pushing release versions if they fail staging. 101 failed, but 102 is available.

**Comment by danushkaf** [comment]
102 have a okhttp upgrade. We are having issues with that. Cant you release 101.

**Comment by jimmidyson** [comment]
102 does not have an okhttp upgrade. You can see the changes in https://github.com/fabric8io/kubernetes-client/compare/v1.3.101...v1.3.102. Perhaps if you tell us what issues you are having we can help to figure out what's wrong?

**Comment by danushkaf** [comment]
Sorry my bad. I am getting following issue. First I thought an okhttp version issue. Then I realized that I checked the version in master. Sorry about that.
Any how I am getting following error. My k8s version is 1.3.0 with core os.

Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:418)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:58)
        at org.wso2.appcloud.provisioning.runtime.KubernetesRuntimeProvisioningService.<init>(KubernetesRuntimeProvisioningService.java:79)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.mozilla.javascript.MemberBox.newInstance(MemberBox.java:159)
        ... 81 more
Caused by: java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)], supported protocols=[TLSv1]
        at com.squareup.okhttp.internal.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:73)
        at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:185)
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:83)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:416)
        ... 88 more

**Comment by jimmidyson** [comment]
OK that makes more sense. As a workaround until I get a new release out, you should be able to either:

* Use `.withTlsVersions(TlsVersion.TLS_1_2, TlsVersion.TLS_1_1, TlsVersion.TLS_1_0)` in ConfigBuilder (preferred - this is what I will change the default to)
* Set env var `KUBERNETES_TLS_VERSION` or system property `kubernetes.tls.version` to `TLSv1.2,TLSv1.1,TLSv1`.

Can you try that & let me know how you get on?

**Comment by danushkaf** [comment]
2nd one I already tried. First one will try and let you know.
Anyhow AFAIU this is about the cipher suits allowed by k8s.

**Comment by jimmidyson** [comment]
I think it's not the cipher suites, but the TLS version that can't be agreed upon between client & server:

    tlsVersions=[TLS_1_2], ..., supported protocols=[TLSv1]

What version of Kubernetes are you using?

**Comment by danushkaf** [comment]
Its 1.3.0 with core os

**Comment by jimmidyson** [comment]
Can you share the stack trace (if there is one) when you've tried the options above? I think they should work but if not then need to fix up. I failed to put together a unit test for this, couldn't figure out how to create a SSLSocketFactory that you could change the default supported TLS versions, but looks like I might need to look at that again to prevent this breaking in future.

**Comment by danushkaf** [comment]
With the second option, its the same stacktrace

**Comment by jimmidyson** [comment]
Doh! Just noticed it should be `KUBERNETES_TLS_VERSIONS` (extra s at the end, both in env var & system property). This works in our tests so could you please try that out?

**Comment by danushkaf** [comment]
when I do that I am getting protocol version error.
And I set only 1.2 there then back to same error
Caused by: java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)], supported protocols=[TLSv1]

**Comment by jimmidyson** [comment]
Could you share the code that you are running & the full stack trace please? I assume you're using 102 now & are setting environment variable `KUBERNETES_TLS_VERSIONS=TLSv1.2,TLSv1.1,TLSv1`?

**Comment by jimmidyson** [comment]
And just to check what Java version are you using?

**Comment by danushkaf** [comment]
when I set KUBERNETES_TLS_VERSIONS=TLSv1.2,TLSv1.1,TLSv1 I get protocol versions error. Which means TLS version mismatch. 
So I used following and got the same error
KUBERNETES_TLS_VERSIONS=TLSv1.2,TLSv1.1
KUBERNETES_TLS_VERSIONS=TLSv1.2

So AFAIU in [1] we need to add something similar to following code. Todo that we need cipher suits supported by k8s api server.
.cipherSuites(CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256)

[1] https://github.com/fabric8io/kubernetes-client/blob/v1.3.102/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/HttpClientUtils.java#L135

**Comment by danushkaf** [comment]
We are using java 7.

**Comment by jimmidyson** [comment]
MODERN_TLS connection spec already includes that cipher suite - https://github.com/square/okhttp/blob/parent-2.7.5/okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java#L43-L68

**Comment by jimmidyson** [comment]
Ah https://github.com/square/okhttp/blob/parent-2.7.5/okhttp/src/main/java/com/squareup/okhttp/ConnectionSpec.java#L48-L50:

> ... none of the better cipher suites listed above shipped with Android 4.4 or Java 7

**Comment by jimmidyson** [comment]
Try it with just `KUBERNETES_TLS_VERSIONS=TLSv1`

**Comment by danushkaf** [comment]
With java8 problem is not there. Was trying to figureout a way work it in java 7. Seems there is none.

**Comment by jimmidyson** [comment]
Well we have to fix that as we advertise java 7 compatibility. Let me have a bit more of a play around & see what we can do.

**Comment by jimmidyson** [comment]
Can you share the output of `curl -v -k https://<APISERVER_IP>` (assuming you're on Linux/OS X)? Just want to see what TLS version & cipher suite is negotiated by curl?

**Comment by jimmidyson** [comment]
Ah I think I have a potential fix for Java 7. Once I push a fix, would you be able to do a local build & try it out to see if it works for you?

**Comment by danushkaf** [comment]
Sure will do. Could you give me the diff as well. So I can try with older okhttp version.

**Comment by jimmidyson** [comment]
I'll push it to a 1.3 branch so it uses the older okhttp version. I've managed to recreate it now so I should be pretty confident it will work for you.

**Comment by danushkaf** [comment]
Thanks

**Comment by jimmidyson** [comment]
Published 1.3.104 - please try with that. Should work with defaults against Kubernetes 1.3.0. Let me know hot you get on & we can close this issue if you're happy.

**Comment by danushkaf** [comment]
Thanks Jimmi. It works finally.

**Comment by jimmidyson** [comment]
Awesome thanks!
