### ISSUE TITLE
watch auto closed

### ISSUE THREAD

**Issue by gjj2016** [fabric8io/kubernetes-client#4840]
### Describe the bug

```client.configMaps().inNamespace("default").watch(new Watcher<ConfigMap>() {
            @Override
            public void eventReceived(Watcher.Action action, ConfigMap resource) {
                try {
                    Thread.sleep(40000);
                } catch (Exception e) {
                    log.error("Event receive sleep error", e);
                }
                log.info("{} configmap:{}", action.name(), resource.getMetadata().getName());
            }

            @Override
            public void onClose(WatcherException cause) {
                log.info("Watch configmap closed");
            }
        });
```

If we mock a long block in eventReceived() method, bigger then the default ping/pong interval(30s), then the watch will be auto closed.

The reason behind is that a smaller resourceVersion is used in reConnect watch.

I wonder if there are any solutions except set a bigger ping/pong interval?

### Fabric8 Kubernetes Client version

6.4.1

### Steps to reproduce

Just use the specified code

### Expected behavior

The watch exit

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows

### Fabric8 Kubernetes Client Logs

```shell
15:53:41.917 [ForkJoinPool.commonPool-worker-1] DEBUG io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager - Watching https://1.2.3.4:6443/api/v1/namespaces/default/configmaps?allowWatchBookmarks=true&watch=true...
15:53:42.270 [OkHttp https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener - WebSocket successfully opened
15:53:42.271 [main] INFO tt.fabric8.test.ConfigMapTest - Done
15:54:22.327 [OkHttp https://1.2.3.4:6443/...] INFO tt.fabric8.test.ConfigMapTest - ADDED configmap:demo-literal-config
15:54:42.282 [OkHttp WebSocket https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener - WebSocket error received
java.net.SocketTimeoutException: sent ping but didn't receive pong within 30000ms (after 0 successful ping/pongs)
	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:546)
	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:530)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
15:54:42.283 [OkHttp WebSocket https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager - Scheduling reconnect task
15:54:42.283 [OkHttp WebSocket https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.utils.internal.ExponentialBackoffIntervalCalculator - Current reconnect backoff is 1000 milliseconds (T0)
15:54:43.294 [-1087072654-pool-1-thread-1] DEBUG io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager - Watching https://1.2.3.4:6443/api/v1/namespaces/default/configmaps?resourceVersion=72595620&allowWatchBookmarks=true&watch=true...
15:54:43.296 [-1087072654-pool-1-thread-1] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Closing websocket io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl@3377cdc0
15:54:43.297 [-1087072654-pool-1-thread-1] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Websocket already closed io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl@3377cdc0
15:54:43.555 [OkHttp https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener - WebSocket successfully opened
15:54:43.580 [OkHttp https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager - Closing websocket io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl@58bfbb69
15:54:43.580 [OkHttp https://1.2.3.4:6443/...] INFO tt.fabric8.test.ConfigMapTest - Watch configmap closed
15:54:43.580 [OkHttp https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager - Force closing the watch io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@4eec3183
15:54:43.580 [OkHttp https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager - Ignoring duplicate firing of onClose event
15:54:43.581 [OkHttp https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener - WebSocket close received. code: 1000, reason: 
15:54:43.582 [OkHttp https://1.2.3.4:6443/...] DEBUG io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager - Ignoring already closed/closing connection
15:55:02.340 [OkHttp https://1.2.3.4:6443/...] INFO tt.fabric8.test.ConfigMapTest - ADDED configmap:demo-yaml-config
```

### Additional context

v1.20.7

**Comment by shawkins** [comment]
> I wonder if there are any solutions except set a bigger ping/pong interval?

It is not recommended to use long / blocking operations in callbacks.  Due to how thread usage is now minimized in the client that has negative consequences.  As you see for okhttp it prevents ping / pong processing.  For the other http client types the threads are shared for all work, so this style of processing would eventually prevent any httpclient layer progress.

You should switch to a paradigm of only performing non-blocking work in the callback methods.  If something needs to block, then put that into a work queue so you can further manage the thread utilization.
