### ISSUE TITLE
No mock server support for PatchType.STRATEGIC_MERGE

### ISSUE THREAD

**Issue by balamuru** [fabric8io/kubernetes-client#4913]
### Describe the bug

When attempting to mock a patch call that was using a STRATEGIC MERGE, I observed a 415 response code .

Upon investigating, I noticed that the mock server does not yet support PatchType.STRATEGIC_MERGE  (see code below). I was using the 6.2.0 API but the behavior exists in the latest too.

https://github.com/fabric8io/kubernetes-client/blob/master/junit/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/crud/PatchHandler.java#L109

### Fabric8 Kubernetes Client version

6.2.0

### Steps to reproduce

1. Create a K8s resource
2. Persist it to a mock kubernetes server
3. Attempt to patch it using 
```
client.resource(resource).patch(PatchContext.of(PatchType.STRATEGIC_MERGE));
```

The patch will fail as described earlier (415)

### Expected behavior

The patch command should succeed

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

### Fabric8 Kubernetes Client Logs

```shell
INFO: MockWebServer[57947] received request: PATCH /api/v1/namespaces/hpinternal/pods/bosun-dev-abcdef-5wxyz HTTP/1.1 and responded: HTTP/1.1 415 Client Error

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://localhost:57947/api/v1/namespaces/hpinternal/pods/bosun-dev-abcdef-5wxyz. Message: Unsupported Media Type. Received status: Status(apiVersion=v1, code=415, details=StatusDetails(causes=[], group=null, kind=Unknown, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Unsupported Media Type, metadata=null, reason=Invalid, status=Failure, additionalProperties={}).

	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:517)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:551)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:414)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handlePatch(OperationSupport.java:391)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handlePatch(BaseOperation.java:685)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.lambda$patch$2(HasMetadataOperation.java:215)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:220)
	at io.fabric8.kubernetes.client.dsl.internal.HasMetadataOperation.patch(HasMetadataOperation.java:230)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.patch(BaseOperation.java:537)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.patch(BaseOperation.java:88)
	at io.fabric8.kubernetes.client.extension.ResourceAdapter.patch(ResourceAdapter.java:302)
```

**Comment by balamuru** [comment]
Looks like STRATEGIC_MERGE is unsupported . Can someone explain why or if it will be supported in the future ?

https://github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/junit/kubernetes-server-mock/src/test/java/io/fabric8/kubernetes/client/server/mock/crud/KubernetesCrudDispatcherPatchTest.java#L85

**Comment by shawkins** [comment]
> Can someone explain why or if it will be supported in the future ?

The mock server has and will continue to be only a best effort api server implementation.  Many features are not present in the mock server.  If you want to add this support look for an applicable library providing strategic merge support and see about wiring it into the mock server like the json patch support.
