### ISSUE TITLE
NoClassDefFoundError: io/fabric8/kubernetes/client/dsl/ServerSideApplicable

### ISSUE THREAD

**Issue by marrek13** [fabric8io/kubernetes-client#4946]
### Describe the bug

Hello, I try to upgrade the client from the 5.* to the last 6.* version. Unfortunately after replacing deprecated usage of `DefaultKubernetesClient` class with `KubernetesClientBuilder().build()` the application during the runtime throws the NoClassDefFoundError.

### Fabric8 Kubernetes Client version

6.4.1

### Steps to reproduce

As in the bug description

### Expected behavior

No exception related to a class that I can't even found in the codebase.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Amazon

### Fabric8 Kubernetes Client Logs

```shell
java.lang.ClassNotFoundException: io.fabric8.kubernetes.client.dsl.ServerSideApplicable
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:149)
... 1 frames excluded
... 97 common frames omitted
Wrapped by: <#30136981> java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/dsl/ServerSideApplicable
at io.fabric8.kubernetes.client.impl.KubernetesClientImpl.<init>(KubernetesClientImpl.java:239)
... 96 common frames omitted
Wrapped by: <#344814dc> java.lang.reflect.InvocationTargetException: null
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Unknown Source)
... 4 frames excluded
at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:79)
... 90 common frames omitted
Wrapped by: <#6c6dd14d> io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129)
at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:122)
at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:83)
at com.sumup.catalog.gateway.config.grpc.KubernetesNameResolver.<init>(KubernetesNameResolver.kt:31)
at com.sumup.catalog.gateway.config.grpc.KubernetesNameResolverProvider.newNameResolver(KubernetesNameResolverProvider.kt:30)
at io.grpc.NameResolverRegistry$NameResolverFactory.newNameResolver(NameResolverRegistry.java:166)
at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:750)
at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:782)
at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:662)
at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:631)
at io.grpc.internal.AbstractManagedChannelImplBuild...
```

**Comment by rohanKanojia** [comment]
Do you have `io.fabric8:kubernetes-client-api` dependency in your classpath?

https://github.com/fabric8io/kubernetes-client/blob/master/doc/MIGRATION-v6.md#apiimpl-split

**Comment by marrek13** [comment]
Indeed I missed this dependency. After adding it and making the `kubernetes-client` runtimeOnly I had another exception

```
java.lang.ClassNotFoundException: io.fabric8.kubernetes.client.http.HttpClient$AsyncBody
```

I noticed that there are different versions of libraries resolved by Gradle
![image](https://user-images.githubusercontent.com/3691208/222690676-02fa47ef-892d-4ffc-8a3f-49de6d6f144d.png)

I needed to add also `io.fabric8:kubernetes-httpclient-okhttp` dependency to finally get it working
