### ISSUE TITLE
where is the ConfigBuilder classs

### ISSUE THREAD

**Issue by bigfreeZhou** [fabric8io/kubernetes-client#497]
hello,where is the ConfigBuilder classs, i can't find it...

**Comment by jimmidyson** [comment]
It's generated as part of the build. What are you trying to do?

**Comment by imshashank** [comment]
I am also getting error that ConfigBuilder is not found. 

```
Unresolved compilation problems:
	The import io.fabric8.kubernetes.client.ConfigBuilder cannot be resolved
	ConfigBuilder cannot be resolved to a type

	at io.fabric8.openshift.client.mock.TemplateTest.<init>(TemplateTest.java:38)

testList(io.fabric8.openshift.client.mock.TemplateTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.Error:
Unresolved compilation problems:
	The import io.fabric8.kubernetes.client.ConfigBuilder cannot be resolved
	ConfigBuilder cannot be resolved to a type

	at io.fabric8.openshift.client.mock.TemplateTest.<init>(TemplateTest.java:38)

testProcess(io.fabric8.openshift.client.mock.TemplateTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Error:
Unresolved compilation problems:
	The import io.fabric8.kubernetes.client.ConfigBuilder cannot be resolved
	ConfigBuilder cannot be resolved to a type

	at io.fabric8.openshift.client.mock.TemplateTest.<init>(TemplateTest.java:38)

testDelete(io.fabric8.openshift.client.mock.TemplateTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.Error:
Unresolved compilation problems:
	The import io.fabric8.kubernetes.client.ConfigBuilder cannot be resolved
	ConfigBuilder cannot be resolved to a type

	at io.fabric8.openshift.client.mock.TemplateTest.<init>(TemplateTest.java:38)
```

I got same error in eclipse and in CLI "mvn clean install"

Can u please post minimum requirements on main git page for JAVA/mvn versions.

**Comment by subaprasanna** [comment]
i am also getting the same error .. Can you please point us to correct direction
