### ISSUE TITLE
waitUntilReady() throws exception | 4.13.1

### ISSUE THREAD

**Issue by Vishwamagdavan** [fabric8io/kubernetes-client#5210]
I have Spring boot application, that creates k8s object using manifest file. fabric8 java client version: 4.13.1. waitUntilReady failing to execute
```
List<HasMetadata> result = client.load(new ByteArrayInputStream(manifest.getBytes())).get();
client.resourceList(result).inNamespace(namespace).createOrReplaceAnd().waitUntilReady(10,TimeUnit.SECONDS);
```

```
Exception in thread "OkHttp Dispatcher" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6c117487[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@2e8c4d43[Wrapped task = io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2@4fe59ed1]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@44c62cb[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:715)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:748)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.scheduleReconnect(WatchConnectionManager.java:305)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$800(WatchConnectionManager.java:50)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:217)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onFailure(RealWebSocket.kt:202)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by NayanPatidar** [comment]
is the issue still there ??
