### ISSUE TITLE
NullPointerException in StandardHttpClient.getTag() on FIPS enabled OpenShift Cluster

### ISSUE THREAD

**Issue by LinghaoYu** [fabric8io/kubernetes-client#5291]
### Describe the bug

Fabric8 Kubernetes Client is `6.5.1`, OpenShift version `4.10.54`, and FIPS is enabled. See Full stack trace below.
NPE is thrown from this line https://github.com/fabric8io/kubernetes-client/blob/v6.5.1/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/http/StandardHttpClient.java#L228. The only possible cause I can think of is the variable `builder` itself is null, because `type` coming from line 167 is not null, `builder.tags` is a LinkedHashMap not null, `Class.cast(null)` won’t throw error. Can anyone suggest in which condition will this happen? **Note that the error only happens on FIPS enabled clusters. On Non-FIPS enabled cluster everything works fine.**
This is how we are calling the library, which hasn't been changed for 2 years
```
JobBuilder jobBuilder = KubernetesMetadataController.getInstance().setMetaDataForJob(new JobBuilder(), msjob);
jobBuilder = setJobSpec(jobBuilder, msjob, podName);
final Job job = jobBuilder.build();
client.batch().jobs().inNamespace(namespace).create(job);
```

### Fabric8 Kubernetes Client version

6.5.1

### Steps to reproduce

Try starting a job on an FIPS-enabled cluster

### Expected behavior

No exception

### Runtime

OpenShift

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
java.lang.NullPointerException
at io.fabric8.kubernetes.client.http.StandardHttpClient.getTag(StandardHttpClient.java:228)
at io.fabric8.kubernetes.client.http.StandardHttpClient.retryWithExponentialBackoff(StandardHttpClient.java:167)
at io.fabric8.kubernetes.client.http.StandardHttpClient.consumeBytes(StandardHttpClient.java:79)
at io.fabric8.kubernetes.client.http.SendAsyncUtils.bytes(SendAsyncUtils.java:51)
at io.fabric8.kubernetes.client.http.HttpResponse$SupportedResponses.sendAsync(HttpResponse.java:105)
at io.fabric8.kubernetes.client.http.StandardHttpClient.sendAsync(StandardHttpClient.java:65)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:589)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:566)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:350)
at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:707)
at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:93)
at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:42)
```

**Comment by shawkins** [comment]
That looks very odd.  There doesn't appear to be any path where any of the references can be null.  Would it be possible to debug this and see what is happening in the getTag call?

**Comment by LinghaoYu** [comment]
It was actually caused by passing a null as builder to initiate the HTTP client.
