### ISSUE TITLE
can't seem to post an ImageStreamTag

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-client#535]
trying to post this
```
---
apiVersion: "v1"
kind: "ImageStreamTag"
metadata:
  name: "bar1:1.0.12"
tag:
  from:
    kind: "ImageStreamImage"
    name: "bar1@sha256:1e924a1281084eea8e882d1bd96ee020cd077b48d71fea201de85f8ab3f67874"
    namespace: "default"
  name: "1.0.12"
```
generates this
```
14:57:27.319 [main] ERROR io.fabric8.kubernetes.api.Controller - Failed to create ImageStreamTag from ab483f0b-72fa-4baf-a919-46984449f2ee. io.fabric8.kubernetes.client.KubernetesClientException: Error executing: POST at: https://192.168.64.86:8443/oapi/v1/namespaces/default-testing/imagestreamtags. Cause: No resource type found for kind:DockerImage
 at [Source: buffer(okhttp3.internal.http.Http1xStream$FixedLengthSource@27976390).inputStream(); line: 1, column: 661] (through reference chain: io.fabric8.openshift.api.model.ImageStreamTag["image"]->io.fabric8.openshift.api.model.Image["dockerImageMetadata"])
io.fabric8.kubernetes.client.KubernetesClientException: Error executing: POST at: https://192.168.64.86:8443/oapi/v1/namespaces/default-testing/imagestreamtags. Cause: No resource type found for kind:DockerImage
 at [Source: buffer(okhttp3.internal.http.Http1xStream$FixedLengthSource@27976390).inputStream(); line: 1, column: 661] (through reference chain: io.fabric8.openshift.api.model.ImageStreamTag["image"]->io.fabric8.openshift.api.model.Image["dockerImageMetadata"])
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestException(OperationSupport.java:323)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:246)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:207)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:578)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:278)
	at io.fabric8.openshift.client.handlers.ImageStreamTagHandler.create(ImageStreamTagHandler.java:42)
	at io.fabric8.openshift.client.handlers.ImageStreamTagHandler.create(ImageStreamTagHandler.java:31)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetDeleteRecreateApplicableImpl.apply(NamespaceVisitFromServerGetDeleteRecreateApplicableImpl.java:123)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetDeleteRecreateApplicableImpl.apply(NamespaceVisitFromServerGetDeleteRecreateApplicableImpl.java:51)
	at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:280)
	at io.fabric8.kubernetes.api.Controller.apply(Controller.java:218)
	at io.fabric8.arquillian.kubernetes.SessionListener.applyConfiguration(SessionListener.java:377)
	at io.fabric8.arquillian.kubernetes.SessionListener.start(SessionListener.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
	at io.fabric8.arquillian.kubernetes.SuiteListener.start(SuiteListener.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:75)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for kind:DockerImage
 at [Source: buffer(okhttp3.internal.http.Http1xStream$FixedLengthSource@27976390).inputStream(); line: 1, column: 661] (through reference chain: io.fabric8.openshift.api.model.ImageStreamTag["image"]->io.fabric8.openshift.api.model.Image["dockerImageMetadata"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:867)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:55)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2796)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:238)
	... 48 common frames omitted
```

Am guessing the issue is the transitive `ImageStreamTag.image` of kind `DockerImage` needs to be supported too? Incidentally I tried missing that kind off but the POST still barfs

**Comment by jstrachan** [comment]
note that I"m not 100% sure that you can/should post individual ImageStreamTag resources - but it does feel like the right thing to do. e.g. we could make 2 releases; 1.0 and 2.0; we want to be able to promote a single release/tag in a single environment; so it feels better to just post tag 1.0 or 2.0 to some environment to create it - rather than posting the ImageStream with an embedded list of tags (which means you could accidentally remove tags etc!)

As a workaround I've left the S2I release pipeline creating an ImageStream - then I've added a custom merge function to ensure when applying an ImageStream we add any new tags to the existing ImageStream if it already exists:
https://github.com/fabric8io/fabric8/pull/6416/commits/f00872f1c2aa70f327b49637b6755cb778977670

If you want to experiment with the ImageStreamTag version of the fabric8-maven-plugin there's a branch here:
https://github.com/jstrachan/fabric8-maven-plugin/tree/istag

which whenever you do a build using S2I mode on openshift it generates an ImageStreamTag that you can then apply to another namespace (e.g.  via an ARQ test). To enable S2I mode btw use `-Dfabric8.mode=auto` and use minishift

**Comment by iocanel** [comment]
Added DockerImage to the kubernetes-model. Waiting for the release...

**Comment by iocanel** [comment]
Release is ready. Upgrade to the latest release. Now we need to try it out.

**Comment by iocanel** [comment]
@jstrachan: Tried your branch against the spring-boot-webmvc quickstart on minishift. Seems to work fine, so I think we can close now.
