### ISSUE TITLE
"Cannot construct instance of `io.fabric8.kubernetes.client.Config$ExecCredential`" when creating a config

### ISSUE THREAD

**Issue by tomslot** [fabric8io/kubernetes-client#5361]
### Describe the bug

I am getting the following exception from a unit test:

Cannot construct instance of `io.fabric8.kubernetes.client.Config$ExecCredential` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile.')
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
java.lang.IllegalArgumentException: Cannot construct instance of `io.fabric8.kubernetes.client.Config$ExecCredential` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile.')
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4334)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.parseYaml(KubernetesSerialization.java:276)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.unmarshal(KubernetesSerialization.java:252)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.unmarshal(KubernetesSerialization.java:342)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.unmarshal(KubernetesSerialization.java:327)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:185)
	at io.fabric8.kubernetes.client.Config.getExecCredentialFromExecConfig(Config.java:817)
	at io.fabric8.kubernetes.client.Config.mergeKubeConfigExecCredential(Config.java:784)
	at io.fabric8.kubernetes.client.Config.mergeKubeConfigAuthInfo(Config.java:763)
	at io.fabric8.kubernetes.client.Config.mergeKubeConfigContents(Config.java:733)
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:707)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:669)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:290)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:255)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:246)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:10)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:7)

I debugged your library code and I found that the bug is located in **io.fabric8.kubernetes.client.Config.getExecCredentialFromExecConfig()**:
The library is trying to parse a plain string error message output from ProcessBuilder as ExecCredential json.
The ProcessBuilder is executing the following command:

/usr/local/bin/aws --region XXX eks get-token --cluster-name YYY --output json

And the actual output is

"The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile." (not a JSON)
	

### Fabric8 Kubernetes Client version

6.8.0

### Steps to reproduce

Probably just create a ConfigBulider with dummy values and provide no k8s configuration

### Expected behavior

The error output from the aws command is handled gracefully and is presented to the user in an unobfuscated manner

### Runtime

minikube

### Kubernetes API Server version

1.25.3@latest

### Environment

macOS

**Comment by manusa** [comment]
It seems that we're persisting the errored command output:

However, you should still be able to see some warning in your logs:

https://github.com/fabric8io/kubernetes-client/blob/b81ebaea8139a2496ce25ce6b85a61387a8c0202/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L814-L816

I'm not really sure if there's much more we can do in this regard. We could make the behavior more disruptive and throw a `KubernetesClientException`, but this might not be expected for all of the current users.
