### ISSUE TITLE
 too old resource version: 2262939 (6575374)

### ISSUE THREAD

**Issue by lostting** [fabric8io/kubernetes-client#5372]
### Describe the bug

o.fabric8.kubernetes.client.WatcherException: too old resource version: 2262939 (6575374)
报错了too old resource version: 2262939 (6575374)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onStatus(AbstractWatchManager.java:322)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:289)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:68)
	at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onMessage(OkHttpWebSocketImpl.java:97)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Fabric8 Kubernetes Client version

5.11.2

### Steps to reproduce

开启watch监听后，会莫名其妙的关闭出现资源版本对不上的问题，而导致watch关闭

### Expected behavior

希望可以得知什么情况下会导致资源变动更新版本号，如何避免这种问题发生

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
报错了too old resource version: 17174445 (27840729)
io.fabric8.kubernetes.client.WatcherException: too old resource version: 17174445 (27840729)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onStatus(AbstractWatchManager.java:322)
	at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:289)
	at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:68)
	at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onMessage(OkHttpWebSocketImpl.java:97)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 17174445 (27840729)
	... 13 more
```

**Comment by manusa** [comment]
Your watcher has become stale. You need to restart it.
This is automatically handled in v6.x.

**Comment by shawkins** [comment]
> This is automatically handled in v6.x.

This is handled automatically by Informers, but not for Watches.  Bookmarks will be used by default, which for newer api servers make this exception much more infrequent.

**Comment by manusa** [comment]
>  Bookmarks will be used by default, which for newer api servers make this exception much more infrequent.

Yes, that's an important nuance :sweat_smile:

**Comment by lostting** [comment]
> 你的观察者已经过时了。您需要重新启动它。 这在 v6.x 中自动处理。

Thank you for your reply. I have replaced the latest version and will try again to see if the same problem will occur.
