### ISSUE TITLE
kubernetes client fails with NoClassFound

### ISSUE THREAD

**Issue by khauser** [fabric8io/kubernetes-client#5376]
### Describe the bug

With:
```java
Config config = Config.autoConfigure(null);
KubernetesClient client = new KubernetesClientBuilder().withConfig(config).build();
```

I get:
```
java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/V1Alpha1AdmissionRegistrationAPIGroupDSL
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:79)
```

### Fabric8 Kubernetes Client version

6.3.1

### Steps to reproduce

1. gradle project with kubernetes client

### Expected behavior

gradle clean build should pass through

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Windows

**Comment by rohanKanojia** [comment]
@khauser : Could you please check if upgrading to latest versions would resolve this issue?

**Comment by khauser** [comment]
@rohanKanojia: It also fails with 6.8.0.

**Comment by khauser** [comment]
I was updating from 6.2.0 and there it works.

**Comment by rohanKanojia** [comment]
@khauser : Could you please share a reproducer project? Do you have any kind of dependency exclusions in your project?

**Comment by khauser** [comment]
Sure
[project.zip](https://github.com/fabric8io/kubernetes-client/files/12288100/project.zip)
You must add your own kube-config under integrationTest/resources.

**Comment by rohanKanojia** [comment]
@khauser : I'm trying to run your test but I'm getting this error. I copied my `~/.kube/config` into integrationTest/resources like you specified:

```

> Task :integrationTest

ISTEKubernetesClientTest > test() FAILED
    io.fabric8.kubernetes.client.KubernetesClientException at ISTEKubernetesClientTest.java:27
        Caused by: java.io.IOException at ISTEKubernetesClientTest.java:27
            Caused by: java.net.SocketTimeoutException at NioSocketImpl.java:546

1 test completed, 1 failed

> Task :integrationTest FAILED

 ***** All completed @ Tue Aug 08 13:48:20 IST 2023  ***

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integrationTest'.
> There were failing tests. See the report at: file:///home/rokumar/Downloads/project/build/reports/tests/integrationTest/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
11 actionable tasks: 11 executed

```

**Comment by khauser** [comment]
Maybe you find more information under ///home/rokumar/Downloads/project/build/reports/tests/integrationTest/index.html (open in browser.

**Comment by khauser** [comment]
Nethertheless I was able to fix my problem by using this bom approach I founf here #4503.

```
kubernetesClientVersion = '6.8.0'
...
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        mavenBom "io.fabric8:kubernetes-client-bom:${kubernetesClientVersion}"
    }
}
...
implementation group: 'io.fabric8', name: 'kubernetes-client', version: "${kubernetesClientVersion}"
```

With this the build passes successful.
