### ISSUE TITLE
升级到6x版本后出现的 io/fabric8/kubernetes/model/jackson/UnmatchedFieldTypeModule

### ISSUE THREAD

**Issue by lostting** [fabric8io/kubernetes-client#5386]
### Describe the bug

 io/fabric8/kubernetes/model/jackson/UnmatchedFieldTypeModule

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

从5.12.2升级到6.8.0版本出现的问题 构建client连接时出现的问题
Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/model/jackson/UnmatchedFieldTypeModule
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.<init>(KubernetesSerialization.java:68)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.<init>(KubernetesSerialization.java:76)
	at io.fabric8.kubernetes.client.utils.Serialization.<clinit>(Serialization.java:38)
	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:47)
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:706)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:669)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:290)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:255)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:246)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:10)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:7)
	at com.guoyutec.container.util.Fabric8Utils.getK8sClient(Fabric8Utils.java:43)
	at com.guoyutec.container.util.Fabric8Utils.main(Fabric8Utils.java:279)
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.model.jackson.UnmatchedFieldTypeModule
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more

### Expected behavior

解决问题

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/model/jackson/UnmatchedFieldTypeModule
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.<init>(KubernetesSerialization.java:68)
	at io.fabric8.kubernetes.client.utils.KubernetesSerialization.<init>(KubernetesSerialization.java:76)
	at io.fabric8.kubernetes.client.utils.Serialization.<clinit>(Serialization.java:38)
	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:47)
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:706)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:669)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:290)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:255)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:246)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:10)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:7)
	at com.guoyutec.container.util.Fabric8Utils.getK8sClient(Fabric8Utils.java:43)
	at com.guoyutec.container.util.Fabric8Utils.main(Fabric8Utils.java:279)
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.model.jackson.UnmatchedFieldTypeModule
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more
```

**Comment by manusa** [comment]
Looks like you might have convergent dependencies with incompatible versions of different Kubernetes Client modules.

Are you using Spring cloud or something like that (a 3rd party dependency that might be overriding the dependency configuration for the Kubernetes Client version)?

Have you tried to provide a `dependencyManagement` configuration:

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>kubernetes-client-bom</artifactId>
      <version>${fabric8.client.version}</version>
      <scope>import</scope>
      <type>pom</type>
    </dependency>
  <!-- ... -->
  </dependencies>
</dependencyManagement>
```

https://github.com/fabric8io/kubernetes-client/blob/main/doc/FAQ.md#ive-tried-adding-a-dependency-to-kubernetes-client-but-im-still-getting-weird-class-loading-issues-what-gives

**Comment by kaktos** [comment]
I got the same problem..

**Comment by manusa** [comment]
> I got the same problem..

Could you provide details regarding the pointers given in my previous comment (https://github.com/fabric8io/kubernetes-client/issues/5386#issuecomment-1706323562)?

**Comment by lihao712** [comment]
I am facing the same issue, and it seems that this error indicates that the version of jackson databind dependency used by Fabric8 Kubernetes Client is higher than the one used in the current project.

`Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/MismatchedInputException
	at io.fabric8.kubernetes.model.jackson.UnmatchedFieldTypeModule$1.lambda$updateBuilder$0(UnmatchedFieldTypeModule.java:57)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at io.fabric8.kubernetes.model.jackson.UnmatchedFieldTypeModule$1.updateBuilder(UnmatchedFieldTypeModule.java:57)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:267)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:169)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3732)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
	at io.fabric8.kubernetes.client.internal.KubeConfigUtils.parseConfigFromString(KubeConfigUtils.java:47)
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:653)
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:616)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:286)
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:282)
	at org.apache.spark.deploy.k8s.SparkKubernetesClientFactory$.createKubernetesClient(SparkKubernetesClientFactory.scala:86)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$4.apply(KubernetesClientApplication.scala:220)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication$$anonfun$run$4.apply(KubernetesClientApplication.scala:220)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2576)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:227)
	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:199)`

**Comment by lihao712** [comment]
I used Fabric8 Kubernetes Client in spark ，and the version of jackson core/databind is 2.6.7

**Comment by manusa** [comment]
Have you tried what's pointed out here: https://github.com/fabric8io/kubernetes-client/issues/5386#issuecomment-1706323562

_Setting dependencyManagement versions for the conflicting dependencies_

**Comment by lihao712** [comment]
> Have you tried what's pointed out here: [#5386 (comment)](https://github.com/fabric8io/kubernetes-client/issues/5386#issuecomment-1706323562)
> 
> _Setting dependencyManagement versions for the conflicting dependencies_

yes，I check all the dependency which could import fabric8io/kubernetes-client, and use IDEA maven tool to check, but I will also use method you have mentioned, thanks

**Comment by jebeaudet** [comment]
FYI I had the same problem with spring cloud dependency management. I added the `kubernetes-client-bom` above the spring-cloud entry and it worked, thanks @manusa!
