### ISSUE TITLE
rc/rs rollingUpdate fails with '409 conflict' on k8s v1.4.x clusters

### ISSUE THREAD

**Issue by ravilr** [fabric8io/kubernetes-client#546]
@iocanel @jimmidyson 

k8s v1.4.0 introduced resource garbage collection which makes rc deletion asynchronous: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md/#kubectl-delete--v140-client-vs-v140-cluster

rc/rs rollUpdate(), creates a new rc with deployment hash label, and then cleans up the old rc, and finally renames the new rc with old rc name..
During this, the delete operation on old rc returns quickly, followed by the create() call on with old rc name. the create() call fails with "rc with name 'blah' already exists".

This change in server api needs to be handled in this client somehow. We can either retry on '409 Conflict' or wait some time before creating a resource with same name.

this exception trace is from kubernetes-client-1.3.95:

2016-10-18 02:04:56 ERROR KubeClient:403 - Error updating replication controller
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kube-master.com:6443/api/v1/namespaces/shortcircuit/replicationcontrollers. Message: replicationcontrollers "boson.adapter-controller" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=replicationcontrollers, name=boson.adapter-controller, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=replicationcontrollers "boson.adapter-controller" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:294)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:247)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:216)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:198)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:542)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:243)
        at io.fabric8.kubernetes.client.dsl.internal.RollingUpdater.rollUpdate(RollingUpdater.java:149)
        at io.fabric8.kubernetes.client.dsl.internal.ReplicationControllerOperationsImpl.replace(ReplicationControllerOperationsImpl.java:236)
        at io.fabric8.kubernetes.client.dsl.internal.ReplicationControllerOperationsImpl.replace(ReplicationControllerOperationsImpl.java:54)

**Comment by ravilr** [comment]
here is the pr in upstream: https://github.com/kubernetes/kubernetes/pull/29971 which made changes to kubectl rolling-update.

the fix here should be:
1. first delete the new rc with deleteOption set to OrphanDependents:true
2. keep polling to see the above rc is not get'able upto 60 seconds (by that time, the oldRC with oldName, deleted should also be gone).
3. create the rc with oldName with resourceVersion set to null.
