### ISSUE TITLE
Intermittent issue while retrieving pod list after upgrading from 5.8.0 to 6.8.1

### ISSUE THREAD

**Issue by venu19304** [fabric8io/kubernetes-client#5511]
### Describe the bug

We have piece of java code which retrieves pod list and was working fine in 5.8.0 version. But after upgrading client version to 6.8.1, sometimes fetching pod list is failing. Have attached logs for the same. This is intermittent and not observed in all pods. In which ever pod this issue shows up will not go till we restart the pod. 

### Fabric8 Kubernetes Client version

6.8.1

### Steps to reproduce

Execute below code - 

```
try(final KubernetesClient k8s = new DefaultKubernetesClient();) {
	k8s.pods().list().getItems().forEach(pod-> podsSet.add(pod.getMetadata().getName()));
	Logger.logInfo("Pod Set-->" + podsSet);
} catch (Exception e) {
	Logger.logError(e);
}
```

### Expected behavior

Return pod list

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Fabric8 Kubernetes Client Logs

```shell
ERROR - - - - - - CONSOLE Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [fsgbu-baics--kkkkkk]  failed.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [fsgbu-baics--kkkkkk]  failed.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:159) ~[kubernetes-client-api-6.8.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:422) ~[kubernetes-client-6.8.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:388) ~[kubernetes-client-6.8.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:92) ~[kubernetes-client-6.8.1.jar:?]
        at o.f.dia.core.utils.GlobalUtils.getPods(GlobalUtils.java:853) ~[acct-int-services.jar:3.2.1]
        at o.f.dia.core.dao.impl.UtilityDAO.activeLedgComb(UtilityDAO.java:470) ~[acct-int-services.jar:3.2.1]
        at o.f.dia.core.dao.impl.UtilityDAO.activeLedgCombMap(UtilityDAO.java:460) ~[acct-int-services.jar:3.2.1]
        at o.f.dia.core.dao.impl.SubledgerDAO.list(SubledgerDAO.java:237) ~[acct-int-services.jar:3.2.1]
        at o.f.dia.service.factory.AbstractService.list(AbstractService.java:75) ~[acct-int-services.jar:3.2.1]
        at o.f.dia.rest.controller.RestController.list(RestController.java:120) ~[acct-int-services.jar:3.2.1]
        at jdk.internal.reflect.GeneratedMethodAccessor185.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-3.0.9.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-3.0.9.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-3.0.9.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-3.0.9.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-3.0.9.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-3.0.9.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) ~[jersey-server-3.0.9.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-3.0.9.jar:?]
        at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:335) ~[helidon-webserver-jersey-3.2.1.jar:3.2.1]
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:117) ~[helidon-common-context-3.2.1.jar:3.2.1]
        at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154) ~[helidon-common-context-3.2.1.jar:3.2.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.IOException: Failed to authenticate with proxy
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:504) ~[kubernetes-client-6.8.1.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.list(BaseOperation.java:420) ~[kubernetes-client-6.8.1.jar:?]
        ... 34 more
Caused by: java.io.IOException: Failed to authenticate with proxy
        at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:418) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:236) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:177) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172) ~[okhttp-3.14.9.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.14.9.jar:?]
```

### Additional context

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.16", GitCommit:"b28e1f370a4a4c428ddbeababcaf0198f048fcac", GitTreeState:"archive", BuildDate:"2023-06-10T00:41:27Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.16", GitCommit:"b28e1f370a4a4c428ddbeababcaf0198f048fcac", GitTreeState:"archive", BuildDate:"2023-06-10T00:41:16Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by manusa** [comment]
From the logs, it seems you're sitting behind a proxy. The issue seems to come from the interaction with the intermediate proxy and not the Kube API server.

Could you provide more details? How are you setting the proxy configuration, and so on.

**Comment by venu19304** [comment]
Thanks @manusa for your response. 
We have a egress secrete with outbound proxy details and same is mount to all pods. But I don't know when Kubernetes client is try to connect through proxy. 

Below are more logs with debug enabled and also printing kubectl config information from working pod. 
Which config parameter here will tell the client to use proxy or not? 
 
```
2023-10-12 08:12:18.405 Trying to configure client from Kubernetes config...
2023-10-12 08:12:18.407 Did not find Kubernetes config at: [/home/oracle/.kube/config]. Ignoring.
2023-10-12 08:12:18.407 Trying to configure client from service account...
2023-10-12 08:12:18.407 Found service account host and port: 172.31.0.1:443
2023-10-12 08:12:18.408 Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt}].
2023-10-12 08:12:18.408 Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
2023-10-12 08:12:18.408 Trying to configure client namespace from Kubernetes service account namespace path...
2023-10-12 08:12:18.408 Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
2023-10-12 08:12:18.416 Using httpclient io.fabric8.kubernetes.client.okhttp.OkHttpClientFactory factory
2023-10-12 08:12:20.300 - [securitseverity:-] - - [-] - - - INFO - - - - - - CONSOLE --------------------
* DefaultKubernetesClient.KUBERNETES_VERSION_ENDPOINT = version;
* ClientAdapter.client = io.fabric8.kubernetes.client.impl.KubernetesClientImpl@3986b22e;
* NamespacedKubernetesClientAdapter.type = interface io.fabric8.kubernetes.client.NamespacedKubernetesClient;
2023-10-12 08:12:20.303 - [securitseverity:-] - - [-] - - - INFO - - - - - - CONSOLE --------------------
* Config.ACCESS_TOKEN = access-token;
* Config.DEFAULT_LOGGING_INTERVAL = 20000;
* Config.DEFAULT_MASTER_URL = https://kubernetes.default.svc;
* Config.DEFAULT_MAX_CONCURRENT_REQUESTS = 64;
* Config.DEFAULT_MAX_CONCURRENT_REQUESTS_PER_HOST = 5;
* Config.DEFAULT_REQUEST_RETRY_BACKOFFINTERVAL = 100;
* Config.DEFAULT_REQUEST_RETRY_BACKOFFLIMIT = 10;
* Config.DEFAULT_REQUEST_TIMEOUT = 10000;
* Config.DEFAULT_SCALE_TIMEOUT = 600000;
* Config.DEFAULT_UPLOAD_REQUEST_TIMEOUT = 120000;
* Config.DEFAULT_WEBSOCKET_PING_INTERVAL = 30000;
* Config.HTTPS_PROTOCOL_PREFIX = https://;
* Config.HTTP_PROTOCOL_PREFIX = http://;
* Config.ID_TOKEN = id-token;
* Config.KUBERNETES_ALL_PROXY = all.proxy;
* Config.KUBERNETES_API_VERSION_SYSTEM_PROPERTY = kubernetes.api.version;
* Config.KUBERNETES_AUTH_BASIC_PASSWORD_SYSTEM_PROPERTY = kubernetes.auth.basic.password;
* Config.KUBERNETES_AUTH_BASIC_USERNAME_SYSTEM_PROPERTY = kubernetes.auth.basic.username;
* Config.KUBERNETES_AUTH_SERVICEACCOUNT_TOKEN_FILE_SYSTEM_PROPERTY = kubernetes.auth.serviceAccount.token;
* Config.KUBERNETES_AUTH_TRYKUBECONFIG_SYSTEM_PROPERTY = kubernetes.auth.tryKubeConfig;
* Config.KUBERNETES_AUTH_TRYSERVICEACCOUNT_SYSTEM_PROPERTY = kubernetes.auth.tryServiceAccount;
* Config.KUBERNETES_CA_CERTIFICATE_DATA_SYSTEM_PROPERTY = kubernetes.certs.ca.data;
* Config.KUBERNETES_CA_CERTIFICATE_FILE_SYSTEM_PROPERTY = kubernetes.certs.ca.file;
* Config.KUBERNETES_CLIENT_CERTIFICATE_DATA_SYSTEM_PROPERTY = kubernetes.certs.client.data;
* Config.KUBERNETES_CLIENT_CERTIFICATE_FILE_SYSTEM_PROPERTY = kubernetes.certs.client.file;
* Config.KUBERNETES_CLIENT_KEY_ALGO_SYSTEM_PROPERTY = kubernetes.certs.client.key.algo;
* Config.KUBERNETES_CLIENT_KEY_DATA_SYSTEM_PROPERTY = kubernetes.certs.client.key.data;
* Config.KUBERNETES_CLIENT_KEY_FILE_SYSTEM_PROPERTY = kubernetes.certs.client.key.file;
* Config.KUBERNETES_CLIENT_KEY_PASSPHRASE_SYSTEM_PROPERTY = kubernetes.certs.client.key.passphrase;
* Config.KUBERNETES_CONNECTION_TIMEOUT_SYSTEM_PROPERTY = kubernetes.connection.timeout;
* Config.KUBERNETES_DISABLE_AUTO_CONFIG_SYSTEM_PROPERTY = kubernetes.disable.autoConfig;
* Config.KUBERNETES_DISABLE_HOSTNAME_VERIFICATION_SYSTEM_PROPERTY = kubernetes.disable.hostname.verification;
* Config.KUBERNETES_HTTP2_DISABLE = http2.disable;
* Config.KUBERNETES_HTTPS_PROXY = https.proxy;
* Config.KUBERNETES_HTTP_PROXY = http.proxy;
* Config.KUBERNETES_IMPERSONATE_GROUP = kubernetes.impersonate.group;
* Config.KUBERNETES_IMPERSONATE_USERNAME = kubernetes.impersonate.username;
* Config.KUBERNETES_KEYSTORE_FILE_PROPERTY = kubernetes.keystore.file;
* Config.KUBERNETES_KEYSTORE_PASSPHRASE_PROPERTY = kubernetes.keystore.passphrase;
* Config.KUBERNETES_KUBECONFIG_FILE = kubeconfig;
* Config.KUBERNETES_LOGGING_INTERVAL_SYSTEM_PROPERTY = kubernetes.logging.interval;
* Config.KUBERNETES_MASTER_SYSTEM_PROPERTY = kubernetes.master;
* Config.KUBERNETES_MAX_CONCURRENT_REQUESTS = kubernetes.max.concurrent.requests;
* Config.KUBERNETES_MAX_CONCURRENT_REQUESTS_PER_HOST = kubernetes.max.concurrent.requests.per.host;
* Config.KUBERNETES_NAMESPACE_FILE = kubenamespace;
* Config.KUBERNETES_NAMESPACE_PATH = /var/run/secrets/kubernetes.io/serviceaccount/namespace;
* Config.KUBERNETES_NAMESPACE_SYSTEM_PROPERTY = kubernetes.namespace;
* Config.KUBERNETES_NO_PROXY = no.proxy;
* Config.KUBERNETES_OAUTH_TOKEN_SYSTEM_PROPERTY = kubernetes.auth.token;
* Config.KUBERNETES_PROXY_PASSWORD = proxy.password;
* Config.KUBERNETES_PROXY_USERNAME = proxy.username;
* Config.KUBERNETES_REQUEST_RETRY_BACKOFFINTERVAL_SYSTEM_PROPERTY = kubernetes.request.retry.backoffInterval;
* Config.KUBERNETES_REQUEST_RETRY_BACKOFFLIMIT_SYSTEM_PROPERTY = kubernetes.request.retry.backoffLimit;
* Config.KUBERNETES_REQUEST_TIMEOUT_SYSTEM_PROPERTY = kubernetes.request.timeout;
* Config.KUBERNETES_SCALE_TIMEOUT_SYSTEM_PROPERTY = kubernetes.scale.timeout;
* Config.KUBERNETES_SERVICE_ACCOUNT_CA_CRT_PATH = /var/run/secrets/kubernetes.io/serviceaccount/ca.crt;
* Config.KUBERNETES_SERVICE_ACCOUNT_TOKEN_PATH = /var/run/secrets/kubernetes.io/serviceaccount/token;
* Config.KUBERNETES_SERVICE_HOST_PROPERTY = KUBERNETES_SERVICE_HOST;
* Config.KUBERNETES_SERVICE_PORT_PROPERTY = KUBERNETES_SERVICE_PORT;
* Config.KUBERNETES_TLS_VERSIONS = kubernetes.tls.versions;
* Config.KUBERNETES_TRUSTSTORE_FILE_PROPERTY = kubernetes.truststore.file;
* Config.KUBERNETES_TRUSTSTORE_PASSPHRASE_PROPERTY = kubernetes.truststore.passphrase;
* Config.KUBERNETES_TRUST_CERT_SYSTEM_PROPERTY = kubernetes.trust.certificates;
* Config.KUBERNETES_TRYNAMESPACE_PATH_SYSTEM_PROPERTY = kubernetes.tryNamespacePath;
* Config.KUBERNETES_UPLOAD_REQUEST_TIMEOUT_SYSTEM_PROPERTY = kubernetes.upload.request.timeout;
* Config.KUBERNETES_USER_AGENT = kubernetes.user.agent;
* Config.KUBERNETES_WATCH_RECONNECT_INTERVAL_SYSTEM_PROPERTY = kubernetes.watch.reconnectInterval;
* Config.KUBERNETES_WATCH_RECONNECT_LIMIT_SYSTEM_PROPERTY = kubernetes.watch.reconnectLimit;
* Config.KUBERNETES_WEBSOCKET_PING_INTERVAL_SYSTEM_PROPERTY = kubernetes.websocket.ping.interval;
* Config.LOGGER = org.apache.logging.slf4j.Log4jLogger@8e4a6;
* Config.additionalProperties = {};
* Config.apiVersion = v1;
  Config.authProvider = null;
* Config.autoConfigure = true;
* Config.autoOAuthToken = *********************************************************************
  Config.caCertData = null;
* Config.caCertFile = /var/run/secrets/kubernetes.io/serviceaccount/ca.crt;
  Config.clientCertData = null;
  Config.clientCertFile = null;
  Config.clientKeyAlgo = null;
  Config.clientKeyData = null;
  Config.clientKeyFile = null;
* Config.clientKeyPassphrase = changeit;
* Config.connectionTimeout = 10000;
* Config.contexts = [];
  Config.currentContext = null;
  Config.customHeaders = null;
* Config.defaultNamespace = true;
* Config.disableHostnameVerification = false;
* Config.errorMessages = {};
  Config.file = null;
* Config.http2Disable = false;
  Config.httpProxy = null;
  Config.httpsProxy = null;
  Config.impersonateExtras = null;
  Config.impersonateGroup = null;
  Config.impersonateGroups = null;
  Config.impersonateUsername = null;
  Config.keyStoreFile = null;
  Config.keyStorePassphrase = null;
* Config.loggingInterval = 20000;
* Config.masterUrl = https://172.31.0.1:443/;
* Config.maxConcurrentRequests = 64;
* Config.maxConcurrentRequestsPerHost = 5;
* Config.namespace = fsgbu-baics--xlt8cr-prd;
* Config.noProxy = [Ljava.lang.String;@5b73f7ae;
  Config.oauthToken = null;
  Config.oauthTokenProvider = null;
  Config.password = null;
  Config.proxyPassword = null;
  Config.proxyUsername = null;
* Config.requestConfig = io.fabric8.kubernetes.client.RequestConfig@532c5438;
* Config.requestRetryBackoffInterval = 0;
* Config.requestRetryBackoffLimit = 0;
* Config.requestTimeout = 10000;
* Config.scaleTimeout = 600000;
* Config.tlsVersions = [Lio.fabric8.kubernetes.client.http.TlsVersion;@7ddc626e;
* Config.trustCerts = false;
  Config.trustStoreFile = null;
  Config.trustStorePassphrase = null;
* Config.uploadRequestTimeout = 120000;
* Config.userAgent = fabric8-kubernetes-client/6.8.1;
  Config.username = null;
* Config.watchReconnectInterval = 1000;
* Config.watchReconnectLimit = -1;
* Config.websocketPingInterval = 30000;
2023-10-12 08:12:20.315 - [securitseverity:-] - - [-] - - - INFO - - - - - - CONSOLE --------------------
```

**Comment by manusa** [comment]
I can now see that the application is running in a Pod and that Kubernetes Client properly detects this. The client configures the cluster access using the provided Service Account details mounted in the Pod.

So I can only guess here.

Is it possible that the Pod's outbound traffic towards the Kube API goes through the configured Egress instead of performing the requests directly to the Kube API server?

Have you tried disabling the Egress configuration for this Pod?
