### ISSUE TITLE
io.fabric8.kubernetes.client.informers.impl.cache.Reflector | listSyncAndWatch failed for v1/persistentvolumes, will stop

### ISSUE THREAD

**Issue by iampratapak** [fabric8io/kubernetes-client#5559]
### Describe the bug

I am unable to sync or retrieve Kubernetes persistent volumes after a node pool is deleted and a new pool is created. I have not been able to find the root cause. Can someone please guide me in understanding the reason for this issue?

Note: While I can list the PVs via kubectl, it's failing when using the fabric8 Kubernetes Java Client.

### Fabric8 Kubernetes Client version

other (please specify in additional context)

### Steps to reproduce

Delete the existing node pool and create a new one. Then, attempt to sync or retrieve Kubernetes Persistent Volumes.

### Expected behavior

Should be able to sync or list the Persistent Volumes.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
2023-10-30 01:56:12.135+0000 |  | ::: |    OkHttp Dispatcher |  | ERROR | io.fabric8.kubernetes.client.informers.impl.cache.Reflector | listSyncAndWatch failed for v1/persistentvolumes, will stop
java.util.concurrent.CompletionException: com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public io.fabric8.kubernetes.api.model.CSIPersistentVolumeSource()
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:140)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$OkHttpAsyncBody.doConsume(OkHttpClientImpl.java:137)
        at java.base@11.0.19/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.19/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.19/java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public io.fabric8.kubernetes.api.model.CSIPersistentVolumeSource()
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.base@11.0.19/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:73)
        at java.base@11.0.19/java.lang.reflect.Constructor.newInstance(Constructor.java:487)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:123)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:278)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:303)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at io.fabric8.kubernetes.model.jackson.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:134)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at io.fabric8.kubernetes.model.jackson.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:134)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at io.fabric8.kubernetes.model.jackson.SettableBeanPropertyDelegate.deserializeAndSet(SettableBeanPropertyDelegate.java:134)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
        at io.fabric8.kubernetes.client.utils.KubernetesSerialization.unmarshal(KubernetesSerialization.java:254)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:562)
        at java.base@11.0.19/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        ... 18 more
```

### Additional context

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"483cb40e07a8ff9643b1ce68c649a21b81fb59bb", GitTreeState:"clean", BuildDate:"2023-05-23T15:52:04Z", GoVersion:"go1.19.3 A1727 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

**Comment by shawkins** [comment]
The issue is with the vm or native image - there is some additional config you'll need to ensure the model classes you are using get registered to allow for reflective access.  If you try running your code on a plain openjdk vm you'll see that it works as expected.

**Comment by iampratapak** [comment]
@shawkins Thanks for the quick response. Indeed, it was a native image tracing issue. After running the NI tracing, it's working again.
