### ISSUE TITLE
"Forbidden! User ... doesn't have permission.." since 1.4.15

### ISSUE THREAD

**Issue by donovanmuller** [fabric8io/kubernetes-client#558]
Everything working fine with version [1.4.14](https://github.com/fabric8io/kubernetes-client/commits/v1.4.15) using basic auth `-Dkubernetes.auth.basic.username=admin ...` to connect to an OpenShift 1.3.1 instance (minishift).

Updated to any version >= 1.4.15 and I now get this error:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://192.168.64.10:8443/oapi/v1/namespaces/scdf/builds?labelSelector=spring-app-id%20in%20(timelog-time). Message: Forbidden! User admin/192-168-64-10:8443 doesn't have permission..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:315) ~[kubernetes-client-1.4.18.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:266) ~[kubernetes-client-1.4.18.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237) ~[kubernetes-client-1.4.18.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230) ~[kubernetes-client-1.4.18.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:477) ~[kubernetes-client-1.4.18.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:59) ~[kubernetes-client-1.4.18.jar:na]
```

Trying to see what commit breaks it...

**Comment by donovanmuller** [comment]
Turning up the logging a bit and I get:

```
... okhttp3.OkHttpClient                     : --> GET https://192.168.64.10:8443/api/v1/namespaces/scdf/pods?labelSelector=spring-app-id%3Dtimelog-log http/1.1
... okhttp3.OkHttpClient                     : Authorization: Basic YWRtaW46YWRtaW4=
... okhttp3.OkHttpClient                     : Accept: application/json
... okhttp3.OkHttpClient                     : Host: 192.168.64.10:8443
... okhttp3.OkHttpClient                     : Connection: Keep-Alive
... okhttp3.OkHttpClient                     : Accept-Encoding: gzip
... okhttp3.OkHttpClient                     : User-Agent: okhttp/3.4.1
... okhttp3.OkHttpClient                     : --> END GET
... okhttp3.OkHttpClient                     : <-- 403 Forbidden https://192.168.64.10:8443/api/v1/namespaces/scdf/pods?labelSelector=spring-app-id%3Dtimelog-log (6ms)
... okhttp3.OkHttpClient                     : Cache-Control: no-store
... okhttp3.OkHttpClient                     : Content-Type: application/json
... okhttp3.OkHttpClient                     : Date: Thu, 03 Nov 2016 13:17:35 GMT
... okhttp3.OkHttpClient                     : Content-Length: 244
... okhttp3.OkHttpClient                     : 
... okhttp3.OkHttpClient                     : {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot list pods in project \"scdf\"",
  "reason": "Forbidden",
  "details": {
    "kind": "pods"
  },
  "code": 403
}

... okhttp3.OkHttpClient                     : <-- END HTTP (244-byte body)
... okhttp3.OkHttpClient                     : --> GET https://192.168.64.10:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client http/1.1
... okhttp3.OkHttpClient                     : Authorization: Basic YWRtaW46YWRtaW4=
... okhttp3.OkHttpClient                     : Authorization: Basic YWRtaW46YWRtaW4=
... okhttp3.OkHttpClient                     : Host: 192.168.64.10:8443
... okhttp3.OkHttpClient                     : Connection: Keep-Alive
... okhttp3.OkHttpClient                     : Accept-Encoding: gzip
... okhttp3.OkHttpClient                     : User-Agent: okhttp/3.4.1
... okhttp3.OkHttpClient                     : --> END GET
... okhttp3.OkHttpClient                     : <-- 302 Found https://192.168.64.10:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client (18ms)
... okhttp3.OkHttpClient                     : Cache-Control: no-cache, no-store, max-age=0, must-revalidate
... okhttp3.OkHttpClient                     : Expires: Fri, 01 Jan 1990 00:00:00 GMT
... okhttp3.OkHttpClient                     : Location: https://192.168.64.10:8443/oauth/token/implicit#access_token=0gDT7HGIBHgB0ROmhS3izK7wYJj9CYstT0Zxj8Ekty0&expires_in=86400&scope=user:full&token_type=Bearer
... okhttp3.OkHttpClient                     : Pragma: no-cache
... okhttp3.OkHttpClient                     : Set-Cookie: ssn=MTQ3ODE3OTA1NXxnNDBNcEFsdFNmejVIUHFKazM0dzNYdjFKN1M2R3JDNVNWNXNGbUpZTUJGQjEydjFVQmQxTGxMTDRjS3IwcEFwSk50VVlucHNOVFNWcmxRdUJUV2tZNkhxR0lPclptZ2dFNE1WdnVDMTB1c2ZQdUlvRjZUbERTVmNlM1BlOTZKNmpnPT183HKevbJcyF7BWtDV8eUCAbItIyNIv5RT_poTITeR190=; Path=/; Expires=Thu, 03 Nov 2016 13:22:35 GMT; Max-Age=300; HttpOnly; Secure
... okhttp3.OkHttpClient                     : Date: Thu, 03 Nov 2016 13:17:35 GMT
... okhttp3.OkHttpClient                     : Content-Length: 0
... okhttp3.OkHttpClient                     : Content-Type: text/plain; charset=utf-8
... okhttp3.OkHttpClient                     : <-- END HTTP (0-byte body)
... okhttp3.OkHttpClient                     : --> GET https://192.168.64.10:8443/oauth/token/implicit#access_token=0gDT7HGIBHgB0ROmhS3izK7wYJj9CYstT0Zxj8Ekty0&expires_in=86400&scope=user:full&token_type=Bearer http/1.1
... okhttp3.OkHttpClient                     : Authorization: Basic YWRtaW46YWRtaW4=
... okhttp3.OkHttpClient                     : Authorization: Basic YWRtaW46YWRtaW4=
... okhttp3.OkHttpClient                     : Host: 192.168.64.10:8443
... okhttp3.OkHttpClient                     : Connection: Keep-Alive
... okhttp3.OkHttpClient                     : Accept-Encoding: gzip
... okhttp3.OkHttpClient                     : User-Agent: okhttp/3.4.1
... okhttp3.OkHttpClient                     : --> END GET
... okhttp3.OkHttpClient                     : <-- 200 OK https://192.168.64.10:8443/oauth/token/implicit#access_token=0gDT7HGIBHgB0ROmhS3izK7wYJj9CYstT0Zxj8Ekty0&expires_in=86400&scope=user:full&token_type=Bearer (0ms)
... okhttp3.OkHttpClient                     : Content-Type: text/plain
... okhttp3.OkHttpClient                     : Date: Thu, 03 Nov 2016 13:17:35 GMT
... okhttp3.OkHttpClient                     : Content-Length: 756
... okhttp3.OkHttpClient                     : 
... okhttp3.OkHttpClient                     : 
You have reached this page by following a redirect Location header from an OAuth authorize request.

If a response_type=token parameter was passed to the /authorize endpoint, that requested an 
"Implicit Grant" OAuth flow (see https://tools.ietf.org/html/rfc6749#section-4.2).

That flow requires the access token to be returned in the fragment portion of a redirect header.
Rather than following the redirect here, you can obtain the access token from the Location header
(see https://tools.ietf.org/html/rfc6749#section-4.2.2):

  1. Parse the URL in the Location header and extract the fragment portion
  2. Parse the fragment using the "application/x-www-form-urlencoded" format
  3. The access_token parameter contains the granted OAuth access token

... okhttp3.OkHttpClient                     : <-- END HTTP (756-byte body)
... okhttp3.OkHttpClient                     : --> GET https://192.168.64.10:8443/api/v1/namespaces/scdf/pods?labelSelector=spring-app-id%3Dtimelog-log http/1.1
... okhttp3.OkHttpClient                     : Accept: application/json
... okhttp3.OkHttpClient                     : Authorization: Bearer 0gDT7HGIBHgB0ROmhS3izK7wYJj9CYstT0Zxj8Ekty0
... okhttp3.OkHttpClient                     : Host: 192.168.64.10:8443
... okhttp3.OkHttpClient                     : Connection: Keep-Alive
... okhttp3.OkHttpClient                     : Accept-Encoding: gzip
... okhttp3.OkHttpClient                     : User-Agent: okhttp/3.4.1
... okhttp3.OkHttpClient                     : --> END GET
... okhttp3.OkHttpClient                     : <-- 200 OK https://192.168.64.10:8443/api/v1/namespaces/scdf/pods?labelSelector=spring-app-id%3Dtimelog-log (2ms)
... okhttp3.OkHttpClient                     : Cache-Control: no-store
... okhttp3.OkHttpClient                     : Content-Type: application/json
... okhttp3.OkHttpClient                     : Date: Thu, 03 Nov 2016 13:17:35 GMT
... okhttp3.OkHttpClient                     : Content-Length: 129
... okhttp3.OkHttpClient                     : 
... okhttp3.OkHttpClient                     : {"kind":"PodList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/scdf/pods","resourceVersion":"56046"},"items":[]}

... okhttp3.OkHttpClient                     : <-- END HTTP (129-byte body)
... okhttp3.OkHttpClient                     : --> GET https://192.168.64.10:8443/oapi/v1/namespaces/scdf/builds?labelSelector=spring-app-id%20in%20(timelog-log) http/1.1
... okhttp3.OkHttpClient                     : Authorization: Basic YWRtaW46YWRtaW4=
... okhttp3.OkHttpClient                     : Host: 192.168.64.10:8443
... okhttp3.OkHttpClient                     : Connection: Keep-Alive
... okhttp3.OkHttpClient                     : Accept-Encoding: gzip
... okhttp3.OkHttpClient                     : User-Agent: okhttp/3.4.1
... okhttp3.OkHttpClient                     : --> END GET
... okhttp3.OkHttpClient                     : <-- 403 Forbidden https://192.168.64.10:8443/oapi/v1/namespaces/scdf/builds?labelSelector=spring-app-id%20in%20(timelog-log) (1ms)
... okhttp3.OkHttpClient                     : Cache-Control: no-store
... okhttp3.OkHttpClient                     : Content-Type: application/json
... okhttp3.OkHttpClient                     : Date: Thu, 03 Nov 2016 13:17:35 GMT
... okhttp3.OkHttpClient                     : Content-Length: 248
... okhttp3.OkHttpClient                     : 
... okhttp3.OkHttpClient                     : {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot list builds in project \"scdf\"",
  "reason": "Forbidden",
  "details": {
    "kind": "builds"
  },
  "code": 403
}

... okhttp3.OkHttpClient                     : <-- END HTTP (248-byte body)

...

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://192.168.64.10:8443/oapi/v1/namespaces/scdf/builds?labelSelector=spring-app-id%20in%20(timelog-log). Message: Forbidden! User admin/192-168-64-10:8443 doesn't have permission..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:315) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:266) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:477) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:59) ~[kubernetes-client-1.4-SNAPSHOT.jar:na]
```

this ` "message": "User \"system:anonymous\" cannot list builds in project \"scdf\"",` message seems very odd and if you look at the last GET that returns the `403`, the `Authorization: Bearer ...` header is not present but instead the `Authorization: Basic ...` header is.

**Comment by donovanmuller** [comment]
Seems this commit (https://github.com/fabric8io/kubernetes-client/commit/739f2b9f414f9ce02293dac6c92defc3802ed1ac) broke it.
