### ISSUE TITLE
GenericKubernetesResource field type is changed from string to integer

### ISSUE THREAD

**Issue by speedfl** [fabric8io/kubernetes-client#5585]
### Describe the bug

I have a simple script that Fetch a keda ScaledObject Resources in a namepace and copy them into the destination namespace:

```java
public void test() {
        var scaledObjectCrdContext = new ResourceDefinitionContext.Builder()
                .withNamespaced(true)
                .withGroup("keda.sh")
                .withKind("ScaledObject")
                .withVersion("v1alpha1")
                .withPlural("scaledobjects")
                .build();
        kubernetesClient.genericKubernetesResources(scaledObjectCrdContext)
                        .inNamespace("source-namespace")
                        .withLabels(Map.of("my-selector", "my-app"))
                        .list()
                        .getItems()
                        .stream()
                        .peek(item -> item.getMetadata().setNamespace("destination-namespace"))
                        .forEach(item -> kubernetesClient.genericKubernetesResources(scaledObjectCrdContext).resource(item).create());
    }
```

When doing the create I get:

```log
 POST at: https://localhost/apis/keda.sh/v1alpha1/namespaces/destination-namespace/scaledobjects. Message: ScaledObject.keda.sh "my-scaled-object" is invalid: spec.triggers[0].metadata.desiredReplicas: Invalid value: "integer": spec.triggers[0].metadata.desiredReplicas in body must be of type string: "integer". Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.triggers[0].metadata.desiredReplicas, message=Invalid value: "integer": spec.triggers[0].metadata.desiredReplicas in body must be of type string: "integer", reason=FieldValueTypeInvalid, additionalProperties={})], group=keda.sh, kind=ScaledObject, name=my-scaled-object, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=ScaledObject.keda.sh "my-scaled-object" is invalid: spec.triggers[0].metadata.desiredReplicas: Invalid value: "integer": spec.triggers[0].metadata.desiredReplicas in body must be of type string: "integer", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={})
at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:518)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:340)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:703)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:92)
        at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:42)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:1108)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:92)
        at io.fabric8.kubernetes.client.extension.ResourceAdapter.create(ResourceAdapter.java:114)
```

The issue is due to the desiredReplicas which must be of type string and is replaced with integer.

### Fabric8 Kubernetes Client version

6.9.2

### Steps to reproduce

1. Install keda crds on your cluster
2. Create a scaledObject
```yaml
kind: ScaledObject
metadata:
  annotations:
    autoscaling.keda.sh/paused-replicas: 0
  labels:
    my-selector: my-app
  name: my-scaled-object
  namespace: source-namespace
spec:
  maxReplicaCount: 1
  scaleTargetRef:
    kind: Deployment
    name: my-deployment
  triggers:
    - metadata:
        desiredReplicas: '1'
        end: 30 */2 * * *
        start: 0 */2 * * *
        timezone: America/Montreal
      type: cron
```
3. Create following code
```java
public void test() {
        var scaledObjectCrdContext = new ResourceDefinitionContext.Builder()
                .withNamespaced(true)
                .withGroup("keda.sh")
                .withKind("ScaledObject")
                .withVersion("v1alpha1")
                .withPlural("scaledobjects")
                .build();
        kubernetesClient.genericKubernetesResources(scaledObjectCrdContext)
                        .inNamespace("source-namespace")
                        .withLabels(Map.of("my-selector", "my-app"))
                        .list()
                        .getItems()
                        .stream()
                        .peek(item -> item.getMetadata().setNamespace("destination-namespace"))
                        .forEach(item -> kubernetesClient.genericKubernetesResources(scaledObjectCrdContext).resource(item).create());
    }
```
4. Run it

### Expected behavior

Type must not be changed

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```log
 POST at: https://localhost/apis/keda.sh/v1alpha1/namespaces/destination-namespace/scaledobjects. Message: ScaledObject.keda.sh "my-scaled-object" is invalid: spec.triggers[0].metadata.desiredReplicas: Invalid value: "integer": spec.triggers[0].metadata.desiredReplicas in body must be of type string: "integer". Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.triggers[0].metadata.desiredReplicas, message=Invalid value: "integer": spec.triggers[0].metadata.desiredReplicas in body must be of type string: "integer", reason=FieldValueTypeInvalid, additionalProperties={})], group=keda.sh, kind=ScaledObject, name=my-scaled-object, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=ScaledObject.keda.sh "my-scaled-object" is invalid: spec.triggers[0].metadata.desiredReplicas: Invalid value: "integer": spec.triggers[0].metadata.desiredReplicas in body must be of type string: "integer", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={})
at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:518)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
        at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:340)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:703)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:92)
        at io.fabric8.kubernetes.client.dsl.internal.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:42)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:1108)
        at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:92)
        at io.fabric8.kubernetes.client.extension.ResourceAdapter.create(ResourceAdapter.java:114)
```

### Additional context

I see this issue which may be related: https://github.com/FasterXML/jackson-databind/issues/796

**Comment by shawkins** [comment]
Trying something similar locally does not exhibit the behavior you are seeing:

```
    String yaml = "x: '1'";
    String json = "{\"x\":\"1\"}";
    GenericKubernetesResource yamlValue = Serialization.unmarshal(yaml, GenericKubernetesResource.class);
    GenericKubernetesResource jsonValue = Serialization.unmarshal(json, GenericKubernetesResource.class);
    System.out.println(Serialization.asYaml(yamlValue));
    System.out.println(Serialization.asJson(jsonValue));
```
The output shows the string type is preserved.

Can you check the contents of the item retrieved from the server in your java code, and also from kubectl?

**Comment by speedfl** [comment]
Thanks @shawkins. I was not able to reproduce the environment locally. I will try to investigate on my side and let you know. Have a good day
