### ISSUE TITLE
What is the reason for this problem “io.fabric8.kubernetes.client.KubernetesClientException: Failure executing“

### ISSUE THREAD

**Issue by 314937885** [fabric8io/kubernetes-client#5593]
**Jenkins：Jenkins 2.401.2
Kubernetes： v1.27.7
Kubernetes plugin :4054.v2da_8e2794884
Kubernetes Client API Plugin: 6.8.1-224.vd388fca_4db_3b_**
```
What is the reason for this problem “io.fabric8.kubernetes.client.KubernetesClientException: Failure executing“, It happens once a day.

Failed to start websocket connection: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: http://10.10.188.118:6443/api/v1/namespaces/dnode/pods/suite-gh9h5-sm1gs. Message: Bad Request.
15:08:17  	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:507)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleGet(OperationSupport.java:467)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:741)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:185)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.getItemOrRequireFromServer(BaseOperation.java:168)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.validateOrDefaultContainerId(PodOperationsImpl.java:327)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.getURL(PodOperationsImpl.java:317)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:286)
15:08:17  	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.doLaunch(ContainerExecDecorator.java:448)
15:08:17  	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.launch(ContainerExecDecorator.java:335)
15:08:17  	at hudson.Launcher$ProcStarter.start(Launcher.java:509)
15:08:17  	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:176)
15:08:17  	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:134)
15:08:17  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:329)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:322)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
15:08:17  	at jdk.internal.reflect.GeneratedMethodAccessor5217.invoke(Unknown Source)
15:08:17  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:08:17  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:08:17  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
15:08:17  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
15:08:17  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
15:08:17  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
15:08:17  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
15:08:17  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
15:08:17  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
15:08:17  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:180)
15:08:17  	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
15:08:17  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:163)
15:08:17  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:178)
15:08:17  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:182)
15:08:17  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:152)
15:08:17  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:152)
15:08:17  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.LoggingInvoker.methodCall(LoggingInvoker.java:105)
15:08:17  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:90)
15:08:17  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:116)
15:08:17  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:85)
15:08:17  	at jdk.internal.reflect.GeneratedMethodAccessor531.invoke(Unknown Source)
15:08:17  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:08:17  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:08:17  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
15:08:17  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
15:08:17  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
15:08:17  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:152)
15:08:17  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:146)
15:08:17  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
15:08:17  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
15:08:17  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:146)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:422)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
15:08:17  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
15:08:17  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
15:08:17  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
15:08:17  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
15:08:17  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
15:08:17  	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
15:08:17  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
15:08:17  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
15:08:17  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
15:08:17  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
15:08:17  	at java.base/java.lang.Thread.run(Thread.java:829)
15:08:17  Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: `http://10.10.188.118:6443/api/v1/namespaces/dnode/pods/suite-gh9h5-sm1gs`. Message: Bad Request.
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:640)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:589)
15:08:17  	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:549)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
15:08:17  	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:140)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
15:08:17  	at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
15:08:17  	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
15:08:17  	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$OkHttpAsyncBody.doConsume(OkHttpClientImpl.java:137)
15:08:17  	... 3 more
```

**Comment by manusa** [comment]
Could you please share the part of the code that triggered that exception?

**Comment by shawkins** [comment]
This is trying to lookup a pod and getting a bad request response.  That is strange as you'd see a 404 if the pod simply didn't exist.  @314937885 this is likely not something that the client is directly responsible for - the api-server or more likely some intermediary is returning an unexpected response.
