### ISSUE TITLE
java.lang.IllegalArgumentException: Failure in creating proxy URL. Proxy port is required!

### ISSUE THREAD

**Issue by manusa** [fabric8io/kubernetes-client#5605]
## Description

From https://github.com/quarkusio/quarkus/discussions/37137

It seems that environment variables such as:

```
ALL_PROXY=proxy-se-uan.ddc.teliasonera.net:8080
NO_PROXY=localhost
```

Are causing the following stack-trace:
``` 
 java.base/java.lang.Thread.run(Thread.java:1583) Caused by: java.lang.IllegalArgumentException: Failure in creating proxy URL. Proxy port is required! at
   io.fabric8.kubernetes.client.utils.HttpClientUtils.getProxyUri(HttpClientUtils.java:91) at
   io.fabric8.kubernetes.client.utils.HttpClientUtils.configureProxy(HttpClientUtils.java:210) at
   io.fabric8.kubernetes.client.utils.HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:185) at io.fabric8.kubernetes.client.http.HttpClient$Factory.newBuilder(HttpClient.java:51) at
   io.quarkus.kubernetes.client.runtime.QuarkusHttpClientFactory.newBuilder(QuarkusHttpClientFactory.java:57) at
   io.fabric8.kubernetes.client.KubernetesClientBuilder.getHttpClient(KubernetesClientBuilder.java:90) at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:79) at
   io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createClient(KubernetesClientUtils.java:54) at
   io.quarkus.kubernetes.config.runtime.KubernetesConfigSourceFactoryBuilder$KubernetesConfigFactory.getConfigSources(KubernetesConfigSourceFactoryBuilder.java:31) at ....

```

**Comment by manusa** [comment]
Complete analysis and reproducer can be found at: https://github.com/marcnuri-work/fabric8io-kubernetes-client-issues-5605-all-proxy
