### ISSUE TITLE
When using dynamicPVC volume kubernetes client crashes

### ISSUE THREAD

**Issue by ccpsupport** [fabric8io/kubernetes-client#5771]
### Describe the bug

ERROR: Failed to launch pps-aar-shape-cae-23470-prepare-ci-env-to-build-the-app-8-fq79n
java.lang.NoSuchMethodError: 'io.fabric8.kubernetes.api.model.ResourceRequirementsFluent io.fabric8.kubernetes.api.model.PersistentVolumeClaimSpecFluent$ResourcesNested.withRequests(java.util.Map)'
	at org.csanchez.jenkins.plugins.kubernetes.volumes.DynamicPVC.createPVC(DynamicPVC.java:58)
	at org.csanchez.jenkins.plugins.kubernetes.volumes.workspace.DynamicPVCWorkspaceVolume.createVolume(DynamicPVCWorkspaceVolume.java:73)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:166)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Fabric8 Kubernetes Client version

6.10.0

### Steps to reproduce

I am using below pipeline:

pipeline {
    agent {
        kubernetes {
            defaultContainer 'main'
            yamlFile 'KubernetesPod.yaml'
            workspaceVolume dynamicPVC(accessModes: 'ReadWriteOnce', requestsSize: '150Gi', storageClassName: 'linux-ext4-gp3-ebs-csi-encrypted')
            }
    }

### Expected behavior

Expected to create the pod and pvc.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Amazon

### Fabric8 Kubernetes Client Logs

```shell
Created Pod: kubernetes_custom_ccp custom-ccp/pps-aar-shape-cae-23470-prepare-ci-env-to-build-the-app-8-b4kmr
ERROR: Failed to launch pps-aar-shape-cae-23470-prepare-ci-env-to-build-the-app-8-b4kmr
java.lang.NoSuchMethodError: 'io.fabric8.kubernetes.api.model.ResourceRequirementsFluent io.fabric8.kubernetes.api.model.PersistentVolumeClaimSpecFluent$ResourcesNested.withRequests(java.util.Map)'
	at org.csanchez.jenkins.plugins.kubernetes.volumes.DynamicPVC.createPVC(DynamicPVC.java:58)
	at org.csanchez.jenkins.plugins.kubernetes.volumes.workspace.DynamicPVCWorkspaceVolume.createVolume(DynamicPVCWorkspaceVolume.java:73)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:166)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by rohanKanojia** [comment]
@ccpsupport : Could you please prepare a [minimal reproducible example ](https://en.wikipedia.org/wiki/Minimal_reproducible_example) ?

Could you please check in jenkins plugin code which is invoking KubernetesClient and causing this exception?

**Comment by ccpsupport** [comment]
Hello @rohanKanojia 

Thank you for the reply, we've just tested the upgrade to the Jenkins plugins - kubernetes and kubernetes client API(also the corresponding dependencies), as well as the Jenkins versions.

Now the pipeline config added in the Steps to reproduce works fine.

The issue can be closed.

**Comment by rohanKanojia** [comment]
@ccpsupport : Do you mean root cause of the issue was due to misalignment of Jenkins Kubernetes API versions?
