### ISSUE TITLE
Deadlock between the Kubernetes client and the SharedIndexInformer

### ISSUE THREAD

**Issue by PierreBtz** [fabric8io/kubernetes-client#5822]
### Describe the bug

When closing the Kubernetes client right after having waited on a resource (eg with the `withTimeout` method), a deadlock appears between the informer thread (in charge of notifying the client) and the thread closing the client.

### Fabric8 Kubernetes Client version

6.10.0

### Steps to reproduce

1. Use the following sample:

```
  public static void main(String[] args) {
    try (var client = new KubernetesClientBuilder().build()) {
      var namespace = "hello-world";
      var testNamespace =
          client
              .namespaces()
              .resource(
                  new NamespaceBuilder()
                      .withNewMetadata()
                      . withName(namespace)
                      .endMetadata()
                      .build()
              );
      testNamespace.create();
      testNamespace.waitUntilReady(60, TimeUnit.SECONDS);
      System.out.println("Created namespace " + namespace);
      testNamespace.withTimeout(60, TimeUnit.SECONDS).delete();
      System.out.println("Deleted namespace " + namespace);
    }
    System.out.println("I'm not reached");
  }
```

Observe that the "I'm not reached" line is not reached and the program hangs.
Take a thread dump and observe the two following threads:

```
"-56112634-pool-1-thread-1" #24 daemon prio=5 os_prio=31 cpu=6.00ms elapsed=15.78s tid=0x00007fe8d66f3e00 nid=0xba1f waiting for monitor entry  [0x0000000307624000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.fabric8.kubernetes.client.impl.BaseClient.removeFromCloseable(BaseClient.java:423)
	- waiting to lock <0x0000000601136d90> (a io.fabric8.kubernetes.client.impl.KubernetesClientImpl)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.lambda$null$16(BaseOperation.java:1076)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation$$Lambda$412/0x0000000801003198.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@17.0.4/CompletableFuture.java:863)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@17.0.4/CompletableFuture.java:841)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17.0.4/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17.0.4/CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.informers.impl.cache.Reflector.stop(Reflector.java:96)
	at io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer.stop(DefaultSharedIndexInformer.java:182)
	- locked <0x0000000601125c00> (a io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.lambda$informOnCondition$12(BaseOperation.java:954)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation$$Lambda$340/0x0000000800faeca8.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(java.base@17.0.4/CompletableFuture.java:863)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(java.base@17.0.4/CompletableFuture.java:841)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17.0.4/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17.0.4/CompletableFuture.java:2147)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.lambda$informOnCondition$13(BaseOperation.java:961)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation$$Lambda$341/0x0000000800faeee0.accept(Unknown Source)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation$3.onDelete(BaseOperation.java:976)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation$3.onDelete(BaseOperation.java:968)
	at io.fabric8.kubernetes.client.informers.impl.cache.ProcessorListener$DeleteNotification.handle(ProcessorListener.java:122)
	at io.fabric8.kubernetes.client.informers.impl.cache.ProcessorListener.add(ProcessorListener.java:50)
	at io.fabric8.kubernetes.client.informers.impl.cache.SharedProcessor.lambda$distribute$0(SharedProcessor.java:91)
	at io.fabric8.kubernetes.client.informers.impl.cache.SharedProcessor$$Lambda$365/0x0000000800fb6468.accept(Unknown Source)
	at io.fabric8.kubernetes.client.informers.impl.cache.SharedProcessor.lambda$distribute$1(SharedProcessor.java:114)
	at io.fabric8.kubernetes.client.informers.impl.cache.SharedProcessor$$Lambda$366/0x0000000800fb66a0.run(Unknown Source)
	at io.fabric8.kubernetes.client.utils.internal.SerialExecutor.lambda$execute$0(SerialExecutor.java:58)
	at io.fabric8.kubernetes.client.utils.internal.SerialExecutor$$Lambda$367/0x0000000800fb68c8.run(Unknown Source)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation$$Lambda$334/0x0000000800fa7210.execute(Unknown Source)
	at io.fabric8.kubernetes.client.utils.internal.SerialExecutor.scheduleNext(SerialExecutor.java:76)
	- locked <0x0000000601433610> (a io.fabric8.kubernetes.client.utils.internal.SerialExecutor)
	at io.fabric8.kubernetes.client.utils.internal.SerialExecutor.execute(SerialExecutor.java:70)
```

and 

```
"main" #1 prio=5 os_prio=31 cpu=2515.50ms elapsed=25.04s tid=0x00007fe8d6808200 nid=0x2b03 waiting for monitor entry  [0x0000000304ca3000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer.stop(DefaultSharedIndexInformer.java:181)
	- waiting to lock <0x0000000601125c00> (a io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer)
	at io.fabric8.kubernetes.client.informers.SharedIndexInformer.close(SharedIndexInformer.java:110)
	at io.fabric8.kubernetes.client.impl.BaseClient.lambda$close$0(BaseClient.java:161)
	at io.fabric8.kubernetes.client.impl.BaseClient$$Lambda$428/0x000000080100e688.accept(Unknown Source)
	at java.lang.Iterable.forEach(java.base@17.0.4/Iterable.java:75)
	at java.util.Collections$SetFromMap.forEach(java.base@17.0.4/Collections.java:5700)
	at io.fabric8.kubernetes.client.impl.BaseClient.close(BaseClient.java:159)
	- locked <0x0000000601136d90> (a io.fabric8.kubernetes.client.impl.KubernetesClientImpl)
	at **.main(**.java:163)
```

### Expected behavior

No deadlock

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Additional context

This code was run against two fresh kind clusters with different versions:

* kindest/node:v1.27.3: `Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.11", GitCommit:"b9e2ad67ad146db566be5a6db140d47e52c8adb2", GitTreeState:"clean", BuildDate:"2024-02-14T22:47:06Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/arm64"}`
* kindest/node:v1.25.3: `Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-11-02T03:24:50Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}`

**Comment by shawkins** [comment]
This was addressed by https://github.com/fabric8io/kubernetes-client/pull/5731/commits/7babf6eb1be239edfc189e520161bd1d5959cfbb

Unfortunately it did not make it into 6.10.

@manusa will there be a 6.10.1, or when do you think 6.11 will be available?

**Comment by rohanKanojia** [comment]
@PierreBtz : Is this still an issue with KubernetesClient v6.11.0 ?
