### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: io/fabric8/kubernetes/api/builder/Fluent

### ISSUE THREAD

**Issue by wdt1988520** [fabric8io/kubernetes-client#5963]
### Describe the bug

Caused by: java.lang.NoClassDefFoundError: io/fabric8/kubernetes/api/builder/Fluent
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at io.fabric8.kubernetes.client.utils.KubernetesResourceUtil.loadRelated(KubernetesResourceUtil.java:489)
	at io.fabric8.kubernetes.client.utils.KubernetesResourceUtil.inferBuilderType(KubernetesResourceUtil.java:484)
	at io.fabric8.kubernetes.client.impl.ResourceHandlerImpl.<init>(ResourceHandlerImpl.java:44)
	at io.fabric8.kubernetes.client.impl.Handlers.register(Handlers.java:47)
	at io.fabric8.kubernetes.client.impl.KubernetesClientImpl.registerDefaultHandlers(KubernetesClientImpl.java:286)
	at io.fabric8.kubernetes.client.impl.KubernetesClientImpl.<init>(KubernetesClientImpl.java:202)
	... 6 more

### Fabric8 Kubernetes Client version

6.12.1

### Steps to reproduce

public static KubernetesClient connectK8s(ClusterDto clusterDto) {
    Config config = new ConfigBuilder().withMasterUrl(clusterDto.getApiProtocol() + "://" + clusterDto.getApiHost())
        .withTrustCerts(true)
        .withOauthToken(clusterDto.getApiToken())
        .build();
    try {
      return new KubernetesClientBuilder().withConfig(config).build();
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }

### Expected behavior

connect success

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

**Comment by manusa** [comment]
Are you by any chance using Spring Cloud Kubernetes?

Check the FAQ: https://github.com/fabric8io/kubernetes-client/blob/main/doc/FAQ.md#ive-tried-adding-a-dependency-to-kubernetes-client-but-im-still-getting-weird-class-loading-issues-what-gives
