### ISSUE TITLE
k8s client header can't support content-type protobuf.

### ISSUE THREAD

**Issue by BUPT-wxq** [fabric8io/kubernetes-client#6039]
### Describe the bug

fabric8io/kubernetes-client set http header access api server

contentType="application/vnd.kubernetes.protobuf"
Accept: application/vnd.kubernetes.protobuf：
But I got an error when set Accept: application/vnd.kubernetes.protobuf

### Fabric8 Kubernetes Client version

6.8.1

### Steps to reproduce

set k8s client http header
contentType="application/vnd.kubernetes.protobuf"
Accept: application/vnd.kubernetes.protobuf

### Expected behavior

set
contentType="application/vnd.kubernetes.protobuf"
Accept: application/vnd.kubernetes.protobuf
change application/json to protobuf reduce network overhead

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
Caused by:
io.fabric8.kubernetes.client.KubernetesClientException: Error executing: GET at: https://ip:443/api/v1/namespaces/xxx/configmaps/leader-election-token-renewal. Cause: java.nio.charset.Malforme
dInputException: Input length
= 1
at
10.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestException(OperationSupport.java:682)
at
io.fabric8. kubernetes.client.dsl.internal.OperationSupport.requestException(OperationSupport.java:686)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:568)
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
at
java.util. concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$9(StandardHttpClient.java:136)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at
java.util.concurrent.CompletableFuture.complete(CompletableFuture.java: 1962)
at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$0kHttpAsyncBody.doConsume(OkHttpClientImpl.java:137)
3 more
Caused by: org.snakeyaml.engine.v2.exceptions.YamlEngineException: java.nio.charset.MalformedInputException: Input length = 1
at org.snakeyaml.engine.v2.scanner.StreamReader.update(StreamReader.java:281)
at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:237)
at org.snakeyaml.engine.v2.scanner.StreamReader.ensureEnoughData(StreamReader.java:232)
at org.snakeyaml.engine.v2.scanner.StreamReader.peek(StreamReader.java: 187)
at org.snakeyaml.engine.v2.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1114)
at org.snakeyaml.engine.v2.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:292)
at org.snakeyaml.engine.v2.scanner.ScannerImpl.checkToken(ScannerImpl.java:192)
at org.snakeyaml.engine.v2.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:444)
at org.snakeyaml.engine.v2.parser.ParserImpl.lambda$produce$1(ParserImpl.java:232)
at java.util.Optional.ifPresent(Optional.java:159)
org.snakeyaml.engine.v2.parser.ParserImpl.produce(ParserImpl.java:232)
at org.snakeyaml.engine.v2.parser.ParserImpl.peekEvent(ParserImpl.java:206)
at org.snakeyaml.engine.v2.parser.ParserImpl.checkEvent(ParserImpl.java:198)
at org.snakeyaml. engine.v2. composer.Composer.hasNext(Composer.java:110)
at org.snakeyaml.engine.v2.api.Load$YamlIterator.hasNext(Load.java:226)
at
at
io.fabric8.kubernetes.client.utils.Serialization.parseYaml(Serialization.java:293)
io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:274)
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:440)
at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:423)
at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:561)
18 more
Caused by:
java.nio.charset.MalformedInputException: Input length = 1
at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java: 339)
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
at
java. io.InputStreamReader.read(InputStreamReader.java:184)
at org.snakeyaml.engine.v2.api.YamlUnicodeReader.read(YamlUnicodeReader.java:129)
at org.snakeyaml.engine.v2.scanner.StreamReader.update(StreamReader.java:244)
37 more
```

**Comment by manusa** [comment]
The client is not yet capable of handling protobuf response types.
So regardless of setting an accept header, we'd still need to add handling support for this response type.

Could you please provide more insights about your use case?
