### ISSUE TITLE
Unknown host exception 

### ISSUE THREAD

**Issue by FunTK** [fabric8io/kubernetes-client#6132]
### Describe the bug

I added 'leader election' code refered to this repository as below

```
@Slf4j
@Configuration
public class LeaderElectionConfig {

    @Value("${dqs.namespace:default}")
    private String namespace;
    private String name = "kdms-device-query-service";

    private boolean isLeader = false;

    final String lockIdentity = InetAddress.getLocalHost().getHostName();
    ////generateId().toString();

    public LeaderElectionConfig() throws UnknownHostException {
    }

    @PostConstruct
    public void init() {

        log.info("Leader Election Config initialized  namespace : {},  name : {}, identity : {}",
                namespace, name, lockIdentity);

        try (KubernetesClient kubernetesClient = new KubernetesClientBuilder().build()) {
            LeaderElector leaderElector = kubernetesClient.leaderElector()
                    .withConfig(
                            new LeaderElectionConfigBuilder()
                                    .withName("Concurrent leader Election configuration")
                                    .withLeaseDuration(Duration.ofSeconds(30))
                                    .withLock(new LeaseLock(namespace, name, lockIdentity))
                                    .withRenewDeadline(Duration.ofSeconds(15))
                                    .withRetryPeriod(Duration.ofSeconds(5))
                                    .withLeaderCallbacks(new LeaderCallbacks(
                                            () -> {log.info("Started leadership"); isLeader = true;},
                                            () -> {log.info("Stopped leadership"); isLeader =false; },
                                            newLeader -> log.info("New leader elected {}", newLeader)))
                                    .build())
                    .build();

            CompletableFuture<?> f = leaderElector.start();
            Thread.sleep(10000);
            f.cancel(true);
            Thread.sleep(5000);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
  }
```
but there is a exception as below 
could I know what is a problem? and how to fix it?

```
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Lease]  with name: [kdms-device-query-service]  in namespace: [default]  failed.
2024-07-12T06:32:16.3551166Z 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:159)
2024-07-12T06:32:16.3553185Z 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:195)
2024-07-12T06:32:16.3554890Z 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:149)
2024-07-12T06:32:16.3556449Z 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:98)
2024-07-12T06:32:16.3558905Z 	at io.fabric8.kubernetes.client.extended.leaderelection.resourcelock.ResourceLock.get(ResourceLock.java:48)
2024-07-12T06:32:16.3561045Z 	at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.tryAcquireOrRenew(LeaderElector.java:227)
2024-07-12T06:32:16.3563451Z 	at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.lambda$acquire$4(LeaderElector.java:177)
2024-07-12T06:32:16.3566234Z 	at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.lambda$loop$8(LeaderElector.java:292)
2024-07-12T06:32:16.3568333Z 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
2024-07-12T06:32:16.3570317Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-07-12T06:32:16.3572635Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-07-12T06:32:16.3573943Z 	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-07-12T06:32:16.3574935Z Caused by: java.io.IOException: kubernetes.default.svc
2024-07-12T06:32:16.3576514Z 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:504)
2024-07-12T06:32:16.3578648Z 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:524)
2024-07-12T06:32:16.3580539Z 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleGet(OperationSupport.java:467)
2024-07-12T06:32:16.3582297Z 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:792)
2024-07-12T06:32:16.3584096Z 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:193)
2024-07-12T06:32:16.3585871Z 	... 10 common frames omitted
2024-07-12T06:32:16.3586820Z Caused by: java.net.UnknownHostException: kubernetes.default.svc
2024-07-12T06:32:16.3587979Z 	at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988)
2024-07-12T06:32:16.3589203Z 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
2024-07-12T06:32:16.3590417Z 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688)
2024-07-12T06:32:16.3591522Z 	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
2024-07-12T06:32:16.3592874Z 	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
2024-07-12T06:32:16.3594470Z 	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
2024-07-12T06:32:16.3595837Z 	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
2024-07-12T06:32:16.3597276Z 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
2024-07-12T06:32:16.3599093Z 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2024-07-12T06:32:16.3600596Z 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2024-07-12T06:32:16.3601960Z 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2024-07-12T06:32:16.3602645Z 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-07-12T06:32:16.3603177Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-12T06:32:16.3603660Z 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-07-12T06:32:16.3604152Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-12T06:32:16.3604638Z 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2024-07-12T06:32:16.3605145Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-12T06:32:16.3605689Z 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2024-07-12T06:32:16.3606240Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-12T06:32:16.3606792Z 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2024-07-12T06:32:16.3607301Z 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
```

### Fabric8 Kubernetes Client version

SNAPSHOT

### Steps to reproduce

.

### Expected behavior

.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3@latest

### Environment

Amazon

**Comment by rohanKanojia** [comment]
@FunTK : From exception it looks like applicable is unable to connect with any Kubernetes API server. Could you please check whether you've provided appropriate kubernetes cluster configuration in your application?

**Comment by FunTK** [comment]
Hi @rohanKanojia 
Could I know how to set cluster configuration to connect kubernetes API?

**Comment by rohanKanojia** [comment]
@FunTK : Usually KubernetesClient autodetects cluster configuration when running from outside (kubeconfig) or inside a Pod (via mounted ServiceAccount) (see [this FAQ](https://github.com/fabric8io/kubernetes-client/blob/main/doc/FAQ.md#what-credentials-does-the-client-use-for-authentication) for more details).

Could you please provide more detail about how you're deploying your application?

**Comment by manusa** [comment]
> ```
>            Thread.sleep(10000);
>            f.cancel(true);
>            Thread.sleep(5000);
> ```

Note that this part is used in the example to keep it alive during ten seconds.

In your application, you should probably have a general KubernetesClient instance (bean). The leader election process should start when your application becomes ready, and stop when your application is about to shutdown.
