### ISSUE TITLE
Unhandled exception: java.util.concurrent.RejectedExecutionException when closing LocalPortForward

### ISSUE THREAD

**Issue by matteriben** [fabric8io/kubernetes-client#6215]
### Describe the bug

Closing an instance of `LocalPortForward` sometimes results in an unhandled `RejectedExecutionException`. This does not appear to be causing any problem other than producing unnecessary exception messages.

### Fabric8 Kubernetes Client version

6.12.1

### Steps to reproduce

Run nginx:
```
kubectl run nginx --image=nginx
```
Then run this test:
```
public class PortForwardTest {
    KubernetesClient client = new KubernetesClientBuilder().build();
    @Test
    void test() throws Exception {
        for (int i = 0; i < 1000; i++) {
            try (LocalPortForward lpf = client.pods().inNamespace("default").withName("nginx").portForward(80)) {
                new URL("http://localhost:" + lpf.getLocalPort()).openStream().close();
            }
        }
    }
}
```

### Expected behavior

No unhandled exceptions.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
2024-08-02 01:29:44,480 ERROR [io.ver.cor.imp.ContextImpl] (vert.x-eventloop-thread-9) Unhandled exception: java.util.concurrent.RejectedExecutionException
	at io.fabric8.kubernetes.client.utils.internal.SerialExecutor.execute(SerialExecutor.java:47)
	at io.fabric8.kubernetes.client.dsl.internal.PortForwarderWebsocketListener.onMessage(PortForwarderWebsocketListener.java:128)
	at io.fabric8.kubernetes.client.vertx.VertxWebSocket.lambda$init$0(VertxWebSocket.java:48)
	at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handleBinaryFrame(WebSocketImplBase.java:658)
	at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handle(WebSocketImplBase.java:603)
	at io.vertx.core.http.impl.WebSocketImplBase$FrameAggregator.handle(WebSocketImplBase.java:589)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.http.impl.WebSocketImplBase.receiveFrame(WebSocketImplBase.java:534)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:255)
	at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:242)
	at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:295)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Additional context

```
serverVersion:
  buildDate: "2024-02-14T22:25:42Z"
  compiler: gc
  gitCommit: 4b8e819355d791d96b7e9d9efe4cbafae2311c88
  gitTreeState: clean
  gitVersion: v1.29.2
  goVersion: go1.21.7
  major: "1"
  minor: "29"
  platform: linux/arm64
```

**Comment by matteriben** [comment]
Thank you @shawkins !
