### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported response type: [B

### ISSUE THREAD

**Issue by iampratapak** [fabric8io/kubernetes-client#6218]
### Describe the bug

We are encountering `java.lang.IllegalArgumentException: Unsupported response type: [B` during the initial informer sync for CRDs. Can someone please guide us on what the issue might be?

This is happening after we migrated our services to Java 21. While running the application locally, it starts without any issues. However, when running it on an OKE cluster as a GraalVM Native Image, we are getting this error.

```
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

### Fabric8 Kubernetes Client version

6.13.1

### Steps to reproduce

Upgrade the service to Java 21, build the native image, and run it on the OKE cluster.

### Expected behavior

The application starts without errors.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

### Fabric8 Kubernetes Client Logs

```shell
java.lang.IllegalArgumentException: Unsupported response type: [B
	at io.fabric8.kubernetes.client.http.HttpResponse$SupportedResponses.from(HttpResponse.java:120)
	at io.fabric8.kubernetes.client.http.StandardHttpClient.sendAsync(StandardHttpClient.java:76)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:547)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.submitList(BaseOperation.java:441)
	at io.fabric8.kubernetes.client.informers.impl.cache.Reflector.processList(Reflector.java:184)
	at io.fabric8.kubernetes.client.informers.impl.cache.Reflector.listSyncAndWatch(Reflector.java:126)
	at io.fabric8.kubernetes.client.informers.impl.cache.Reflector.start(Reflector.java:81)
	at io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer.start(DefaultSharedIndexInformer.java:166)
	at io.fabric8.kubernetes.client.informers.impl.DefaultSharedIndexInformer.run(DefaultSharedIndexInformer.java:175)
```

**Comment by shawkins** [comment]
> Upgrade the service to Java 21, build the native image, and run it on the OKE cluster.

Seems like a native issue. The byte[] response type is supported. Can you try with a regular vm as well?

**Comment by iampratapak** [comment]
@shawkins indeed, it was a Native Image issue. I faced this problem when I was using GraalVM version 21.0.1+12.1. The issue was resolved after I upgraded to the latest GraalVM version 22.0.2+9.1 and performed fresh native image tracing.

**Comment by manusa** [comment]
Can we close this issue then?

**Comment by iampratapak** [comment]
@manusa Please go ahead and close it. Thank you.
