### ISSUE TITLE
DefaultMockServerWebSocketTest failing intermittently on CI

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/kubernetes-client#6228]
### Is your task related to a problem? Please describe

I've seen repeated failures of DefaultMockServerWebSocketTest on GitHub actions CI , for example [this one](https://github.com/fabric8io/kubernetes-client/actions/runs/10283343683/job/28456962479?pr=6226)

```
Error:  Failures: 
Error:    DefaultMockServerWebSocketTest.andUpgradeToWebSocket, with request header 'sec-websocket-protocol', should create response with matching header:203->andUpgradeToWebSocket, with request header 'sec-websocket-protocol', should create response with matching header_closure11:-1->andUpgradeToWebSocket, with request header 'sec-websocket-protocol', should create response with matching header_closure11:204 Condition failed with Exception:

future.get(10, TimeUnit.SECONDS) == "v4.channel.k8s.io"
|      |       |
|      |       class java.util.concurrent.TimeUnit
|      java.util.concurrent.TimeoutException
|      	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
|      	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
|      	at io.fabric8.mockwebserver.DefaultMockServerWebSocketTest.andUpgradeToWebSocket, with request header 'sec-websocket-protocol', should create response with matching header_closure11(DefaultMockServerWebSocketTest.groovy:204)
|      	at spock.util.concurrent.AsyncConditions.evaluate(AsyncConditions.java:101)
|      	at io.fabric8.mockwebserver.DefaultMockServerWebSocketTest.andUpgradeToWebSocket, with request header 'sec-websocket-protocol', should create response with matching header(DefaultMockServerWebSocketTest.groovy:203)
java.util.concurrent.CompletableFuture@6a486afb[Not completed]

```

### Describe the solution you'd like

DefaultMockServerWebSocketTest should pass uniformly on CI. It shouldn't fail intermittently.

**Comment by manusa** [comment]
This test doesn't seem to be failing any more since MockWebServer is based on Vert.x.
Closing again.
