### ISSUE TITLE
Cannot set OwnerReferences during edit

### ISSUE THREAD

**Issue by foxish** [fabric8io/kubernetes-client#635]
If I do not provide an OwnerReference at the time of creation of the resource, I cannot specify it later either
Repro:

```
    var k8ConfBuilder = new ConfigBuilder()
      .withApiVersion("v1")
      .withMasterUrl("http://127.0.0.1:8080")
      .withNamespace("default")

    val secret = kubernetesClient.secrets().createNew()
      .withNewMetadata()
      .withName("foo")
      .endMetadata()
      .withData(Map("bar" -> "dXNlcjpwYXNz").asJava)
      .withType("Opaque")
      .done()
```

Now, edit the secret using:

```
    val ownerRefs = new ArrayBuffer[OwnerReference]
    ownerRefs += new OwnerReferenceBuilder()
      .withApiVersion(service.getApiVersion)
      .withController(false)
      .withKind(service.getKind)
      .withName(service.getMetadata.getName)
      .withUid(service.getMetadata.getUid)
      .build()


    kubernetesClient.secrets().inNamespace("default").withName("foo")
      .edit()
      .editMetadata()
        .addToOwnerReferences(ownerRefs: _*)
      .endMetadata()
      .done()
```

The error thrown is:

```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: http://127.0.0.1:8080/api/v1/namespaces/default/secrets/foo. Message: jsonpatch add operation does not apply: doc is missing path: /metadata/ownerReferences/0. Received status: Status(apiVersion=v1, code=500, details=null, kind=Status, message=jsonpatch add operation does not apply: doc is missing path: /metadata/ownerReferences/0, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:315)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:268)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:221)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:619)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$3.apply(HasMetadataOperation.java:134)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$3.apply(HasMetadataOperation.java:130)
	at io.fabric8.kubernetes.api.model.DoneableSecret.done(DoneableSecret.java:26)
	at io.fabric8.kubernetes.api.model.DoneableSecret.done(DoneableSecret.java:5)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:141)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$1.apply(HasMetadataOperation.java:51)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$1.apply(HasMetadataOperation.java:41)
	at io.fabric8.kubernetes.api.model.DoneableSecret.done(DoneableSecret.java:26)
	at KubeSpark$.main(KubeSpark.scala:78)
	at KubeSpark.main(KubeSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by iocanel** [comment]
@dhirajsb: Isn't this pretty similar with the issue you were having and fixed with: #614 

If this is the case, 1.4.34 should have a fix for it. @foxish: what is the version you are using?

**Comment by ash211** [comment]
@foxish were you able to work around this?

**Comment by andrewkandzuba** [comment]
@ash211 Hello. I am struggling from the same issue with **Openshift Container Platform v3.9**. And the only work around I have found to the date is to manually edit yaml in UI (which is obviously not an option at all). All attempts to "fake" "/metadata/ownerReferences/0" record upon creation haven't fly too. Can you please confirm this bug has been ever reportedly fixed...
