### ISSUE TITLE
NPE in Config.tryKubeConfig

### ISSUE THREAD

**Issue by carlossg** [fabric8io/kubernetes-client#703]
As seen in jenkins k8s plugin

```
java.lang.NullPointerException
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:346)
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:143)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:16)
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:13)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesFactoryAdapter.createClient(KubernetesFactoryAdapter.java:81)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.connect(KubernetesCloud.java:306)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.addProvisionedSlave(KubernetesCloud.java:742)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.provision(KubernetesCloud.java:550)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:701)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:307)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:60)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:798)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

`currentAuthInfo.getAuthProvider().getConfig()` is null in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L346

**Comment by carlossg** [comment]
My `.kube/config` had this entry

```
users:
- name: gke_api-project-xxx-east1-d_jenkins
  user:
    auth-provider:
      name: gcp
```

After deleting it, it worked, but it can be there

**Comment by rohanKanojia** [comment]
@carlossg : Is this still an issue with latest versions?

**Comment by carlossg** [comment]
yes, I still see the null pointer dereference in https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/Config.java#L529

**Comment by rohanKanojia** [comment]
oh, okay.
