### ISSUE TITLE
Can I create StatefulSet via kubernetes-client API?

### ISSUE THREAD

**Issue by puyangsky** [fabric8io/kubernetes-client#706]
Although I found StatefulSet.java in "io.fabric8.kubernetes.api.model.extensions", but I cannot find API to create it.

**Comment by khogeland** [comment]
No, there needs to be a `StatefulSetOperationsImpl` and accompanying wiring. I'm currently trying to figure out how that should look; I think much (most?) of the code could be taken from/shared with `ReplicaSetOperationsImpl`. Maybe a maintainer has already thought this through?

**Comment by kennyzli** [comment]
is there any ETA for this? or we can simply use resource operation to handle the statefulSet

**Comment by hollinwilkins** [comment]
I am also having trouble with StatefulSet. When I try to create it, I get this error:

```
[error] (run-main-0) java.lang.NullPointerException
java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:267)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:184)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:63)
```

**Comment by hollinwilkins** [comment]
I guess the error is because a ResourceHandler has not yet been implemented for StatefulSet. Are there any plans to add one? I could potentially take a look at it.

**Comment by khogeland** [comment]
Apologies for the delay. https://github.com/fabric8io/kubernetes-client/pull/745

**Comment by WMostert1** [comment]
With version 3.4.0 of the fabric8-maven-plugin the `fabric8:apply` goal does not support statefulsets. Error below:
```
Failed to execute goal io.fabric8:fabric8-maven-plugin:3.4.0:apply (default-cli) on project keycloak: Failed to create StatefulSet from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: No handler found for object:StatefulSet(apiVersion=apps/v1beta1, kind=StatefulSet, metadata=ObjectMeta(annotations=...
```
Which uses the kubernetes client.
