### ISSUE TITLE
OperationSupport.createStatus() can throw a NPE occasionally

### ISSUE THREAD

**Issue by amisevsk** [fabric8io/kubernetes-client#733]
I'm occasionally seeing NPEs from OperationSupport while running, but I sadly don't have consistent steps to reproduce. 

Occasionally, the Response passed into [`OperationSupport.createStatus()`](https://github.com/fabric8io/kubernetes-client/blob/871aa0cc8abf84fe288eb5603f8c8231e5ea03d3/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/base/OperationSupport.java#L287) is `null`. There is a null check performed, but it occurs after attempting `response.code()`.

Stack Trace: 

```
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.createStatus(OperationSupport.java:287)
	at io.fabric8.kubernetes.client.dsl.internal.ExecWebSocketListener.onFailure(ExecWebSocketListener.java:166)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:203)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by snjeza** [comment]
Related issue: https://github.com/square/okhttp/issues/3297
You can slow down or debug the ExecWebSocketListener.onMessage method, debug ExecExample and set a breakpoint to the start of the method.

**Comment by amisevsk** [comment]
Closing as I think problem is solved.
