### ISSUE TITLE
Restart policy OnFailure not supported

### ISSUE THREAD

**Issue by hbutalia** [fabric8io/kubernetes-client#742]
version - 2.0.3

spec.template.spec.restartPolicy: Unsupported value: "OnFailure": supported values: Always. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.template.spec.restartPolicy, message=Unsupported value: "OnFailure": supported values: Always, reason=FieldValueNotSupported, additionalProperties={})], group=extensions, kind=Deployment, name=dp-inframanagerservice-701203f7-ffb4-4e11-89f1-fefa2ff19b48, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Deployment.extensions "dp-701203f7-ffb4-4e11-89f1-fefa2ff19b48" is invalid: spec.template.spec.restartPolicy: Unsupported value: "OnFailure": supported values: Always, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
2017-04-24T07:14:35.201151174Z  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:318) ~[kubernetes-client.jar!/:na]
2017-04-24T07:14:35.201157340Z  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:267) ~[kubernetes-client.jar!/:na]
2017-04-24T07:14:35.201163085Z  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237) ~[kubernetes-client.jar!/:na]
2017-04-24T07:14:35.201168603Z  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230) ~[kubernetes-client.jar!/:na]
2017-04-24T07:14:35.201173824Z  at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:208) ~[kubernetes-client.jar!/:na]
2017-04-24T07:14:35.201179408Z  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:696) ~[kubernetes-client.jar!/:na]
2017-04-24T07:14:35.201184697Z  at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:320) ~[kubernetes-client.jar!/:na]

**Comment by ravjanga** [comment]
Based on the k8 documentation, we should be supporting values - Always, OnFailure, and Never

But if you are using Deployments, then Always is the only option supported.

https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-lifetime

**Comment by jimmidyson** [comment]
That is a server-side validation error that, as @ravjanga said (thanks!), is correct - Deployments only support Always restart policy. Closing as this is not a client issue.
