### ISSUE TITLE
ClassCastException on io.fabric8.openshift.api.model.DoneableRoleBinding.done

### ISSUE THREAD

**Issue by dimonv** [fabric8io/kubernetes-client#793]
Hi all,

after migrating to openshift-client version from 1.4.x to 2.x I'm facing ClassCastException (see below):
`Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lio.fabric8.openshift.api.model.RoleBinding;
	at io.fabric8.openshift.client.dsl.internal.RoleBindingOperationsImpl.create(RoleBindingOperationsImpl.java:34) ~[openshift-client-2.2.9.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation$1.apply(BaseOperation.java:341) ~[kubernetes-client-2.2.9.jar:na]
	at io.fabric8.openshift.api.model.DoneableRoleBinding.done(DoneableRoleBinding.java:27) ~[kubernetes-model-1.0.67.jar:1.0.67]`

Please advise how to avoid that.

Thanks and kind regards,
Dmitri

**Comment by dimonv** [comment]
Hello all,
could anybody answer this please?
Thanks
