### ISSUE TITLE
Kubeconfig pointing to certificate files not working correctly

### ISSUE THREAD

**Issue by OrfeasZ** [fabric8io/kubernetes-client#809]
When having a kubeconfig file that points to certificate/key files instead of embedding their data directly the Kubernetes client fails to initialize properly (using `DefaultKubernetesClient`).

There seem to be two issues with this:

1. If file paths are relative they always resolve relative to the current executing directory and not the directory of the kubeconfig file.
2. Certificates/keys are being decoded as DER instead of PEM (thrown error is `Could not parse certificate: java.io.IOException: Empty input`). Kubeconfig currently only supports pointing to PEM-encoded certificates/keys.

**Comment by sta-szek** [comment]
Hi,
I encounter similar issue when using: https://github.com/spring-cloud-incubator/spring-cloud-kubernetes in my spring boot app.

I can build and run app locally, where I have configured kubeconfig.
However when building the application in bamboo agent (which uses docker agent: https://hub.docker.com/r/pojo/docker-bamboo-agent/) I have exception:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.kubernetes.profile.KubernetesApplicationContextInitializer]: Constructor threw exception; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
build	27-Jun-2018 07:46:18		at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182)
build	27-Jun-2018 07:46:18		at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:444)
build	27-Jun-2018 07:46:18		... 61 common frames omitted
build	27-Jun-2018 07:46:18	Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:168)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.internal.SSLUtils.isHttpsAvailable(SSLUtils.java:64)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:189)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.Config.<init>(Config.java:170)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:18)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:15)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:47)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:53)
build	27-Jun-2018 07:46:18		at org.springframework.cloud.kubernetes.profile.KubernetesApplicationContextInitializer.<init>(KubernetesApplicationContextInitializer.java:35)
build	27-Jun-2018 07:46:18		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
build	27-Jun-2018 07:46:18		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
build	27-Jun-2018 07:46:18		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
build	27-Jun-2018 07:46:18		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
build	27-Jun-2018 07:46:18		at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
build	27-Jun-2018 07:46:18		... 62 common frames omitted
build	27-Jun-2018 07:46:18	Caused by: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
build	27-Jun-2018 07:46:18		at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:110)
build	27-Jun-2018 07:46:18		at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:94)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:72)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:114)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:93)
build	27-Jun-2018 07:46:18		at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:63)
build	27-Jun-2018 07:46:18		... 75 common frames omitted
build	27-Jun-2018 07:46:18	Caused by: java.io.IOException: Empty input
build	27-Jun-2018 07:46:18		at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:106)
build	27-Jun-2018 07:46:18		... 81 common frames omitted

**Comment by astellingwerf** [comment]
@OrfeasZ, Did you ever find a fix or work around for this issue?
