### ISSUE TITLE
Failed attempts to access configmap should log which service account was used

### ISSUE THREAD

**Issue by InfoSec812** [fabric8io/kubernetes-client#824]
We're using the Vert.x ConfigMap module and getting errors like:

```
19:50:52.880 [vert.x-eventloop-thread-6] ERROR com.redhat.rhambassador.RhAmbassadorLauncher - Failed to load configuration before deployments. Refusing to continue.
--
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/default/configmaps/ambassador-service. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:319)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:266)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:226)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:686)
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:187)
  | at io.vertx.config.kubernetes.ConfigMapStore.lambda$null$2(ConfigMapStore.java:132)
  | at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
  | at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:748)
  | 19:50:52.880 [main] WARN com.redhat.rhambassador.RhAmbassadorLauncher - Failed to set deployment options.
```
But there is no indication of WHICH service account is unable to access the configmap... It would be AWESOME if the log message detailed which service account was forbidden.

**Comment by jimmidyson** [comment]
What version of the client library are you using? I vaguely remember this being fixed, but may be wrong.

**Comment by InfoSec812** [comment]
The version included in Vert.x 3.4.2 - io.fabric8:kubernetes-client:1.4.35

**Comment by jimmidyson** [comment]
Hmm it was a different issue that was fixed. This is still an issue in the latest version.

I can't think off the top of my head how we can know what service account is being used. Ideas welcome :)

**Comment by InfoSec812** [comment]
I'm not familiar with how this whole thing works yet, so I'm not going to be much help...
