### ISSUE TITLE
isOpenShift causes failure on Kubernetes with RBAC

### ISSUE THREAD

**Issue by carlossg** [fabric8io/kubernetes-client#850]
GKE with RBAC

Trying `kubernetesApply` fails even when the service account has full cluster admin permissions. `isOpenshift` method tries to get API `/`

```
ERROR: Error during kubernetes apply: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:kubernetes-plugin:jenkins" cannot get path "/".: "Unknown user \"system:serviceaccount:kubernetes-plugin:jenkins\"".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:236)
	at io.fabric8.kubernetes.client.BaseClient.rootPaths(BaseClient.java:140)
	at io.fabric8.openshift.client.OpenshiftAdapterSupport.isOpenShift(OpenshiftAdapterSupport.java:53)
	at io.fabric8.openshift.client.OpenshiftAdapterSupport.isAdaptable(OpenshiftAdapterSupport.java:37)
	at io.fabric8.kubernetes.client.BaseClient.isAdaptable(BaseClient.java:122)
	at io.fabric8.kubernetes.pipeline.devops.ApplyStepExecution.loadImageStreams(ApplyStepExecution.java:329)
	at io.fabric8.kubernetes.pipeline.devops.ApplyStepExecution.run(ApplyStepExecution.java:160)
	at io.fabric8.kubernetes.pipeline.devops.ApplyStepExecution.run(ApplyStepExecution.java:92)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:42)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:224)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:150)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
	at sun.reflect.GeneratedMethodAccessor318.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
```

Seems that the `/` url will return 403 no matter your permissions

```
$ curl -i -sSL -k  -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc.cluster.local/api/v1/pods  | head
HTTP/2 200
content-type: application/json
date: Fri, 25 Aug 2017 12:22:05 GMT


$ curl -i -sSL -k  -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc.cluster.local/  | head
HTTP/2 403
content-type: text/plain
x-content-type-options: nosniff
content-length: 143
date: Fri, 25 Aug 2017 12:22:10 GMT

User "system:serviceaccount:kubernetes-plugin:jenkins" cannot get path "/".: "Unknown user \"system:serviceaccount:kubernetes-plugin:jenkins\""jenkins@jenkins-0:/$
```

**Comment by maragao** [comment]
I found this code in io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths():
`URL requestUrl = new URL(config.getMasterUrl());`

I changed it to:

`URL requestUrl = new URL(config.getMasterUrl() + "api/" + config.getApiVersion() + "/namespaces/" + config.getNamespace());`

And it worked (I tested resource, apply and deploy)

I don't know if this is the best solution, cos I didn't check if the method(getRootPaths()) is called in other places.

**Comment by scholzj** [comment]
I run into what seems to be the same problem. It looks that for me it helps to create a clusterolebinding to the cluster-admin role. **The cluster-admin role has unlimited access so this is very unsecure!** But it seems to work as a workaround for development purposes.

**Comment by graziergeek** [comment]
I pulled in `spring-cloud-starter-kubernetes` v `0.2.0.RELEASE` to read props from ConfigMap in GKE cluster.  We have RBAC turned on in our cluster.  Now this is failing during liveness probe (health check).

Reopen?

`io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/staging/pods/broker-cdf9457f4-h8v2w. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "broker-cdf9457f4-h8v2w" is forbidden: User "system:serviceaccount:staging:default" cannot get pods in the namespace "staging": Unknown user "system:serviceaccount:staging:default".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:312) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:295) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:753) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:206) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:181) ~[kubernetes-client-2.4.1.jar!/:na]
	at org.springframework.cloud.kubernetes.StandardPodUtils.internalGetPod(StandardPodUtils.java:61) [spring-cloud-kubernetes-core-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at org.springframework.cloud.kubernetes.StandardPodUtils.lambda$new$0(StandardPodUtils.java:45) [spring-cloud-kubernetes-core-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at org.springframework.cloud.kubernetes.LazilyInstantiate.swapper(LazilyInstantiate.java:41) ~[spring-cloud-kubernetes-core-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at org.springframework.cloud.kubernetes.LazilyInstantiate.lambda$new$0(LazilyInstantiate.java:34) ~[spring-cloud-kubernetes-core-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at org.springframework.cloud.kubernetes.LazilyInstantiate.get(LazilyInstantiate.java:29) ~[spring-cloud-kubernetes-core-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
	at org.springframework.cloud.kubernetes.KubernetesHealthIndicator.doHealthCheck(KubernetesHealthIndicator.java:35) ~[spring-cloud-kubernetes-core-0.2.0.RELEASE.jar!/:0.2.0.RELEASE]
`

**Comment by schnatterer** [comment]
Similar issue here. Using the kubernetes-client via jenkinsci/kubernetes-cd-plugin (version 0.1.5 of kubernetes-cd-plugin uses kubernetes-client 3.1.7) with kubeconfig file.
The same file works with `kubectl`, e.g. `kubectl --kubeconfig myconf apply -f mydeployment.yaml`.

Jenkinsfile
```
#!groovy

node {

    writeDeployment()


    withCredentials([file(credentialsId: 'kubeconfig-test', variable: 'kubeconfig')]) {
        withEnv(['NGINX_VERSION=1.13-alpine']) {
            echo "nginx version to be set $NGINX_VERSION"

            kubernetesDeploy(
                    credentialsType: 'KubeConfig',
                    kubeConfig: [path: kubeconfig],

                    configs: 'deployment.yaml',
                    enableConfigSubstitution: true
            )
        }
    }

}

void writeDeployment() {
    writeFile file: 'deployment.yaml', text: '''apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:$NGINX_VERSION
        name: nginx'''
}
```

Stacktrace:
```
ERROR: ERROR: Failure executing: GET at: https://MY_IP/apis/extensions/v1beta1/namespaces/default/deployments/nginx. Message: Forbidden! User my-svc-account doesn't have permission. deployments.extensions "nginx" is forbidden: User "system:serviceaccount:default:my-svc-account" cannot get deployments.extensions in the namespace "default": Unknown user "system:serviceaccount:default:my-svc-account".
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://MY_IP/apis/extensions/v1beta1/namespaces/default/deployments/nginx. Message: Forbidden! User my-svc-account doesn't have permission. deployments.extensions "nginx" is forbidden: User "system:serviceaccount:default:my-svc-account" cannot get deployments.extensions in the namespace "default": Unknown user "system:serviceaccount:default:my-svc-account".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:312)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:295)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:787)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:217)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:184)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$DeploymentUpdater.getCurrentResource(KubernetesClientWrapper.java:365)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$DeploymentUpdater.getCurrentResource(KubernetesClientWrapper.java:353)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper$ResourceUpdater.createOrApply(KubernetesClientWrapper.java:319)
	at com.microsoft.jenkins.kubernetes.KubernetesClientWrapper.apply(KubernetesClientWrapper.java:127)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:102)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$1.call(DeploymentCommand.java:66)
	at hudson.FilePath.act(FilePath.java:1084)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:66)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
	at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
	at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
	at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
	at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
	at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
