### ISSUE TITLE
Wait for pod to be ready doesn't work due to java.lang.InstantiationError: okhttp3.internal.ws.RealWebSocket

### ISSUE THREAD

**Issue by rasheedamir** [fabric8io/kubernetes-client#903]
So, in the pipeline we want `kubernetesApply` step to wait until the pod is ready or timeout otherwise and fail the pipeline. But currently if you set any value for `readinessTimeout` then it just goes red due to an error in `kubernetes-client`. 

Here are the details:

**Jenkinsfile Stage**

```
        // timeout is in milliseconds
        stage('Rollout to Stage') {
            kubernetesApply(readinessTimeout: 180000, environment: envStage)
            // TODO: figure out why to stash deployments?
            // TODO: from where does the stash command comes?
            //stash deployments
            stashName = label
            stash includes: '**/*.yml', name: stashName
        }
```

**Error in Console Output**

```
ERROR: Error during kubernetes apply: io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [180000] milliseconds for multiple resources. Resources that are not ready: [Kind:Deployment Name:organization-preference Namespace:apps]
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.waitUntilReady(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:125)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.waitUntilReady(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:66)
	at io.fabric8.kubernetes.pipeline.devops.ApplyStepExecution.run(ApplyStepExecution.java:253)
	at io.fabric8.kubernetes.pipeline.devops.ApplyStepExecution.run(ApplyStepExecution.java:94)
```

**kubernetes-client Logs**

```
Entering waitUntilReady
Nov 06, 2017 7:54:03 PM INFO io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl$1 run
Running waitUntilReady
Nov 06, 2017 7:54:03 PM INFO io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl$1 run
Error while waiting for: [Deployment] with name: [organization-preference] in namespace: [apps]: okhttp3.internal.ws.RealWebSocket. The resource will be considered not ready.
Nov 06, 2017 7:54:03 PM INFO io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl$1 run
The error stack trace:
java.lang.InstantiationError: okhttp3.internal.ws.RealWebSocket
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:145)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:97)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:723)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:711)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.periodicWatchUntilReady(HasMetadataOperation.java:200)
	at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl.waitUntilReady(DeploymentOperationsImpl.java:165)
	at io.fabric8.kubernetes.client.handlers.DeploymentHandler.waitUntilReady(DeploymentHandler.java:78)
	at io.fabric8.kubernetes.client.handlers.DeploymentHandler.waitUntilReady(DeploymentHandler.java:32)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl$1.run(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Nov 06, 2017 7:54:03 PM INFO io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl waitUntilReady
Exiting waitUntilReady
```

**Comment by rasheedamir** [comment]
@iocanel @jstrachan @rawlingsj can you please help me fix this issue? Its blocking from proceeding.

I think it could be due to multiple versions of okhttp3? I assume you use okhttp3 it at different places so, they all should be breaking as well.

**Comment by rasheedamir** [comment]
Here is the discussion with @iocanel on the slack

So, this error means that there is a version mismatch. Now looking closer to the devops-step plugin it seems that this occurs due to the presence of okhttp-ws 3.4.1 a module that was later on merged in 3.6 or higher oktthp.jar
so having dublicate classes in your classpath can lead to that
I think that the 3.4.1 version is pulled by the docker-client 
ok then we should update docker-client to latest version of okhttp?

**Comment by rasheedamir** [comment]
Fixing https://github.com/fabric8io/docker-client/issues/102 should fix this error or maybe this won't be an error anymore then.

**Comment by iocanel** [comment]
@rasheedamir: I am closing this one, as its not actually a client issue.

It's more a kubernetes-pipeline-plugin one.

**Comment by rasheedamir** [comment]
makes sense @iocanel !
