### ISSUE TITLE
[Question] Create Istio RouteRule

### ISSUE THREAD

**Issue by lordofthejars** [fabric8io/kubernetes-client#942]
Hi, I have a question regarding how to create Istio `RouteRule` resources using Kubernetes client.

I have next Istio resource:

```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-test-v2
spec:
  destination:
    name: reviews
  precedence: 2
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(user=alex)(;.*)?$"
  route:
  - labels:
      version: v2
```
And next code:

```java
private final NamespacedOpenShiftClient client;
client.inNamespace(configuration.getNamespace()).load(content).createOrReplace();
```

But then I get:

```
Caused by: io.fabric8.kubernetes.clnt.v3_1.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.clnt.v3_1.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.clnt.v3_1.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.clnt.v3_1.utils.Serialization.unmarshal(Serialization.java:123)
	at io.fabric8.kubernetes.clnt.v3_1.utils.Serialization.unmarshal(Serialization.java:85)
	at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:185)
	at io.fabric8.kubernetes.clnt.v3_1.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:171)
	at io.fabric8.kubernetes.clnt.v3_1.DefaultKubernetesClient$1.<init>(DefaultKubernetesClient.java:101)
	at io.fabric8.kubernetes.clnt.v3_1.DefaultKubernetesClient.load(DefaultKubernetesClient.java:101)
	at io.fabric8.openshift.clnt.v3_1.DefaultOpenShiftClient.load(DefaultOpenShiftClient.java:160)
	at org.arquillian.cube.openshift.impl.fabric8.F8OpenShiftAdapter$StreamOpenShiftResourceHandle.<init>(F8OpenShiftAdapter.java:793)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for kind:RouteRule
 at [Source: java.io.BufferedInputStream@546ccad7; line: 17, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:982)
	at io.fabric8.kubernetes.clnt.v3_1.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:56)
	at io.fabric8.kubernetes.clnt.v3_1.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:31)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1578)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1166)
	at io.fabric8.kubernetes.clnt.v3_1.utils.Serialization.unmarshal(Serialization.java:121)
```

So is there any way to just send the yaml to cluster without any parsing?

**Comment by iocanel** [comment]
We can't avoid deserializing the objects. In many ways this is required.

Here are the things that need to be done:

The `KubernetesDeserializer` exposes a static method called `registerCustomKind` which accepts the kind and the class (that extends the KuberentesResource). This will get you through this Exception.

Then you will most probably need implement a ResourceHandler for RouteRule.

I think that we need an actual client extension for istio. @cmoulliard: Is your team working on something like that? Can you point us to the project?

**Comment by metacosm** [comment]
@iocanel @lordofthejars yes, we're working on an extension of kubernetes-model that will handle istio-specific resources.

**Comment by gastaldi** [comment]
It would be nice if the `KubernetesDeserializer` used the ServiceLoader API to register custom extensions automatically, therefore supporting that would just requiring adding the JAR with the extension to the classpath

**Comment by iocanel** [comment]
The `KubernetesDeserializer` has been updated like @gastaldi  described, so from the client side we are done.

There relevant commit is:

https://github.com/fabric8io/kubernetes-model/commit/16c5203f592726471822cdf598dead2087adabf4

The istio java api now only needs to provide an implementation of `KubernetesResourceMappingProvider` for example:

https://github.com/fabric8io/kubernetes-model/blob/16c5203f592726471822cdf598dead2087adabf4/kubernetes-model/src/main/java/io/fabric8/kubernetes/internal/InternalResourceMappingProvider.java

An other example from the ServiceCatalog client:

https://github.com/snowdrop/service-catalog-java-api/blob/30164168d62af5155f6d295a58ecc19c08d6c5a3/model/src/main/java/me/snowdrop/servicecatalog/api/model/ServiceCatalogResourceMappingProvider.java

Note that you also need to include the /META-INF/services/io.fabric8.kubernetes.client.ResourceHandler for the ServiceLoader to pick this up.

I think this can be closed now

**Comment by piyush1594** [comment]
This feature is in Kubernetes-Client 3.2.0, Thanks
